import { q, r } from './helpers.mjs';

export default [
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'easy',
    skill: 'ler coordenadas na base padrão',
    commandType: 'leitura direta',
    commonError: 'trocar a ordem das componentes',
    statement: r`Na base padrão $E=\{(1,0),(0,1)\}$ de $\mathbb R^2$, qual é o vetor de coordenadas de $v=(-2,5)$?`,
    options: ['$(-2,5)$', '$(5,-2)$', '$(2,-5)$', '$(-2,-5)$'],
    correct: 0,
    hints: [
      'Na base padrão, os coeficientes coincidem com as componentes usuais.',
      'Escreva $v=a(1,0)+b(0,1)$.',
      'Confira primeiro a componente horizontal e depois a vertical.',
    ],
    finalAnswer: '$(-2,5)$',
    explanation:
      'A base padrão isola cada eixo, portanto a primeira componente multiplica o primeiro vetor e a segunda multiplica o segundo. Não é necessário resolver um sistema adicional.',
    steps: [
      ['Expanda na base', '$v=a(1,0)+b(0,1)=(a,b)$.'],
      ['Compare a primeira entrada', '$a=-2$.'],
      ['Compare a segunda entrada', '$b=5$.'],
      ['Registre as coordenadas', '$[v]_E=(-2,5)$.'],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'easy',
    skill: 'interpretar a notação de coordenadas em uma base',
    commandType: 'leitura de representação',
    commonError: 'tratar coordenadas como componentes na base padrão',
    statement: r`Se $B=(b_1,b_2)$ é uma base e $[v]_B=(0,4)$, qual igualdade descreve $v$?`,
    options: [
      '$v=4b_2$',
      '$v=4b_1$',
      '$v=(0,4)$ na base padrão',
      '$v=b_1+4b_2$',
    ],
    correct: 0,
    hints: [
      'As entradas de $[v]_B$ são pesos dos vetores da base, na ordem indicada.',
      'Escreva a combinação correspondente a $(0,4)$.',
      'O primeiro peso multiplica $b_1$ e o segundo multiplica $b_2$.',
    ],
    finalAnswer: '$v=4b_2$',
    explanation:
      'Coordenadas em uma base registram os coeficientes da combinação linear de seus vetores, respeitando a ordem da base. Aqui o coeficiente de $b_1$ é zero.',
    steps: [
      ['Leia a primeira coordenada', 'Ela fornece o peso $0$ para $b_1$.'],
      ['Leia a segunda coordenada', 'Ela fornece o peso $4$ para $b_2$.'],
      ['Monte a combinação', '$v=0b_1+4b_2$.'],
      ['Simplifique', '$v=4b_2$.'],
    ],
  }),
  q({
    topic: 'mudanca-de-base',
    difficulty: 'easy',
    skill: 'reconstruir vetor a partir de coordenadas',
    commandType: 'reconstrução',
    commonError: 'tratar coordenadas como o próprio vetor',
    statement: r`Se $B=\{(1,0),(1,1)\}$ e $[v]_B=(2,-1)$, qual é $v$ na base padrão?`,
    options: ['$(1,-1)$', '$(2,-1)$', '$(3,1)$', '$(-1,2)$'],
    correct: 0,
    hints: [
      'Use os números dados como coeficientes dos vetores de $B$.',
      'Calcule $2(1,0)-(1,1)$.',
      'Confira separadamente as duas componentes do resultado.',
    ],
    finalAnswer: '$(1,-1)$',
    explanation:
      'O vetor de coordenadas registra pesos relativos à base indicada. Para recuperar o vetor geométrico, multiplicamos cada vetor da base por seu coeficiente e somamos.',
    steps: [
      ['Interprete a notação', '$v=2b_1-1b_2$.'],
      ['Substitua a base', '$v=2(1,0)-(1,1)$.'],
      ['Some componentes', '$v=(2,0)+(-1,-1)=(1,-1)$.'],
      [
        'Diferencie as representações',
        'O par $(2,-1)$ são coordenadas em $B$; o vetor padrão é $(1,-1)$.',
      ],
    ],
  }),
  q({
    topic: 'mudanca-de-base',
    difficulty: 'easy',
    skill: 'montar matriz da base para a base padrão',
    commandType: 'organização de dados',
    commonError: 'colocar vetores da base nas linhas',
    statement: r`Para $B=\{(2,1),(0,3)\}$, qual matriz converte $[v]_B$ em coordenadas padrão?`,
    options: [
      r`$\begin{pmatrix}2&0\\1&3\end{pmatrix}$`,
      r`$\begin{pmatrix}2&1\\0&3\end{pmatrix}$`,
      r`$\begin{pmatrix}1/2&0\\-1/6&1/3\end{pmatrix}$`,
      r`$\begin{pmatrix}2&0\\3&1\end{pmatrix}$`,
    ],
    correct: 0,
    hints: [
      'A imagem de cada vetor coordenado padrão deve ser o vetor correspondente de $B$.',
      'As colunas da matriz são os vetores da base escritos na base de chegada.',
      'Preserve a ordem dos vetores em $B$.',
    ],
    finalAnswer: r`$\begin{pmatrix}2&0\\1&3\end{pmatrix}$`,
    explanation:
      'A matriz de coordenadas de $B$ para a base padrão é formada colocando os vetores de $B$ como colunas. Multiplicá-la pelos coeficientes reproduz a combinação linear original.',
    steps: [
      ['Use a primeira coluna', 'Ela deve ser o vetor $(2,1)$.'],
      ['Use a segunda coluna', 'Ela deve ser o vetor $(0,3)$.'],
      [
        'Monte a matriz',
        r`$P_{E\leftarrow B}=\begin{pmatrix}2&0\\1&3\end{pmatrix}$.`,
      ],
      ['Confira', '$P_{E\leftarrow B}(a,b)=a(2,1)+b(0,3)$.'],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'easy',
    skill: 'representar polinômio na base monomial',
    commandType: 'leitura de coeficientes',
    commonError: 'ordenar coeficientes do maior grau para o menor',
    statement: r`Na base ordenada $B=(1,x,x^2)$ de $P_2$, quais são as coordenadas de $p(x)=2-x+3x^2$?`,
    options: ['$(2,-1,3)$', '$(3,-1,2)$', '$(2,1,3)$', '$(-1,2,3)$'],
    correct: 0,
    hints: [
      'A ordem da base determina a ordem das coordenadas.',
      'Leia primeiro o termo constante.',
      'O coeficiente de $x$ inclui seu sinal.',
    ],
    finalAnswer: '$(2,-1,3)$',
    explanation:
      'Na base monomial ordenada do termo constante ao quadrático, as coordenadas são exatamente os coeficientes nessa mesma ordem. Inverter a ordem ou perder o sinal muda a representação.',
    steps: [
      ['Separe os termos', '$p=2\cdot1+(-1)\cdot x+3\cdot x^2$.'],
      ['Associe à base', 'Os pesos de $(1,x,x^2)$ são $2,-1,3$.'],
      [
        'Respeite a ordem',
        'A primeira coordenada é a constante, não o coeficiente líder.',
      ],
      ['Conclua', '$[p]_B=(2,-1,3)$.'],
    ],
  }),
  q({
    topic: 'somas-diretas',
    difficulty: 'easy',
    skill: 'decompor vetor em soma direta',
    commandType: 'decomposição geométrica',
    commonError: 'misturar componentes dos subespaços',
    statement: r`Considere $\mathbb R^2=U\oplus V$, com $U=\operatorname{span}\{(1,0)\}$ e $V=\operatorname{span}\{(0,1)\}$. Qual é a decomposição de $(3,-2)$?`,
    options: [
      '$(3,0)+(0,-2)$',
      '$(0,3)+(-2,0)$',
      '$(3,-2)+(0,0)$',
      '$(1,0)+(0,1)$',
    ],
    correct: 0,
    hints: [
      'A parcela em $U$ deve ter segunda componente zero.',
      'A parcela em $V$ deve ter primeira componente zero.',
      'As duas parcelas precisam somar o vetor original.',
    ],
    finalAnswer: '$(3,0)+(0,-2)$',
    explanation:
      'Na soma direta dos eixos coordenados, cada componente pertence a um dos subespaços. A decomposição é única porque os eixos só se intersectam no vetor zero.',
    steps: [
      [
        'Projete em $U$',
        'A componente horizontal de $(3,-2)$ fornece $(3,0)$.',
      ],
      ['Projete em $V$', 'A componente vertical fornece $(0,-2)$.'],
      ['Some', '$(3,0)+(0,-2)=(3,-2)$.'],
      [
        'Confira a unicidade',
        '$U\cap V=\{0\}$, então não há outra decomposição.',
      ],
    ],
  }),
  q({
    topic: 'mudanca-de-base',
    difficulty: 'medium',
    skill: 'converter coordenadas de base para padrão',
    commandType: 'execução em duas representações',
    commonError: 'aplicar a inversa da matriz de transição',
    statement: r`Na base $B=\{(1,1),(1,-1)\}$, um vetor tem coordenadas $(2,3)$. Quais são suas coordenadas na base padrão?`,
    options: ['$(5,-1)$', '$(-1,5)$', '$(2,3)$', '$(1,5)$'],
    correct: 0,
    hints: [
      'As coordenadas em $B$ são coeficientes dos dois vetores da base.',
      'Calcule $2b_1+3b_2$.',
      'Confira o sinal da segunda componente de $b_2$.',
    ],
    finalAnswer: '$(5,-1)$',
    explanation:
      'Converter da base $B$ para a padrão significa reconstruir o vetor pela combinação linear. A matriz cujas colunas são os vetores de $B$ multiplica o vetor de coordenadas.',
    steps: [
      ['Escreva a combinação', '$v=2(1,1)+3(1,-1)$.'],
      ['Calcule as parcelas', '$2b_1=(2,2)$ e $3b_2=(3,-3)$.'],
      ['Some', '$v=(5,-1)$.'],
      [
        'Confira por matriz',
        r`$\begin{pmatrix}1&1\\1&-1\end{pmatrix}(2,3)=(5,-1)$.`,
      ],
    ],
  }),
  q({
    topic: 'bases-e-dimensao',
    difficulty: 'medium',
    skill: 'determinar valores que preservam uma base',
    commandType: 'análise paramétrica',
    commonError: 'excluir apenas vetores nulos',
    statement: r`Para quais valores de $a$ o conjunto $B_a=\{(1,a),(a,1)\}$ é uma base de $\mathbb R^2$?`,
    options: ['$a\\ne1$ e $a\\ne-1$', '$a\\ne0$', '$a>0$', 'Todo $a$ real'],
    correct: 0,
    hints: [
      'Dois vetores em $\mathbb R^2$ formam base quando o determinante é não nulo.',
      'Use os vetores como colunas.',
      'Fatore $1-a^2$.',
    ],
    finalAnswer: '$a\\ne1$ e $a\\ne-1$',
    explanation:
      'O determinante mede a independência das duas direções. Ele zera quando os vetores coincidem ou são opostos, exatamente nos dois valores que precisam ser excluídos.',
    steps: [
      ['Monte a matriz', r`$P=\begin{pmatrix}1&a\\a&1\end{pmatrix}$.`],
      ['Calcule o determinante', '$\det P=1-a^2$.'],
      ['Encontre os zeros', '$1-a^2=(1-a)(1+a)=0$ em $a=\pm1$.'],
      [
        'Conclua',
        'Fora desses valores, o determinante é não nulo e $B_a$ é base.',
      ],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'medium',
    skill: 'resolver coordenadas por sistema triangular',
    commandType: 'cálculo de representação',
    commonError: 'dividir ambas as coordenadas pelo mesmo fator',
    statement: r`Se $B=\{(2,0),(1,1)\}$, determine $[(1,2)]_B$.`,
    options: ['$(-1/2,2)$', '$(1/2,2)$', '$(1,2)$', '$(2,-1/2)$'],
    correct: 0,
    hints: [
      'Escreva $a(2,0)+b(1,1)=(1,2)$.',
      'A segunda componente determina $b$ imediatamente.',
      'Substitua esse valor na primeira componente.',
    ],
    finalAnswer: '$(-1/2,2)$',
    explanation:
      'A base é triangular: a segunda coordenada do vetor determina diretamente o segundo coeficiente. O primeiro coeficiente surge depois de compensar a contribuição desse vetor na primeira entrada.',
    steps: [
      ['Compare a segunda entrada', '$b=2$.'],
      ['Compare a primeira', '$2a+b=1$.'],
      ['Substitua', '$2a+2=1$, então $a=-1/2$.'],
      ['Confira', '$(-1/2)(2,0)+2(1,1)=(-1,0)+(2,2)=(1,2)$.'],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'medium',
    skill: 'converter coordenadas padrão para uma base dada por matriz',
    commandType: 'resolução de sistema de transição',
    commonError: 'usar a matriz de base no sentido inverso',
    statement: r`A matriz $P_{E\leftarrow B}=\begin{pmatrix}1&2\\0&1\end{pmatrix}$ converte coordenadas de $B$ para a base padrão $E$. Se $[v]_E=(5,2)$, qual é $[v]_B$?`,
    options: ['$(1,2)$', '$(5,2)$', '$(1,-2)$', '$(9,2)$'],
    correct: 0,
    hints: [
      r`A relação dada é $[v]_E=P_{E\leftarrow B}[v]_B$.`,
      'Chame $[v]_B=(a,b)$ e multiplique a matriz pelo par.',
      'A segunda linha determina $b$ antes da primeira linha.',
    ],
    finalAnswer: '$(1,2)$',
    explanation:
      'A matriz fornecida leva coordenadas da base $B$ para a base padrão. Para voltar de $E$ para $B$, resolvemos o sistema matricial indicado, sem trocar a direção da transformação.',
    steps: [
      [
        'Escreva a relação',
        r`$\begin{pmatrix}5\\2\end{pmatrix}=\begin{pmatrix}1&2\\0&1\end{pmatrix}\begin{pmatrix}a\\b\end{pmatrix}$.`,
      ],
      ['Leia a segunda linha', '$b=2$.'],
      ['Use a primeira linha', '$a+2b=5$, então $a=1$.'],
      [
        'Verifique no sentido direto',
        r`$\begin{pmatrix}1&2\\0&1\end{pmatrix}\begin{pmatrix}1\\2\end{pmatrix}=\begin{pmatrix}5\\2\end{pmatrix}$.`,
      ],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'medium',
    skill: 'representar matriz em base ordenada',
    commandType: 'codificação de objeto',
    commonError: 'ignorar a ordem dos vetores da base',
    statement: r`Em $M_{2\times2}$, considere a base ordenada $B=(E_{11},E_{21},E_{12},E_{22})$. Quais são as coordenadas de $A=\begin{pmatrix}2&-1\\3&4\end{pmatrix}$?`,
    options: ['$(2,3,-1,4)$', '$(2,-1,3,4)$', '$(4,3,-1,2)$', '$(2,3,4,-1)$'],
    correct: 0,
    hints: [
      'Siga a ordem da base, que não é a ordem usual de leitura por linhas.',
      '$E_{21}$ registra a entrada inferior esquerda.',
      'Associe uma coordenada a cada matriz unitária.',
    ],
    finalAnswer: '$(2,3,-1,4)$',
    explanation:
      'As coordenadas dependem da ordem declarada. Nesta base, as duas primeiras posições percorrem a primeira coluna e as duas últimas percorrem a segunda coluna.',
    steps: [
      ['Expanda pela base', '$A=2E_{11}+3E_{21}-E_{12}+4E_{22}$.'],
      [
        'Leia os dois primeiros pesos',
        'Para $E_{11},E_{21}$, os coeficientes são $2,3$.',
      ],
      ['Leia os restantes', 'Para $E_{12},E_{22}$, são $-1,4$.'],
      ['Conclua', '$[A]_B=(2,3,-1,4)$.'],
    ],
  }),
  q({
    topic: 'mudanca-de-base',
    difficulty: 'medium',
    skill: 'interpretar determinante da matriz de base',
    commandType: 'interpretação geométrica',
    commonError: 'usar o módulo e perder orientação',
    statement: r`A matriz $P_{E\leftarrow B}$ de uma base ordenada de $\mathbb R^2$ tem determinante $-3$. O que o sinal negativo informa?`,
    options: [
      'A orientação de $B$ é oposta à da base padrão.',
      'Os vetores de $B$ são dependentes.',
      'A área do paralelogramo é negativa.',
      'A mudança de base não é invertível.',
    ],
    correct: 0,
    hints: [
      'Determinante não nulo já garante que há uma base.',
      'O módulo mede o fator de área.',
      'O sinal registra preservação ou reversão de orientação.',
    ],
    finalAnswer: 'A orientação de $B$ é oposta à da base padrão.',
    explanation:
      'O módulo três indica o fator de escala de área, sempre interpretado como positivo. O sinal negativo não destrói a invertibilidade; ele registra uma reversão de orientação.',
    steps: [
      ['Use o módulo', '$|\det P|=3$ é o fator de área.'],
      ['Use o sinal', '$\det P<0$ indica inversão da orientação ordenada.'],
      [
        'Exclua dependência',
        'Como o determinante não é zero, as colunas são independentes.',
      ],
      ['Conclua', 'A base existe, mas sua orientação é oposta à padrão.'],
    ],
  }),
  q({
    topic: 'mudanca-de-base',
    difficulty: 'hard',
    skill: 'construir matriz de transição entre bases',
    commandType: 'reconstrução de operador coordenado',
    commonError: 'usar coordenadas dos vetores de chegada na base errada',
    statement: r`Se $B=\{(1,1),(1,0)\}$ e $C=\{(1,0),(1,1)\}$, qual matriz transforma $[v]_B$ em $[v]_C$?`,
    options: [
      r`$\begin{pmatrix}0&1\\1&0\end{pmatrix}$`,
      r`$\begin{pmatrix}1&1\\1&0\end{pmatrix}$`,
      r`$\begin{pmatrix}0&1\\1&-1\end{pmatrix}$`,
      r`$\begin{pmatrix}1&0\\0&1\end{pmatrix}$`,
    ],
    correct: 0,
    hints: [
      'Cada coluna é a coordenada de um vetor de $B$ na base $C$.',
      'Escreva primeiro $(1,1)$ como combinação dos vetores de $C$.',
      'Repita para $(1,0)$ e preserve a ordem.',
    ],
    finalAnswer: r`$\begin{pmatrix}0&1\\1&0\end{pmatrix}$`,
    explanation:
      'A matriz de transição $C\leftarrow B$ recebe coeficientes na base $B$. Por isso suas colunas são as coordenadas, em $C$, dos vetores da base de partida.',
    steps: [
      ['Converta $b_1$', '$(1,1)=0(1,0)+1(1,1)$, então $[b_1]_C=(0,1)$.'],
      ['Converta $b_2$', '$(1,0)=1(1,0)+0(1,1)$, então $[b_2]_C=(1,0)$.'],
      [
        'Monte pelas colunas',
        r`$P_{C\leftarrow B}=\begin{pmatrix}0&1\\1&0\end{pmatrix}$.`,
      ],
      [
        'Confira',
        'A matriz troca as duas coordenadas, coerente com a troca de ordem entre as bases.',
      ],
    ],
  }),
  q({
    topic: 'mudanca-de-base',
    difficulty: 'hard',
    skill: 'compor mudanças de coordenadas',
    commandType: 'planejamento de rota',
    commonError: 'multiplicar matrizes na ordem da leitura',
    statement: r`São conhecidas $P_{C\leftarrow B}$ e $P_{D\leftarrow C}$. Qual expressão converte diretamente $[v]_B$ em $[v]_D$?`,
    options: [
      r`$P_{D\leftarrow C}P_{C\leftarrow B}$`,
      r`$P_{C\leftarrow B}P_{D\leftarrow C}$`,
      r`$P_{D\leftarrow C}+P_{C\leftarrow B}$`,
      r`$P_{C\leftarrow B}^{-1}P_{D\leftarrow C}$`,
    ],
    correct: 0,
    hints: [
      'Aplique primeiro a conversão de $B$ para $C$.',
      'A transformação aplicada primeiro aparece à direita no produto.',
      'A saída intermediária em $C$ deve ser a entrada da segunda matriz.',
    ],
    finalAnswer: r`$P_{D\leftarrow C}P_{C\leftarrow B}$`,
    explanation:
      'A composição segue o fluxo das coordenadas: $B$ para $C$ e depois $C$ para $D$. Na notação matricial, a primeira ação fica à direita, garantindo compatibilidade entre os espaços intermediários.',
    steps: [
      ['Faça a primeira conversão', '$[v]_C=P_{C\leftarrow B}[v]_B$.'],
      ['Faça a segunda', '$[v]_D=P_{D\leftarrow C}[v]_C$.'],
      [
        'Substitua a expressão',
        '$[v]_D=P_{D\leftarrow C}P_{C\leftarrow B}[v]_B$.',
      ],
      [
        'Leia a matriz direta',
        'O produto na ordem indicada é $P_{D\leftarrow B}$.',
      ],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'hard',
    skill: 'converter base deslocada de polinômios',
    commandType: 'reescrita por variável auxiliar',
    commonError: 'substituir $x-1$ por $x$ sem expandir',
    statement: r`Na base $B=(1,x-1,(x-1)^2)$ de $P_2$, quais são as coordenadas de $x^2$?`,
    options: ['$(1,2,1)$', '$(0,0,1)$', '$(1,-2,1)$', '$(1,1,2)$'],
    correct: 0,
    hints: [
      'Defina $y=x-1$, de modo que $x=y+1$.',
      'Reescreva $x^2$ em potências de $y$.',
      'Associe os coeficientes a $1,y,y^2$.',
    ],
    finalAnswer: '$(1,2,1)$',
    explanation:
      'A base é centrada em $x=1$, então os coeficientes devem ser obtidos em potências de $x-1$. Uma substituição simples evita expandir combinações desconhecidas.',
    steps: [
      ['Troque a variável', 'Se $y=x-1$, então $x=y+1$.'],
      ['Eleve ao quadrado', '$x^2=(y+1)^2=1+2y+y^2$.'],
      ['Retorne à base', '$x^2=1+2(x-1)+(x-1)^2$.'],
      ['Leia as coordenadas', 'Os coeficientes são $(1,2,1)$.'],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'hard',
    skill: 'reconstruir vetor de base desconhecido',
    commandType: 'problema inverso',
    commonError: 'ignorar a ordem da base',
    statement: r`Uma base ordenada de $\mathbb R^2$ é $B=(b_1,b_2)$, com $b_1=(1,2)$. Sabe-se que $[(5,1)]_B=(2,-1)$. Qual é $b_2$?`,
    options: ['$(-3,3)$', '$(3,-3)$', '$(7,5)$', '$(-1,2)$'],
    correct: 0,
    hints: [
      'Traduza as coordenadas como uma combinação $2b_1-b_2$.',
      'Substitua o vetor conhecido $b_1$.',
      'Isole $b_2$ na igualdade vetorial.',
    ],
    finalAnswer: '$(-3,3)$',
    explanation:
      'O dado coordenado fornece uma equação vetorial capaz de determinar o segundo vetor da base. É preciso respeitar o coeficiente negativo associado a $b_2$ ao isolá-lo.',
    steps: [
      ['Traduza o dado', '$(5,1)=2b_1-b_2$.'],
      ['Substitua $b_1$', '$(5,1)=(2,4)-b_2$.'],
      ['Isole o vetor', '$b_2=(2,4)-(5,1)=(-3,3)$.'],
      [
        'Confira a base',
        '$b_1$ e $b_2$ não são proporcionais e $2b_1-b_2=(5,1)$.',
      ],
    ],
  }),
  q({
    topic: 'somas-diretas',
    difficulty: 'hard',
    skill: 'obter projeção associada a decomposição oblíqua',
    commandType: 'modelagem de operador',
    commonError: 'usar projeção ortogonal sem que ela seja pedida',
    statement: r`Considere $\mathbb R^2=U\oplus V$, onde $U=\operatorname{span}\{(1,0)\}$ e $V=\operatorname{span}\{(1,1)\}$. A projeção sobre $U$ ao longo de $V$ envia $(3,2)$ em qual vetor?`,
    options: ['$(1,0)$', '$(3,0)$', '$(2,2)$', '$(0,2)$'],
    correct: 0,
    hints: [
      'Decomponha $(3,2)=u+v$ com $u\in U$ e $v\in V$.',
      'Escreva $u=(a,0)$ e $v=(b,b)$.',
      'A projeção pedida mantém apenas a parcela em $U$.',
    ],
    finalAnswer: '$(1,0)$',
    explanation:
      'A projeção ao longo de $V$ usa a decomposição direta definida pelos dois subespaços, não a perpendicularidade. O vetor é separado em uma parcela horizontal e outra na direção $(1,1)$.',
    steps: [
      ['Parametrize as parcelas', '$(3,2)=(a,0)+(b,b)=(a+b,b)$.'],
      ['Compare a segunda entrada', '$b=2$.'],
      ['Encontre a parcela em $U$', '$a+b=3$ dá $a=1$.'],
      ['Aplique a projeção', 'A parcela preservada é $u=(1,0)$.'],
    ],
  }),
  q({
    topic: 'coordenadas-em-bases',
    difficulty: 'hard',
    skill: 'interpretar coordenadas em base de subespaço',
    commandType: 'verificação cruzada',
    commonError: 'acrescentar coordenada ambiente desnecessária',
    statement: r`No plano $W=\{(x,y,z):x+y+z=0\}$, use a base $B=\{(1,-1,0),(1,0,-1)\}$. Qual é $[(3,-1,-2)]_B$?`,
    options: ['$(1,2)$', '$(2,1)$', '$(3,-1)$', '$(1,2,0)$'],
    correct: 0,
    hints: [
      'Primeiro confira que o vetor pertence a $W$.',
      'Escreva $a(1,-1,0)+b(1,0,-1)=(3,-1,-2)$.',
      'As componentes $y$ e $z$ determinam diretamente $a$ e $b$.',
    ],
    finalAnswer: '$(1,2)$',
    explanation:
      'Embora $W$ esteja dentro de $\mathbb R^3$, sua base tem dois vetores e as coordenadas relativas a ela têm apenas duas entradas. As componentes ambiente determinam esses dois pesos.',
    steps: [
      ['Confira a pertinência', '$3-1-2=0$, então o vetor está em $W$.'],
      ['Compare a componente $y$', '$-a=-1$, logo $a=1$.'],
      ['Compare a componente $z$', '$-b=-2$, logo $b=2$.'],
      ['Verifique a componente $x$', '$a+b=1+2=3$, confirmando $[v]_B=(1,2)$.'],
    ],
  }),
];
