import { q, r } from './helpers.mjs';

const make = (
  topic,
  difficulty,
  skill,
  statement,
  options,
  finalAnswer,
  explanation,
  steps,
) =>
  q({
    topic,
    difficulty,
    skill,
    commandType: 'interpretação geométrica e cálculo',
    commonError: 'confundir a fórmula com outra construção próxima',
    statement,
    options,
    correct: 0,
    hints: [
      'Identifique a definição ou decomposição geométrica que se aplica.',
      'Calcule cada produto ou coeficiente separadamente.',
      'Verifique sinal, dimensão e ortogonalidade no resultado.',
    ],
    finalAnswer,
    explanation: `${explanation} ${steps.at(-1)[1]}`,
    steps,
  });

export default [
  make(
    'produto-interno-e-norma',
    'easy',
    'calcular produto interno',
    r`Qual é o produto interno usual de $(1,2,-1)$ e $(3,0,4)$?`,
    ['$-1$', '$1$', '$7$', '$-7$'],
    '$-1$',
    'O produto interno usual soma os produtos das componentes correspondentes. Aqui os termos são três, zero e menos quatro, cuja soma é menos um.',
    [
      ['Multiplique a primeira componente', '$1\cdot3=3$.'],
      ['Multiplique a segunda', '$2\cdot0=0$.'],
      ['Multiplique a terceira', '$(-1)\cdot4=-4$.'],
      ['Some', '$3+0-4=-1$.'],
    ],
  ),
  make(
    'produto-interno-e-norma',
    'easy',
    'calcular norma euclidiana',
    r`Qual é a norma euclidiana de $(2,-3,6)$?`,
    ['$7$', '$11$', '$49$', '$5$'],
    '$7$',
    'A norma é a raiz quadrada da soma dos quadrados das componentes. A soma é quarenta e nove, cuja raiz positiva é sete.',
    [
      ['Eleve ao quadrado', '$2^2=4$, $(-3)^2=9$ e $6^2=36$.'],
      ['Some', '$4+9+36=49$.'],
      ['Extraia a raiz', '$\sqrt{49}=7$.'],
      ['Conclua', 'A norma vale $7$.'],
    ],
  ),
  make(
    'produto-interno-e-norma',
    'easy',
    'calcular distância',
    r`Qual é a distância entre $a=(1,4)$ e $b=(-2,0)$ no plano euclidiano?`,
    ['$5$', '$7$', '$\sqrt7$', '$25$'],
    '$5$',
    'A distância é a norma da diferença entre os pontos. O vetor diferença possui componentes três e quatro, formando o conhecido triângulo retângulo de hipotenusa cinco.',
    [
      ['Subtraia os pontos', '$a-b=(3,4)$.'],
      ['Calcule os quadrados', '$3^2+4^2=9+16$.'],
      ['Extraia a raiz', '$\sqrt{25}=5$.'],
      ['Conclua', 'A distância é $5$.'],
    ],
  ),
  make(
    'ortogonalidade',
    'easy',
    'testar ortogonalidade',
    r`Qual vetor é ortogonal a $(2,1)$?`,
    ['$(1,-2)$', '$(1,2)$', '$(2,-1)$', '$(0,1)$'],
    '$(1,-2)$',
    'Dois vetores são ortogonais quando seu produto interno é zero. O produto de $(2,1)$ por $(1,-2)$ soma dois e menos dois.',
    [
      ['Escolha o candidato', 'Considere $(1,-2)$.'],
      ['Calcule o produto', '$2\cdot1+1\cdot(-2)=0$.'],
      ['Interprete', 'Produto interno zero significa ortogonalidade.'],
      ['Conclua', 'O vetor correto é $(1,-2)$.'],
    ],
  ),
  make(
    'projecoes-e-minimos-quadrados',
    'easy',
    'projetar em eixo coordenado',
    r`Qual é a projeção ortogonal de $(3,-2)$ sobre o eixo $x$?`,
    ['$(3,0)$', '$(0,-2)$', '$(3,-2)$', '$(-3,0)$'],
    '$(3,0)$',
    'Projetar sobre o eixo horizontal preserva a componente nessa direção e remove a componente vertical. Portanto a segunda coordenada se torna zero.',
    [
      ['Identifique o subespaço', 'O eixo $x$ é gerado por $(1,0)$.'],
      ['Preserve a componente paralela', 'A componente horizontal é $3$.'],
      ['Elimine a perpendicular', 'A componente vertical vira $0$.'],
      ['Conclua', 'A projeção é $(3,0)$.'],
    ],
  ),
  make(
    'formas-quadraticas',
    'easy',
    'avaliar forma quadrática diagonal',
    r`Para $Q(x,y)=2x^2-y^2$, quanto vale $Q(2,3)$?`,
    ['$-1$', '$1$', '$17$', '$-17$'],
    '$-1$',
    'Avaliar uma forma quadrática exige substituir as coordenadas e respeitar os quadrados. O primeiro termo vale oito e o segundo vale nove.',
    [
      ['Substitua $x$', '$2(2^2)=8$.'],
      ['Substitua $y$', '$3^2=9$.'],
      ['Faça a diferença', '$8-9=-1$.'],
      ['Conclua', '$Q(2,3)=-1$.'],
    ],
  ),
  make(
    'produto-interno-e-norma',
    'medium',
    'calcular ângulo entre vetores',
    r`Qual é o ângulo entre $(1,1)$ e $(1,-1)$?`,
    ['$90^\circ$', '$45^\circ$', '$0^\circ$', '$180^\circ$'],
    '$90^\circ$',
    'O produto interno dos vetores é zero e ambos são não nulos. Essa condição caracteriza um ângulo reto no espaço euclidiano.',
    [
      ['Calcule o produto', '$1\cdot1+1\cdot(-1)=0$.'],
      ['Observe as normas', 'Ambas são positivas.'],
      ['Use a fórmula', '$\cos\theta=0$.'],
      ['Conclua', '$\theta=90^\circ$.'],
    ],
  ),
  make(
    'projecoes-e-minimos-quadrados',
    'medium',
    'projetar sobre reta',
    r`Qual é a projeção ortogonal de $v=(2,3)$ sobre a reta gerada por $u=(1,1)$?`,
    ['$(5/2,5/2)$', '$(1/2,1/2)$', '$(2,2)$', '$(3,3)$'],
    '$(5/2,5/2)$',
    'A projeção sobre uma reta é $(v\cdot u)/(u\cdot u)$ vezes o vetor diretor. O coeficiente é cinco meios.',
    [
      ['Calcule o numerador', '$v\cdot u=2+3=5$.'],
      ['Calcule o denominador', '$u\cdot u=1+1=2$.'],
      ['Forme o coeficiente', '$5/2$.'],
      ['Multiplique', 'A projeção é $(5/2,5/2)$.'],
    ],
  ),
  make(
    'ortogonalidade',
    'medium',
    'executar Gram-Schmidt',
    r`Ao aplicar Gram–Schmidt a $v_1=(1,0)$ e $v_2=(1,2)$, qual segundo vetor ortogonal é obtido antes da normalização?`,
    ['$(0,2)$', '$(1,2)$', '$(1,0)$', '$(-2,0)$'],
    '$(0,2)$',
    'Subtrai-se de $v_2$ sua projeção sobre o primeiro vetor. A projeção é $(1,0)$, deixando apenas a componente vertical.',
    [
      ['Mantenha o primeiro', '$u_1=(1,0)$.'],
      ['Projete', '$\operatorname{proj}_{u_1}v_2=(1,0)$.'],
      ['Subtraia', '$u_2=(1,2)-(1,0)=(0,2)$.'],
      ['Confira', '$u_1\cdot u_2=0$.'],
    ],
  ),
  make(
    'ortogonalidade',
    'medium',
    'calcular complemento ortogonal',
    r`Em $\mathbb R^3$, qual é o complemento ortogonal de $W=\operatorname{span}\{(1,1,0),(0,1,1)\}$?`,
    [
      r`$\operatorname{span}\{(1,-1,1)\}$`,
      r`$\operatorname{span}\{(1,1,1)\}$`,
      r`$\operatorname{span}\{(1,0,-1)\}$`,
      r`$\{0\}$`,
    ],
    r`$\operatorname{span}\{(1,-1,1)\}$`,
    'Um vetor do complemento deve ser ortogonal aos dois geradores. As equações impõem $y=-x$ e $z=x$, produzindo a direção indicada.',
    [
      ['Imponha a primeira ortogonalidade', '$x+y=0$.'],
      ['Imponha a segunda', '$y+z=0$.'],
      ['Parametrize', '$y=-x$ e $z=x$.'],
      ['Conclua', r`$W^\perp=\operatorname{span}\{(1,-1,1)\}$.`],
    ],
  ),
  make(
    'projecoes-e-minimos-quadrados',
    'medium',
    'resolver aproximação constante',
    r`Qual constante $c$ minimiza $(c-1)^2+(c-4)^2+(c-7)^2$?`,
    ['$4$', '$3$', '$5$', '$12$'],
    '$4$',
    'O melhor ajuste constante em mínimos quadrados é a média dos dados. A soma dos três valores é doze e sua média é quatro.',
    [
      ['Derive a função', '$2(c-1)+2(c-4)+2(c-7)=0$.'],
      ['Simplifique', '$6c-24=0$.'],
      ['Resolva', '$c=4$.'],
      ['Confira', 'A segunda derivada é positiva.'],
    ],
  ),
  make(
    'formas-quadraticas',
    'medium',
    'classificar definitude',
    r`Como se classifica $Q(x,y)=3x^2+2y^2$?`,
    [
      'Positiva definida',
      'Negativa definida',
      'Indefinida',
      'Semidefinida negativa',
    ],
    'Positiva definida',
    'Ambos os coeficientes diagonais são positivos e não há termo misto. Para todo vetor não nulo, pelo menos um quadrado contribui positivamente.',
    [
      ['Observe os coeficientes', '$3>0$ e $2>0$.'],
      ['Use os quadrados', '$x^2,y^2\ge0$.'],
      ['Teste não nulidade', 'Se $(x,y)\\ne0$, ao menos um termo é positivo.'],
      ['Conclua', '$Q(x,y)>0$ fora da origem.'],
    ],
  ),
  make(
    'produto-interno-e-norma',
    'hard',
    'trabalhar com produto interno ponderado',
    r`No produto interno $\langle x,y\rangle_G=x^TGy$, com $G=\operatorname{diag}(2,1)$, qual é a norma de $(1,2)$?`,
    [r`$\sqrt6$`, r`$\sqrt5$`, '$3$', '$6$'],
    r`$\sqrt6$`,
    'A norma induzida é a raiz de $x^TGx$. A ponderação duplica o quadrado da primeira coordenada e mantém o da segunda.',
    [
      ['Aplique a matriz', '$G(1,2)=(2,2)$.'],
      ['Faça o produto', '$(1,2)\cdot(2,2)=2+4=6$.'],
      ['Extraia a raiz', r`$\|x\|_G=\sqrt6$.`],
      ['Conclua', r`A norma é $\sqrt6$.`],
    ],
  ),
  make(
    'ortogonalidade',
    'hard',
    'ortogonalizar polinômios',
    r`Em $P_2$ com $\langle p,q\rangle=\int_{-1}^1p(x)q(x)\,dx$, qual polinômio obtido de $x^2$ é ortogonal a $1$?`,
    [r`$x^2-1/3$`, r`$x^2-1/2$`, r`$x^2-x$`, r`$x^2+1/3$`],
    r`$x^2-1/3$`,
    'Retira-se de $x^2$ sua projeção sobre o polinômio constante. O coeficiente é a razão entre as integrais de $x^2$ e de um, igual a um terço.',
    [
      ['Calcule o numerador', r`$\int_{-1}^1x^2dx=2/3$.`],
      ['Calcule o denominador', r`$\int_{-1}^11dx=2$.`],
      ['Forme a projeção', '$((2/3)/2)\cdot1=1/3$.'],
      ['Subtraia', r`$x^2-1/3$.`],
    ],
  ),
  make(
    'projecoes-e-minimos-quadrados',
    'hard',
    'ajustar reta por mínimos quadrados',
    r`Qual reta $y=a+bx$ ajusta por mínimos quadrados os pontos $(0,1),(1,2),(2,2)$?`,
    [r`$y=7/6+x/2$`, r`$y=1+x$`, r`$y=4/3+x/3$`, r`$y=1+x/2$`],
    r`$y=7/6+x/2$`,
    'As equações normais usam as somas dos valores, dos quadrados e dos produtos. Resolver o sistema fornece intercepto sete sextos e inclinação um meio.',
    [
      ['Monte a primeira equação', '$3a+3b=5$.'],
      ['Monte a segunda', '$3a+5b=6$.'],
      ['Subtraia', '$2b=1$, então $b=1/2$.'],
      ['Recupere $a$', '$3a+3/2=5$, então $a=7/6$.'],
    ],
  ),
  make(
    'projecoes-e-minimos-quadrados',
    'hard',
    'usar fatoração QR',
    r`Se $A=QR$ tem colunas independentes e $Q^TQ=I$, qual sistema triangular produz a solução de mínimos quadrados de $Ax\approx b$?`,
    ['$Rx=Q^Tb$', '$Qx=R^Tb$', '$R^TRx=b$', '$Rx=Qb$'],
    '$Rx=Q^Tb$',
    'A ortogonalidade de $Q$ transforma as equações normais sem formar $A^TA$. Como $R$ é triangular e invertível, resta resolver o sistema indicado.',
    [
      ['Escreva a fatoração', '$A=QR$.'],
      ['Projete a equação', '$Q^TAx=Q^Tb$.'],
      ['Simplifique', '$Q^TQRx=Rx$.'],
      ['Conclua', '$Rx=Q^Tb$.'],
    ],
  ),
  make(
    'formas-quadraticas',
    'hard',
    'diagonalizar forma simétrica',
    r`Quais são os valores principal máximo e mínimo de $Q(x,y)=2x^2+2xy+2y^2$ sobre $x^2+y^2=1$?`,
    ['$3$ e $1$', '$4$ e $0$', '$2$ e $2$', '$3$ e $-1$'],
    '$3$ e $1$',
    'A matriz simétrica da forma tem elementos diagonais iguais a dois e elementos fora da diagonal iguais a um. Seus autovalores são os extremos na circunferência unitária.',
    [
      ['Monte a matriz', r`$S=\begin{pmatrix}2&1\\1&2\end{pmatrix}$.`],
      ['Ache o polinômio', r`$\det(\lambda I-S)=(\lambda-2)^2-1$.`],
      ['Resolva', 'Os autovalores são $3$ e $1$.'],
      ['Interprete', 'Máximo $3$ e mínimo $1$.'],
    ],
  ),
  make(
    'formas-quadraticas',
    'hard',
    'minimizar forma com restrição',
    r`Qual é o mínimo de $Q(x,y)=x^2+4y^2$ sujeito a $x+y=1$?`,
    ['$4/5$', '$1$', '$1/2$', '$4$'],
    '$4/5$',
    'Substituir a restrição reduz o problema a uma quadrática convexa em uma variável. Seu vértice ocorre em $y=1/5$ e produz quatro quintos.',
    [
      ['Elimine uma variável', '$x=1-y$.'],
      ['Substitua', '$Q=(1-y)^2+4y^2=1-2y+5y^2$.'],
      ['Ache o vértice', '$-2+10y=0$, logo $y=1/5$.'],
      ['Avalie', '$x=4/5$ e $Q=16/25+4/25=4/5$.'],
    ],
  ),
];
