import { q, r } from './helpers.mjs';

const make = (
  topic,
  difficulty,
  skill,
  statement,
  options,
  finalAnswer,
  explanation,
  steps,
) =>
  q({
    topic,
    difficulty,
    skill,
    commandType: 'análise espectral e determinantal',
    commonError: 'aplicar uma regra sem verificar suas hipóteses',
    statement,
    options,
    correct: 0,
    hints: [
      'Identifique a propriedade estrutural relevante antes de calcular.',
      'Faça o cálculo simbólico de forma organizada.',
      'Confira o resultado por traço, determinante, dimensão ou substituição.',
    ],
    finalAnswer,
    explanation: `${explanation} A checagem indicada na resolução também elimina as alternativas incompatíveis com os dados.`,
    steps,
  });

export default [
  make(
    'determinantes',
    'easy',
    'calcular determinante triangular',
    r`Qual é o determinante de $\begin{pmatrix}2&1&4\\0&-3&5\\0&0&2\end{pmatrix}$?`,
    ['$-12$', '$12$', '$-6$', '$7$'],
    '$-12$',
    'Em uma matriz triangular, somente o produto associado à diagonal principal contribui para o determinante. Multiplicando os três elementos diagonais obtemos o valor pedido.',
    [
      ['Reconheça a forma', 'A matriz é triangular superior.'],
      ['Use a regra', 'O determinante é o produto da diagonal.'],
      ['Multiplique', '$2\cdot(-3)\cdot2=-12$.'],
      ['Conclua', 'Logo o determinante vale $-12$.'],
    ],
  ),
  make(
    'determinantes',
    'easy',
    'acompanhar troca de linhas',
    r`Uma matriz $B$ é obtida de $A$ trocando duas linhas, e $\det A=7$. Quanto vale $\det B$?`,
    ['$-7$', '$7$', '$14$', '$0$'],
    '$-7$',
    'Uma única troca de duas linhas inverte o sinal do determinante, sem alterar seu módulo. Portanto o valor sete passa imediatamente a menos sete.',
    [
      ['Identifique a operação', 'Houve uma troca de linhas.'],
      ['Use o efeito', 'Cada troca multiplica o determinante por $-1$.'],
      ['Calcule', '$\det B=-\det A=-7$.'],
      ['Conclua', 'O valor é $-7$.'],
    ],
  ),
  make(
    'determinantes',
    'easy',
    'interpretar área por determinante',
    r`Os vetores $(3,0)$ e $(1,4)$ formam lados de um paralelogramo. Qual é sua área?`,
    ['$12$', '$11$', '$7$', '$4$'],
    '$12$',
    'A área do paralelogramo é o valor absoluto do determinante formado pelos vetores. O determinante é doze e já é positivo.',
    [
      ['Monte a matriz', r`$\begin{pmatrix}3&1\\0&4\end{pmatrix}$.`],
      ['Calcule o determinante', '$3\cdot4-0\cdot1=12$.'],
      ['Tome o módulo', '$|12|=12$.'],
      ['Interprete', 'A área é $12$.'],
    ],
  ),
  make(
    'autovalores-e-autovetores',
    'easy',
    'verificar autovetor',
    r`Para $A=\begin{pmatrix}2&1\\0&3\end{pmatrix}$, qual vetor é autovetor associado a $\lambda=2$?`,
    ['$(1,0)$', '$(0,1)$', '$(1,1)$', '$(2,1)$'],
    '$(1,0)$',
    'Um autovetor para o valor dois deve ser não nulo e satisfazer $Av=2v$. A primeira direção coordenada cumpre exatamente essa igualdade.',
    [
      ['Teste a condição', '$A(1,0)=(2,0)$.'],
      ['Compare', '$2(1,0)=(2,0)$.'],
      ['Verifique não nulidade', '$(1,0)$ não é nulo.'],
      ['Conclua', 'Ele é autovetor de autovalor $2$.'],
    ],
  ),
  make(
    'autovalores-e-autovetores',
    'easy',
    'ler autovalores diagonais',
    r`Quais são os autovalores de $D=\operatorname{diag}(5,-1,2)$?`,
    ['$5,-1,2$', '$6,1,2$', '$5,1,-2$', '$10,-2,4$'],
    '$5,-1,2$',
    'Em uma matriz diagonal, cada vetor da base padrão é escalado pelo elemento diagonal correspondente. Assim os próprios elementos da diagonal são os autovalores.',
    [
      ['Observe a forma', '$D$ é diagonal.'],
      ['Aplique em $e_1$', '$De_1=5e_1$.'],
      ['Repita', '$De_2=-e_2$ e $De_3=2e_3$.'],
      ['Liste', 'Os autovalores são $5,-1,2$.'],
    ],
  ),
  make(
    'autovalores-e-autovetores',
    'easy',
    'usar traço e determinante',
    r`Uma matriz $2\times2$ tem autovalores $3$ e $-2$. Quais são seu traço e seu determinante?`,
    ['$1$ e $-6$', '$5$ e $6$', '$1$ e $6$', '$-1$ e $-6$'],
    '$1$ e $-6$',
    'O traço é a soma dos autovalores com multiplicidade, enquanto o determinante é seu produto. Isso fornece um e menos seis, respectivamente.',
    [
      ['Some os autovalores', '$3+(-2)=1$.'],
      ['Multiplique', '$3\cdot(-2)=-6$.'],
      ['Associe', 'Soma corresponde ao traço.'],
      ['Conclua', 'Traço $1$ e determinante $-6$.'],
    ],
  ),
  make(
    'determinantes',
    'medium',
    'combinar operações elementares',
    r`Partindo de $A$ com $\det A=4$, multiplica-se a primeira linha por $3$ e depois soma-se duas vezes a primeira linha à segunda. Qual é o novo determinante?`,
    ['$12$', '$4$', '$24$', '$36$'],
    '$12$',
    'Escalar uma linha por três escala o determinante pelo mesmo fator. Somar um múltiplo de uma linha a outra não o altera, então o resultado é doze.',
    [
      [
        'Acompanhe a escala',
        'A primeira operação multiplica o determinante por $3$.',
      ],
      ['Calcule o parcial', '$3\cdot4=12$.'],
      ['Analise a soma de linhas', 'Ela preserva o determinante.'],
      ['Conclua', 'O novo determinante é $12$.'],
    ],
  ),
  make(
    'determinantes',
    'medium',
    'determinar invertibilidade com parâmetro',
    r`Para quais valores de $t$ a matriz $\begin{pmatrix}t&2\\3&t\end{pmatrix}$ é singular?`,
    [r`$t=\pm\sqrt6$`, '$t=6$', '$t=\pm5$', '$t=0$'],
    r`$t=\pm\sqrt6$`,
    'Uma matriz quadrada é singular exatamente quando seu determinante é zero. A equação resultante é $t^2-6=0$, com duas raízes reais.',
    [
      ['Calcule o determinante', '$t^2-2\cdot3=t^2-6$.'],
      ['Imponha singularidade', '$t^2-6=0$.'],
      ['Resolva', '$t^2=6$.'],
      ['Conclua', r`$t=\pm\sqrt6$.`],
    ],
  ),
  make(
    'autovalores-e-autovetores',
    'medium',
    'obter polinômio característico',
    r`Qual é o polinômio característico $p(\lambda)=\det(\lambda I-A)$ de $A=\begin{pmatrix}1&2\\0&4\end{pmatrix}$?`,
    [
      r`$(\lambda-1)(\lambda-4)$`,
      r`$(\lambda+1)(\lambda+4)$`,
      r`$\lambda^2-5$`,
      r`$(\lambda-2)(\lambda-3)$`,
    ],
    r`$(\lambda-1)(\lambda-4)$`,
    'A matriz é triangular, por isso o determinante de $\lambda I-A$ é o produto de seus elementos diagonais. O termo fora da diagonal não altera as raízes.',
    [
      [
        'Forme a matriz',
        r`$\lambda I-A=\begin{pmatrix}\lambda-1&-2\\0&\lambda-4\end{pmatrix}$.`,
      ],
      ['Use triangularidade', 'O determinante é o produto diagonal.'],
      ['Multiplique', r`$(\lambda-1)(\lambda-4)$.`],
      ['Conclua', 'Esse é o polinômio característico.'],
    ],
  ),
  make(
    'autovalores-e-autovetores',
    'medium',
    'calcular autoespaço',
    r`Qual é o autoespaço de $A=\begin{pmatrix}3&1\\0&3\end{pmatrix}$ associado a $\lambda=3$?`,
    [
      r`$\operatorname{span}\{(1,0)\}$`,
      r`$\operatorname{span}\{(0,1)\}$`,
      r`$\mathbb R^2$`,
      r`$\{0\}$`,
    ],
    r`$\operatorname{span}\{(1,0)\}$`,
    'O autoespaço é o núcleo de $A-3I$. A equação restante força a segunda coordenada a zero e deixa a primeira livre.',
    [
      ['Subtraia $3I$', r`$A-3I=\begin{pmatrix}0&1\\0&0\end{pmatrix}$.`],
      ['Resolva o núcleo', '$y=0$.'],
      ['Parametrize', '$(x,y)=x(1,0)$.'],
      ['Conclua', r`$E_3=\operatorname{span}\{(1,0)\}$.`],
    ],
  ),
  make(
    'diagonalizacao',
    'medium',
    'reconhecer diagonalização por espectro simples',
    r`Uma matriz real $4\times4$ possui quatro autovalores reais distintos. Qual conclusão é garantida?`,
    [
      'Ela é diagonalizável sobre $\mathbb R$.',
      'Ela é ortogonal.',
      'Ela é simétrica.',
      'Seu determinante é positivo.',
    ],
    'Ela é diagonalizável sobre $\mathbb R$.',
    'Autovetores associados a autovalores distintos são linearmente independentes. Quatro deles formam uma base de $\mathbb R^4$, o que garante diagonalização.',
    [
      ['Associe autovetores', 'Cada autovalor possui um autovetor não nulo.'],
      [
        'Use independência',
        'Autovalores distintos fornecem autovetores independentes.',
      ],
      [
        'Conte dimensões',
        'Há quatro vetores independentes em dimensão quatro.',
      ],
      ['Conclua', 'Eles formam uma base de diagonalização.'],
    ],
  ),
  make(
    'diagonalizacao',
    'medium',
    'usar Cayley-Hamilton',
    r`Se $A$ satisfaz o polinômio característico $p(\lambda)=\lambda^2-5\lambda+6$, qual identidade permite reduzir $A^2$?`,
    ['$A^2=5A-6I$', '$A^2=5A+6I$', '$A^2=-5A+6I$', '$A^2=6A-5I$'],
    '$A^2=5A-6I$',
    'Pelo teorema de Cayley–Hamilton, a matriz anula seu polinômio característico. Isolar o termo quadrático produz a identidade indicada.',
    [
      ['Aplique o teorema', '$p(A)=0$.'],
      ['Substitua', '$A^2-5A+6I=0$.'],
      ['Isole', '$A^2=5A-6I$.'],
      ['Conclua', 'Essa relação reduz potências superiores.'],
    ],
  ),
  make(
    'determinantes',
    'hard',
    'explorar multilinearidade',
    r`Se as colunas de $A$ são $u,v,w$ e $\det[u,v,w]=5$, quanto vale $\det[u+2v,v,w]$?`,
    ['$5$', '$10$', '$15$', '$0$'],
    '$5$',
    'A linearidade na primeira coluna separa o determinante em dois termos. O termo que repete a coluna $v$ é zero por alternância, restando o valor original.',
    [
      ['Expanda a coluna', r`$\det[u+2v,v,w]=\det[u,v,w]+2\det[v,v,w]$.`],
      ['Use alternância', r`$\det[v,v,w]=0$.`],
      ['Substitua', '$5+2\cdot0=5$.'],
      ['Conclua', 'O determinante permanece $5$.'],
    ],
  ),
  make(
    'autovalores-e-autovetores',
    'hard',
    'comparar multiplicidades',
    r`Uma matriz $3\times3$ tem polinômio característico $(\lambda-2)^3$ e $\dim\ker(A-2I)=2$. O que se conclui?`,
    [
      'Não é diagonalizável.',
      'É diagonalizável.',
      'É necessariamente simétrica.',
      'Tem três autovalores distintos.',
    ],
    'Não é diagonalizável.',
    'A multiplicidade algébrica de dois é três, mas o autoespaço tem somente dimensão dois. Faltam autovetores para formar uma base completa.',
    [
      [
        'Leia a multiplicidade algébrica',
        'O autovalor $2$ aparece três vezes.',
      ],
      ['Leia a geométrica', 'O autoespaço tem dimensão $2$.'],
      ['Compare', 'A multiplicidade geométrica é menor que a algébrica.'],
      ['Conclua', 'Não existem três autovetores independentes.'],
    ],
  ),
  make(
    'diagonalizacao',
    'hard',
    'construir diagonalização',
    r`Se $Av_1=4v_1$, $Av_2=-v_2$ e $(v_1,v_2)$ é uma base, qual fatoração diagonaliza $A$ para $P=(v_1\ v_2)$?`,
    [
      r`$A=P\operatorname{diag}(4,-1)P^{-1}$`,
      r`$A=P^{-1}\operatorname{diag}(4,-1)P$`,
      r`$A=P\operatorname{diag}(-1,4)P^{-1}$`,
      r`$A=P^{-1}P$`,
    ],
    r`$A=P\operatorname{diag}(4,-1)P^{-1}$`,
    'As colunas de $P$ são autovetores na mesma ordem em que seus autovalores aparecem na diagonal. A relação $AP=PD$ equivale à fatoração dada.',
    [
      ['Agrupe as equações', r`$AP=(Av_1\ Av_2)$.`],
      ['Use os autovalores', r`$AP=P\operatorname{diag}(4,-1)$.`],
      ['Multiplique à direita', r`$A=PDP^{-1}$.`],
      ['Conclua', 'A ordem das colunas determina a ordem diagonal.'],
    ],
  ),
  make(
    'diagonalizacao',
    'hard',
    'calcular potência por decomposição espectral',
    r`Uma matriz $A$ satisfaz $Au=2u$ e $Av=3v$, com $(u,v)$ base. Se $x=u-2v$, qual é $A^4x$?`,
    ['$16u-162v$', '$8u-54v$', '$16u-81v$', '$32u-162v$'],
    '$16u-162v$',
    'Potências preservam cada direção própria e elevam o autovalor à potência correspondente. O coeficiente menos dois de $v$ permanece multiplicando $3^4$.',
    [
      ['Eleve na primeira direção', '$A^4u=2^4u=16u$.'],
      ['Eleve na segunda', '$A^4v=3^4v=81v$.'],
      ['Use linearidade', '$A^4(u-2v)=16u-2(81v)$.'],
      ['Conclua', '$A^4x=16u-162v$.'],
    ],
  ),
  make(
    'diagonalizacao',
    'hard',
    'usar projetores espectrais',
    r`Uma matriz diagonalizável possui apenas autovalores $1$ e $4$. Qual polinômio em $A$ projeta sobre o autoespaço de $4$?`,
    [r`$(A-I)/3$`, r`$(4I-A)/3$`, r`$A-I$`, r`$A/4$`],
    r`$(A-I)/3$`,
    'O polinômio projetor deve valer zero no autovalor um e um no autovalor quatro. A interpolação linear $(t-1)/3$ tem exatamente esses valores.',
    [
      ['Defina a exigência', '$p(1)=0$ e $p(4)=1$.'],
      ['Escolha o polinômio', r`$p(t)=(t-1)/3$.`],
      ['Substitua a matriz', r`$p(A)=(A-I)/3$.`],
      ['Confira', 'Ele anula o primeiro autoespaço e fixa o segundo.'],
    ],
  ),
  make(
    'determinantes',
    'hard',
    'relacionar determinante e volume orientado',
    r`Uma transformação em $\mathbb R^3$ duplica volumes e inverte orientação. Qual pode ser seu determinante?`,
    ['$-2$', '$2$', '$-8$', '$0$'],
    '$-2$',
    'O módulo do determinante fornece o fator de escala dos volumes, enquanto seu sinal registra a orientação. Duplicação com inversão corresponde a menos dois.',
    [
      ['Use o volume', '$|\det A|=2$.'],
      ['Use a orientação', 'Inverter orientação exige determinante negativo.'],
      ['Combine', '$\det A=-2$.'],
      ['Conclua', 'O valor compatível é $-2$.'],
    ],
  ),
];
