import { q, r } from './helpers.mjs';

export default [
  q({
    topic: 'nucleo-e-imagem',
    difficulty: 'easy',
    skill: 'testar linearidade pelo vetor zero',
    commandType: 'diagnóstico rápido',
    commonError: 'aceitar toda função dada por fórmula simples',
    statement: r`A função $F:\mathbb R^2\to\mathbb R^2$ é dada por $F(x,y)=(x+1,y)$. Qual fato prova imediatamente que $F$ não é linear?`,
    options: [
      '$F(0,0)\ne(0,0)$',
      '$F(1,0)=(2,0)$',
      '$F$ é injetiva',
      '$F$ preserva a segunda componente',
    ],
    correct: 0,
    hints: [
      'Toda transformação linear precisa preservar uma combinação muito especial.',
      'Aplique a função ao vetor nulo.',
      'Compare o resultado com o vetor nulo do contradomínio.',
    ],
    finalAnswer: '$F(0,0)\ne(0,0)$',
    explanation:
      'Transformações lineares sempre enviam o vetor nulo ao vetor nulo, consequência direta da homogeneidade. O termo constante na primeira componente viola essa condição necessária.',
    steps: [
      [
        'Use uma condição necessária',
        'Se $F$ fosse linear, teríamos $F(0)=0$.',
      ],
      ['Calcule a imagem do zero', '$F(0,0)=(1,0)$.'],
      ['Compare', 'O vetor $(1,0)$ não é o vetor nulo.'],
      ['Conclua', 'A condição necessária falha, portanto $F$ não é linear.'],
    ],
  }),
  q({
    topic: 'nucleo-e-imagem',
    difficulty: 'easy',
    skill: 'calcular núcleo de transformação elementar',
    commandType: 'resolução de equação vetorial',
    commonError: 'zerar apenas uma variável',
    statement: r`Para $T(x,y)=(x+y,0)$, qual é $\ker T$?`,
    options: [
      r`$\operatorname{span}\{(1,-1)\}$`,
      r`$\operatorname{span}\{(1,1)\}$`,
      r`$\operatorname{span}\{(1,0)\}$`,
      '$\{(0,0)\}$',
    ],
    correct: 0,
    hints: [
      'O núcleo reúne entradas enviadas ao vetor nulo.',
      'Imponha $x+y=0$.',
      'Use uma variável livre para parametrizar as soluções.',
    ],
    finalAnswer: r`$\operatorname{span}\{(1,-1)\}$`,
    explanation:
      'A segunda componente da saída já é sempre zero; a primeira impõe uma única relação. As soluções têm uma variável livre e formam a reta de direção $(1,-1)$.',
    steps: [
      ['Imponha saída nula', '$T(x,y)=(0,0)$ exige $x+y=0$.'],
      ['Isole uma variável', '$y=-x$.'],
      ['Parametrize', '$(x,y)=x(1,-1)$.'],
      ['Conclua', 'O núcleo é o espaço gerado por $(1,-1)$.'],
    ],
  }),
  q({
    topic: 'nucleo-e-imagem',
    difficulty: 'easy',
    skill: 'identificar imagem por colunas',
    commandType: 'leitura de matriz',
    commonError: 'usar as linhas para descrever a imagem',
    statement: r`A transformação $T:\mathbb R^2\to\mathbb R^3$ tem matriz $A=\begin{pmatrix}1&0\\2&0\\0&1\end{pmatrix}$. Qual conjunto gera $\operatorname{Im}T$?`,
    options: [
      r`$\{(1,2,0),(0,0,1)\}$`,
      r`$\{(1,0),(2,0),(0,1)\}$`,
      r`$\{(1,2,1)\}$`,
      r`$\{(1,0,0),(0,2,1)\}$`,
    ],
    correct: 0,
    hints: [
      'A imagem de uma transformação matricial é o espaço coluna.',
      'Leia cada coluna como a imagem de um vetor da base padrão.',
      'As duas colunas são independentes.',
    ],
    finalAnswer: r`$\{(1,2,0),(0,0,1)\}$`,
    explanation:
      'Cada saída $Ax$ é uma combinação das colunas de $A$. Por isso a imagem é gerada pelas colunas, que neste caso apontam em duas direções independentes de $\mathbb R^3$.',
    steps: [
      ['Leia a primeira coluna', '$T(e_1)=(1,2,0)$.'],
      ['Leia a segunda coluna', '$T(e_2)=(0,0,1)$.'],
      ['Descreva saídas gerais', '$T(x,y)=x(1,2,0)+y(0,0,1)$.'],
      ['Conclua', 'Esses dois vetores geram toda a imagem.'],
    ],
  }),
  q({
    topic: 'matriz-de-transformacao',
    difficulty: 'easy',
    skill: 'montar matriz pelas imagens da base',
    commandType: 'organização de imagens',
    commonError: 'dispor imagens como linhas',
    statement: r`Uma transformação linear satisfaz $T(1,0)=(2,-1)$ e $T(0,1)=(3,4)$. Qual é sua matriz na base padrão?`,
    options: [
      r`$\begin{pmatrix}2&3\\-1&4\end{pmatrix}$`,
      r`$\begin{pmatrix}2&-1\\3&4\end{pmatrix}$`,
      r`$\begin{pmatrix}3&2\\4&-1\end{pmatrix}$`,
      r`$\begin{pmatrix}-1&4\\2&3\end{pmatrix}$`,
    ],
    correct: 0,
    hints: [
      'As colunas da matriz são imagens dos vetores da base do domínio.',
      'A primeira imagem ocupa a primeira coluna.',
      'Preserve a ordem $(e_1,e_2)$.',
    ],
    finalAnswer: r`$\begin{pmatrix}2&3\\-1&4\end{pmatrix}$`,
    explanation:
      'Uma matriz de transformação é construída coluna a coluna: a coluna $j$ contém as coordenadas da imagem do $j$-ésimo vetor da base do domínio.',
    steps: [
      ['Associe a primeira coluna', '$T(e_1)=(2,-1)$.'],
      ['Associe a segunda', '$T(e_2)=(3,4)$.'],
      ['Monte a matriz', r`$[T]=\begin{pmatrix}2&3\\-1&4\end{pmatrix}$.`],
      [
        'Confira',
        'Multiplicar por $e_1$ ou $e_2$ recupera a coluna correspondente.',
      ],
    ],
  }),
  q({
    topic: 'transformacoes-geometricas',
    difficulty: 'easy',
    skill: 'reconhecer matriz de reflexão',
    commandType: 'interpretação geométrica',
    commonError: 'refletir no eixo errado',
    statement: r`Qual matriz representa a reflexão de $\mathbb R^2$ em torno do eixo $x$?`,
    options: [
      r`$\begin{pmatrix}1&0\\0&-1\end{pmatrix}$`,
      r`$\begin{pmatrix}-1&0\\0&1\end{pmatrix}$`,
      r`$\begin{pmatrix}0&1\\1&0\end{pmatrix}$`,
      r`$\begin{pmatrix}-1&0\\0&-1\end{pmatrix}$`,
    ],
    correct: 0,
    hints: [
      'Pontos do eixo $x$ devem permanecer fixos.',
      'A componente vertical deve trocar de sinal.',
      'A transformação leva $(x,y)$ em $(x,-y)$.',
    ],
    finalAnswer: r`$\begin{pmatrix}1&0\\0&-1\end{pmatrix}$`,
    explanation:
      'Refletir no eixo $x$ preserva a coordenada horizontal e inverte a vertical. Uma matriz diagonal com fatores $1$ e $-1$ produz exatamente esse efeito.',
    steps: [
      ['Determine a imagem geral', 'A reflexão envia $(x,y)$ em $(x,-y)$.'],
      ['Imagem de $e_1$', 'O vetor $(1,0)$ permanece $(1,0)$.'],
      ['Imagem de $e_2$', 'O vetor $(0,1)$ vira $(0,-1)$.'],
      ['Monte pelas colunas', 'As imagens formam a matriz diagonal indicada.'],
    ],
  }),
  q({
    topic: 'composicao-e-inversa',
    difficulty: 'easy',
    skill: 'avaliar composição de transformações',
    commandType: 'execução sequencial',
    commonError: 'trocar a ordem da composição',
    statement: r`Considere as transformações $S(x,y)=(x+y,y)$ e $T(x,y)=(2x,-y)$. Calcule $(T\circ S)(1,2)$.`,
    options: ['$(6,-2)$', '$(0,-2)$', '$(2,-2)$', '$(6,2)$'],
    correct: 0,
    hints: [
      'Em $T\circ S$, aplique $S$ primeiro.',
      'Calcule $S(1,2)$ antes de usar $T$.',
      'Confira o sinal introduzido na segunda componente por $T$.',
    ],
    finalAnswer: '$(6,-2)$',
    explanation:
      'A composição é lida da direita para a esquerda. A saída de $S$ torna-se a entrada de $T$; inverter essa ordem produz uma transformação diferente.',
    steps: [
      ['Aplique a função interna', '$S(1,2)=(3,2)$.'],
      ['Use a saída em $T$', '$T(3,2)=(2\cdot3,-2)$.'],
      ['Simplifique', 'O resultado é $(6,-2)$.'],
      [
        'Confira a ordem',
        '$S(T(1,2))=S(2,-2)=(0,-2)$ seria outra alternativa, mas outra composição.',
      ],
    ],
  }),
  q({
    topic: 'nucleo-e-imagem',
    difficulty: 'medium',
    skill: 'decidir injetividade por nulidade',
    commandType: 'dedução dimensional',
    commonError: 'usar o posto sem considerar o domínio',
    statement: r`Uma transformação linear $T:\mathbb R^4\to\mathbb R^5$ tem posto $4$. Qual conclusão é obrigatória?`,
    options: [
      '$T$ é injetiva.',
      '$T$ é sobrejetiva.',
      '$\ker T$ tem dimensão $1$.',
      '$T$ não pode existir.',
    ],
    correct: 0,
    hints: [
      'Compare o posto com a dimensão do domínio.',
      'Use posto-nulidade.',
      'Injetividade equivale a núcleo trivial.',
    ],
    finalAnswer: '$T$ é injetiva.',
    explanation:
      'O posto já ocupa todas as quatro dimensões do domínio. Pelo teorema posto-nulidade, não sobra dimensão para o núcleo, o que caracteriza a injetividade.',
    steps: [
      ['Aplique posto-nulidade', '$\dim\ker T+\operatorname{posto}T=4$.'],
      ['Substitua o posto', '$\dim\ker T+4=4$.'],
      ['Calcule a nulidade', '$\dim\ker T=0$.'],
      [
        'Interprete',
        'O núcleo é trivial, portanto $T$ é injetiva; não pode ser sobrejetiva em $\mathbb R^5$.',
      ],
    ],
  }),
  q({
    topic: 'nucleo-e-imagem',
    difficulty: 'medium',
    skill: 'determinar parâmetro para linearidade',
    commandType: 'reconstrução por axioma',
    commonError: 'testar somente aditividade',
    statement: r`Para qual valor de $c$ a função $F(x,y)=(3x,y+c)$ pode ser linear?`,
    options: ['$c=0$', '$c=1$', '$c=-1$', 'Qualquer $c$'],
    correct: 0,
    hints: [
      'Teste a imagem do vetor nulo.',
      'Uma transformação linear não pode ter deslocamento constante.',
      'A primeira componente já é homogênea; concentre-se na segunda.',
    ],
    finalAnswer: '$c=0$',
    explanation:
      'O termo constante desloca todas as saídas e faz o vetor nulo sair da origem. Somente quando ele desaparece a fórmula passa a ser dada por multiplicações lineares das entradas.',
    steps: [
      ['Calcule a imagem do zero', '$F(0,0)=(0,c)$.'],
      ['Imponha a condição linear', 'Precisamos de $F(0,0)=(0,0)$.'],
      ['Resolva o parâmetro', 'Isso exige $c=0$.'],
      [
        'Confirme a fórmula restante',
        'Com $c=0$, $F(x,y)=(3x,y)$ é uma transformação matricial linear.',
      ],
    ],
  }),
  q({
    topic: 'matriz-de-transformacao',
    difficulty: 'medium',
    skill: 'obter matriz entre bases distintas',
    commandType: 'representação coordenada',
    commonError: 'expressar saídas na base padrão',
    statement: r`Seja $T(x,y)=(x+y,x-y)$. No domínio use a base padrão e no contradomínio a base $C=\{(1,1),(1,-1)\}$. Qual é a matriz de $T$ nessas bases?`,
    options: [
      r`$\begin{pmatrix}1&0\\0&1\end{pmatrix}$`,
      r`$\begin{pmatrix}1&1\\1&-1\end{pmatrix}$`,
      r`$\begin{pmatrix}1&0\\1&0\end{pmatrix}$`,
      r`$\begin{pmatrix}0&1\\1&0\end{pmatrix}$`,
    ],
    correct: 0,
    hints: [
      'Calcule $T(e_1)$ e $T(e_2)$.',
      'Expresse cada imagem na base $C$, não na padrão.',
      'As coordenadas obtidas formam as colunas.',
    ],
    finalAnswer: r`$\begin{pmatrix}1&0\\0&1\end{pmatrix}$`,
    explanation:
      'As imagens dos vetores padrão coincidem exatamente com os vetores da base ordenada $C$. Assim suas coordenadas em $C$ são os vetores padrão, produzindo a identidade.',
    steps: [
      ['Imagem de $e_1$', '$T(1,0)=(1,1)=c_1$, então $[T(e_1)]_C=(1,0)$.'],
      ['Imagem de $e_2$', '$T(0,1)=(1,-1)=c_2$, então $[T(e_2)]_C=(0,1)$.'],
      ['Monte as colunas', 'As colunas são $(1,0)$ e $(0,1)$.'],
      ['Conclua', 'A matriz relativa é a identidade $2\times2$.'],
    ],
  }),
  q({
    topic: 'composicao-e-inversa',
    difficulty: 'medium',
    skill: 'encontrar fórmula da transformação inversa',
    commandType: 'resolução de saída',
    commonError: 'inverter cada coeficiente isoladamente',
    statement: r`A transformação $T(x,y)=(x+y,x-y)$ é invertível. Qual é $T^{-1}(u,v)$?`,
    options: [
      r`$((u+v)/2,(u-v)/2)$`,
      r`$(u+v,u-v)$`,
      r`$((u-v)/2,(u+v)/2)$`,
      r`$(u-v,u+v)$`,
    ],
    correct: 0,
    hints: [
      'Trate $u=x+y$ e $v=x-y$ como um sistema.',
      'Some as duas equações para isolar $x$.',
      'Subtraia a segunda da primeira para isolar $y$.',
    ],
    finalAnswer: r`$((u+v)/2,(u-v)/2)$`,
    explanation:
      'A inversa recupera as entradas a partir das duas combinações de saída. Somar e subtrair as equações separa as variáveis, e o fator dois precisa ser dividido.',
    steps: [
      ['Escreva o sistema', '$u=x+y$ e $v=x-y$.'],
      ['Isole $x$', '$u+v=2x$, então $x=(u+v)/2$.'],
      ['Isole $y$', '$u-v=2y$, então $y=(u-v)/2$.'],
      [
        'Confira',
        'Substituir essas expressões em $T$ recupera exatamente $(u,v)$.',
      ],
    ],
  }),
  q({
    topic: 'nucleo-e-imagem',
    difficulty: 'medium',
    skill: 'relacionar núcleo de composição',
    commandType: 'verificação de inclusão',
    commonError: 'afirmar igualdade sem hipótese adicional',
    statement: r`Para transformações lineares compatíveis $S$ e $T$, qual inclusão é sempre verdadeira?`,
    options: [
      '$\ker T\subseteq\ker(S\circ T)$',
      '$\ker S\subseteq\ker T$',
      '$\operatorname{Im}S\subseteq\ker T$',
      '$\ker(S\circ T)\subseteq\ker T$',
    ],
    correct: 0,
    hints: [
      'Comece com um vetor que $T$ envia a zero.',
      'Depois aplique $S$ ao resultado.',
      'Toda transformação linear envia zero a zero.',
    ],
    finalAnswer: '$\ker T\subseteq\ker(S\circ T)$',
    explanation:
      'Se $T$ já anula um vetor, qualquer transformação linear aplicada depois continuará produzindo zero. A inclusão inversa exigiria que $S$ não anulasse novas direções.',
    steps: [
      ['Escolha um vetor do núcleo', 'Seja $v\in\ker T$, então $T(v)=0$.'],
      ['Aplique a composição', '$(S\circ T)(v)=S(T(v))=S(0)$.'],
      ['Use linearidade', '$S(0)=0$.'],
      ['Conclua', 'Logo $v\in\ker(S\circ T)$ e a inclusão sempre vale.'],
    ],
  }),
  q({
    topic: 'transformacoes-geometricas',
    difficulty: 'medium',
    skill: 'interpretar determinante de composição geométrica',
    commandType: 'comparação de efeitos',
    commonError: 'confundir rotação com reflexão',
    statement: r`Uma transformação do plano é composta por uma rotação e depois uma reflexão. Qual deve ser o sinal do determinante de sua matriz?`,
    options: ['Negativo', 'Positivo', 'Zero', 'Depende do ângulo da rotação'],
    correct: 0,
    hints: [
      'Rotações preservam orientação.',
      'Reflexões invertem orientação.',
      'O determinante da composição é o produto dos determinantes.',
    ],
    finalAnswer: 'Negativo',
    explanation:
      'Toda rotação plana tem determinante $1$, enquanto uma reflexão tem determinante $-1$. O produto é negativo independentemente do ângulo escolhido para a rotação.',
    steps: [
      ['Analise a rotação', 'Sua matriz tem determinante $1$.'],
      ['Analise a reflexão', 'Sua matriz tem determinante $-1$.'],
      ['Use multiplicatividade', '$\det(Rot\cdot Ref)=1\cdot(-1)=-1$.'],
      [
        'Interprete',
        'A composição final reverte orientação, portanto o sinal é negativo.',
      ],
    ],
  }),
  q({
    topic: 'matriz-de-transformacao',
    difficulty: 'hard',
    skill: 'determinar transformação pelas imagens de uma base',
    commandType: 'reconstrução de fórmula',
    commonError: 'tratar dados em base não padrão como colunas padrão',
    statement: r`Uma transformação linear $T:\mathbb R^2\to\mathbb R^2$ satisfaz $T(1,1)=(2,0)$ e $T(1,-1)=(0,4)$. Qual é $T(3,1)$?`,
    options: ['$(4,4)$', '$(6,4)$', '$(2,8)$', '$(4,2)$'],
    correct: 0,
    hints: [
      'Expresse $(3,1)$ na base formada pelos dois vetores dados.',
      'Resolva $a(1,1)+b(1,-1)=(3,1)$.',
      'Use linearidade sobre a combinação encontrada.',
    ],
    finalAnswer: '$(4,4)$',
    explanation:
      'As imagens de uma base determinam a transformação inteira. Primeiro escrevemos a entrada nessa base; depois aplicamos os mesmos coeficientes às imagens fornecidas.',
    steps: [
      ['Calcule as coordenadas', '$a+b=3$ e $a-b=1$, então $a=2$ e $b=1$.'],
      ['Escreva a entrada', '$(3,1)=2(1,1)+(1,-1)$.'],
      ['Aplique linearidade', '$T(3,1)=2(2,0)+(0,4)$.'],
      ['Some', 'O resultado é $(4,4)$.'],
    ],
  }),
  q({
    topic: 'nucleo-e-imagem',
    difficulty: 'hard',
    skill: 'restringir transformação para obter isomorfismo',
    commandType: 'análise de restrição',
    commonError:
      'presumir que sobrejetividade implica injetividade sem dimensões iguais',
    statement: r`Se $T:\mathbb R^3\to\mathbb R^2$ é sobrejetiva e $U$ é um complemento de $\ker T$ em $\mathbb R^3$, o que vale para a restrição $T|_U:U\to\mathbb R^2$?`,
    options: [
      'É um isomorfismo.',
      'É a transformação nula.',
      'Não é injetiva.',
      'Sua imagem tem dimensão $1$.',
    ],
    correct: 0,
    hints: [
      'Use posto-nulidade para descobrir a dimensão do núcleo.',
      'Um complemento tem interseção trivial com o núcleo.',
      'A restrição mantém a mesma imagem porque toda classe módulo núcleo tem representante em $U$.',
    ],
    finalAnswer: 'É um isomorfismo.',
    explanation:
      'A sobrejetividade dá posto dois e núcleo unidimensional. O complemento $U$ tem dimensão dois, não contém vetores não nulos anulados e ainda representa todas as saídas, tornando a restrição bijetiva.',
    steps: [
      ['Calcule dimensões', '$\dim\ker T=3-2=1$, então $\dim U=2$.'],
      [
        'Teste o núcleo restrito',
        '$U\cap\ker T=\{0\}$, logo $T|_U$ é injetiva.',
      ],
      [
        'Use dimensões iguais',
        'Uma aplicação injetiva de $U$ bidimensional em $\mathbb R^2$ é sobrejetiva.',
      ],
      ['Conclua', 'A restrição é linear e bijetiva, portanto um isomorfismo.'],
    ],
  }),
  q({
    topic: 'composicao-e-inversa',
    difficulty: 'hard',
    skill: 'calcular núcleo de composição por pré-imagem',
    commandType: 'análise de composição',
    commonError: 'somar diretamente os núcleos',
    statement: r`Se $T(x,y,z)=(x+y,z)$ e $S(u,v)=u+v$, qual é uma equação para $\ker(S\circ T)$?`,
    options: ['$x+y+z=0$', '$x+y=0$ e $z=0$', '$x=0$', '$y+z=0$'],
    correct: 0,
    hints: [
      'Calcule primeiro a fórmula da composição.',
      'A saída de $T$ tem duas componentes que entram em $S$.',
      'Depois imponha que o escalar resultante seja zero.',
    ],
    finalAnswer: '$x+y+z=0$',
    explanation:
      'O núcleo da composição não exige necessariamente que $T$ produza o vetor zero; basta que sua saída pertença ao núcleo de $S$. Substituir as fórmulas revela uma única equação.',
    steps: [
      ['Aplique $T$', '$T(x,y,z)=(x+y,z)$.'],
      ['Aplique $S$', '$S(T(x,y,z))=(x+y)+z$.'],
      ['Imponha o núcleo', 'Precisamos de $x+y+z=0$.'],
      [
        'Compare',
        'Exigir $x+y=0$ e $z=0$ seria mais restritivo do que o necessário.',
      ],
    ],
  }),
  q({
    topic: 'composicao-e-inversa',
    difficulty: 'hard',
    skill: 'relacionar matrizes semelhantes',
    commandType: 'derivação de identidade',
    commonError: 'posicionar a inversa do lado errado',
    statement: r`A matriz $P$ converte coordenadas da base $C$ para a base $B$. Se $A_B$ representa um operador na base $B$, qual matriz o representa na base $C$?`,
    options: ['$P^{-1}A_BP$', '$PA_BP^{-1}$', '$P^{-1}A_B$', '$A_BP^{-1}$'],
    correct: 0,
    hints: [
      'Comece com coordenadas em $C$ e converta-as para $B$.',
      'Aplique $A_B$ no sistema de coordenadas correto.',
      'Converta a saída de volta usando $P^{-1}$.',
    ],
    finalAnswer: '$P^{-1}A_BP$',
    explanation:
      'Mudar a representação de um operador exige converter a entrada, aplicar a matriz antiga e desfazer a conversão na saída. Essa conjugação é a relação de semelhança.',
    steps: [
      ['Converta a entrada', '$[v]_B=P[v]_C$.'],
      ['Aplique o operador', '$[T(v)]_B=A_BP[v]_C$.'],
      ['Volte para $C$', '$[T(v)]_C=P^{-1}A_BP[v]_C$.'],
      ['Identifique', 'Logo $A_C=P^{-1}A_BP$.'],
    ],
  }),
  q({
    topic: 'transformacoes-geometricas',
    difficulty: 'hard',
    skill: 'analisar projeção idempotente',
    commandType: 'diagnóstico por identidade',
    commonError: 'confundir projeção com reflexão',
    statement: r`Uma transformação linear $P$ satisfaz $P^2=P$. Se $v=P(u)$ pertence à imagem de $P$, o que necessariamente ocorre ao aplicar $P$ novamente?`,
    options: ['$P(v)=v$', '$P(v)=0$', '$P(v)=-v$', '$P(v)=u$'],
    correct: 0,
    hints: [
      'Substitua $v=P(u)$ na expressão $P(v)$.',
      'Use a identidade $P^2=P$.',
      'Interprete o resultado para vetores que já estão na imagem.',
    ],
    finalAnswer: '$P(v)=v$',
    explanation:
      'A identidade idempotente caracteriza projeções: depois que um vetor chega ao subespaço imagem, novas aplicações não o alteram. Isso não exige que a projeção seja ortogonal.',
    steps: [
      ['Use a origem de $v$', '$v=P(u)$.'],
      ['Aplique $P$', '$P(v)=P(P(u))=P^2(u)$.'],
      ['Use idempotência', '$P^2(u)=P(u)$.'],
      [
        'Conclua',
        '$P(v)=v$, então a imagem é o conjunto de pontos fixos de $P$.',
      ],
    ],
  }),
  q({
    topic: 'matriz-de-transformacao',
    difficulty: 'hard',
    skill: 'usar base para calcular potência de operador',
    commandType: 'estratégia por representação',
    commonError: 'multiplicar vetores em vez da matriz diagonal',
    statement: r`Um operador $T$ satisfaz $T(v_1)=2v_1$ e $T(v_2)=-v_2$, onde $(v_1,v_2)$ é uma base. Se $w=3v_1+4v_2$, qual é $T^3(w)$?`,
    options: ['$24v_1-4v_2$', '$6v_1-4v_2$', '$24v_1+4v_2$', '$8v_1-v_2$'],
    correct: 0,
    hints: [
      'Cada vetor da base permanece em sua própria direção sob $T$.',
      'Ao aplicar $T$ três vezes, eleve os fatores escalares à terceira potência.',
      'Mantenha os coeficientes originais de $w$.',
    ],
    finalAnswer: '$24v_1-4v_2$',
    explanation:
      'Na base fornecida, a matriz de $T$ é diagonal. Potências do operador elevam cada fator diagonal à potência correspondente, sem misturar as duas direções.',
    steps: [
      ['Use linearidade', '$T^3(w)=3T^3(v_1)+4T^3(v_2)$.'],
      ['Calcule a primeira direção', '$T^3(v_1)=2^3v_1=8v_1$.'],
      ['Calcule a segunda', '$T^3(v_2)=(-1)^3v_2=-v_2$.'],
      ['Combine', '$3\cdot8v_1+4(-v_2)=24v_1-4v_2$.'],
    ],
  }),
];
