// Original drafts authored with Codex, 2026-09-07. Independent review pending.
const r = String.raw;
const q = (
  topic,
  difficulty,
  statement,
  options,
  steps,
  integrand,
  primitives,
) => ({
  topic,
  difficulty,
  statement,
  options,
  steps,
  verification: { kind: 'antiderivative', integrand, primitives },
});
export default [
  q(
    'partes',
    'easy',
    r`Calcule $\int xe^x\,dx$.`,
    [r`$e^x(x-1)+C$`, r`$xe^x+C$`, r`$e^x(x+1)+C$`, r`$x^2e^x/2+C$`],
    [
      r`Escolha $u=x$ e $dv=e^x dx$, logo $du=dx$ e $v=e^x$.`,
      r`Por partes, $\int xe^x dx=xe^x-\int e^x dx=e^x(x-1)+C$.`,
    ],
    'x*exp(x)',
    ['exp(x)*(x-1)', 'x*exp(x)', 'exp(x)*(x+1)', 'x**2*exp(x)/2'],
  ),
  q(
    'partes',
    'easy',
    r`Para $x>0$, calcule $\int\ln x\,dx$.`,
    [r`$x\ln x-x+C$`, r`$x\ln x+C$`, r`$1/x+C$`, r`$x\ln x+x+C$`],
    [
      r`Use $u=\ln x$ e $dv=dx$, de modo que $du=dx/x$ e $v=x$.`,
      r`A fórmula dá $x\ln x-\int 1\,dx=x\ln x-x+C$.`,
    ],
    'log(x)',
    ['x*log(x)-x', 'x*log(x)', '1/x', 'x*log(x)+x'],
  ),
  q(
    'partes',
    'medium',
    r`Calcule $\int x\cos x\,dx$.`,
    [
      r`$x\sin x+\cos x+C$`,
      r`$x\sin x-\cos x+C$`,
      r`$x\cos x-\sin x+C$`,
      r`$\sin x+C$`,
    ],
    [
      r`Tome $u=x$, $dv=\cos x\,dx$. Então $v=\sin x$.`,
      r`Obtemos $x\sin x-\int\sin x\,dx=x\sin x+\cos x+C$.`,
    ],
    'x*cos(x)',
    ['x*sin(x)+cos(x)', 'x*sin(x)-cos(x)', 'x*cos(x)-sin(x)', 'sin(x)'],
  ),
  q(
    'partes',
    'medium',
    r`Calcule $\int xe^{2x}\,dx$.`,
    [
      r`$e^{2x}(x/2-1/4)+C$`,
      r`$e^{2x}(x-1)+C$`,
      r`$xe^{2x}/2+C$`,
      r`$e^{2x}(x/2+1/4)+C$`,
    ],
    [
      r`Com $u=x$ e $dv=e^{2x}dx$, temos $v=e^{2x}/2$.`,
      r`Subtraia $\frac12\int e^{2x}dx$ de $xe^{2x}/2$, obtendo $e^{2x}(x/2-1/4)+C$.`,
    ],
    'x*exp(2*x)',
    [
      'exp(2*x)*(x/2-1/4)',
      'exp(2*x)*(x-1)',
      'x*exp(2*x)/2',
      'exp(2*x)*(x/2+1/4)',
    ],
  ),
  q(
    'partes',
    'medium',
    r`Para $x>0$, calcule $\int x\ln x\,dx$.`,
    [
      r`$x^2\ln x/2-x^2/4+C$`,
      r`$x^2\ln x/2-x^2/2+C$`,
      r`$x^2\ln x-x^2+C$`,
      r`$x^2\ln x/2+C$`,
    ],
    [
      r`Escolha $u=\ln x$ e $dv=x\,dx$, com $v=x^2/2$.`,
      r`O termo restante é $\frac12\int x\,dx=x^2/4$, que deve ser subtraído de $x^2\ln x/2$.`,
    ],
    'x*log(x)',
    [
      'x**2*log(x)/2-x**2/4',
      'x**2*log(x)/2-x**2/2',
      'x**2*log(x)-x**2',
      'x**2*log(x)/2',
    ],
  ),
  q(
    'partes',
    'hard',
    r`Calcule $\int x^2e^x\,dx$.`,
    [
      r`$e^x(x^2-2x+2)+C$`,
      r`$e^x(x^2-2x)+C$`,
      r`$e^x(x^2+2x+2)+C$`,
      r`$e^x(x^2-x+1)+C$`,
    ],
    [
      r`Uma integração por partes resulta em $x^2e^x-2\int xe^x dx$.`,
      r`Repita por partes: $\int xe^x dx=e^x(x-1)$. Substituindo, resulta $e^x(x^2-2x+2)+C$.`,
    ],
    'x**2*exp(x)',
    [
      'exp(x)*(x**2-2*x+2)',
      'exp(x)*(x**2-2*x)',
      'exp(x)*(x**2+2*x+2)',
      'exp(x)*(x**2-x+1)',
    ],
  ),
  q(
    'partes',
    'hard',
    r`Calcule $\int e^x\sin x\,dx$.`,
    [
      r`$e^x(\sin x-\cos x)/2+C$`,
      r`$e^x(\sin x+\cos x)/2+C$`,
      r`$e^x(\sin x-\cos x)+C$`,
      r`$e^x\sin x+C$`,
    ],
    [
      r`Defina $I=\int e^x\sin x dx$. Por partes, $I=e^x\sin x-\int e^x\cos x dx$.`,
      r`A segunda integral é $e^x\cos x+I$. Logo $2I=e^x(\sin x-\cos x)$; divida por dois.`,
    ],
    'exp(x)*sin(x)',
    [
      'exp(x)*(sin(x)-cos(x))/2',
      'exp(x)*(sin(x)+cos(x))/2',
      'exp(x)*(sin(x)-cos(x))',
      'exp(x)*sin(x)',
    ],
  ),
  q(
    'fracoes',
    'easy',
    r`Em um intervalo que não contém $0$ nem $-1$, calcule $\int\frac{dx}{x(x+1)}$.`,
    [
      r`$\ln|x|-\ln|x+1|+C$`,
      r`$\ln|x|+\ln|x+1|+C$`,
      r`$-1/[x(x+1)]+C$`,
      r`$\ln|x+1|-\ln|x|+C$`,
    ],
    [
      r`Decomponha $1/[x(x+1)]=1/x-1/(x+1)$.`,
      r`Integre cada fração: $\ln|x|-\ln|x+1|+C$. Os módulos permitem os intervalos admissíveis.`,
    ],
    '1/(x*(x+1))',
    ['log(x)-log(x+1)', 'log(x)+log(x+1)', '-1/(x*(x+1))', 'log(x+1)-log(x)'],
  ),
  q(
    'fracoes',
    'easy',
    r`Para $x>2$, calcule $\int\frac{3}{(x-2)(x+1)}\,dx$.`,
    [
      r`$\ln(x-2)-\ln(x+1)+C$`,
      r`$3\ln(x-2)-3\ln(x+1)+C$`,
      r`$\ln(x-2)+\ln(x+1)+C$`,
      r`$\ln(x+1)-\ln(x-2)+C$`,
    ],
    [
      r`Busque $A/(x-2)+B/(x+1)$. A identidade $3=A(x+1)+B(x-2)$ dá $A=1$, $B=-1$.`,
      r`Integre as duas parcelas; como $x>2$, os argumentos dos logaritmos são positivos.`,
    ],
    '3/((x-2)*(x+1))',
    [
      'log(x-2)-log(x+1)',
      '3*log(x-2)-3*log(x+1)',
      'log(x-2)+log(x+1)',
      'log(x+1)-log(x-2)',
    ],
  ),
  q(
    'fracoes',
    'medium',
    r`Para $x>0$, calcule $\int\frac{2x+3}{x(x+1)}\,dx$.`,
    [
      r`$3\ln x-\ln(x+1)+C$`,
      r`$2\ln x+3\ln(x+1)+C$`,
      r`$\ln x+\ln(x+1)+C$`,
      r`$3\ln x+\ln(x+1)+C$`,
    ],
    [
      r`A identidade $2x+3=A(x+1)+Bx$ fornece $A=3$ e $B=-1$.`,
      r`Integre $3/x-1/(x+1)$ para obter $3\ln x-\ln(x+1)+C$.`,
    ],
    '(2*x+3)/(x*(x+1))',
    [
      '3*log(x)-log(x+1)',
      '2*log(x)+3*log(x+1)',
      'log(x)+log(x+1)',
      '3*log(x)+log(x+1)',
    ],
  ),
  q(
    'fracoes',
    'medium',
    r`Para $x>1$, calcule $\int\frac{dx}{x^2-1}$.`,
    [
      r`$\frac12\ln(x-1)-\frac12\ln(x+1)+C$`,
      r`$\ln(x-1)-\ln(x+1)+C$`,
      r`$\frac12\ln(x^2-1)+C$`,
      r`$\arctan x+C$`,
    ],
    [
      r`Fatore $x^2-1=(x-1)(x+1)$. As frações têm coeficientes $1/2$ e $-1/2$.`,
      r`Integre $1/[2(x-1)]-1/[2(x+1)]$, conservando o fator $1/2$.`,
    ],
    '1/(x**2-1)',
    ['log(x-1)/2-log(x+1)/2', 'log(x-1)-log(x+1)', 'log(x**2-1)/2', 'atan(x)'],
  ),
  q(
    'fracoes',
    'hard',
    r`Para $x>0$, calcule $\int\frac{dx}{x(x+1)^2}$.`,
    [
      r`$\ln x-\ln(x+1)+1/(x+1)+C$`,
      r`$\ln x-\ln(x+1)-1/(x+1)+C$`,
      r`$\ln x-2\ln(x+1)+C$`,
      r`$1/(x+1)+C$`,
    ],
    [
      r`O fator repetido exige $A/x+B/(x+1)+D/(x+1)^2$. A identidade dos numeradores dá $A=1$, $B=-1$, $D=-1$.`,
      r`A primitiva de $-(x+1)^{-2}$ é $+(x+1)^{-1}$. Some esse termo aos dois logaritmos.`,
    ],
    '1/(x*(x+1)**2)',
    [
      'log(x)-log(x+1)+1/(x+1)',
      'log(x)-log(x+1)-1/(x+1)',
      'log(x)-2*log(x+1)',
      '1/(x+1)',
    ],
  ),
  q(
    'fracoes',
    'hard',
    r`Para $x>0$, calcule $\int\frac{x^2+1}{x(x+1)}\,dx$.`,
    [
      r`$x+\ln x-2\ln(x+1)+C$`,
      r`$\ln x-2\ln(x+1)+C$`,
      r`$x+\ln x+2\ln(x+1)+C$`,
      r`$x-\ln x+C$`,
    ],
    [
      r`Faça primeiro a divisão: $(x^2+1)/(x^2+x)=1+(1-x)/(x(x+1))$.`,
      r`A parte própria é $1/x-2/(x+1)$. Integrando com o termo polinomial, resulta $x+\ln x-2\ln(x+1)+C$.`,
    ],
    '(x**2+1)/(x*(x+1))',
    [
      'x+log(x)-2*log(x+1)',
      'log(x)-2*log(x+1)',
      'x+log(x)+2*log(x+1)',
      'x-log(x)',
    ],
  ),
  q(
    'trigonometricas',
    'easy',
    r`Calcule $\int\sin^2x\,dx$.`,
    [
      r`$x/2-\sin(2x)/4+C$`,
      r`$x/2+\sin(2x)/4+C$`,
      r`$-\cos^3x/3+C$`,
      r`$x-\sin(2x)/2+C$`,
    ],
    [
      r`Use a identidade $\sin^2x=(1-\cos2x)/2$.`,
      r`A primitiva de $\cos2x$ é $\sin2x/2$; logo o segundo termo é $-\sin2x/4$.`,
    ],
    'sin(x)**2',
    ['x/2-sin(2*x)/4', 'x/2+sin(2*x)/4', '-cos(x)**3/3', 'x-sin(2*x)/2'],
  ),
  q(
    'trigonometricas',
    'easy',
    r`Calcule $\int\cos^2x\,dx$.`,
    [
      r`$x/2+\sin(2x)/4+C$`,
      r`$x/2-\sin(2x)/4+C$`,
      r`$\sin^3x/3+C$`,
      r`$x/2+\sin(2x)/2+C$`,
    ],
    [
      r`Escreva $\cos^2x=(1+\cos2x)/2$.`,
      r`Integre termo a termo, incluindo o fator da regra da cadeia: $x/2+\sin2x/4+C$.`,
    ],
    'cos(x)**2',
    ['x/2+sin(2*x)/4', 'x/2-sin(2*x)/4', 'sin(x)**3/3', 'x/2+sin(2*x)/2'],
  ),
  q(
    'trigonometricas',
    'medium',
    r`Calcule $\int\sin^3x\,dx$.`,
    [
      r`$-\cos x+\cos^3x/3+C$`,
      r`$-\cos x-\cos^3x/3+C$`,
      r`$\sin^4x/4+C$`,
      r`$\cos x-\cos^3x/3+C$`,
    ],
    [
      r`Separe $\sin x$ e use $\sin^2x=1-\cos^2x$. Com $u=\cos x$, $du=-\sin x dx$.`,
      r`Integre $-\int(1-u^2)du=-u+u^3/3+C$ e retorne a $x$.`,
    ],
    'sin(x)**3',
    [
      '-cos(x)+cos(x)**3/3',
      '-cos(x)-cos(x)**3/3',
      'sin(x)**4/4',
      'cos(x)-cos(x)**3/3',
    ],
  ),
  q(
    'trigonometricas',
    'medium',
    r`Calcule $\int\cos^3x\,dx$.`,
    [
      r`$\sin x-\sin^3x/3+C$`,
      r`$\sin x+\sin^3x/3+C$`,
      r`$\cos^4x/4+C$`,
      r`$-\sin x+\sin^3x/3+C$`,
    ],
    [
      r`Escreva $\cos^3x=(1-\sin^2x)\cos x$. Use $u=\sin x$.`,
      r`A integral vira $\int(1-u^2)du=u-u^3/3+C$.`,
    ],
    'cos(x)**3',
    [
      'sin(x)-sin(x)**3/3',
      'sin(x)+sin(x)**3/3',
      'cos(x)**4/4',
      '-sin(x)+sin(x)**3/3',
    ],
  ),
  q(
    'trigonometricas',
    'medium',
    r`Em $(-\pi/2,\pi/2)$, calcule $\int\tan^2x\,dx$.`,
    [r`$\tan x-x+C$`, r`$\tan x+x+C$`, r`$\tan^3x/3+C$`, r`$\sec^2x+C$`],
    [
      r`A identidade $1+\tan^2x=\sec^2x$ fornece $\tan^2x=\sec^2x-1$.`,
      r`Integre as parcelas: a primitiva de $\sec^2x$ é $\tan x$, resultando $\tan x-x+C$.`,
    ],
    'tan(x)**2',
    ['tan(x)-x', 'tan(x)+x', 'tan(x)**3/3', '1/cos(x)**2'],
  ),
  q(
    'trigonometricas',
    'hard',
    r`Calcule $\int\sin^2x\cos^2x\,dx$.`,
    [
      r`$x/8-\sin(4x)/32+C$`,
      r`$x/4-\sin(4x)/16+C$`,
      r`$x/8+\sin(4x)/32+C$`,
      r`$\sin^3x\cos^3x/3+C$`,
    ],
    [
      r`Use $\sin x\cos x=\sin2x/2$, depois $\sin^22x=(1-\cos4x)/2$. O integrando é $(1-\cos4x)/8$.`,
      r`Integre; a frequência quatro introduz mais um fator $1/4$, dando $x/8-\sin4x/32+C$.`,
    ],
    'sin(x)**2*cos(x)**2',
    [
      'x/8-sin(4*x)/32',
      'x/4-sin(4*x)/16',
      'x/8+sin(4*x)/32',
      'sin(x)**3*cos(x)**3/3',
    ],
  ),
  q(
    'trigonometricas',
    'hard',
    r`Em $(-\pi/2,\pi/2)$, calcule $\int\sec^4x\,dx$.`,
    [
      r`$\tan x+\tan^3x/3+C$`,
      r`$\tan x-\tan^3x/3+C$`,
      r`$\tan^5x/5+C$`,
      r`$\sec^5x/5+C$`,
    ],
    [
      r`Separe $\sec^2x\,dx$ e substitua $u=\tan x$, usando $\sec^2x=1+\tan^2x$.`,
      r`Resta $\int(1+u^2)du=u+u^3/3+C$. Volte a $x$.`,
    ],
    '1/cos(x)**4',
    [
      'tan(x)+tan(x)**3/3',
      'tan(x)-tan(x)**3/3',
      'tan(x)**5/5',
      '1/(5*cos(x)**5)',
    ],
  ),
];
