const r = String.raw;
const q = (
  topic,
  difficulty,
  statement,
  options,
  steps,
  integrand,
  lower,
  upper,
  expected,
) => ({
  topic,
  difficulty,
  statement,
  options,
  steps,
  verification: { kind: 'improper', integrand, lower, upper, expected },
});
export default [
  q(
    'infinitos',
    'easy',
    r`Calcule $\int_1^\infty x^{-2}\,dx$.`,
    ['$1$', '$2$', '$0$', 'Diverge.'],
    [
      r`Substitua o limite infinito por $b$ e use a primitiva $-1/x$.`,
      r`O valor é $\lim_{b\to\infty}(1-1/b)=1$.`,
    ],
    'x**-2',
    '1',
    'oo',
    '1',
  ),
  q(
    'infinitos',
    'easy',
    r`Calcule $\int_0^\infty e^{-2x}\,dx$.`,
    ['$1/2$', '$2$', '$1$', 'Diverge.'],
    [
      r`A primitiva é $-e^{-2x}/2$. Avalie entre $0$ e $b$.`,
      r`Como $e^{-2b}\to0$, a integral vale $1/2$.`,
    ],
    'exp(-2*x)',
    '0',
    'oo',
    '1/2',
  ),
  q(
    'infinitos',
    'medium',
    r`Qual é o comportamento de $\int_1^\infty dx/x$?`,
    [r`Diverge para $+\infty$.`, '$0$', '$1$', '$-1$'],
    [
      r`Em $[1,b]$, a integral é $\ln b$.`,
      r`Embora $1/x\to0$, $\ln b\to+\infty$; portanto a integral diverge.`,
    ],
    '1/x',
    '1',
    'oo',
    'oo',
  ),
  q(
    'infinitos',
    'medium',
    r`Calcule $\int_2^\infty 3x^{-2}\,dx$.`,
    ['$3/2$', '$3$', '$2/3$', 'Diverge.'],
    [r`Use a primitiva $-3/x$ em $[2,b]$.`, r`O limite de $3/2-3/b$ é $3/2$.`],
    '3/x**2',
    '2',
    'oo',
    '3/2',
  ),
  q(
    'infinitos',
    'hard',
    r`Calcule $\int_1^\infty\frac{\ln x}{x^2}\,dx$.`,
    ['$1$', '$0$', '$2$', 'Diverge.'],
    [
      r`Por partes, uma primitiva é $-(\ln x+1)/x$.`,
      r`Como $\ln b/b\to0$, o limite da avaliação entre $1$ e $b$ é $1$.`,
    ],
    'log(x)/x**2',
    '1',
    'oo',
    '1',
  ),
  q(
    'infinitos',
    'hard',
    r`Calcule $\int_{-\infty}^{\infty}\frac{dx}{1+x^2}$ no sentido usual de integral imprópria.`,
    [r`$\pi$`, r`$\pi/2$`, '$0$', 'Diverge.'],
    [
      r`Separe em $0$: ambas as integrais laterais precisam convergir. A primitiva é $\arctan x$.`,
      r`Cada lado vale $\pi/2$; somando, o resultado é $\pi$.`,
    ],
    '1/(1+x**2)',
    '-oo',
    'oo',
    'pi',
  ),
  q(
    'descontinuidades',
    'easy',
    r`Calcule $\int_0^1 x^{-1/2}\,dx$.`,
    ['$2$', '$1/2$', '$1$', 'Diverge.'],
    [
      r`Use $a>0$ no lugar de zero. A primitiva é $2\sqrt{x}$.`,
      r`O limite de $2-2\sqrt a$ quando $a\to0^+$ é $2$.`,
    ],
    '1/sqrt(x)',
    '0',
    '1',
    '2',
  ),
  q(
    'descontinuidades',
    'easy',
    r`Qual é o comportamento de $\int_0^1 dx/x$?`,
    [r`Diverge para $+\infty$.`, '$0$', '$1$', '$-1$'],
    [
      r`Em $[a,1]$ a integral é $-\ln a$.`,
      r`Quando $a\to0^+$, $-\ln a\to+\infty$.`,
    ],
    '1/x',
    '0',
    '1',
    'oo',
  ),
  q(
    'descontinuidades',
    'medium',
    r`Calcule $\int_0^4\frac{dx}{\sqrt{4-x}}$.`,
    ['$4$', '$2$', '$8$', 'Diverge.'],
    [
      r`A singularidade fica no limite superior; integre até $b<4$ usando $-2\sqrt{4-x}$.`,
      r`A avaliação é $4-2\sqrt{4-b}$, que tende a $4$.`,
    ],
    '1/sqrt(4-x)',
    '0',
    '4',
    '4',
  ),
  q(
    'descontinuidades',
    'medium',
    r`Calcule $\int_0^1\ln x\,dx$.`,
    ['$-1$', '$1$', '$0$', r`Diverge para $-\infty$.`],
    [
      r`Uma primitiva é $x\ln x-x$. Avalie de $a>0$ até $1$.`,
      r`Como $a\ln a\to0$, o resultado é $-1$. Um integrando ilimitado pode ter integral finita.`,
    ],
    'log(x)',
    '0',
    '1',
    '-1',
  ),
  q(
    'descontinuidades',
    'hard',
    r`Calcule $\int_{-1}^1\frac{dx}{\sqrt{|x|}}$.`,
    ['$4$', '$2$', '$0$', 'Diverge.'],
    [
      r`Separe no ponto singular $0$. Por simetria, cada integral lateral equivale a $\int_0^1x^{-1/2}dx$.`,
      r`Cada lado vale $2$; os limites existem separadamente e a soma é $4$.`,
    ],
    '1/sqrt(Abs(x))',
    '-1',
    '1',
    '4',
  ),
  q(
    'descontinuidades',
    'hard',
    r`No sentido usual (não valor principal), $\int_{-1}^1dx/x$ é:`,
    [
      'Divergente, pois as integrais laterais não são finitas.',
      '$0$, por simetria.',
      '$2$',
      '$-2$',
    ],
    [
      r`A integral de $-1$ até $-a$ tende a $-\infty$, enquanto a de $a$ até $1$ tende a $+\infty$.`,
      r`Não se pode cancelar infinitos. O valor principal simétrico é zero, mas a integral imprópria usual não existe.`,
    ],
    '1/x',
    '-1',
    '1',
    'divergent-split',
  ),
];
