const r = String.raw;
const q = (
  topic,
  difficulty,
  statement,
  options,
  steps,
  expression,
  start,
  expected,
) => ({
  topic,
  difficulty,
  statement,
  options,
  steps,
  verification: { kind: 'series', expression, start, expected },
});
export default [
  q(
    'geometricas',
    'easy',
    r`Calcule $\sum_{n=0}^\infty(1/4)^n$.`,
    ['$4/3$', '$1/3$', '$4$', 'Diverge.'],
    [
      r`A razão é $1/4$, com módulo menor que um, e o primeiro termo é $1$.`,
      r`A soma é $1/(1-1/4)=4/3$.`,
    ],
    '(1/4)**n',
    0,
    '4/3',
  ),
  q(
    'geometricas',
    'easy',
    r`Calcule $\sum_{n=1}^\infty(1/2)^n$.`,
    ['$1$', '$2$', '$1/2$', 'Diverge.'],
    [
      r`O primeiro termo é $1/2$ e a razão é $1/2$.`,
      r`Use primeiro termo dividido por $1-r$: $(1/2)/(1-1/2)=1$.`,
    ],
    '(1/2)**n',
    1,
    '1',
  ),
  q(
    'geometricas',
    'medium',
    r`Calcule $\sum_{n=0}^\infty3(-1/2)^n$.`,
    ['$2$', '$6$', '$-2$', 'Diverge.'],
    [r`Apesar dos sinais alternados, $|r|=1/2<1$.`, r`A soma é $3/(1+1/2)=2$.`],
    '3*(-1/2)**n',
    0,
    '2',
  ),
  q(
    'geometricas',
    'medium',
    r`Calcule $\sum_{n=2}^\infty(1/3)^n$.`,
    ['$1/6$', '$1/2$', '$3/2$', '$1/9$'],
    [
      r`O índice inicial faz o primeiro termo ser $1/9$.`,
      r`Divida por $1-1/3$: $(1/9)/(2/3)=1/6$.`,
    ],
    '(1/3)**n',
    2,
    '1/6',
  ),
  q(
    'geometricas',
    'hard',
    r`Calcule $\sum_{n=0}^\infty(2^{n+1}+1)/5^n$.`,
    ['$55/12$', '$15/4$', '$10/3$', 'Diverge.'],
    [
      r`Separe em $2\sum(2/5)^n+\sum(1/5)^n$. Ambas as razões têm módulo menor que um.`,
      r`Some $2/(1-2/5)+1/(1-1/5)=10/3+5/4=55/12$.`,
    ],
    '(2**(n+1)+1)/5**n',
    0,
    '55/12',
  ),
  q(
    'geometricas',
    'hard',
    r`Calcule $\sum_{n=1}^\infty[3(1/2)^n-2(1/4)^n]$.`,
    ['$7/3$', '$1$', '$11/3$', '$5/3$'],
    [
      r`As duas séries geométricas convergem absolutamente, então podem ser subtraídas.`,
      r`Desde $n=1$, suas somas são $1$ e $1/3$. O resultado é $3\cdot1-2\cdot(1/3)=7/3$.`,
    ],
    '3*(1/2)**n-2*(1/4)**n',
    1,
    '7/3',
  ),
  q(
    'convergencia',
    'easy',
    r`A série $\sum_{n=1}^\infty n/(n+1)$:`,
    [
      'Diverge, pois o termo geral tende a $1$.',
      'Converge para $1$.',
      'Converge para $0$.',
      'Converge, pois seus termos são menores que $1$.',
    ],
    [
      r`A convergência de uma série exige que seu termo geral tenda a zero.`,
      r`Aqui $n/(n+1)\to1$, violando essa condição necessária.`,
    ],
    'n/(n+1)',
    1,
    'divergent',
  ),
  q(
    'convergencia',
    'easy',
    r`A série harmônica $\sum_{n=1}^\infty1/n$:`,
    [
      'Diverge, apesar de o termo geral tender a zero.',
      'Converge porque $1/n$ tende a zero.',
      'Converge para $1$.',
      'Diverge porque $1/n$ não tende a zero.',
    ],
    [
      r`Agrupe os termos em blocos entre potências de dois. Cada bloco após o primeiro soma pelo menos $1/2$.`,
      r`Há infinitos blocos; as somas parciais crescem sem limite. Ter termo geral tendendo a zero não basta.`,
    ],
    '1/n',
    1,
    'divergent',
  ),
  q(
    'convergencia',
    'medium',
    r`A série $\sum_{n=1}^\infty1/n^{3/2}$:`,
    [
      'Converge pelo critério das séries de potências de $n$, pois $p=3/2>1$.',
      'Diverge porque $p>1$.',
      'Diverge porque os termos são positivos.',
      'Converge para zero porque os termos tendem a zero.',
    ],
    [
      r`Trata-se de uma série $\sum n^{-p}$, com $p=3/2$.`,
      r`O critério das séries desse tipo garante convergência quando $p>1$; não determina soma zero.`,
    ],
    '1/n**(3/2)',
    1,
    'convergent',
  ),
  q(
    'convergencia',
    'medium',
    r`Calcule $\sum_{n=1}^\infty1/[n(n+1)]$.`,
    ['$1$', '$1/2$', '$2$', 'Diverge.'],
    [
      r`Decomponha $1/[n(n+1)]=1/n-1/(n+1)$.`,
      r`A soma parcial é $1-1/(N+1)$; seu limite é $1$.`,
    ],
    '1/(n*(n+1))',
    1,
    '1',
  ),
  q(
    'convergencia',
    'hard',
    r`Calcule $\sum_{n=1}^\infty1/[n(n+2)]$.`,
    ['$3/4$', '$1/2$', '$3/2$', 'Diverge.'],
    [
      r`Use $1/[n(n+2)]=(1/n-1/(n+2))/2$.`,
      r`Após cancelar os termos, a soma parcial é $(1+1/2-1/(N+1)-1/(N+2))/2$. O limite é $3/4$.`,
    ],
    '1/(n*(n+2))',
    1,
    '3/4',
  ),
  q(
    'convergencia',
    'hard',
    r`Calcule $\sum_{n=1}^\infty\ln[(n+1)^2/(n(n+2))]$.`,
    [r`$\ln2$`, '$0$', r`$2\ln2$`, 'Diverge.'],
    [
      r`A soma dos logaritmos é o logaritmo do produto. Esse produto até $N$ se simplifica para $2(N+1)/(N+2)$.`,
      r`Quando $N\to\infty$, o produto tende a $2$, e a soma tende a $\ln2$.`,
    ],
    'log((n+1)**2/(n*(n+2)))',
    1,
    'log(2)',
  ),
];
