const r = String.raw;
const power = (
  difficulty,
  statement,
  options,
  steps,
  coefficient,
  center,
  radius,
  endpoints,
) => ({
  topic: 'potencias',
  difficulty,
  statement,
  options,
  steps,
  verification: { kind: 'power', coefficient, center, radius, endpoints },
});
export default [
  power(
    'easy',
    r`Qual é o raio de convergência de $\sum_{n=0}^\infty x^n/3^n$?`,
    ['$3$', '$1/3$', '$1$', '$0$'],
    [
      r`A série é geométrica, de razão $x/3$.`,
      r`A condição $|x/3|<1$ equivale a $|x|<3$, logo $R=3$.`,
    ],
    '1/3**n',
    0,
    '3',
    [false, false],
  ),
  power(
    'easy',
    r`Qual é o intervalo de convergência de $\sum_{n=0}^\infty((x-2)/4)^n$?`,
    ['$(-2,6)$', '$(-4,4)$', '$[-2,6]$', '$(2,4)$'],
    [
      r`A condição geométrica é $|x-2|<4$, isto é, $-2<x<6$.`,
      r`Nos extremos, os termos são $(-1)^n$ ou $1$ e não tendem a zero. Os extremos são excluídos.`,
    ],
    '1/4**n',
    2,
    '4',
    [false, false],
  ),
  power(
    'easy',
    r`Qual é o raio de convergência de $\sum_{n=1}^\infty nx^n/2^n$?`,
    ['$2$', '$1/2$', '$0$', r`$\infty$`],
    [
      r`O teste da razão fornece limite $|x|/2$, pois $(n+1)/n\to1$.`,
      r`A condição é $|x|<2$, portanto $R=2$.`,
    ],
    'n/2**n',
    0,
    '2',
    [false, false],
  ),
  power(
    'medium',
    r`Qual é o intervalo de convergência de $\sum_{n=1}^\infty x^n/n$?`,
    ['$[-1,1)$', '$(-1,1)$', '$[-1,1]$', '$(-1,1]$'],
    [
      r`A razão fornece $R=1$. Os extremos precisam de análise separada.`,
      r`Em $x=1$ surge a harmônica divergente. Em $x=-1$ surge uma harmônica alternada convergente. Logo o intervalo é $[-1,1)$.`,
    ],
    '1/n',
    0,
    '1',
    [true, false],
  ),
  power(
    'medium',
    r`Qual é o intervalo de convergência de $\sum_{n=1}^\infty x^n/n^2$?`,
    ['$[-1,1]$', '$(-1,1)$', '$[-1,1)$', '$(-1,1]$'],
    [
      r`O raio calculado pela razão é $1$.`,
      r`Em ambos os extremos, os módulos formam $\sum1/n^2$, que converge. Inclua os dois extremos.`,
    ],
    '1/n**2',
    0,
    '1',
    [true, true],
  ),
  power(
    'medium',
    r`Qual é o intervalo de convergência de $\sum_{n=1}^\infty(x-1)^n/(n2^n)$?`,
    ['$[-1,3)$', '$(-1,3]$', '$(-2,2)$', '$[-1,3]$'],
    [
      r`A razão dá $|x-1|/2<1$, logo $R=2$.`,
      r`Em $x=-1$ temos $\sum(-1)^n/n$, convergente; em $x=3$, a harmônica diverge. O intervalo é $[-1,3)$.`,
    ],
    '1/(n*2**n)',
    1,
    '2',
    [true, false],
  ),
  power(
    'medium',
    r`Qual é o raio de convergência de $\sum_{n=0}^\infty x^n/n!$?`,
    [r`$\infty$`, '$1$', '$0$', '$e$'],
    [
      r`Para cada $x$ fixo, a razão dos módulos é $|x|/(n+1)$.`,
      r`O limite é zero para todo $x$, portanto a série converge em toda a reta e $R=\infty$.`,
    ],
    '1/factorial(n)',
    0,
    'oo',
    null,
  ),
  power(
    'hard',
    r`Qual é o raio de convergência de $\sum_{n=1}^\infty n!x^n$?`,
    ['$0$', '$1$', r`$\infty$`, '$1/2$'],
    [
      r`Se $x\ne0$, a razão dos módulos é $(n+1)|x|\to\infty$, causando divergência.`,
      r`Em $x=0$, todos os termos são zero. Só há convergência no centro, então $R=0$.`,
    ],
    'factorial(n)',
    0,
    '0',
    null,
  ),
  power(
    'hard',
    r`Qual é o intervalo de convergência de $\sum_{n=1}^\infty(x+2)^n/(n^2 3^n)$?`,
    ['$[-5,1]$', '$(-5,1)$', '$[-5,1)$', '$(-3,3)$'],
    [
      r`O centro é $-2$ e a razão fornece raio $3$, com interior $(-5,1)$.`,
      r`Nos extremos, os módulos são $1/n^2$ e somam uma série convergente. Ambos pertencem ao intervalo.`,
    ],
    '1/(n**2*3**n)',
    -2,
    '3',
    [true, true],
  ),
  {
    topic: 'taylor',
    difficulty: 'easy',
    statement: r`Qual é o polinômio de Maclaurin de grau dois de $e^x$?`,
    options: [r`$1+x+x^2/2$`, r`$1+x+x^2$`, r`$x+x^2/2$`, r`$1-x+x^2/2$`],
    steps: [
      r`As derivadas de $e^x$ em zero valem $1$.`,
      r`A fórmula $f(0)+f'(0)x+f''(0)x^2/2!$ dá $1+x+x^2/2$.`,
    ],
    verification: {
      kind: 'taylor',
      expression: 'exp(x)',
      center: 0,
      degree: 2,
      expected: '1+x+x**2/2',
    },
  },
  {
    topic: 'taylor',
    difficulty: 'medium',
    statement: r`Qual é o polinômio de Maclaurin de grau três de $\sin x$?`,
    options: [r`$x-x^3/6$`, r`$x+x^3/6$`, r`$1-x^2/2$`, r`$x-x^3/3$`],
    steps: [
      r`As derivadas de ordem zero a três em zero são $0,1,0,-1$.`,
      r`Dividindo pelos fatoriais, resulta $x-x^3/3!=x-x^3/6$.`,
    ],
    verification: {
      kind: 'taylor',
      expression: 'sin(x)',
      center: 0,
      degree: 3,
      expected: 'x-x**3/6',
    },
  },
  {
    topic: 'taylor',
    difficulty: 'medium',
    statement: r`Qual é o polinômio de Taylor de grau dois de $\ln x$ centrado em $x=1$?`,
    options: [
      r`$(x-1)-(x-1)^2/2$`,
      r`$(x-1)+(x-1)^2/2$`,
      r`$x-x^2/2$`,
      r`$1+(x-1)-(x-1)^2/2$`,
    ],
    steps: [
      r`No centro, $f(1)=0$, $f'(1)=1$ e $f''(1)=-1$.`,
      r`Use potências de $x-1$: o polinômio é $(x-1)-(x-1)^2/2$.`,
    ],
    verification: {
      kind: 'taylor',
      expression: 'log(x)',
      center: 1,
      degree: 2,
      expected: '(x-1)-(x-1)**2/2',
    },
  },
  {
    topic: 'taylor',
    difficulty: 'hard',
    statement: r`A aproximação $\cos(0{,}2)\approx1-(0{,}2)^2/2$ tem qual cota de erro absoluto pelo primeiro termo omitido da série de Maclaurin?`,
    options: [
      r`$(0{,}2)^4/24=1/15000$`,
      r`$(0{,}2)^3/6=1/750$`,
      r`$(0{,}2)^2/2=1/50$`,
      r`$(0{,}2)^4/4=1/2500$`,
    ],
    steps: [
      r`A série é $1-x^2/2!+x^4/4!-\cdots$. Para $x=0{,}2$, os módulos decrescem para zero.`,
      r`O resto após o termo quadrático tem módulo no máximo $(1/5)^4/24=1/15000$.`,
    ],
    verification: {
      kind: 'taylor-error',
      expression: 'cos(x)',
      at: '1/5',
      polynomial: '1-x**2/2',
      bound: '1/15000',
    },
  },
];
