const r = String.raw;
const q = (
  difficulty,
  statement,
  options,
  steps,
  expression,
  method,
  limit,
  expected,
) => ({
  topic: 'testes',
  difficulty,
  statement,
  options,
  steps,
  verification: {
    kind: 'convergence-test',
    expression,
    method,
    limit,
    expected,
  },
});
export default [
  q(
    'easy',
    r`Qual comparação prova a convergência de $\sum_{n=1}^\infty1/(n^2+1)$?`,
    [
      r`$0<1/(n^2+1)\le1/n^2$.`,
      r`$1/(n^2+1)\le1/n$.`,
      r`$1/(n^2+1)\ge1/n^2$.`,
      r`O termo geral tende a zero, o que basta.`,
    ],
    [
      r`Como $n^2+1\ge n^2$, o inverso é menor ou igual a $1/n^2$.`,
      r`A série maior é convergente, com $p=2$; a comparação direta conclui.`,
    ],
    '1/(n**2+1)',
    'comparison',
    '1/n**2',
    'convergent',
  ),
  q(
    'easy',
    r`Qual comparação prova que $\sum_{n=1}^\infty1/\sqrt n$ diverge?`,
    [
      r`$1/\sqrt n\ge1/n$ e a série harmônica diverge.`,
      r`$1/\sqrt n\le1$ e a série constante diverge.`,
      r`$1/\sqrt n\ge1/n^2$ e a série de quadrados converge.`,
      r`O termo tende a zero, logo a série diverge.`,
    ],
    [
      r`Para $n\ge1$, $\sqrt n\le n$, então $1/\sqrt n\ge1/n$.`,
      r`A série menor já diverge; as somas parciais da maior também são ilimitadas.`,
    ],
    '1/sqrt(n)',
    'comparison',
    '1/n',
    'divergent',
  ),
  q(
    'medium',
    r`Ao comparar $a_n=(3n+1)/(n^3+2)$ com $b_n=1/n^2$, qual conclusão é correta?`,
    [
      r`$a_n/b_n\to3$; a série de $a_n$ converge.`,
      r`$a_n/b_n\to0$; a série diverge.`,
      r`$a_n/b_n\to3$; a série diverge.`,
      r`$a_n/b_n\to\infty$; a série converge.`,
    ],
    [
      r`A razão é $(3n^3+n^2)/(n^3+2)$ e tende a $3$.`,
      r`Esse limite é positivo e finito; as duas séries têm o mesmo comportamento. Como $\sum1/n^2$ converge, a série proposta também converge.`,
    ],
    '(3*n+1)/(n**3+2)',
    'limit-comparison',
    '3',
    'convergent',
  ),
  q(
    'hard',
    r`Compare $a_n=1/\sqrt{n^2+3n}$ com $b_n=1/n$.`,
    [
      r`A razão tende a $1$, e $\sum a_n$ diverge.`,
      r`A razão tende a $1$, e $\sum a_n$ converge.`,
      r`A razão tende a $0$, e $\sum a_n$ converge.`,
      r`A razão tende a $3$, e $\sum a_n$ diverge.`,
    ],
    [
      r`A razão é $n/\sqrt{n^2+3n}=1/\sqrt{1+3/n}\to1$.`,
      r`A comparação pelo limite com a série harmônica garante divergência, apesar de cada termo ser menor que $1/n$.`,
    ],
    '1/sqrt(n**2+3*n)',
    'limit-comparison-harmonic',
    '1',
    'divergent',
  ),
  q(
    'easy',
    r`Pelo teste da razão, $\sum_{n=1}^\infty n/3^n$:`,
    [
      r`Converge, com limite da razão $1/3$.`,
      r`Diverge, com limite da razão $3$.`,
      r`Converge, com limite da razão $0$.`,
      r`O teste é inconclusivo, pois o limite é $1$.`,
    ],
    [
      r`A razão entre termos consecutivos é $(n+1)/(3n)$.`,
      r`Seu limite é $1/3<1$; a série converge.`,
    ],
    'n/3**n',
    'ratio',
    '1/3',
    'convergent',
  ),
  q(
    'medium',
    r`Pelo teste da razão, $\sum_{n=1}^\infty2^n/n!$:`,
    [
      r`Converge, com limite da razão $0$.`,
      r`Diverge, com limite da razão $2$.`,
      r`O teste é inconclusivo, com limite $1$.`,
      r`Converge, com limite da razão $1/2$.`,
    ],
    [
      r`Usando $(n+1)!=(n+1)n!$, a razão é $2/(n+1)$.`,
      r`Ela tende a zero, menor que um, garantindo convergência.`,
    ],
    '2**n/factorial(n)',
    'ratio',
    '0',
    'convergent',
  ),
  q(
    'medium',
    r`Pelo teste da razão, $\sum_{n=1}^\infty n!/4^n$:`,
    [
      r`Diverge, pois a razão tende a $+\infty$.`,
      r`Converge, pois a razão tende a $0$.`,
      r`Converge, pois a razão tende a $1/4$.`,
      r`O teste é inconclusivo, pois a razão tende a $1$.`,
    ],
    [
      r`A razão é $(n+1)/4$.`,
      r`Ela ultrapassa um e tende a infinito; em particular os termos não tendem a zero.`,
    ],
    'factorial(n)/4**n',
    'ratio',
    'oo',
    'divergent',
  ),
  q(
    'hard',
    r`Para $\sum_{n=1}^\infty1/n^2$, o teste da razão:`,
    [
      r`É inconclusivo: o limite é $1$, mas a série converge pelo critério $p>1$.`,
      r`Prova divergência porque o limite é $1$.`,
      r`Prova convergência porque o limite é $1$.`,
      r`Prova convergência porque o limite é $0$.`,
    ],
    [
      r`A razão é $n^2/(n+1)^2\to1$. O teste da razão não decide nesse caso.`,
      r`Outro critério resolve: a série tem $p=2>1$, logo converge.`,
    ],
    '1/n**2',
    'ratio',
    '1',
    'convergent',
  ),
  q(
    'easy',
    r`Pelo teste da raiz, $\sum_{n=1}^\infty(2/5)^n$:`,
    [
      r`Converge, com limite da raiz $2/5$.`,
      r`Diverge, com limite da raiz $5/2$.`,
      r`É inconclusivo, com limite $1$.`,
      r`Converge, com limite da raiz $0$.`,
    ],
    [
      r`A raiz de ordem $n$ do termo positivo é exatamente $2/5$.`,
      r`Como $2/5<1$, o teste garante convergência.`,
    ],
    '(2/5)**n',
    'root',
    '2/5',
    'convergent',
  ),
  q(
    'medium',
    r`Pelo teste da raiz, $\sum_{n=1}^\infty[(n+1)/(3n)]^n$:`,
    [
      r`Converge, com limite da raiz $1/3$.`,
      r`Diverge, com limite da raiz $3$.`,
      r`É inconclusivo, com limite $1$.`,
      r`Converge, com limite da raiz $0$.`,
    ],
    [
      r`A raiz de ordem $n$ cancela a potência, deixando $(n+1)/(3n)$.`,
      r`Esse valor tende a $1/3<1$.`,
    ],
    '((n+1)/(3*n))**n',
    'root',
    '1/3',
    'convergent',
  ),
  q(
    'medium',
    r`Pelo teste da raiz, $\sum_{n=1}^\infty(2n/(n+1))^n$:`,
    [
      r`Diverge, com limite da raiz $2$.`,
      r`Converge, com limite da raiz $1/2$.`,
      r`É inconclusivo, com limite $1$.`,
      r`Converge, com limite da raiz $0$.`,
    ],
    [
      r`A raiz de ordem $n$ é $2n/(n+1)$.`,
      r`Seu limite é $2>1$, o que implica divergência.`,
    ],
    '(2*n/(n+1))**n',
    'root',
    '2',
    'divergent',
  ),
  q(
    'hard',
    r`Pelo teste da raiz, $\sum_{n=1}^\infty n^3/2^n$:`,
    [
      r`Converge, com limite da raiz $1/2$.`,
      r`Diverge, com limite da raiz $2$.`,
      r`É inconclusivo, com limite $1$.`,
      r`Converge, com limite da raiz $0$.`,
    ],
    [
      r`A raiz é $n^{3/n}/2$. Escreva $n^{3/n}=e^{3\ln n/n}$.`,
      r`Como $\ln n/n\to0$, o numerador tende a $1$. O limite é $1/2<1$.`,
    ],
    'n**3/2**n',
    'root',
    '1/2',
    'convergent',
  ),
];
