const r = String.raw;
const q = (
  topic,
  difficulty,
  statement,
  options,
  steps,
  expression,
  expected,
  monotonic,
) => ({
  topic,
  difficulty,
  statement,
  options,
  steps,
  verification: { kind: 'sequence', expression, expected, monotonic },
});
export default [
  q(
    'limites-sequencias',
    'easy',
    r`Calcule $\lim_{n\to\infty}(3n+2)/(n+5)$.`,
    ['$3$', '$2/5$', '$0$', r`$+\infty$`],
    [
      r`Divida numerador e denominador por $n$.`,
      r`A razão vira $(3+2/n)/(1+5/n)$ e tende a $3$.`,
    ],
    '(3*n+2)/(n+5)',
    '3',
  ),
  q(
    'limites-sequencias',
    'easy',
    r`Calcule $\lim_{n\to\infty}1/n^2$.`,
    ['$0$', '$1$', '$2$', r`$+\infty$`],
    [
      r`Para $n\ge1$, temos $0<1/n^2\le1/n$.`,
      r`Como $1/n\to0$, o confronto fornece limite zero.`,
    ],
    '1/n**2',
    '0',
  ),
  q(
    'limites-sequencias',
    'medium',
    r`Calcule $\lim_{n\to\infty}(\sqrt{n^2+n}-n)$.`,
    ['$1/2$', '$0$', '$1$', r`$+\infty$`],
    [
      r`Racionalize: a diferença é $n/(\sqrt{n^2+n}+n)$.`,
      r`Divida por $n$, obtendo $1/(\sqrt{1+1/n}+1)\to1/2$.`,
    ],
    'sqrt(n**2+n)-n',
    '1/2',
  ),
  q(
    'limites-sequencias',
    'medium',
    r`Calcule $\lim_{n\to\infty}n/2^n$.`,
    ['$0$', '$1/2$', '$1$', r`$+\infty$`],
    [
      r`Para $a_n=n/2^n$, a razão $a_{n+1}/a_n=(n+1)/(2n)$ tende a $1/2$.`,
      r`A partir de algum índice, essa razão é menor que $3/4$, permitindo comparação com uma sequência geométrica que tende a zero.`,
    ],
    'n/2**n',
    '0',
  ),
  q(
    'limites-sequencias',
    'hard',
    r`Calcule $\lim_{n\to\infty}n\ln(1+2/n)$.`,
    ['$2$', '$0$', '$1$', r`$e^2$`],
    [
      r`Escreva $n\ln(1+2/n)=2\,\ln(1+2/n)/(2/n)$.`,
      r`Use $\lim_{t\to0}\ln(1+t)/t=1$. O limite é $2$, não sua exponencial.`,
    ],
    'n*log(1+2/n)',
    '2',
  ),
  q(
    'monotonicidade',
    'easy',
    r`Para $n\ge1$, a sequência $a_n=1-1/n$ é:`,
    [
      'Estritamente crescente e convergente para $1$.',
      'Estritamente decrescente e convergente para $1$.',
      'Crescente e ilimitada.',
      'Constante e igual a $0$.',
    ],
    [
      r`A diferença $a_{n+1}-a_n=1/[n(n+1)]$ é positiva.`,
      r`Além disso, $a_n<1$ e $1/n\to0$, portanto o limite é $1$.`,
    ],
    '1-1/n',
    '1',
    'increasing',
  ),
  q(
    'monotonicidade',
    'easy',
    r`Para $n\ge1$, a sequência $a_n=2+1/n$ é:`,
    [
      'Estritamente decrescente e convergente para $2$.',
      'Estritamente crescente e convergente para $2$.',
      'Decrescente e convergente para $0$.',
      'Constante e igual a $2$.',
    ],
    [
      r`A diferença entre termos consecutivos é $-1/[n(n+1)]<0$.`,
      r`A sequência é limitada inferiormente por $2$, e $1/n\to0$ fornece o limite $2$.`,
    ],
    '2+1/n',
    '2',
    'decreasing',
  ),
  q(
    'monotonicidade',
    'medium',
    r`Para $n\ge1$, classifique $a_n=n/(n+2)$.`,
    [
      'Crescente, limitada e convergente para $1$.',
      'Decrescente e convergente para $0$.',
      'Crescente e divergente para infinito.',
      'Constante e igual a $1$.',
    ],
    [
      r`Escreva $a_n=1-2/(n+2)$: a parcela subtraída diminui quando $n$ aumenta.`,
      r`Logo $a_n$ cresce e permanece abaixo de $1$. Seu limite é $1$.`,
    ],
    'n/(n+2)',
    '1',
    'increasing',
  ),
  q(
    'monotonicidade',
    'medium',
    r`Para $n\ge1$, a sequência $a_n=\sqrt{n+1}-\sqrt n$ é:`,
    [
      'Positiva, decrescente e convergente para $0$.',
      'Positiva, crescente e convergente para $1$.',
      'Negativa e convergente para $0$.',
      'Positiva e divergente para infinito.',
    ],
    [
      r`Racionalize: $a_n=1/(\sqrt{n+1}+\sqrt n)$.`,
      r`O denominador é positivo, cresce estritamente e tende a infinito. Portanto os termos decrescem para zero.`,
    ],
    'sqrt(n+1)-sqrt(n)',
    '0',
    'decreasing',
  ),
  q(
    'monotonicidade',
    'hard',
    r`Para $n\ge1$, $a_n=(1+1/n)^n$ é:`,
    [
      r`Crescente e convergente para $e$.`,
      r`Decrescente e convergente para $e$.`,
      'Crescente e convergente para $1$.',
      'Crescente e ilimitada.',
    ],
    [
      r`Considere $f(x)=x\ln(1+1/x)$. Sua derivada é $\ln(1+1/x)-1/(x+1)>0$, pois $\ln(1+t)>t/(1+t)$ para $t>0$.`,
      r`Assim $a_n=e^{f(n)}$ cresce. Como $f(n)\to1$, temos $a_n\to e$.`,
    ],
    '(1+1/n)**n',
    'E',
    'increasing',
  ),
];
