import { BookOpen, ChevronRight, Search } from 'lucide-react';

import { AppShell } from '@/components/app-shell';
import { ArcCard } from '@/components/arc-ui';

const topics = [{ name: 'Integrais', count: 48 }, { name: 'Técnicas de integração', count: 36 }, { name: 'Integrais impróprias', count: 21 }, { name: 'Sequências e séries', count: 39 }];

export default function ExplorePage() {
  return <AppShell active="explore"><section className="mx-auto max-w-6xl px-5 pb-10 pt-12 sm:px-8 sm:pt-16"><p className="text-sm font-medium text-[#6b766f]">Banco de questões</p><div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-medium tracking-[-0.065em] sm:text-5xl">Explore por assunto.</h1><p className="mt-3 text-[15px] text-[#68706b]">Acesse qualquer questão ou comece por um conteúdo específico.</p></div><button className="inline-flex items-center gap-2 text-sm text-[#68706b]"><Search className="size-4" /> Buscar</button></div><ArcCard className="mt-10 overflow-hidden"><div className="flex items-center gap-3 border-b border-black/[0.07] px-5 py-5 sm:px-8"><span className="grid size-9 place-items-center rounded-xl bg-[#eff4f0] text-[#466254]"><BookOpen className="size-4" /></span><div><p className="font-medium tracking-[-0.025em]">Cálculo II</p><p className="mt-0.5 text-xs text-[#68706b]">Catálogo de demonstração</p></div></div><div className="grid lg:grid-cols-[0.92fr_1.08fr]"><div className="border-b border-black/[0.07] p-5 sm:p-8 lg:border-b-0 lg:border-r"><p className="text-xs font-medium uppercase tracking-[0.14em] text-[#7b817d]">Começar rápido</p><p className="mt-5 text-2xl font-medium tracking-[-0.05em]">Todas as questões</p><p className="mt-2 text-sm leading-6 text-[#68706b]">Veja o banco inteiro ou use os filtros para chegar ao conteúdo exato.</p><a className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#1d221d] px-4 py-2.5 text-sm font-medium text-white" href="/practice">Ver questões <ChevronRight className="size-4" /></a></div><div className="p-5 sm:p-8"><p className="text-xs font-medium uppercase tracking-[0.14em] text-[#7b817d]">Escolha um assunto</p><div className="mt-4 divide-y divide-black/[0.06]">{topics.map((topic, index) => <a className="group flex items-center gap-4 py-4" href="/practice" key={topic.name}><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#f3f4f2] text-xs font-medium text-[#637167]">{String(index + 1).padStart(2, '0')}</span><span className="min-w-0 flex-1"><span className="block text-[15px] font-medium tracking-[-0.02em]">{topic.name}</span><span className="mt-1 block text-xs text-[#68706b]">{topic.count} questões</span></span><ChevronRight className="size-4 text-zinc-300 transition-all group-hover:translate-x-1 group-hover:text-zinc-700" /></a>)}</div></div></div></ArcCard></section></AppShell>;
}
