// Lote 02 — representação, aritmética e ponto flutuante; autoria Arc.
import { q } from './batch-01.mjs';

const rows = [
['001','easy','representação binária','Qual valor decimal corresponde a $101011_2$?','$43$',['$41$','$42$','$44$'],'Cada bit $1$ contribui com sua potência de dois.','Some $32+8+2+1$.','A soma dos pesos ativos deve reproduzir a representação original.'],
['002','medium','representação binária','Qual é a representação binária sem sinal de $156_{10}$?','$10011100_2$',['$10011010_2$','$10101100_2$','$11100100_2$'],'A conversão decompõe o número em potências de dois.','Selecione $128+16+8+4$.','Os pesos dos bits marcados somam $156$.'],
['003','easy','faixa sem sinal','Qual é o maior inteiro sem sinal em 12 bits?','$4095$',['$2047$','$4096$','$8191$'],'Com $n$ bits sem sinal, o máximo é $2^n-1$.','Use $2^{12}-1$.','O valor $4096$ precisaria de uma combinação adicional.'],
['004','medium','complemento de dois','Em 8 bits com sinal, qual valor representa $11110110_2$?','$-10$',['$246$','$-9$','$10$'],'Para um padrão negativo, inverter bits e somar um fornece o módulo.','Inverta para $00001001$ e some um.','O módulo é $10$ e o sinal é negativo.'],
['005','hard','complemento de dois','Qual soma em 8 bits com sinal causa overflow?','$01110000_2+00110000_2$',['$11110000_2+00001000_2$','$00000101_2+11111011_2$','$10000000_2+00000000_2$'],'Overflow ocorre ao somar dois números de mesmo sinal e obter sinal oposto.','Observe os bits de sinal antes e depois da soma.','$112+48=160$ excede o máximo $127$.'],
['006','medium','subtração binária','Em complemento de dois de 8 bits, $18-27$ resulta em:','$11110111_2$',['$00001001_2$','$11111001_2$','$00010111_2$'],'Subtrair é somar o complemento de dois do subtraendo.','Calcule $18+(-27)=-9$.','O padrão de $-9$ em 8 bits é $11110111_2$.'],
['007','easy','hexadecimal','Qual grupo hexadecimal corresponde a $1110_2$?','$E$',['$D$','$F$','$C$'],'Cada dígito hexadecimal codifica quatro bits.','Converta o grupo binário para valor decimal $14$.','$E$ representa o valor decimal $14$.'],
['008','medium','hexadecimal','Qual é $0x3A+0x17$ em hexadecimal?','$0x51$',['$0x4F$','$0x61$','$0x50$'],'A aritmética hexadecimal usa base 16.','Some $10+7=17$, deixando $1$ e levando $1$.','$0x3A+0x17=0x51$.'],
['009','hard','extensão de sinal','Ao ampliar $10110110_2$ de 8 para 16 bits em complemento de dois, qual padrão preserva o valor?','$1111111110110110_2$',['$0000000010110110_2$','$0000000011011011_2$','$1011011000000000_2$'],'Extensão de sinal replica o bit mais significativo.','O bit de sinal é $1$, então complete com uns à esquerda.','Replicar o sinal mantém o número negativo.'],
['010','easy','bits e capacidade','Quantos valores diferentes podem ser codificados por 5 bits?','$32$',['$5$','$25$','$31$'],'Cada bit tem duas escolhas independentes.','Calcule $2^5$.','Inclui de $0$ a $31$, totalizando $32$ valores.'],
['011','medium','codificação','Um campo precisa representar 30 estados distintos. Qual é o menor número de bits necessário?','$5$',['$4$','$6$','$30$'],'Escolha $n$ tal que $2^n$ cubra todos os estados.','Compare $2^4=16$ e $2^5=32$.','Cinco bits são suficientes; quatro não são.'],
['012','hard','aritmética saturada','Em aritmética saturada de 8 bits com sinal, qual resultado produz $120+20$?','$127$',['$140$','$-116$','$0$'],'Saturação limita o resultado ao extremo representável, em vez de envolver.','Compare $140$ com a faixa $[-128,127]$.','O resultado é limitado ao máximo $127$.'],
['013','easy','ponto flutuante','Qual propriedade diferencia ponto flutuante de inteiro de tamanho fixo?','A posição do ponto é indicada por expoente.',['Todo valor é exato.','Não há sinal.','Não existem limites de faixa.'],'A notação científica separa significando e expoente.','Pergunte como a escala do número é representada.','O expoente ajusta a magnitude do significando.'],
['014','medium','ponto flutuante','Por que $0,1$ decimal pode não ser armazenado exatamente em binário?','Sua expansão binária pode ser periódica.',['O processador não possui ULA.','Binário não representa frações.','O sinal sempre é perdido.'],'Frações com denominadores que não são potência de dois podem repetir em base dois.','Compare a fração a somas de potências negativas de dois.','Uma aproximação finita introduz arredondamento.'],
['015','hard','IEEE 754','Dois cálculos matematicamente equivalentes em ponto flutuante dão resultados levemente diferentes ao mudar parênteses. Qual causa é mais provável?','Arredondamento após operações intermediárias.',['A ISA perdeu uma instrução.','A cache alterou o valor.','A memória virou somente leitura.'],'Ponto flutuante tem precisão finita e cada operação pode arredondar.','Compare quando cada forma descarta bits de baixa ordem.','A adição não é estritamente associativa sob arredondamento.'],
['016','medium','ponto flutuante','Qual situação descreve underflow?','Um resultado não nulo tem magnitude menor que o mínimo representável normal.',['O resultado excede o máximo.','Dois inteiros têm mesmo sinal.','A cache não encontra uma linha.'],'Underflow está ligado a valores muito próximos de zero.','Diferencie limite inferior de limite superior da faixa.','Valores extremamente pequenos podem virar subnormais ou zero.'],
['017','medium','ponto flutuante','Qual situação descreve overflow em ponto flutuante?','A magnitude do resultado excede o maior valor finito representável.',['O expoente é zero.','A mantissa tem um bit $1$.','Um endereço não está alinhado.'],'Overflow acontece no limite superior de magnitude.','Compare o resultado esperado à faixa do formato.','O resultado pode ser representado como infinito conforme o formato.'],
['018','easy','ASCII e Unicode','Por que Unicode é necessário além do ASCII tradicional?','Para representar muito mais caracteres e sistemas de escrita.',['Para aumentar a frequência da CPU.','Para codificar apenas números binários.','Para substituir a RAM.'],'ASCII original tem conjunto limitado; Unicode amplia o repertório.','Pense em alfabetos, símbolos e idiomas fora do conjunto básico.','A necessidade é de cobertura de caracteres, não de desempenho.'],
['019','medium','paridade','Um bit de paridade par é adicionado a $1011001$. Qual bit deve ser acrescentado?','$0$',['$1$','Depende do clock.','Não é necessário.'],'Paridade par exige quantidade total par de bits $1$.','Conte os quatro bits $1$ existentes.','Como já há quatro uns, acrescenta-se zero.'],
['020','hard','ECC','Por que um código SECDED detecta mais casos que um código de Hamming simples?','Usa paridade global adicional para distinguir certos erros duplos.',['Dobra a frequência da memória.','Elimina todos os erros.','Não usa bits redundantes.'],'SECDED combina correção de um erro com detecção de dois erros.','Compare a informação fornecida pela paridade extra.','Dois erros não são corrigidos, mas podem ser identificados.'],
['021','easy','alinhamento','Por que dados de 4 bytes frequentemente são alinhados em endereços múltiplos de 4?','Para permitir acessos mais simples e eficientes no hardware.',['Para eliminar endereços.','Para converter bytes em bits.','Para impedir cache hits.'],'Alinhamento combina tamanho do dado com fronteiras naturais de acesso.','Verifique se o endereço inicial respeita a largura do objeto.','O alinhamento pode evitar acessos divididos em duas palavras.'],
['022','medium','little-endian','Em little-endian, o que significa o endereço do primeiro byte de uma palavra?','Ele contém o byte menos significativo.',['Ele sempre contém o byte mais significativo.','Ele contém o opcode.','Ele não armazena dados.'],'A convenção define a ordem dos bytes na memória.','Associe “menor endereço” a “menor significância”.','A palavra mantém valor lógico; só muda a disposição física.'],
['023','hard','conversão de base','Qual é $0,625_{10}$ em binário?','$0,101_2$',['$0,110_2$','$0,011_2$','$0,100_2$'],'Frações binárias usam pesos $1/2$, $1/4$, $1/8$ e assim por diante.','Decomponha $0,625=1/2+1/8$.','Os bits nas posições $1/2$ e $1/8$ são $1$.'],
['024','medium','shifts','Para um inteiro sem sinal sem overflow, deslocar $00101101_2$ uma posição à esquerda equivale a:','Multiplicar o valor por $2$.',['Dividir o valor por $2$.','Inverter todos os bits.','Adicionar sempre $1$.'],'Um shift lógico à esquerda desloca cada peso para a próxima potência de dois.','Compare os pesos antes e depois do deslocamento.','Cada contribuição dobra, se nenhum bit significativo for perdido.'],
['025','hard','precisão','Qual é a melhor explicação para usar mais bits no significando de um formato de ponto flutuante?','Reduzir o erro relativo de arredondamento para valores representáveis.',['Aumentar apenas o maior expoente.','Eliminar a necessidade de sinal.','Tornar todas as frações exatas.'],'Precisão está ligada aos bits do significando; faixa está ligada principalmente ao expoente.','Diferencie quantos dígitos são preservados de quão grande o número pode ser.','Mais precisão reduz, mas não elimina, erros de representação.'],
];

export default rows.map(([n, difficulty, focus, statement, answer, distractors, principle, action, check]) => q(`ca-r02-${n}`, difficulty, focus, statement, answer, distractors, principle, action, check));
