// Lote 01 — 25 questões autorais. Referência curricular: Tanenbaum/Austin.
// Não contém enunciados, exemplos ou soluções reproduzidos da obra.

export const q = (id, difficulty, focus, statement, answer, distractors, principle, action, check) => ({
  id, difficulty, focus, statement, answer, distractors, principle, action, check,
  hints: [
    `Primeiro separe o nível ou componente que está sendo analisado: ${focus}.`,
    action,
    check,
  ],
  solution: [
    ['Delimite o problema', `O caso trata de ${focus}; leia o que é observável antes de escolher uma implementação.`],
    ['Recupere o princípio', principle],
    ['Aplique ao cenário', action],
    ['Elimine as alternativas', 'As demais alternativas confundem níveis de abstração, responsabilidade de componentes ou uma consequência que não decorre dos dados.'],
    ['Verifique a conclusão', `${check} Portanto, a resposta é: ${answer}.`],
  ],
});

export default [
  q('ca-r01-001','easy','níveis de abstração','Um compilador transforma um programa em C em código de máquina para uma ISA específica. Qual mudança pode ocorrer sem exigir que o código-fonte em C seja reescrito?','Trocar a microarquitetura mantendo a mesma ISA.',['Trocar a semântica das instruções da ISA.','Remover o compilador.','Alterar o resultado definido do programa.'],'A ISA é a interface visível ao software de baixo nível; a microarquitetura é uma implementação dessa interface.','Compare o que o compilador assume — a ISA — com a forma interna de executá-la.','Se as instruções preservam significado e efeitos, o binário continua válido.'),
  q('ca-r01-002','medium','níveis de abstração','Uma equipe substitui uma ULA de 32 bits por outra mais rápida, sem alterar registradores, opcodes nem resultados das instruções. Que camada foi modificada?','A microarquitetura.',['A linguagem de alto nível.','A ISA publicada ao programador.','O formato do arquivo-fonte.'],'Componentes e caminhos internos pertencem à implementação, desde que a interface arquitetural seja preservada.','Pergunte se um programador que usa a ISA percebe uma instrução diferente.','Os mesmos registradores, opcodes e resultados indicam compatibilidade arquitetural.'),
  q('ca-r01-003','hard','níveis de abstração','Um processador passa a executar uma multiplicação por meio de várias microoperações internas em vez de uma unidade dedicada, mas a instrução MUL mantém seus operandos e resultado. Qual afirmação é correta?','A implementação mudou, mas a ISA pode permanecer compatível.',['A instrução deixou de existir na ISA.','Todo programa precisa ser recompilado.','A CPU passou a ter outra linguagem de montagem.'],'Uma mesma instrução arquitetural pode ser realizada por diferentes sequências internas.','Diferencie o contrato da instrução de sua realização física ou microprogramada.','O resultado e os efeitos observáveis de MUL são o teste de compatibilidade.'),
  q('ca-r01-004','easy','hardware e software','Por que uma função como compressão pode ser implementada em hardware ou em software?','Porque ambos podem realizar a mesma transformação lógica, com custos e velocidades diferentes.',['Porque software não usa processador.','Porque hardware nunca precisa de energia.','Porque compiladores eliminam a necessidade de instruções.'],'A escolha hardware/software é um trade-off de desempenho, custo, consumo e flexibilidade, não uma diferença de capacidade lógica.','Avalie a transformação desejada e os custos de cada implementação.','Uma solução em hardware pode acelerar uma função sem tornar a alternativa em software impossível.'),
  q('ca-r01-005','medium','máquinas virtuais','Um interpretador executa bytecodes e oferece instruções que não existem diretamente no processador físico. O conjunto de bytecodes descreve principalmente:','Uma máquina virtual em um nível de abstração superior.',['O circuito lógico da CPU.','A frequência do clock físico.','A disposição dos transistores.'],'Uma máquina virtual define objetos e operações próprios, mesmo quando precisa ser interpretada por outro nível.','Identifique qual conjunto de operações é apresentado ao programador daquele ambiente.','O fato de bytecodes serem interpretados não os transforma em sinais elétricos da CPU.'),
  q('ca-r01-006','medium','desempenho','Dois processadores executam o mesmo programa. A usa clock de 3 GHz e CPI médio 1,5; B usa 2 GHz e CPI médio 0,8, com o mesmo número de instruções. Qual é mais rápido?','B, pois seu tempo proporcional é menor.',['A, pois 3 é maior que 2.','Empatam por executar o mesmo programa.','Não é possível comparar CPI e clock.'],'Tempo de CPU é proporcional a instruções × CPI ÷ frequência.','Compare $1,5/3$ com $0,8/2$, usando a mesma unidade de GHz.','B resulta em $0,4$ contra $0,5$ unidades proporcionais de tempo.'),
  q('ca-r01-007','hard','desempenho','Uma otimização reduz em 20% a contagem de instruções, mas eleva o CPI de 1,0 para 1,3; o clock não muda. Qual efeito ocorre?','O tempo aumenta 4%.',['O tempo reduz 20%.','O tempo não muda.','O tempo reduz 4%.'],'Com clock constante, compare o produto entre número de instruções e CPI antes e depois.','Calcule $0,80\times1,30$ para o novo trabalho relativo.','O produto é $1,04$, maior que o valor inicial $1,00$.'),
  q('ca-r01-008','easy','CPU','Qual componente executa operações aritméticas e lógicas sobre operandos que já estão disponíveis no caminho de dados?','A ULA.',['O contador de programa.','O registrador de instrução.','O barramento de endereços.'],'A ULA realiza cálculos; PC, IR e barramentos exercem papéis de controle, armazenamento ou comunicação.','Associe a operação solicitada ao bloco que soma, compara e aplica lógica booleana.','A descrição não pede guardar endereço nem buscar instrução.'),
  q('ca-r01-009','medium','ciclo de instrução','Após buscar uma instrução, a CPU descobre que ela é um salto condicional tomado. Qual atualização é essencial antes da próxima busca?','Carregar o endereço-alvo no PC.',['Copiar o opcode para a ULA.','Zerar todos os registradores.','Escrever o alvo na cache.'],'O PC determina o endereço da próxima instrução a buscar.','Siga a consequência do desvio: a próxima instrução não é a sequencial.','Sem atualizar o PC, a busca continuaria no caminho incorreto.'),
  q('ca-r01-010','hard','ciclo de instrução','Durante a execução de LOAD R1,[R2], qual sequência representa corretamente o uso lógico dos componentes?','Usar R2 como endereço, ler memória e escrever o dado em R1.',['Usar R1 como endereço e sobrescrever R2.','Somar R1 e R2 sem acessar memória.','Ler R1 e gravar o resultado no PC.'],'Uma carga transfere para um registrador o conteúdo da posição apontada pelo operando de endereço.','Separe registrador-base, endereço efetivo, leitura de memória e destino.','O valor armazenado em R2 é endereço; o dado lido torna-se o novo valor de R1.'),
  q('ca-r01-011','easy','RISC e CISC','Qual característica é mais associada a uma ISA RISC clássica?','Instruções simples e formatos regulares.',['Toda instrução acessa memória duas vezes.','Ausência de registradores.','Instruções de tamanho sempre ilimitado.'],'RISC favorece regularidade e operações simples, o que ajuda decodificação e pipeline.','Procure a alternativa que descreve o conjunto de instruções, não a memória física.','Registradores continuam centrais em arquiteturas RISC.'),
  q('ca-r01-012','medium','paralelismo','Quatro núcleos executam quatro tarefas independentes, cada uma com duração semelhante. Qual ganho é mais diretamente explorado?','Paralelismo no nível do processador.',['Pipeline dentro de uma única instrução.','Compressão de instruções.','Troca de endereçamento direto por imediato.'],'Múltiplos núcleos permitem executar fluxos independentes simultaneamente.','Verifique se o paralelismo vem de várias tarefas ou da sobreposição de etapas de uma só CPU.','As tarefas distintas podem ser distribuídas entre núcleos sem criar dependências entre si.'),
  q('ca-r01-013','hard','paralelismo','Um programa possui 80% de seu tempo perfeitamente paralelizável e 20% inevitavelmente serial. Pelo limite de Amdahl, qual é o ganho máximo com infinitos processadores?','$5$.',['$1,25$.','$4$.','Infinito.'],'A parte serial limita o ganho global: speedup máximo é $1/f_{serial}$.','Faça o número de processadores tender ao infinito na expressão de Amdahl.','Com fração serial $0,20$, o limite é $1/0,20=5$.'),
  q('ca-r01-014','easy','endereços e dados','Qual é a função primária de um endereço de memória?','Selecionar a posição cujo conteúdo será lido ou escrito.',['Representar sempre o dado armazenado.','Determinar a frequência do clock.','Codificar uma operação da ULA.'],'Endereço identifica uma localização; dado é o conteúdo transferido dessa localização.','Diferencie “onde” está a informação de “qual” é a informação.','Um mesmo endereço pode conter valores diferentes ao longo do tempo.'),
  q('ca-r01-015','medium','endereçamento','Uma memória é endereçável por byte e possui 16 linhas de endereço. Qual capacidade diretamente endereçável ela tem?','$64$ KiB.',['$16$ bytes.','$32$ KiB.','$128$ KiB.'],'Com $n$ linhas de endereço existem $2^n$ posições; cada posição contém um byte.','Calcule $2^{16}$ e converta bytes para KiB.','$2^{16}=65536$ bytes, isto é, $64$ KiB.'),
  q('ca-r01-016','hard','ordem de bytes','Uma palavra de 32 bits $0x12345678$ é armazenada no endereço 100 em máquina little-endian. Qual byte fica no endereço 100?','$0x78$.',['$0x12$.','$0x34$.','$0x56$.'],'Little-endian coloca o byte menos significativo no menor endereço.','Separe a palavra em $12$, $34$, $56$ e $78$ e ordene os endereços crescentes.','O menor endereço recebe o byte menos significativo.'),
  q('ca-r01-017','medium','correção de erro','Qual vantagem um código de correção de erro oferece além de um bit de paridade simples?','Pode localizar e corrigir certos erros de um bit.',['Elimina a necessidade de memória.','Aumenta automaticamente o clock.','Impede qualquer erro de múltiplos bits.'],'Paridade normalmente detecta uma classe de erros; códigos com bits redundantes podem identificar a posição de um erro simples.','Compare detectar uma inconsistência com saber qual bit deve ser corrigido.','Correção de um bit não implica correção universal de falhas múltiplas.'),
  q('ca-r01-018','easy','hierarquia de memória','Por que caches usam blocos, e não transferem sempre um único byte?','Para aproveitar a localidade espacial de dados próximos.',['Para eliminar a RAM.','Para tornar endereços desnecessários.','Para impedir leituras repetidas.'],'Dados próximos no endereço tendem a ser acessados juntos; um bloco traz essa vizinhança.','Pense no padrão de acesso sequencial a vetores ou instruções.','Transferir uma linha ajuda acessos próximos, embora não garanta hit em todos eles.'),
  q('ca-r01-019','medium','cache','Uma cache tem taxa de hit de 95%, tempo de hit 2 ns e penalidade de miss 40 ns. Qual AMAT aproxima melhor o tempo médio?','4 ns.',['2 ns.','40 ns.','42 ns.'],'AMAT = tempo de hit + taxa de miss × penalidade de miss.','Use taxa de miss $0,05$ na parcela adicional.','$2+0,05\times40=4$ ns.'),
  q('ca-r01-020','hard','cache','Um laço percorre uma matriz por linhas em memória organizada por linhas. Qual ordem de acesso tende a produzir mais localidade espacial?','Percorrer colunas internas consecutivas dentro de cada linha.',['Saltar uma linha inteira a cada acesso.','Acessar elementos em ordem aleatória.','Alternar sempre entre extremos da matriz.'],'Localidade espacial favorece endereços consecutivos, que costumam estar na mesma linha de cache.','Relacione a ordem lógica do laço à disposição contígua dos elementos.','Acessos adjacentes reutilizam o bloco recém-carregado.'),
  q('ca-r01-021','easy','interrupções','Qual problema uma interrupção de E/S ajuda a evitar?','A CPU consultar continuamente um dispositivo lento para saber se ele terminou.',['A CPU usar registradores.','A memória ter endereços.','O dispositivo transferir dados.'],'Interrupção permite que o dispositivo notifique a CPU quando um evento ocorre.','Compare espera ativa com aviso assíncrono de conclusão.','A CPU pode executar outro trabalho até ser interrompida.'),
  q('ca-r01-022','medium','DMA','Em uma transferência grande de disco para memória, qual é o papel típico de um controlador DMA?','Mover o bloco entre dispositivo e memória com pouca intervenção da CPU.',['Executar cada instrução do processo.','Substituir a memória principal.','Decidir todos os desvios do programa.'],'DMA assume a transferência de dados e costuma sinalizar a conclusão por interrupção.','Diferencie a preparação da operação pela CPU da movimentação repetitiva dos bytes.','A CPU configura o DMA, mas não precisa copiar cada palavra individualmente.'),
  q('ca-r01-023','hard','barramentos','Dois mestres solicitam o mesmo barramento compartilhado no mesmo ciclo. Que mecanismo decide quem pode iniciar a transferência?','Arbitragem de barramento.',['Decodificação de opcode.','Correção de erro.','Previsão de desvio.'],'Arbitragem resolve competição por um recurso compartilhado entre mestres de barramento.','Identifique o conflito: dois solicitantes, um canal físico.','A decisão de posse deve ocorrer antes da transferência de endereço e dados.'),
  q('ca-r01-024','medium','pipeline','A instrução I2 precisa do resultado que I1 ainda produzirá. Que risco de pipeline existe?','Hazard de dados.',['Hazard estrutural causado por um salto.','Falha de página.','Erro de paridade.'],'Dependência produtor-consumidor exige que o valor esteja disponível antes do uso.','Observe se a causa é dado pendente, recurso disputado ou escolha de fluxo.','I2 não pode usar o resultado correto enquanto I1 não o produzir ou encaminhar.'),
  q('ca-r01-025','hard','pipeline','Uma previsão de desvio é considerada tomada, mas a condição avaliada mostra que não deveria desviar. Por que instruções do caminho previsto precisam ser anuladas?','Elas pertencem ao fluxo errado e não podem alterar o estado arquitetural.',['Elas sempre são inválidas.','A cache não pode conter instruções.','O PC não pode ser atualizado.'],'Execução especulativa só é segura se efeitos de um caminho incorreto forem descartados.','Siga o fluxo real após avaliar a condição e compare com o caminho buscado.','Permitir que o caminho errado grave registradores ou memória produziria resultado incorreto.'),
];
