-- Arquitetura de Computadores: revisão de gabaritos, lote 04.
-- Atualiza apenas soluções e passos; tentativas e alternativas são preservadas.
begin;

update public.question_solutions set final_answer_markdown='Porque ficam próximos à ULA e têm pouca capacidade.', explanation_markdown='Níveis superiores trocam capacidade por baixa latência. No caso apresentado, Compare distância e quantidade de dados guardados. Velocidade não elimina a limitação de capacidade. Logo, “Porque ficam próximos à ULA e têm pouca capacidade.” é a conclusão correta. “Porque são não voláteis.” não cumpre o critério técnico do caso: Velocidade não elimina a limitação de capacidade. “Porque usam disco.” não decorre do princípio aplicável: Níveis superiores trocam capacidade por baixa latência. “Porque não armazenam dados.” deixa de executar a análise necessária: Compare distância e quantidade de dados guardados.' where question_id='40000000-0000-4000-8000-000000930076';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de hierarquia de memória: Por que registradores costumam ser mais rápidos que RAM?', sort_order=1 where id='70000000-0000-4000-8000-000009300761';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Níveis superiores trocam capacidade por baixa latência.', sort_order=2 where id='70000000-0000-4000-8000-000009300762';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare distância e quantidade de dados guardados. No enunciado, Por que registradores costumam ser mais rápidos que RAM? Velocidade não elimina a limitação de capacidade.', sort_order=3 where id='70000000-0000-4000-8000-000009300763';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Porque são não voláteis.” não cumpre o critério técnico do caso: Velocidade não elimina a limitação de capacidade. “Porque usam disco.” não decorre do princípio aplicável: Níveis superiores trocam capacidade por baixa latência. “Porque não armazenam dados.” deixa de executar a análise necessária: Compare distância e quantidade de dados guardados.', sort_order=4 where id='70000000-0000-4000-8000-000009300764';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Porque ficam próximos à ULA e têm pouca capacidade.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300765';

update public.question_solutions set final_answer_markdown='Registradores, cache, RAM, SSD.', explanation_markdown='A hierarquia aproxima os dados mais usados do processador. No caso apresentado, Ordene por latência típica. Registradores são o nível mais imediato da CPU. Logo, “Registradores, cache, RAM, SSD.” é a conclusão correta. “RAM, cache, registradores, SSD.” não cumpre o critério técnico do caso: Registradores são o nível mais imediato da CPU. “SSD, RAM, cache, registradores.” não decorre do princípio aplicável: A hierarquia aproxima os dados mais usados do processador. “Cache, registradores, SSD, RAM.” deixa de executar a análise necessária: Ordene por latência típica.' where question_id='40000000-0000-4000-8000-000000930077';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de hierarquia de memória: Qual ordem lista níveis do mais rápido ao mais lento?', sort_order=1 where id='70000000-0000-4000-8000-000009300771';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='A hierarquia aproxima os dados mais usados do processador.', sort_order=2 where id='70000000-0000-4000-8000-000009300772';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Ordene por latência típica. No enunciado, Qual ordem lista níveis do mais rápido ao mais lento? Registradores são o nível mais imediato da CPU.', sort_order=3 where id='70000000-0000-4000-8000-000009300773';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“RAM, cache, registradores, SSD.” não cumpre o critério técnico do caso: Registradores são o nível mais imediato da CPU. “SSD, RAM, cache, registradores.” não decorre do princípio aplicável: A hierarquia aproxima os dados mais usados do processador. “Cache, registradores, SSD, RAM.” deixa de executar a análise necessária: Ordene por latência típica.', sort_order=4 where id='70000000-0000-4000-8000-000009300774';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Registradores, cache, RAM, SSD.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300775';

update public.question_solutions set final_answer_markdown='Temporal.', explanation_markdown='Reuso do mesmo item em pouco tempo é localidade temporal. No caso apresentado, Observe se a repetição é do dado ou de vizinhos. A mesma variável tende a permanecer útil na cache. Logo, “Temporal.” é a conclusão correta. “Espacial.” não cumpre o critério técnico do caso: A mesma variável tende a permanecer útil na cache. “De endereço virtual.” não decorre do princípio aplicável: Reuso do mesmo item em pouco tempo é localidade temporal. “De barramento.” deixa de executar a análise necessária: Observe se a repetição é do dado ou de vizinhos.' where question_id='40000000-0000-4000-8000-000000930078';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de localidade temporal: Um programa consulta repetidamente a mesma variável de controle. Que localidade explora?', sort_order=1 where id='70000000-0000-4000-8000-000009300781';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Reuso do mesmo item em pouco tempo é localidade temporal.', sort_order=2 where id='70000000-0000-4000-8000-000009300782';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Observe se a repetição é do dado ou de vizinhos. No enunciado, Um programa consulta repetidamente a mesma variável de controle. Que localidade explora? A mesma variável tende a permanecer útil na cache.', sort_order=3 where id='70000000-0000-4000-8000-000009300783';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Espacial.” não cumpre o critério técnico do caso: A mesma variável tende a permanecer útil na cache. “De endereço virtual.” não decorre do princípio aplicável: Reuso do mesmo item em pouco tempo é localidade temporal. “De barramento.” deixa de executar a análise necessária: Observe se a repetição é do dado ou de vizinhos.', sort_order=4 where id='70000000-0000-4000-8000-000009300784';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Temporal.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300785';

update public.question_solutions set final_answer_markdown='Espacial.', explanation_markdown='Itens em endereços próximos tendem a compartilhar uma linha de cache. No caso apresentado, Compare o índice atual com o próximo. A próxima posição provavelmente já veio no mesmo bloco. Logo, “Espacial.” é a conclusão correta. “Temporal apenas.” não cumpre o critério técnico do caso: A próxima posição provavelmente já veio no mesmo bloco. “De interrupção.” não decorre do princípio aplicável: Itens em endereços próximos tendem a compartilhar uma linha de cache. “De microcódigo.” deixa de executar a análise necessária: Compare o índice atual com o próximo.' where question_id='40000000-0000-4000-8000-000000930079';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de localidade espacial: Uma rotina percorre um vetor em índices consecutivos. Que localidade é favorecida?', sort_order=1 where id='70000000-0000-4000-8000-000009300791';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Itens em endereços próximos tendem a compartilhar uma linha de cache.', sort_order=2 where id='70000000-0000-4000-8000-000009300792';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare o índice atual com o próximo. No enunciado, Uma rotina percorre um vetor em índices consecutivos. Que localidade é favorecida? A próxima posição provavelmente já veio no mesmo bloco.', sort_order=3 where id='70000000-0000-4000-8000-000009300793';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Temporal apenas.” não cumpre o critério técnico do caso: A próxima posição provavelmente já veio no mesmo bloco. “De interrupção.” não decorre do princípio aplicável: Itens em endereços próximos tendem a compartilhar uma linha de cache. “De microcódigo.” deixa de executar a análise necessária: Compare o índice atual com o próximo.', sort_order=4 where id='70000000-0000-4000-8000-000009300794';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Espacial.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300795';

update public.question_solutions set final_answer_markdown='3 ns.', explanation_markdown='AMAT soma hit a miss rate vezes penalidade. No caso apresentado, Use taxa de miss $0,10$. $1+0,10	imes20=3$ ns. Logo, “3 ns.” é a conclusão correta. “1 ns.” não cumpre o critério técnico do caso: $1+0,10	imes20=3$ ns. “20 ns.” não decorre do princípio aplicável: AMAT soma hit a miss rate vezes penalidade. “21 ns.” deixa de executar a análise necessária: Use taxa de miss $0,10$.' where question_id='40000000-0000-4000-8000-000000930080';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de AMAT: Cache L1 tem hit de 90%, 1 ns de hit e 20 ns de penalidade. Qual AMAT?', sort_order=1 where id='70000000-0000-4000-8000-000009300801';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='AMAT soma hit a miss rate vezes penalidade.', sort_order=2 where id='70000000-0000-4000-8000-000009300802';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Use taxa de miss $0,10$. No enunciado, Cache L1 tem hit de 90%, 1 ns de hit e 20 ns de penalidade. Qual AMAT? $1+0,10	imes20=3$ ns.', sort_order=3 where id='70000000-0000-4000-8000-000009300803';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“1 ns.” não cumpre o critério técnico do caso: $1+0,10	imes20=3$ ns. “20 ns.” não decorre do princípio aplicável: AMAT soma hit a miss rate vezes penalidade. “21 ns.” deixa de executar a análise necessária: Use taxa de miss $0,10$.', sort_order=4 where id='70000000-0000-4000-8000-000009300804';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “3 ns.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300805';

update public.question_solutions set final_answer_markdown='O bloco solicitado está presente na cache.', explanation_markdown='Hit evita consulta ao nível inferior. No caso apresentado, Identifique onde o dado foi encontrado. Presença local é o critério de hit. Logo, “O bloco solicitado está presente na cache.” é a conclusão correta. “A cache foi apagada.” não cumpre o critério técnico do caso: Presença local é o critério de hit. “A RAM falhou.” não decorre do princípio aplicável: Hit evita consulta ao nível inferior. “O processador parou.” deixa de executar a análise necessária: Identifique onde o dado foi encontrado.' where question_id='40000000-0000-4000-8000-000000930081';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de cache hit: O que é cache hit?', sort_order=1 where id='70000000-0000-4000-8000-000009300811';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Hit evita consulta ao nível inferior.', sort_order=2 where id='70000000-0000-4000-8000-000009300812';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique onde o dado foi encontrado. No enunciado, O que é cache hit? Presença local é o critério de hit.', sort_order=3 where id='70000000-0000-4000-8000-000009300813';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A cache foi apagada.” não cumpre o critério técnico do caso: Presença local é o critério de hit. “A RAM falhou.” não decorre do princípio aplicável: Hit evita consulta ao nível inferior. “O processador parou.” deixa de executar a análise necessária: Identifique onde o dado foi encontrado.', sort_order=4 where id='70000000-0000-4000-8000-000009300814';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “O bloco solicitado está presente na cache.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300815';

update public.question_solutions set final_answer_markdown='Permite que um bloco ocupe mais de uma posição possível.', explanation_markdown='Mais posições candidatas reduzem certos conflitos. No caso apresentado, Compare liberdade de colocação dos blocos. A associatividade não elimina capacidade limitada. Logo, “Permite que um bloco ocupe mais de uma posição possível.” é a conclusão correta. “Não precisa de tags.” não cumpre o critério técnico do caso: A associatividade não elimina capacidade limitada. “Não tem misses.” não decorre do princípio aplicável: Mais posições candidatas reduzem certos conflitos. “Dispensa substituição.” deixa de executar a análise necessária: Compare liberdade de colocação dos blocos.' where question_id='40000000-0000-4000-8000-000000930082';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de associatividade: Qual vantagem uma cache associativa tem sobre mapeamento direto?', sort_order=1 where id='70000000-0000-4000-8000-000009300821';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Mais posições candidatas reduzem certos conflitos.', sort_order=2 where id='70000000-0000-4000-8000-000009300822';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare liberdade de colocação dos blocos. No enunciado, Qual vantagem uma cache associativa tem sobre mapeamento direto? A associatividade não elimina capacidade limitada.', sort_order=3 where id='70000000-0000-4000-8000-000009300823';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Não precisa de tags.” não cumpre o critério técnico do caso: A associatividade não elimina capacidade limitada. “Não tem misses.” não decorre do princípio aplicável: Mais posições candidatas reduzem certos conflitos. “Dispensa substituição.” deixa de executar a análise necessária: Compare liberdade de colocação dos blocos.', sort_order=4 where id='70000000-0000-4000-8000-000009300824';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Permite que um bloco ocupe mais de uma posição possível.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300825';

update public.question_solutions set final_answer_markdown='Miss por conflito.', explanation_markdown='Mapeamento restrito pode expulsar blocos úteis entre si. No caso apresentado, Observe que os blocos competem por uma única linha. Alternância causa substituições mesmo com cache pouco cheia. Logo, “Miss por conflito.” é a conclusão correta. “Miss compulsório apenas.” não cumpre o critério técnico do caso: Alternância causa substituições mesmo com cache pouco cheia. “Hit de escrita.” não decorre do princípio aplicável: Mapeamento restrito pode expulsar blocos úteis entre si. “Falha de página.” deixa de executar a análise necessária: Observe que os blocos competem por uma única linha.' where question_id='40000000-0000-4000-8000-000000930083';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de conflito de cache: Dois blocos usados alternadamente mapeiam para a mesma linha em cache direta. Que miss ocorre repetidamente?', sort_order=1 where id='70000000-0000-4000-8000-000009300831';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Mapeamento restrito pode expulsar blocos úteis entre si.', sort_order=2 where id='70000000-0000-4000-8000-000009300832';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Observe que os blocos competem por uma única linha. No enunciado, Dois blocos usados alternadamente mapeiam para a mesma linha em cache direta. Que miss ocorre repetidamente? Alternância causa substituições mesmo com cache pouco cheia.', sort_order=3 where id='70000000-0000-4000-8000-000009300833';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Miss compulsório apenas.” não cumpre o critério técnico do caso: Alternância causa substituições mesmo com cache pouco cheia. “Hit de escrita.” não decorre do princípio aplicável: Mapeamento restrito pode expulsar blocos úteis entre si. “Falha de página.” deixa de executar a análise necessária: Observe que os blocos competem por uma única linha.', sort_order=4 where id='70000000-0000-4000-8000-000009300834';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Miss por conflito.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300835';

update public.question_solutions set final_answer_markdown='Cada escrita atualiza cache e nível inferior.', explanation_markdown='Write-through simplifica consistência, mas gera tráfego. No caso apresentado, Acompanhe o destino da escrita após atualizar a cache. A memória inferior recebe a alteração imediatamente. Logo, “Cada escrita atualiza cache e nível inferior.” é a conclusão correta. “Escreve só no disco.” não cumpre o critério técnico do caso: A memória inferior recebe a alteração imediatamente. “Nunca atualiza memória.” não decorre do princípio aplicável: Write-through simplifica consistência, mas gera tráfego. “Remove a cache.” deixa de executar a análise necessária: Acompanhe o destino da escrita após atualizar a cache.' where question_id='40000000-0000-4000-8000-000000930084';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de write-through: Qual é o efeito de write-through?', sort_order=1 where id='70000000-0000-4000-8000-000009300841';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Write-through simplifica consistência, mas gera tráfego.', sort_order=2 where id='70000000-0000-4000-8000-000009300842';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Acompanhe o destino da escrita após atualizar a cache. No enunciado, Qual é o efeito de write-through? A memória inferior recebe a alteração imediatamente.', sort_order=3 where id='70000000-0000-4000-8000-000009300843';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Escreve só no disco.” não cumpre o critério técnico do caso: A memória inferior recebe a alteração imediatamente. “Nunca atualiza memória.” não decorre do princípio aplicável: Write-through simplifica consistência, mas gera tráfego. “Remove a cache.” deixa de executar a análise necessária: Acompanhe o destino da escrita após atualizar a cache.', sort_order=4 where id='70000000-0000-4000-8000-000009300844';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Cada escrita atualiza cache e nível inferior.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300845';

update public.question_solutions set final_answer_markdown='Quando é substituída ou explicitamente sincronizada.', explanation_markdown='Write-back adia propagação até a linha deixar a cache. No caso apresentado, Relacione dirty bit à necessidade de preservar alteração. A substituição não pode descartar uma alteração não propagada. Logo, “Quando é substituída ou explicitamente sincronizada.” é a conclusão correta. “Em toda leitura.” não cumpre o critério técnico do caso: A substituição não pode descartar uma alteração não propagada. “Antes de toda escrita.” não decorre do princípio aplicável: Write-back adia propagação até a linha deixar a cache. “Nunca.” deixa de executar a análise necessária: Relacione dirty bit à necessidade de preservar alteração.' where question_id='40000000-0000-4000-8000-000000930085';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de write-back: Quando uma linha suja em write-back precisa ser escrita na memória?', sort_order=1 where id='70000000-0000-4000-8000-000009300851';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Write-back adia propagação até a linha deixar a cache.', sort_order=2 where id='70000000-0000-4000-8000-000009300852';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Relacione dirty bit à necessidade de preservar alteração. No enunciado, Quando uma linha suja em write-back precisa ser escrita na memória? A substituição não pode descartar uma alteração não propagada.', sort_order=3 where id='70000000-0000-4000-8000-000009300853';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Em toda leitura.” não cumpre o critério técnico do caso: A substituição não pode descartar uma alteração não propagada. “Antes de toda escrita.” não decorre do princípio aplicável: Write-back adia propagação até a linha deixar a cache. “Nunca.” deixa de executar a análise necessária: Relacione dirty bit à necessidade de preservar alteração.', sort_order=4 where id='70000000-0000-4000-8000-000009300854';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Quando é substituída ou explicitamente sincronizada.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300855';

update public.question_solutions set final_answer_markdown='A página virtual referenciada não está na RAM.', explanation_markdown='Memória virtual precisa trazer a página ausente do armazenamento. No caso apresentado, Diferencie página de linha de cache. A execução só continua após resolver o mapeamento. Logo, “A página virtual referenciada não está na RAM.” é a conclusão correta. “A cache acertou.” não cumpre o critério técnico do caso: A execução só continua após resolver o mapeamento. “O PC é inválido.” não decorre do princípio aplicável: Memória virtual precisa trazer a página ausente do armazenamento. “O disco foi removido.” deixa de executar a análise necessária: Diferencie página de linha de cache.' where question_id='40000000-0000-4000-8000-000000930086';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de paginação: O que indica uma falta de página?', sort_order=1 where id='70000000-0000-4000-8000-000009300861';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Memória virtual precisa trazer a página ausente do armazenamento.', sort_order=2 where id='70000000-0000-4000-8000-000009300862';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Diferencie página de linha de cache. No enunciado, O que indica uma falta de página? A execução só continua após resolver o mapeamento.', sort_order=3 where id='70000000-0000-4000-8000-000009300863';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A cache acertou.” não cumpre o critério técnico do caso: A execução só continua após resolver o mapeamento. “O PC é inválido.” não decorre do princípio aplicável: Memória virtual precisa trazer a página ausente do armazenamento. “O disco foi removido.” deixa de executar a análise necessária: Diferencie página de linha de cache.', sort_order=4 where id='70000000-0000-4000-8000-000009300864';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “A página virtual referenciada não está na RAM.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300865';

update public.question_solutions set final_answer_markdown='Acelerar tradução de endereços virtuais recentes.', explanation_markdown='TLB é uma cache de traduções de página. No caso apresentado, Pergunte qual informação é reutilizada antes de acessar memória. Hit no TLB evita consultar a tabela de páginas. Logo, “Acelerar tradução de endereços virtuais recentes.” é a conclusão correta. “Guardar instruções da ULA.” não cumpre o critério técnico do caso: Hit no TLB evita consultar a tabela de páginas. “Substituir o SSD.” não decorre do princípio aplicável: TLB é uma cache de traduções de página. “Corrigir paridade.” deixa de executar a análise necessária: Pergunte qual informação é reutilizada antes de acessar memória.' where question_id='40000000-0000-4000-8000-000000930087';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de TLB: Qual é a função do TLB?', sort_order=1 where id='70000000-0000-4000-8000-000009300871';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='TLB é uma cache de traduções de página.', sort_order=2 where id='70000000-0000-4000-8000-000009300872';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Pergunte qual informação é reutilizada antes de acessar memória. No enunciado, Qual é a função do TLB? Hit no TLB evita consultar a tabela de páginas.', sort_order=3 where id='70000000-0000-4000-8000-000009300873';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Guardar instruções da ULA.” não cumpre o critério técnico do caso: Hit no TLB evita consultar a tabela de páginas. “Substituir o SSD.” não decorre do princípio aplicável: TLB é uma cache de traduções de página. “Corrigir paridade.” deixa de executar a análise necessária: Pergunte qual informação é reutilizada antes de acessar memória.', sort_order=4 where id='70000000-0000-4000-8000-000009300874';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Acelerar tradução de endereços virtuais recentes.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300875';

update public.question_solutions set final_answer_markdown='Há menos entradas, mas cresce fragmentação interna.', explanation_markdown='Tamanho de página equilibra metadados e espaço ocioso na última página. No caso apresentado, Compare número de páginas com espaço não usado. Menos páginas não garante melhor aproveitamento. Logo, “Há menos entradas, mas cresce fragmentação interna.” é a conclusão correta. “A RAM fica mais rápida.” não cumpre o critério técnico do caso: Menos páginas não garante melhor aproveitamento. “O TLB deixa de existir.” não decorre do princípio aplicável: Tamanho de página equilibra metadados e espaço ocioso na última página. “Endereços perdem bits.” deixa de executar a análise necessária: Compare número de páginas com espaço não usado.' where question_id='40000000-0000-4000-8000-000000930088';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de página: Por que uma página maior pode reduzir tamanho da tabela e aumentar desperdício?', sort_order=1 where id='70000000-0000-4000-8000-000009300881';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Tamanho de página equilibra metadados e espaço ocioso na última página.', sort_order=2 where id='70000000-0000-4000-8000-000009300882';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare número de páginas com espaço não usado. No enunciado, Por que uma página maior pode reduzir tamanho da tabela e aumentar desperdício? Menos páginas não garante melhor aproveitamento.', sort_order=3 where id='70000000-0000-4000-8000-000009300883';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A RAM fica mais rápida.” não cumpre o critério técnico do caso: Menos páginas não garante melhor aproveitamento. “O TLB deixa de existir.” não decorre do princípio aplicável: Tamanho de página equilibra metadados e espaço ocioso na última página. “Endereços perdem bits.” deixa de executar a análise necessária: Compare número de páginas com espaço não usado.', sort_order=4 where id='70000000-0000-4000-8000-000009300884';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Há menos entradas, mas cresce fragmentação interna.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300885';

update public.question_solutions set final_answer_markdown='Movimento mecânico de cabeça e rotação.', explanation_markdown='Discos mecânicos esperam posicionamento físico antes de transferir dados. No caso apresentado, Diferencie mídia giratória de armazenamento eletrônico. Busca e latência rotacional precedem a transferência. Logo, “Movimento mecânico de cabeça e rotação.” é a conclusão correta. “ALU.” não cumpre o critério técnico do caso: Busca e latência rotacional precedem a transferência. “Registrador PC.” não decorre do princípio aplicável: Discos mecânicos esperam posicionamento físico antes de transferir dados. “Paridade.” deixa de executar a análise necessária: Diferencie mídia giratória de armazenamento eletrônico.' where question_id='40000000-0000-4000-8000-000000930089';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de disco: Qual componente domina a latência de acesso em disco magnético aleatório?', sort_order=1 where id='70000000-0000-4000-8000-000009300891';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Discos mecânicos esperam posicionamento físico antes de transferir dados.', sort_order=2 where id='70000000-0000-4000-8000-000009300892';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Diferencie mídia giratória de armazenamento eletrônico. No enunciado, Qual componente domina a latência de acesso em disco magnético aleatório? Busca e latência rotacional precedem a transferência.', sort_order=3 where id='70000000-0000-4000-8000-000009300893';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“ALU.” não cumpre o critério técnico do caso: Busca e latência rotacional precedem a transferência. “Registrador PC.” não decorre do princípio aplicável: Discos mecânicos esperam posicionamento físico antes de transferir dados. “Paridade.” deixa de executar a análise necessária: Diferencie mídia giratória de armazenamento eletrônico.', sort_order=4 where id='70000000-0000-4000-8000-000009300894';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Movimento mecânico de cabeça e rotação.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300895';

update public.question_solutions set final_answer_markdown='Não precisam mover partes mecânicas.', explanation_markdown='Memória flash reduz latência de posicionamento físico. No caso apresentado, Compare o custo de buscar posição em SSD e disco. Flash ainda tem limitações de escrita e desgaste. Logo, “Não precisam mover partes mecânicas.” é a conclusão correta. “Não usam endereços.” não cumpre o critério técnico do caso: Flash ainda tem limitações de escrita e desgaste. “Não possuem blocos.” não decorre do princípio aplicável: Memória flash reduz latência de posicionamento físico. “Não sofrem desgaste.” deixa de executar a análise necessária: Compare o custo de buscar posição em SSD e disco.' where question_id='40000000-0000-4000-8000-000000930090';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de SSD: Por que SSDs são especialmente melhores em acessos aleatórios pequenos?', sort_order=1 where id='70000000-0000-4000-8000-000009300901';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Memória flash reduz latência de posicionamento físico.', sort_order=2 where id='70000000-0000-4000-8000-000009300902';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare o custo de buscar posição em SSD e disco. No enunciado, Por que SSDs são especialmente melhores em acessos aleatórios pequenos? Flash ainda tem limitações de escrita e desgaste.', sort_order=3 where id='70000000-0000-4000-8000-000009300903';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Não usam endereços.” não cumpre o critério técnico do caso: Flash ainda tem limitações de escrita e desgaste. “Não possuem blocos.” não decorre do princípio aplicável: Memória flash reduz latência de posicionamento físico. “Não sofrem desgaste.” deixa de executar a análise necessária: Compare o custo de buscar posição em SSD e disco.', sort_order=4 where id='70000000-0000-4000-8000-000009300904';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Não precisam mover partes mecânicas.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300905';

update public.question_solutions set final_answer_markdown='Espelhamento para tolerar falha de um disco.', explanation_markdown='RAID 1 grava cópias em discos distintos. No caso apresentado, Pense no que permanece disponível após uma falha. A redundância consome capacidade para aumentar disponibilidade. Logo, “Espelhamento para tolerar falha de um disco.” é a conclusão correta. “Capacidade igual à soma sem redundância.” não cumpre o critério técnico do caso: A redundância consome capacidade para aumentar disponibilidade. “Sem cópias de dados.” não decorre do princípio aplicável: RAID 1 grava cópias em discos distintos. “Paridade sem duplicação.” deixa de executar a análise necessária: Pense no que permanece disponível após uma falha.' where question_id='40000000-0000-4000-8000-000000930091';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de RAID: Qual benefício RAID 1 oferece?', sort_order=1 where id='70000000-0000-4000-8000-000009300911';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='RAID 1 grava cópias em discos distintos.', sort_order=2 where id='70000000-0000-4000-8000-000009300912';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Pense no que permanece disponível após uma falha. No enunciado, Qual benefício RAID 1 oferece? A redundância consome capacidade para aumentar disponibilidade.', sort_order=3 where id='70000000-0000-4000-8000-000009300913';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Capacidade igual à soma sem redundância.” não cumpre o critério técnico do caso: A redundância consome capacidade para aumentar disponibilidade. “Sem cópias de dados.” não decorre do princípio aplicável: RAID 1 grava cópias em discos distintos. “Paridade sem duplicação.” deixa de executar a análise necessária: Pense no que permanece disponível após uma falha.', sort_order=4 where id='70000000-0000-4000-8000-000009300914';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Espelhamento para tolerar falha de um disco.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300915';

update public.question_solutions set final_answer_markdown='Para evitar concentrar todas as escritas de paridade em um único disco.', explanation_markdown='Paridade distribuída equilibra carga entre os membros. No caso apresentado, Compare um disco de paridade fixo com rotação de paridade. Ainda há custo de atualização em pequenas escritas. Logo, “Para evitar concentrar todas as escritas de paridade em um único disco.” é a conclusão correta. “Para eliminar redundância.” não cumpre o critério técnico do caso: Ainda há custo de atualização em pequenas escritas. “Para impedir leituras paralelas.” não decorre do princípio aplicável: Paridade distribuída equilibra carga entre os membros. “Para armazenar só metadados.” deixa de executar a análise necessária: Compare um disco de paridade fixo com rotação de paridade.' where question_id='40000000-0000-4000-8000-000000930092';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de RAID: Por que RAID 5 distribui paridade entre discos?', sort_order=1 where id='70000000-0000-4000-8000-000009300921';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Paridade distribuída equilibra carga entre os membros.', sort_order=2 where id='70000000-0000-4000-8000-000009300922';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare um disco de paridade fixo com rotação de paridade. No enunciado, Por que RAID 5 distribui paridade entre discos? Ainda há custo de atualização em pequenas escritas.', sort_order=3 where id='70000000-0000-4000-8000-000009300923';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para eliminar redundância.” não cumpre o critério técnico do caso: Ainda há custo de atualização em pequenas escritas. “Para impedir leituras paralelas.” não decorre do princípio aplicável: Paridade distribuída equilibra carga entre os membros. “Para armazenar só metadados.” deixa de executar a análise necessária: Compare um disco de paridade fixo com rotação de paridade.', sort_order=4 where id='70000000-0000-4000-8000-000009300924';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para evitar concentrar todas as escritas de paridade em um único disco.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300925';

update public.question_solutions set final_answer_markdown='A CPU consulta repetidamente o estado do dispositivo.', explanation_markdown='Polling é espera ativa baseada em consultas. No caso apresentado, Observe quem inicia cada verificação. A CPU consome ciclos mesmo sem dado novo. Logo, “A CPU consulta repetidamente o estado do dispositivo.” é a conclusão correta. “O dispositivo interrompe a CPU.” não cumpre o critério técnico do caso: A CPU consome ciclos mesmo sem dado novo. “DMA move dados.” não decorre do princípio aplicável: Polling é espera ativa baseada em consultas. “A cache substitui o periférico.” deixa de executar a análise necessária: Observe quem inicia cada verificação.' where question_id='40000000-0000-4000-8000-000000930093';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de E/S programada: O que caracteriza polling?', sort_order=1 where id='70000000-0000-4000-8000-000009300931';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Polling é espera ativa baseada em consultas.', sort_order=2 where id='70000000-0000-4000-8000-000009300932';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Observe quem inicia cada verificação. No enunciado, O que caracteriza polling? A CPU consome ciclos mesmo sem dado novo.', sort_order=3 where id='70000000-0000-4000-8000-000009300933';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“O dispositivo interrompe a CPU.” não cumpre o critério técnico do caso: A CPU consome ciclos mesmo sem dado novo. “DMA move dados.” não decorre do princípio aplicável: Polling é espera ativa baseada em consultas. “A cache substitui o periférico.” deixa de executar a análise necessária: Observe quem inicia cada verificação.', sort_order=4 where id='70000000-0000-4000-8000-000009300934';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “A CPU consulta repetidamente o estado do dispositivo.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300935';

update public.question_solutions set final_answer_markdown='O contexto necessário, como PC e registradores relevantes.', explanation_markdown='A rotina de interrupção não pode destruir o estado do trabalho interrompido. No caso apresentado, Pergunte o que define o ponto exato de retorno. Restaurar contexto permite continuar como se a pausa não tivesse ocorrido. Logo, “O contexto necessário, como PC e registradores relevantes.” é a conclusão correta. “A capacidade do disco.” não cumpre o critério técnico do caso: Restaurar contexto permite continuar como se a pausa não tivesse ocorrido. “A tag da cache inteira.” não decorre do princípio aplicável: A rotina de interrupção não pode destruir o estado do trabalho interrompido. “A tabela ASCII.” deixa de executar a análise necessária: Pergunte o que define o ponto exato de retorno.' where question_id='40000000-0000-4000-8000-000000930094';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de interrupção: Após atender uma interrupção, o que a CPU deve preservar para retomar o programa?', sort_order=1 where id='70000000-0000-4000-8000-000009300941';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='A rotina de interrupção não pode destruir o estado do trabalho interrompido.', sort_order=2 where id='70000000-0000-4000-8000-000009300942';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Pergunte o que define o ponto exato de retorno. No enunciado, Após atender uma interrupção, o que a CPU deve preservar para retomar o programa? Restaurar contexto permite continuar como se a pausa não tivesse ocorrido.', sort_order=3 where id='70000000-0000-4000-8000-000009300943';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A capacidade do disco.” não cumpre o critério técnico do caso: Restaurar contexto permite continuar como se a pausa não tivesse ocorrido. “A tag da cache inteira.” não decorre do princípio aplicável: A rotina de interrupção não pode destruir o estado do trabalho interrompido. “A tabela ASCII.” deixa de executar a análise necessária: Pergunte o que define o ponto exato de retorno.', sort_order=4 where id='70000000-0000-4000-8000-000009300944';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “O contexto necessário, como PC e registradores relevantes.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300945';

update public.question_solutions set final_answer_markdown='Porque dispositivo e CPU podem observar cópias diferentes de um mesmo bloco.', explanation_markdown='Transferência externa pode atualizar RAM sem atualizar cache privada. No caso apresentado, Compare onde o dado novo é escrito e onde a CPU ainda pode lê-lo. Invalidar ou sincronizar evita usar cópia antiga. Logo, “Porque dispositivo e CPU podem observar cópias diferentes de um mesmo bloco.” é a conclusão correta. “Porque DMA não usa memória.” não cumpre o critério técnico do caso: Invalidar ou sincronizar evita usar cópia antiga. “Porque o barramento não tem endereço.” não decorre do princípio aplicável: Transferência externa pode atualizar RAM sem atualizar cache privada. “Porque a ULA vira sequencial.” deixa de executar a análise necessária: Compare onde o dado novo é escrito e onde a CPU ainda pode lê-lo.' where question_id='40000000-0000-4000-8000-000000930095';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de DMA: Por que DMA pode exigir coerência de cache?', sort_order=1 where id='70000000-0000-4000-8000-000009300951';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Transferência externa pode atualizar RAM sem atualizar cache privada.', sort_order=2 where id='70000000-0000-4000-8000-000009300952';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare onde o dado novo é escrito e onde a CPU ainda pode lê-lo. No enunciado, Por que DMA pode exigir coerência de cache? Invalidar ou sincronizar evita usar cópia antiga.', sort_order=3 where id='70000000-0000-4000-8000-000009300953';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Porque DMA não usa memória.” não cumpre o critério técnico do caso: Invalidar ou sincronizar evita usar cópia antiga. “Porque o barramento não tem endereço.” não decorre do princípio aplicável: Transferência externa pode atualizar RAM sem atualizar cache privada. “Porque a ULA vira sequencial.” deixa de executar a análise necessária: Compare onde o dado novo é escrito e onde a CPU ainda pode lê-lo.', sort_order=4 where id='70000000-0000-4000-8000-000009300954';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Porque dispositivo e CPU podem observar cópias diferentes de um mesmo bloco.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300955';

update public.question_solutions set final_answer_markdown='Sinais como leitura, escrita e reconhecimento.', explanation_markdown='Controle coordena a transação; dados e endereços têm funções distintas. No caso apresentado, Classifique o sinal por seu papel. READ e WRITE descrevem ação, não conteúdo. Logo, “Sinais como leitura, escrita e reconhecimento.” é a conclusão correta. “Somente conteúdo de memória.” não cumpre o critério técnico do caso: READ e WRITE descrevem ação, não conteúdo. “Apenas endereços.” não decorre do princípio aplicável: Controle coordena a transação; dados e endereços têm funções distintas. “Código-fonte.” deixa de executar a análise necessária: Classifique o sinal por seu papel.' where question_id='40000000-0000-4000-8000-000000930096';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de barramento: Qual informação viaja no barramento de controle?', sort_order=1 where id='70000000-0000-4000-8000-000009300961';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Controle coordena a transação; dados e endereços têm funções distintas.', sort_order=2 where id='70000000-0000-4000-8000-000009300962';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Classifique o sinal por seu papel. No enunciado, Qual informação viaja no barramento de controle? READ e WRITE descrevem ação, não conteúdo.', sort_order=3 where id='70000000-0000-4000-8000-000009300963';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Somente conteúdo de memória.” não cumpre o critério técnico do caso: READ e WRITE descrevem ação, não conteúdo. “Apenas endereços.” não decorre do princípio aplicável: Controle coordena a transação; dados e endereços têm funções distintas. “Código-fonte.” deixa de executar a análise necessária: Classifique o sinal por seu papel.', sort_order=4 where id='70000000-0000-4000-8000-000009300964';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Sinais como leitura, escrita e reconhecimento.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300965';

update public.question_solutions set final_answer_markdown='8 bytes.', explanation_markdown='Oito bits formam um byte. No caso apresentado, Converta largura em bits para bytes. $64/8=8$ bytes por transferência. Logo, “8 bytes.” é a conclusão correta. “4 bytes.” não cumpre o critério técnico do caso: $64/8=8$ bytes por transferência. “16 bytes.” não decorre do princípio aplicável: Oito bits formam um byte. “64 bytes.” deixa de executar a análise necessária: Converta largura em bits para bytes.' where question_id='40000000-0000-4000-8000-000000930097';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de largura de barramento: Um barramento de 64 bits transfere quantos bytes por ciclo, idealmente?', sort_order=1 where id='70000000-0000-4000-8000-000009300971';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Oito bits formam um byte.', sort_order=2 where id='70000000-0000-4000-8000-000009300972';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Converta largura em bits para bytes. No enunciado, Um barramento de 64 bits transfere quantos bytes por ciclo, idealmente? $64/8=8$ bytes por transferência.', sort_order=3 where id='70000000-0000-4000-8000-000009300973';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“4 bytes.” não cumpre o critério técnico do caso: $64/8=8$ bytes por transferência. “16 bytes.” não decorre do princípio aplicável: Oito bits formam um byte. “64 bytes.” deixa de executar a análise necessária: Converta largura em bits para bytes.', sort_order=4 where id='70000000-0000-4000-8000-000009300974';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “8 bytes.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300975';

update public.question_solutions set final_answer_markdown='$3,2$ GB/s.', explanation_markdown='Largura de banda é bytes por transferência vezes transferências por segundo. No caso apresentado, Calcule $16	imes200,000,000$. O resultado é $3,2$ bilhões de bytes por segundo. Logo, “$3,2$ GB/s.” é a conclusão correta. “$200$ MB/s.” não cumpre o critério técnico do caso: O resultado é $3,2$ bilhões de bytes por segundo. “$16$ GB/s.” não decorre do princípio aplicável: Largura de banda é bytes por transferência vezes transferências por segundo. “$1,6$ GB/s.” deixa de executar a análise necessária: Calcule $16	imes200,000,000$.' where question_id='40000000-0000-4000-8000-000000930098';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de largura de banda: Um barramento transfere 16 bytes por ciclo a 200 MHz. Qual pico teórico?', sort_order=1 where id='70000000-0000-4000-8000-000009300981';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Largura de banda é bytes por transferência vezes transferências por segundo.', sort_order=2 where id='70000000-0000-4000-8000-000009300982';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Calcule $16	imes200,000,000$. No enunciado, Um barramento transfere 16 bytes por ciclo a 200 MHz. Qual pico teórico? O resultado é $3,2$ bilhões de bytes por segundo.', sort_order=3 where id='70000000-0000-4000-8000-000009300983';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$200$ MB/s.” não cumpre o critério técnico do caso: O resultado é $3,2$ bilhões de bytes por segundo. “$16$ GB/s.” não decorre do princípio aplicável: Largura de banda é bytes por transferência vezes transferências por segundo. “$1,6$ GB/s.” deixa de executar a análise necessária: Calcule $16	imes200,000,000$.', sort_order=4 where id='70000000-0000-4000-8000-000009300984';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$3,2$ GB/s.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300985';

update public.question_solutions set final_answer_markdown='Reduz o risco de starvation de solicitantes menos prioritários.', explanation_markdown='Round-robin alterna concessões entre solicitantes. No caso apresentado, Compare quem pode ficar esperando indefinidamente. Justiça não garante que cada requisição tenha mesma latência. Logo, “Reduz o risco de starvation de solicitantes menos prioritários.” é a conclusão correta. “Sempre minimiza latência.” não cumpre o critério técnico do caso: Justiça não garante que cada requisição tenha mesma latência. “Elimina colisões elétricas.” não decorre do princípio aplicável: Round-robin alterna concessões entre solicitantes. “Dispensa protocolo.” deixa de executar a análise necessária: Compare quem pode ficar esperando indefinidamente.' where question_id='40000000-0000-4000-8000-000000930099';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de arbitragem: Por que arbitragem round-robin pode ser preferida a prioridade fixa?', sort_order=1 where id='70000000-0000-4000-8000-000009300991';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Round-robin alterna concessões entre solicitantes.', sort_order=2 where id='70000000-0000-4000-8000-000009300992';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare quem pode ficar esperando indefinidamente. No enunciado, Por que arbitragem round-robin pode ser preferida a prioridade fixa? Justiça não garante que cada requisição tenha mesma latência.', sort_order=3 where id='70000000-0000-4000-8000-000009300993';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Sempre minimiza latência.” não cumpre o critério técnico do caso: Justiça não garante que cada requisição tenha mesma latência. “Elimina colisões elétricas.” não decorre do princípio aplicável: Round-robin alterna concessões entre solicitantes. “Dispensa protocolo.” deixa de executar a análise necessária: Compare quem pode ficar esperando indefinidamente.', sort_order=4 where id='70000000-0000-4000-8000-000009300994';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Reduz o risco de starvation de solicitantes menos prioritários.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300995';

update public.question_solutions set final_answer_markdown='Usando instruções normais de carga e armazenamento em endereços reservados.', explanation_markdown='O espaço de endereços inclui regiões atribuídas a dispositivos. No caso apresentado, Pergunte se o periférico responde como um intervalo de memória. LOAD e STORE podem acionar a interface correta via decodificação. Logo, “Usando instruções normais de carga e armazenamento em endereços reservados.” é a conclusão correta. “Com páginas sem endereço.” não cumpre o critério técnico do caso: LOAD e STORE podem acionar a interface correta via decodificação. “Somente com DMA.” não decorre do princípio aplicável: O espaço de endereços inclui regiões atribuídas a dispositivos. “Pelo PC.” deixa de executar a análise necessária: Pergunte se o periférico responde como um intervalo de memória.' where question_id='40000000-0000-4000-8000-000000930100';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de E/S mapeada: Em E/S mapeada em memória, como a CPU acessa registradores de dispositivo?', sort_order=1 where id='70000000-0000-4000-8000-000009301001';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='O espaço de endereços inclui regiões atribuídas a dispositivos.', sort_order=2 where id='70000000-0000-4000-8000-000009301002';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Pergunte se o periférico responde como um intervalo de memória. No enunciado, Em E/S mapeada em memória, como a CPU acessa registradores de dispositivo? LOAD e STORE podem acionar a interface correta via decodificação.', sort_order=3 where id='70000000-0000-4000-8000-000009301003';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Com páginas sem endereço.” não cumpre o critério técnico do caso: LOAD e STORE podem acionar a interface correta via decodificação. “Somente com DMA.” não decorre do princípio aplicável: O espaço de endereços inclui regiões atribuídas a dispositivos. “Pelo PC.” deixa de executar a análise necessária: Pergunte se o periférico responde como um intervalo de memória.', sort_order=4 where id='70000000-0000-4000-8000-000009301004';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Usando instruções normais de carga e armazenamento em endereços reservados.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301005';

commit;
