-- Arquitetura de Computadores: revisão de gabaritos, lote 01.
-- Atualiza apenas soluções e passos; tentativas e alternativas são preservadas.
begin;

update public.question_solutions set final_answer_markdown='Trocar a microarquitetura mantendo a mesma ISA.', explanation_markdown='A ISA é a interface visível ao software de baixo nível; a microarquitetura é uma implementação dessa interface. No caso apresentado, Compare o que o compilador assume — a ISA — com a forma interna de executá-la. Se as instruções preservam significado e efeitos, o binário continua válido. Logo, “Trocar a microarquitetura mantendo a mesma ISA.” é a conclusão correta. “Trocar a semântica das instruções da ISA.” não cumpre o critério técnico do caso: Se as instruções preservam significado e efeitos, o binário continua válido. “Remover o compilador.” não decorre do princípio aplicável: A ISA é a interface visível ao software de baixo nível; a microarquitetura é uma implementação dessa interface. “Alterar o resultado definido do programa.” deixa de executar a análise necessária: Compare o que o compilador assume — a ISA — com a forma interna de executá-la.' where question_id='40000000-0000-4000-8000-000000930001';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de níveis de abstração: Um compilador transforma um programa em C em código de máquina para uma ISA específica. Qual mudança pode ocorrer sem exigir que o código-fonte em C seja reescrito?', sort_order=1 where id='70000000-0000-4000-8000-000009300011';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='A ISA é a interface visível ao software de baixo nível; a microarquitetura é uma implementação dessa interface.', sort_order=2 where id='70000000-0000-4000-8000-000009300012';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare o que o compilador assume — a ISA — com a forma interna de executá-la. No enunciado, Um compilador transforma um programa em C em código de máquina para uma ISA específica. Qual mudança pode ocorrer sem exigir que o código-fonte em C seja reescrito? Se as instruções preservam significado e efeitos, o binário continua válido.', sort_order=3 where id='70000000-0000-4000-8000-000009300013';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Trocar a semântica das instruções da ISA.” não cumpre o critério técnico do caso: Se as instruções preservam significado e efeitos, o binário continua válido. “Remover o compilador.” não decorre do princípio aplicável: A ISA é a interface visível ao software de baixo nível; a microarquitetura é uma implementação dessa interface. “Alterar o resultado definido do programa.” deixa de executar a análise necessária: Compare o que o compilador assume — a ISA — com a forma interna de executá-la.', sort_order=4 where id='70000000-0000-4000-8000-000009300014';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Trocar a microarquitetura mantendo a mesma ISA.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300015';

update public.question_solutions set final_answer_markdown='A microarquitetura.', explanation_markdown='Componentes e caminhos internos pertencem à implementação, desde que a interface arquitetural seja preservada. No caso apresentado, Pergunte se um programador que usa a ISA percebe uma instrução diferente. Os mesmos registradores, opcodes e resultados indicam compatibilidade arquitetural. Logo, “A microarquitetura.” é a conclusão correta. “A linguagem de alto nível.” não cumpre o critério técnico do caso: Os mesmos registradores, opcodes e resultados indicam compatibilidade arquitetural. “A ISA publicada ao programador.” não decorre do princípio aplicável: Componentes e caminhos internos pertencem à implementação, desde que a interface arquitetural seja preservada. “O formato do arquivo-fonte.” deixa de executar a análise necessária: Pergunte se um programador que usa a ISA percebe uma instrução diferente.' where question_id='40000000-0000-4000-8000-000000930002';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de níveis de abstração: Uma equipe substitui uma ULA de 32 bits por outra mais rápida, sem alterar registradores, opcodes nem resultados das instruções. Que camada foi modificada?', sort_order=1 where id='70000000-0000-4000-8000-000009300021';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Componentes e caminhos internos pertencem à implementação, desde que a interface arquitetural seja preservada.', sort_order=2 where id='70000000-0000-4000-8000-000009300022';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Pergunte se um programador que usa a ISA percebe uma instrução diferente. No enunciado, Uma equipe substitui uma ULA de 32 bits por outra mais rápida, sem alterar registradores, opcodes nem resultados das instruções. Que camada foi modificada? Os mesmos registradores, opcodes e resultados indicam compatibilidade arquitetural.', sort_order=3 where id='70000000-0000-4000-8000-000009300023';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A linguagem de alto nível.” não cumpre o critério técnico do caso: Os mesmos registradores, opcodes e resultados indicam compatibilidade arquitetural. “A ISA publicada ao programador.” não decorre do princípio aplicável: Componentes e caminhos internos pertencem à implementação, desde que a interface arquitetural seja preservada. “O formato do arquivo-fonte.” deixa de executar a análise necessária: Pergunte se um programador que usa a ISA percebe uma instrução diferente.', sort_order=4 where id='70000000-0000-4000-8000-000009300024';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “A microarquitetura.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300025';

update public.question_solutions set final_answer_markdown='A implementação mudou, mas a ISA pode permanecer compatível.', explanation_markdown='Uma mesma instrução arquitetural pode ser realizada por diferentes sequências internas. No caso apresentado, Diferencie o contrato da instrução de sua realização física ou microprogramada. O resultado e os efeitos observáveis de MUL são o teste de compatibilidade. Logo, “A implementação mudou, mas a ISA pode permanecer compatível.” é a conclusão correta. “A instrução deixou de existir na ISA.” não cumpre o critério técnico do caso: O resultado e os efeitos observáveis de MUL são o teste de compatibilidade. “Todo programa precisa ser recompilado.” não decorre do princípio aplicável: Uma mesma instrução arquitetural pode ser realizada por diferentes sequências internas. “A CPU passou a ter outra linguagem de montagem.” deixa de executar a análise necessária: Diferencie o contrato da instrução de sua realização física ou microprogramada.' where question_id='40000000-0000-4000-8000-000000930003';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de níveis de abstração: Um processador passa a executar uma multiplicação por meio de várias microoperações internas em vez de uma unidade dedicada, mas a instrução MUL mantém seus operandos e resultado. Qual afirmação é correta?', sort_order=1 where id='70000000-0000-4000-8000-000009300031';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Uma mesma instrução arquitetural pode ser realizada por diferentes sequências internas.', sort_order=2 where id='70000000-0000-4000-8000-000009300032';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Diferencie o contrato da instrução de sua realização física ou microprogramada. No enunciado, Um processador passa a executar uma multiplicação por meio de várias microoperações internas em vez de uma unidade dedicada, mas a instrução MUL mantém seus operandos e resultado. Qual afirmação é correta? O resultado e os efeitos observáveis de MUL são o teste de compatibilidade.', sort_order=3 where id='70000000-0000-4000-8000-000009300033';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A instrução deixou de existir na ISA.” não cumpre o critério técnico do caso: O resultado e os efeitos observáveis de MUL são o teste de compatibilidade. “Todo programa precisa ser recompilado.” não decorre do princípio aplicável: Uma mesma instrução arquitetural pode ser realizada por diferentes sequências internas. “A CPU passou a ter outra linguagem de montagem.” deixa de executar a análise necessária: Diferencie o contrato da instrução de sua realização física ou microprogramada.', sort_order=4 where id='70000000-0000-4000-8000-000009300034';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “A implementação mudou, mas a ISA pode permanecer compatível.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300035';

update public.question_solutions set final_answer_markdown='Porque ambos podem realizar a mesma transformação lógica, com custos e velocidades diferentes.', explanation_markdown='A escolha hardware/software é um trade-off de desempenho, custo, consumo e flexibilidade, não uma diferença de capacidade lógica. No caso apresentado, Avalie a transformação desejada e os custos de cada implementação. Uma solução em hardware pode acelerar uma função sem tornar a alternativa em software impossível. Logo, “Porque ambos podem realizar a mesma transformação lógica, com custos e velocidades diferentes.” é a conclusão correta. “Porque software não usa processador.” não cumpre o critério técnico do caso: Uma solução em hardware pode acelerar uma função sem tornar a alternativa em software impossível. “Porque hardware nunca precisa de energia.” não decorre do princípio aplicável: A escolha hardware/software é um trade-off de desempenho, custo, consumo e flexibilidade, não uma diferença de capacidade lógica. “Porque compiladores eliminam a necessidade de instruções.” deixa de executar a análise necessária: Avalie a transformação desejada e os custos de cada implementação.' where question_id='40000000-0000-4000-8000-000000930004';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de hardware e software: Por que uma função como compressão pode ser implementada em hardware ou em software?', sort_order=1 where id='70000000-0000-4000-8000-000009300041';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='A escolha hardware/software é um trade-off de desempenho, custo, consumo e flexibilidade, não uma diferença de capacidade lógica.', sort_order=2 where id='70000000-0000-4000-8000-000009300042';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Avalie a transformação desejada e os custos de cada implementação. No enunciado, Por que uma função como compressão pode ser implementada em hardware ou em software? Uma solução em hardware pode acelerar uma função sem tornar a alternativa em software impossível.', sort_order=3 where id='70000000-0000-4000-8000-000009300043';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Porque software não usa processador.” não cumpre o critério técnico do caso: Uma solução em hardware pode acelerar uma função sem tornar a alternativa em software impossível. “Porque hardware nunca precisa de energia.” não decorre do princípio aplicável: A escolha hardware/software é um trade-off de desempenho, custo, consumo e flexibilidade, não uma diferença de capacidade lógica. “Porque compiladores eliminam a necessidade de instruções.” deixa de executar a análise necessária: Avalie a transformação desejada e os custos de cada implementação.', sort_order=4 where id='70000000-0000-4000-8000-000009300044';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Porque ambos podem realizar a mesma transformação lógica, com custos e velocidades diferentes.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300045';

update public.question_solutions set final_answer_markdown='Uma máquina virtual em um nível de abstração superior.', explanation_markdown='Uma máquina virtual define objetos e operações próprios, mesmo quando precisa ser interpretada por outro nível. No caso apresentado, Identifique qual conjunto de operações é apresentado ao programador daquele ambiente. O fato de bytecodes serem interpretados não os transforma em sinais elétricos da CPU. Logo, “Uma máquina virtual em um nível de abstração superior.” é a conclusão correta. “O circuito lógico da CPU.” não cumpre o critério técnico do caso: O fato de bytecodes serem interpretados não os transforma em sinais elétricos da CPU. “A frequência do clock físico.” não decorre do princípio aplicável: Uma máquina virtual define objetos e operações próprios, mesmo quando precisa ser interpretada por outro nível. “A disposição dos transistores.” deixa de executar a análise necessária: Identifique qual conjunto de operações é apresentado ao programador daquele ambiente.' where question_id='40000000-0000-4000-8000-000000930005';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de máquinas virtuais: Um interpretador executa bytecodes e oferece instruções que não existem diretamente no processador físico. O conjunto de bytecodes descreve principalmente:', sort_order=1 where id='70000000-0000-4000-8000-000009300051';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Uma máquina virtual define objetos e operações próprios, mesmo quando precisa ser interpretada por outro nível.', sort_order=2 where id='70000000-0000-4000-8000-000009300052';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique qual conjunto de operações é apresentado ao programador daquele ambiente. No enunciado, Um interpretador executa bytecodes e oferece instruções que não existem diretamente no processador físico. O conjunto de bytecodes descreve principalmente: O fato de bytecodes serem interpretados não os transforma em sinais elétricos da CPU.', sort_order=3 where id='70000000-0000-4000-8000-000009300053';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“O circuito lógico da CPU.” não cumpre o critério técnico do caso: O fato de bytecodes serem interpretados não os transforma em sinais elétricos da CPU. “A frequência do clock físico.” não decorre do princípio aplicável: Uma máquina virtual define objetos e operações próprios, mesmo quando precisa ser interpretada por outro nível. “A disposição dos transistores.” deixa de executar a análise necessária: Identifique qual conjunto de operações é apresentado ao programador daquele ambiente.', sort_order=4 where id='70000000-0000-4000-8000-000009300054';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Uma máquina virtual em um nível de abstração superior.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300055';

update public.question_solutions set final_answer_markdown='B, pois seu tempo proporcional é menor.', explanation_markdown='Tempo de CPU é proporcional a instruções × CPI ÷ frequência. No caso apresentado, Compare $1,5/3$ com $0,8/2$, usando a mesma unidade de GHz. B resulta em $0,4$ contra $0,5$ unidades proporcionais de tempo. Logo, “B, pois seu tempo proporcional é menor.” é a conclusão correta. “A, pois 3 é maior que 2.” não cumpre o critério técnico do caso: B resulta em $0,4$ contra $0,5$ unidades proporcionais de tempo. “Empatam por executar o mesmo programa.” não decorre do princípio aplicável: Tempo de CPU é proporcional a instruções × CPI ÷ frequência. “Não é possível comparar CPI e clock.” deixa de executar a análise necessária: Compare $1,5/3$ com $0,8/2$, usando a mesma unidade de GHz.' where question_id='40000000-0000-4000-8000-000000930006';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de desempenho: Dois processadores executam o mesmo programa. A usa clock de 3 GHz e CPI médio 1,5; B usa 2 GHz e CPI médio 0,8, com o mesmo número de instruções. Qual é mais rápido?', sort_order=1 where id='70000000-0000-4000-8000-000009300061';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Tempo de CPU é proporcional a instruções × CPI ÷ frequência.', sort_order=2 where id='70000000-0000-4000-8000-000009300062';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare $1,5/3$ com $0,8/2$, usando a mesma unidade de GHz. No enunciado, Dois processadores executam o mesmo programa. A usa clock de 3 GHz e CPI médio 1,5; B usa 2 GHz e CPI médio 0,8, com o mesmo número de instruções. Qual é mais rápido? B resulta em $0,4$ contra $0,5$ unidades proporcionais de tempo.', sort_order=3 where id='70000000-0000-4000-8000-000009300063';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A, pois 3 é maior que 2.” não cumpre o critério técnico do caso: B resulta em $0,4$ contra $0,5$ unidades proporcionais de tempo. “Empatam por executar o mesmo programa.” não decorre do princípio aplicável: Tempo de CPU é proporcional a instruções × CPI ÷ frequência. “Não é possível comparar CPI e clock.” deixa de executar a análise necessária: Compare $1,5/3$ com $0,8/2$, usando a mesma unidade de GHz.', sort_order=4 where id='70000000-0000-4000-8000-000009300064';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “B, pois seu tempo proporcional é menor.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300065';

update public.question_solutions set final_answer_markdown='O tempo aumenta 4%.', explanation_markdown='Com clock constante, compare o produto entre número de instruções e CPI antes e depois. No caso apresentado, Calcule $0,80	imes1,30$ para o novo trabalho relativo. O produto é $1,04$, maior que o valor inicial $1,00$. Logo, “O tempo aumenta 4%.” é a conclusão correta. “O tempo reduz 20%.” não cumpre o critério técnico do caso: O produto é $1,04$, maior que o valor inicial $1,00$. “O tempo não muda.” não decorre do princípio aplicável: Com clock constante, compare o produto entre número de instruções e CPI antes e depois. “O tempo reduz 4%.” deixa de executar a análise necessária: Calcule $0,80	imes1,30$ para o novo trabalho relativo.' where question_id='40000000-0000-4000-8000-000000930007';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de desempenho: Uma otimização reduz em 20% a contagem de instruções, mas eleva o CPI de 1,0 para 1,3; o clock não muda. Qual efeito ocorre?', sort_order=1 where id='70000000-0000-4000-8000-000009300071';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Com clock constante, compare o produto entre número de instruções e CPI antes e depois.', sort_order=2 where id='70000000-0000-4000-8000-000009300072';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Calcule $0,80	imes1,30$ para o novo trabalho relativo. No enunciado, Uma otimização reduz em 20% a contagem de instruções, mas eleva o CPI de 1,0 para 1,3; o clock não muda. Qual efeito ocorre? O produto é $1,04$, maior que o valor inicial $1,00$.', sort_order=3 where id='70000000-0000-4000-8000-000009300073';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“O tempo reduz 20%.” não cumpre o critério técnico do caso: O produto é $1,04$, maior que o valor inicial $1,00$. “O tempo não muda.” não decorre do princípio aplicável: Com clock constante, compare o produto entre número de instruções e CPI antes e depois. “O tempo reduz 4%.” deixa de executar a análise necessária: Calcule $0,80	imes1,30$ para o novo trabalho relativo.', sort_order=4 where id='70000000-0000-4000-8000-000009300074';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “O tempo aumenta 4%.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300075';

update public.question_solutions set final_answer_markdown='A ULA.', explanation_markdown='A ULA realiza cálculos; PC, IR e barramentos exercem papéis de controle, armazenamento ou comunicação. No caso apresentado, Associe a operação solicitada ao bloco que soma, compara e aplica lógica booleana. A descrição não pede guardar endereço nem buscar instrução. Logo, “A ULA.” é a conclusão correta. “O contador de programa.” não cumpre o critério técnico do caso: A descrição não pede guardar endereço nem buscar instrução. “O registrador de instrução.” não decorre do princípio aplicável: A ULA realiza cálculos; PC, IR e barramentos exercem papéis de controle, armazenamento ou comunicação. “O barramento de endereços.” deixa de executar a análise necessária: Associe a operação solicitada ao bloco que soma, compara e aplica lógica booleana.' where question_id='40000000-0000-4000-8000-000000930008';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de CPU: Qual componente executa operações aritméticas e lógicas sobre operandos que já estão disponíveis no caminho de dados?', sort_order=1 where id='70000000-0000-4000-8000-000009300081';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='A ULA realiza cálculos; PC, IR e barramentos exercem papéis de controle, armazenamento ou comunicação.', sort_order=2 where id='70000000-0000-4000-8000-000009300082';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Associe a operação solicitada ao bloco que soma, compara e aplica lógica booleana. No enunciado, Qual componente executa operações aritméticas e lógicas sobre operandos que já estão disponíveis no caminho de dados? A descrição não pede guardar endereço nem buscar instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009300083';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“O contador de programa.” não cumpre o critério técnico do caso: A descrição não pede guardar endereço nem buscar instrução. “O registrador de instrução.” não decorre do princípio aplicável: A ULA realiza cálculos; PC, IR e barramentos exercem papéis de controle, armazenamento ou comunicação. “O barramento de endereços.” deixa de executar a análise necessária: Associe a operação solicitada ao bloco que soma, compara e aplica lógica booleana.', sort_order=4 where id='70000000-0000-4000-8000-000009300084';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “A ULA.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300085';

update public.question_solutions set final_answer_markdown='Carregar o endereço-alvo no PC.', explanation_markdown='O PC determina o endereço da próxima instrução a buscar. No caso apresentado, Siga a consequência do desvio: a próxima instrução não é a sequencial. Sem atualizar o PC, a busca continuaria no caminho incorreto. Logo, “Carregar o endereço-alvo no PC.” é a conclusão correta. “Copiar o opcode para a ULA.” não cumpre o critério técnico do caso: Sem atualizar o PC, a busca continuaria no caminho incorreto. “Zerar todos os registradores.” não decorre do princípio aplicável: O PC determina o endereço da próxima instrução a buscar. “Escrever o alvo na cache.” deixa de executar a análise necessária: Siga a consequência do desvio: a próxima instrução não é a sequencial.' where question_id='40000000-0000-4000-8000-000000930009';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de ciclo de instrução: Após buscar uma instrução, a CPU descobre que ela é um salto condicional tomado. Qual atualização é essencial antes da próxima busca?', sort_order=1 where id='70000000-0000-4000-8000-000009300091';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='O PC determina o endereço da próxima instrução a buscar.', sort_order=2 where id='70000000-0000-4000-8000-000009300092';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Siga a consequência do desvio: a próxima instrução não é a sequencial. No enunciado, Após buscar uma instrução, a CPU descobre que ela é um salto condicional tomado. Qual atualização é essencial antes da próxima busca? Sem atualizar o PC, a busca continuaria no caminho incorreto.', sort_order=3 where id='70000000-0000-4000-8000-000009300093';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Copiar o opcode para a ULA.” não cumpre o critério técnico do caso: Sem atualizar o PC, a busca continuaria no caminho incorreto. “Zerar todos os registradores.” não decorre do princípio aplicável: O PC determina o endereço da próxima instrução a buscar. “Escrever o alvo na cache.” deixa de executar a análise necessária: Siga a consequência do desvio: a próxima instrução não é a sequencial.', sort_order=4 where id='70000000-0000-4000-8000-000009300094';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Carregar o endereço-alvo no PC.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300095';

update public.question_solutions set final_answer_markdown='Usar R2 como endereço, ler memória e escrever o dado em R1.', explanation_markdown='Uma carga transfere para um registrador o conteúdo da posição apontada pelo operando de endereço. No caso apresentado, Separe registrador-base, endereço efetivo, leitura de memória e destino. O valor armazenado em R2 é endereço; o dado lido torna-se o novo valor de R1. Logo, “Usar R2 como endereço, ler memória e escrever o dado em R1.” é a conclusão correta. “Usar R1 como endereço e sobrescrever R2.” não cumpre o critério técnico do caso: O valor armazenado em R2 é endereço; o dado lido torna-se o novo valor de R1. “Somar R1 e R2 sem acessar memória.” não decorre do princípio aplicável: Uma carga transfere para um registrador o conteúdo da posição apontada pelo operando de endereço. “Ler R1 e gravar o resultado no PC.” deixa de executar a análise necessária: Separe registrador-base, endereço efetivo, leitura de memória e destino.' where question_id='40000000-0000-4000-8000-000000930010';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de ciclo de instrução: Durante a execução de LOAD R1,[R2], qual sequência representa corretamente o uso lógico dos componentes?', sort_order=1 where id='70000000-0000-4000-8000-000009300101';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Uma carga transfere para um registrador o conteúdo da posição apontada pelo operando de endereço.', sort_order=2 where id='70000000-0000-4000-8000-000009300102';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Separe registrador-base, endereço efetivo, leitura de memória e destino. No enunciado, Durante a execução de LOAD R1,[R2], qual sequência representa corretamente o uso lógico dos componentes? O valor armazenado em R2 é endereço; o dado lido torna-se o novo valor de R1.', sort_order=3 where id='70000000-0000-4000-8000-000009300103';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Usar R1 como endereço e sobrescrever R2.” não cumpre o critério técnico do caso: O valor armazenado em R2 é endereço; o dado lido torna-se o novo valor de R1. “Somar R1 e R2 sem acessar memória.” não decorre do princípio aplicável: Uma carga transfere para um registrador o conteúdo da posição apontada pelo operando de endereço. “Ler R1 e gravar o resultado no PC.” deixa de executar a análise necessária: Separe registrador-base, endereço efetivo, leitura de memória e destino.', sort_order=4 where id='70000000-0000-4000-8000-000009300104';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Usar R2 como endereço, ler memória e escrever o dado em R1.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300105';

update public.question_solutions set final_answer_markdown='Instruções simples e formatos regulares.', explanation_markdown='RISC favorece regularidade e operações simples, o que ajuda decodificação e pipeline. No caso apresentado, Procure a alternativa que descreve o conjunto de instruções, não a memória física. Registradores continuam centrais em arquiteturas RISC. Logo, “Instruções simples e formatos regulares.” é a conclusão correta. “Toda instrução acessa memória duas vezes.” não cumpre o critério técnico do caso: Registradores continuam centrais em arquiteturas RISC. “Ausência de registradores.” não decorre do princípio aplicável: RISC favorece regularidade e operações simples, o que ajuda decodificação e pipeline. “Instruções de tamanho sempre ilimitado.” deixa de executar a análise necessária: Procure a alternativa que descreve o conjunto de instruções, não a memória física.' where question_id='40000000-0000-4000-8000-000000930011';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de RISC e CISC: Qual característica é mais associada a uma ISA RISC clássica?', sort_order=1 where id='70000000-0000-4000-8000-000009300111';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='RISC favorece regularidade e operações simples, o que ajuda decodificação e pipeline.', sort_order=2 where id='70000000-0000-4000-8000-000009300112';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Procure a alternativa que descreve o conjunto de instruções, não a memória física. No enunciado, Qual característica é mais associada a uma ISA RISC clássica? Registradores continuam centrais em arquiteturas RISC.', sort_order=3 where id='70000000-0000-4000-8000-000009300113';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Toda instrução acessa memória duas vezes.” não cumpre o critério técnico do caso: Registradores continuam centrais em arquiteturas RISC. “Ausência de registradores.” não decorre do princípio aplicável: RISC favorece regularidade e operações simples, o que ajuda decodificação e pipeline. “Instruções de tamanho sempre ilimitado.” deixa de executar a análise necessária: Procure a alternativa que descreve o conjunto de instruções, não a memória física.', sort_order=4 where id='70000000-0000-4000-8000-000009300114';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Instruções simples e formatos regulares.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300115';

update public.question_solutions set final_answer_markdown='Paralelismo no nível do processador.', explanation_markdown='Múltiplos núcleos permitem executar fluxos independentes simultaneamente. No caso apresentado, Verifique se o paralelismo vem de várias tarefas ou da sobreposição de etapas de uma só CPU. As tarefas distintas podem ser distribuídas entre núcleos sem criar dependências entre si. Logo, “Paralelismo no nível do processador.” é a conclusão correta. “Pipeline dentro de uma única instrução.” não cumpre o critério técnico do caso: As tarefas distintas podem ser distribuídas entre núcleos sem criar dependências entre si. “Compressão de instruções.” não decorre do princípio aplicável: Múltiplos núcleos permitem executar fluxos independentes simultaneamente. “Troca de endereçamento direto por imediato.” deixa de executar a análise necessária: Verifique se o paralelismo vem de várias tarefas ou da sobreposição de etapas de uma só CPU.' where question_id='40000000-0000-4000-8000-000000930012';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de paralelismo: Quatro núcleos executam quatro tarefas independentes, cada uma com duração semelhante. Qual ganho é mais diretamente explorado?', sort_order=1 where id='70000000-0000-4000-8000-000009300121';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Múltiplos núcleos permitem executar fluxos independentes simultaneamente.', sort_order=2 where id='70000000-0000-4000-8000-000009300122';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Verifique se o paralelismo vem de várias tarefas ou da sobreposição de etapas de uma só CPU. No enunciado, Quatro núcleos executam quatro tarefas independentes, cada uma com duração semelhante. Qual ganho é mais diretamente explorado? As tarefas distintas podem ser distribuídas entre núcleos sem criar dependências entre si.', sort_order=3 where id='70000000-0000-4000-8000-000009300123';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Pipeline dentro de uma única instrução.” não cumpre o critério técnico do caso: As tarefas distintas podem ser distribuídas entre núcleos sem criar dependências entre si. “Compressão de instruções.” não decorre do princípio aplicável: Múltiplos núcleos permitem executar fluxos independentes simultaneamente. “Troca de endereçamento direto por imediato.” deixa de executar a análise necessária: Verifique se o paralelismo vem de várias tarefas ou da sobreposição de etapas de uma só CPU.', sort_order=4 where id='70000000-0000-4000-8000-000009300124';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Paralelismo no nível do processador.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300125';

update public.question_solutions set final_answer_markdown='$5$.', explanation_markdown='A parte serial limita o ganho global: speedup máximo é $1/f_{serial}$. No caso apresentado, Faça o número de processadores tender ao infinito na expressão de Amdahl. Com fração serial $0,20$, o limite é $1/0,20=5$. Logo, “$5$.” é a conclusão correta. “$1,25$.” não cumpre o critério técnico do caso: Com fração serial $0,20$, o limite é $1/0,20=5$. “$4$.” não decorre do princípio aplicável: A parte serial limita o ganho global: speedup máximo é $1/f_{serial}$. “Infinito.” deixa de executar a análise necessária: Faça o número de processadores tender ao infinito na expressão de Amdahl.' where question_id='40000000-0000-4000-8000-000000930013';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de paralelismo: Um programa possui 80% de seu tempo perfeitamente paralelizável e 20% inevitavelmente serial. Pelo limite de Amdahl, qual é o ganho máximo com infinitos processadores?', sort_order=1 where id='70000000-0000-4000-8000-000009300131';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='A parte serial limita o ganho global: speedup máximo é $1/f_{serial}$.', sort_order=2 where id='70000000-0000-4000-8000-000009300132';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Faça o número de processadores tender ao infinito na expressão de Amdahl. No enunciado, Um programa possui 80% de seu tempo perfeitamente paralelizável e 20% inevitavelmente serial. Pelo limite de Amdahl, qual é o ganho máximo com infinitos processadores? Com fração serial $0,20$, o limite é $1/0,20=5$.', sort_order=3 where id='70000000-0000-4000-8000-000009300133';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$1,25$.” não cumpre o critério técnico do caso: Com fração serial $0,20$, o limite é $1/0,20=5$. “$4$.” não decorre do princípio aplicável: A parte serial limita o ganho global: speedup máximo é $1/f_{serial}$. “Infinito.” deixa de executar a análise necessária: Faça o número de processadores tender ao infinito na expressão de Amdahl.', sort_order=4 where id='70000000-0000-4000-8000-000009300134';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$5$.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300135';

update public.question_solutions set final_answer_markdown='Selecionar a posição cujo conteúdo será lido ou escrito.', explanation_markdown='Endereço identifica uma localização; dado é o conteúdo transferido dessa localização. No caso apresentado, Diferencie “onde” está a informação de “qual” é a informação. Um mesmo endereço pode conter valores diferentes ao longo do tempo. Logo, “Selecionar a posição cujo conteúdo será lido ou escrito.” é a conclusão correta. “Representar sempre o dado armazenado.” não cumpre o critério técnico do caso: Um mesmo endereço pode conter valores diferentes ao longo do tempo. “Determinar a frequência do clock.” não decorre do princípio aplicável: Endereço identifica uma localização; dado é o conteúdo transferido dessa localização. “Codificar uma operação da ULA.” deixa de executar a análise necessária: Diferencie “onde” está a informação de “qual” é a informação.' where question_id='40000000-0000-4000-8000-000000930014';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de endereços e dados: Qual é a função primária de um endereço de memória?', sort_order=1 where id='70000000-0000-4000-8000-000009300141';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Endereço identifica uma localização; dado é o conteúdo transferido dessa localização.', sort_order=2 where id='70000000-0000-4000-8000-000009300142';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Diferencie “onde” está a informação de “qual” é a informação. No enunciado, Qual é a função primária de um endereço de memória? Um mesmo endereço pode conter valores diferentes ao longo do tempo.', sort_order=3 where id='70000000-0000-4000-8000-000009300143';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Representar sempre o dado armazenado.” não cumpre o critério técnico do caso: Um mesmo endereço pode conter valores diferentes ao longo do tempo. “Determinar a frequência do clock.” não decorre do princípio aplicável: Endereço identifica uma localização; dado é o conteúdo transferido dessa localização. “Codificar uma operação da ULA.” deixa de executar a análise necessária: Diferencie “onde” está a informação de “qual” é a informação.', sort_order=4 where id='70000000-0000-4000-8000-000009300144';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Selecionar a posição cujo conteúdo será lido ou escrito.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300145';

update public.question_solutions set final_answer_markdown='$64$ KiB.', explanation_markdown='Com $n$ linhas de endereço existem $2^n$ posições; cada posição contém um byte. No caso apresentado, Calcule $2^{16}$ e converta bytes para KiB. $2^{16}=65536$ bytes, isto é, $64$ KiB. Logo, “$64$ KiB.” é a conclusão correta. “$16$ bytes.” não cumpre o critério técnico do caso: $2^{16}=65536$ bytes, isto é, $64$ KiB. “$32$ KiB.” não decorre do princípio aplicável: Com $n$ linhas de endereço existem $2^n$ posições; cada posição contém um byte. “$128$ KiB.” deixa de executar a análise necessária: Calcule $2^{16}$ e converta bytes para KiB.' where question_id='40000000-0000-4000-8000-000000930015';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de endereçamento: Uma memória é endereçável por byte e possui 16 linhas de endereço. Qual capacidade diretamente endereçável ela tem?', sort_order=1 where id='70000000-0000-4000-8000-000009300151';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Com $n$ linhas de endereço existem $2^n$ posições; cada posição contém um byte.', sort_order=2 where id='70000000-0000-4000-8000-000009300152';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Calcule $2^{16}$ e converta bytes para KiB. No enunciado, Uma memória é endereçável por byte e possui 16 linhas de endereço. Qual capacidade diretamente endereçável ela tem? $2^{16}=65536$ bytes, isto é, $64$ KiB.', sort_order=3 where id='70000000-0000-4000-8000-000009300153';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$16$ bytes.” não cumpre o critério técnico do caso: $2^{16}=65536$ bytes, isto é, $64$ KiB. “$32$ KiB.” não decorre do princípio aplicável: Com $n$ linhas de endereço existem $2^n$ posições; cada posição contém um byte. “$128$ KiB.” deixa de executar a análise necessária: Calcule $2^{16}$ e converta bytes para KiB.', sort_order=4 where id='70000000-0000-4000-8000-000009300154';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$64$ KiB.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300155';

update public.question_solutions set final_answer_markdown='$0x78$.', explanation_markdown='Little-endian coloca o byte menos significativo no menor endereço. No caso apresentado, Separe a palavra em $12$, $34$, $56$ e $78$ e ordene os endereços crescentes. O menor endereço recebe o byte menos significativo. Logo, “$0x78$.” é a conclusão correta. “$0x12$.” não cumpre o critério técnico do caso: O menor endereço recebe o byte menos significativo. “$0x34$.” não decorre do princípio aplicável: Little-endian coloca o byte menos significativo no menor endereço. “$0x56$.” deixa de executar a análise necessária: Separe a palavra em $12$, $34$, $56$ e $78$ e ordene os endereços crescentes.' where question_id='40000000-0000-4000-8000-000000930016';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de ordem de bytes: Uma palavra de 32 bits $0x12345678$ é armazenada no endereço 100 em máquina little-endian. Qual byte fica no endereço 100?', sort_order=1 where id='70000000-0000-4000-8000-000009300161';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Little-endian coloca o byte menos significativo no menor endereço.', sort_order=2 where id='70000000-0000-4000-8000-000009300162';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Separe a palavra em $12$, $34$, $56$ e $78$ e ordene os endereços crescentes. No enunciado, Uma palavra de 32 bits $0x12345678$ é armazenada no endereço 100 em máquina little-endian. Qual byte fica no endereço 100? O menor endereço recebe o byte menos significativo.', sort_order=3 where id='70000000-0000-4000-8000-000009300163';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$0x12$.” não cumpre o critério técnico do caso: O menor endereço recebe o byte menos significativo. “$0x34$.” não decorre do princípio aplicável: Little-endian coloca o byte menos significativo no menor endereço. “$0x56$.” deixa de executar a análise necessária: Separe a palavra em $12$, $34$, $56$ e $78$ e ordene os endereços crescentes.', sort_order=4 where id='70000000-0000-4000-8000-000009300164';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$0x78$.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300165';

update public.question_solutions set final_answer_markdown='Pode localizar e corrigir certos erros de um bit.', explanation_markdown='Paridade normalmente detecta uma classe de erros; códigos com bits redundantes podem identificar a posição de um erro simples. No caso apresentado, Compare detectar uma inconsistência com saber qual bit deve ser corrigido. Correção de um bit não implica correção universal de falhas múltiplas. Logo, “Pode localizar e corrigir certos erros de um bit.” é a conclusão correta. “Elimina a necessidade de memória.” não cumpre o critério técnico do caso: Correção de um bit não implica correção universal de falhas múltiplas. “Aumenta automaticamente o clock.” não decorre do princípio aplicável: Paridade normalmente detecta uma classe de erros; códigos com bits redundantes podem identificar a posição de um erro simples. “Impede qualquer erro de múltiplos bits.” deixa de executar a análise necessária: Compare detectar uma inconsistência com saber qual bit deve ser corrigido.' where question_id='40000000-0000-4000-8000-000000930017';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de correção de erro: Qual vantagem um código de correção de erro oferece além de um bit de paridade simples?', sort_order=1 where id='70000000-0000-4000-8000-000009300171';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Paridade normalmente detecta uma classe de erros; códigos com bits redundantes podem identificar a posição de um erro simples.', sort_order=2 where id='70000000-0000-4000-8000-000009300172';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare detectar uma inconsistência com saber qual bit deve ser corrigido. No enunciado, Qual vantagem um código de correção de erro oferece além de um bit de paridade simples? Correção de um bit não implica correção universal de falhas múltiplas.', sort_order=3 where id='70000000-0000-4000-8000-000009300173';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Elimina a necessidade de memória.” não cumpre o critério técnico do caso: Correção de um bit não implica correção universal de falhas múltiplas. “Aumenta automaticamente o clock.” não decorre do princípio aplicável: Paridade normalmente detecta uma classe de erros; códigos com bits redundantes podem identificar a posição de um erro simples. “Impede qualquer erro de múltiplos bits.” deixa de executar a análise necessária: Compare detectar uma inconsistência com saber qual bit deve ser corrigido.', sort_order=4 where id='70000000-0000-4000-8000-000009300174';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Pode localizar e corrigir certos erros de um bit.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300175';

update public.question_solutions set final_answer_markdown='Para aproveitar a localidade espacial de dados próximos.', explanation_markdown='Dados próximos no endereço tendem a ser acessados juntos; um bloco traz essa vizinhança. No caso apresentado, Pense no padrão de acesso sequencial a vetores ou instruções. Transferir uma linha ajuda acessos próximos, embora não garanta hit em todos eles. Logo, “Para aproveitar a localidade espacial de dados próximos.” é a conclusão correta. “Para eliminar a RAM.” não cumpre o critério técnico do caso: Transferir uma linha ajuda acessos próximos, embora não garanta hit em todos eles. “Para tornar endereços desnecessários.” não decorre do princípio aplicável: Dados próximos no endereço tendem a ser acessados juntos; um bloco traz essa vizinhança. “Para impedir leituras repetidas.” deixa de executar a análise necessária: Pense no padrão de acesso sequencial a vetores ou instruções.' where question_id='40000000-0000-4000-8000-000000930018';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de hierarquia de memória: Por que caches usam blocos, e não transferem sempre um único byte?', sort_order=1 where id='70000000-0000-4000-8000-000009300181';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Dados próximos no endereço tendem a ser acessados juntos; um bloco traz essa vizinhança.', sort_order=2 where id='70000000-0000-4000-8000-000009300182';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Pense no padrão de acesso sequencial a vetores ou instruções. No enunciado, Por que caches usam blocos, e não transferem sempre um único byte? Transferir uma linha ajuda acessos próximos, embora não garanta hit em todos eles.', sort_order=3 where id='70000000-0000-4000-8000-000009300183';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para eliminar a RAM.” não cumpre o critério técnico do caso: Transferir uma linha ajuda acessos próximos, embora não garanta hit em todos eles. “Para tornar endereços desnecessários.” não decorre do princípio aplicável: Dados próximos no endereço tendem a ser acessados juntos; um bloco traz essa vizinhança. “Para impedir leituras repetidas.” deixa de executar a análise necessária: Pense no padrão de acesso sequencial a vetores ou instruções.', sort_order=4 where id='70000000-0000-4000-8000-000009300184';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para aproveitar a localidade espacial de dados próximos.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300185';

update public.question_solutions set final_answer_markdown='4 ns.', explanation_markdown='AMAT = tempo de hit + taxa de miss × penalidade de miss. No caso apresentado, Use taxa de miss $0,05$ na parcela adicional. $2+0,05	imes40=4$ ns. Logo, “4 ns.” é a conclusão correta. “2 ns.” não cumpre o critério técnico do caso: $2+0,05	imes40=4$ ns. “40 ns.” não decorre do princípio aplicável: AMAT = tempo de hit + taxa de miss × penalidade de miss. “42 ns.” deixa de executar a análise necessária: Use taxa de miss $0,05$ na parcela adicional.' where question_id='40000000-0000-4000-8000-000000930019';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de cache: Uma cache tem taxa de hit de 95%, tempo de hit 2 ns e penalidade de miss 40 ns. Qual AMAT aproxima melhor o tempo médio?', sort_order=1 where id='70000000-0000-4000-8000-000009300191';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='AMAT = tempo de hit + taxa de miss × penalidade de miss.', sort_order=2 where id='70000000-0000-4000-8000-000009300192';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Use taxa de miss $0,05$ na parcela adicional. No enunciado, Uma cache tem taxa de hit de 95%, tempo de hit 2 ns e penalidade de miss 40 ns. Qual AMAT aproxima melhor o tempo médio? $2+0,05	imes40=4$ ns.', sort_order=3 where id='70000000-0000-4000-8000-000009300193';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“2 ns.” não cumpre o critério técnico do caso: $2+0,05	imes40=4$ ns. “40 ns.” não decorre do princípio aplicável: AMAT = tempo de hit + taxa de miss × penalidade de miss. “42 ns.” deixa de executar a análise necessária: Use taxa de miss $0,05$ na parcela adicional.', sort_order=4 where id='70000000-0000-4000-8000-000009300194';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “4 ns.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300195';

update public.question_solutions set final_answer_markdown='Percorrer colunas internas consecutivas dentro de cada linha.', explanation_markdown='Localidade espacial favorece endereços consecutivos, que costumam estar na mesma linha de cache. No caso apresentado, Relacione a ordem lógica do laço à disposição contígua dos elementos. Acessos adjacentes reutilizam o bloco recém-carregado. Logo, “Percorrer colunas internas consecutivas dentro de cada linha.” é a conclusão correta. “Saltar uma linha inteira a cada acesso.” não cumpre o critério técnico do caso: Acessos adjacentes reutilizam o bloco recém-carregado. “Acessar elementos em ordem aleatória.” não decorre do princípio aplicável: Localidade espacial favorece endereços consecutivos, que costumam estar na mesma linha de cache. “Alternar sempre entre extremos da matriz.” deixa de executar a análise necessária: Relacione a ordem lógica do laço à disposição contígua dos elementos.' where question_id='40000000-0000-4000-8000-000000930020';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de cache: Um laço percorre uma matriz por linhas em memória organizada por linhas. Qual ordem de acesso tende a produzir mais localidade espacial?', sort_order=1 where id='70000000-0000-4000-8000-000009300201';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Localidade espacial favorece endereços consecutivos, que costumam estar na mesma linha de cache.', sort_order=2 where id='70000000-0000-4000-8000-000009300202';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Relacione a ordem lógica do laço à disposição contígua dos elementos. No enunciado, Um laço percorre uma matriz por linhas em memória organizada por linhas. Qual ordem de acesso tende a produzir mais localidade espacial? Acessos adjacentes reutilizam o bloco recém-carregado.', sort_order=3 where id='70000000-0000-4000-8000-000009300203';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Saltar uma linha inteira a cada acesso.” não cumpre o critério técnico do caso: Acessos adjacentes reutilizam o bloco recém-carregado. “Acessar elementos em ordem aleatória.” não decorre do princípio aplicável: Localidade espacial favorece endereços consecutivos, que costumam estar na mesma linha de cache. “Alternar sempre entre extremos da matriz.” deixa de executar a análise necessária: Relacione a ordem lógica do laço à disposição contígua dos elementos.', sort_order=4 where id='70000000-0000-4000-8000-000009300204';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Percorrer colunas internas consecutivas dentro de cada linha.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300205';

update public.question_solutions set final_answer_markdown='A CPU consultar continuamente um dispositivo lento para saber se ele terminou.', explanation_markdown='Interrupção permite que o dispositivo notifique a CPU quando um evento ocorre. No caso apresentado, Compare espera ativa com aviso assíncrono de conclusão. A CPU pode executar outro trabalho até ser interrompida. Logo, “A CPU consultar continuamente um dispositivo lento para saber se ele terminou.” é a conclusão correta. “A CPU usar registradores.” não cumpre o critério técnico do caso: A CPU pode executar outro trabalho até ser interrompida. “A memória ter endereços.” não decorre do princípio aplicável: Interrupção permite que o dispositivo notifique a CPU quando um evento ocorre. “O dispositivo transferir dados.” deixa de executar a análise necessária: Compare espera ativa com aviso assíncrono de conclusão.' where question_id='40000000-0000-4000-8000-000000930021';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de interrupções: Qual problema uma interrupção de E/S ajuda a evitar?', sort_order=1 where id='70000000-0000-4000-8000-000009300211';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Interrupção permite que o dispositivo notifique a CPU quando um evento ocorre.', sort_order=2 where id='70000000-0000-4000-8000-000009300212';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare espera ativa com aviso assíncrono de conclusão. No enunciado, Qual problema uma interrupção de E/S ajuda a evitar? A CPU pode executar outro trabalho até ser interrompida.', sort_order=3 where id='70000000-0000-4000-8000-000009300213';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A CPU usar registradores.” não cumpre o critério técnico do caso: A CPU pode executar outro trabalho até ser interrompida. “A memória ter endereços.” não decorre do princípio aplicável: Interrupção permite que o dispositivo notifique a CPU quando um evento ocorre. “O dispositivo transferir dados.” deixa de executar a análise necessária: Compare espera ativa com aviso assíncrono de conclusão.', sort_order=4 where id='70000000-0000-4000-8000-000009300214';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “A CPU consultar continuamente um dispositivo lento para saber se ele terminou.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300215';

update public.question_solutions set final_answer_markdown='Mover o bloco entre dispositivo e memória com pouca intervenção da CPU.', explanation_markdown='DMA assume a transferência de dados e costuma sinalizar a conclusão por interrupção. No caso apresentado, Diferencie a preparação da operação pela CPU da movimentação repetitiva dos bytes. A CPU configura o DMA, mas não precisa copiar cada palavra individualmente. Logo, “Mover o bloco entre dispositivo e memória com pouca intervenção da CPU.” é a conclusão correta. “Executar cada instrução do processo.” não cumpre o critério técnico do caso: A CPU configura o DMA, mas não precisa copiar cada palavra individualmente. “Substituir a memória principal.” não decorre do princípio aplicável: DMA assume a transferência de dados e costuma sinalizar a conclusão por interrupção. “Decidir todos os desvios do programa.” deixa de executar a análise necessária: Diferencie a preparação da operação pela CPU da movimentação repetitiva dos bytes.' where question_id='40000000-0000-4000-8000-000000930022';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de DMA: Em uma transferência grande de disco para memória, qual é o papel típico de um controlador DMA?', sort_order=1 where id='70000000-0000-4000-8000-000009300221';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='DMA assume a transferência de dados e costuma sinalizar a conclusão por interrupção.', sort_order=2 where id='70000000-0000-4000-8000-000009300222';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Diferencie a preparação da operação pela CPU da movimentação repetitiva dos bytes. No enunciado, Em uma transferência grande de disco para memória, qual é o papel típico de um controlador DMA? A CPU configura o DMA, mas não precisa copiar cada palavra individualmente.', sort_order=3 where id='70000000-0000-4000-8000-000009300223';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Executar cada instrução do processo.” não cumpre o critério técnico do caso: A CPU configura o DMA, mas não precisa copiar cada palavra individualmente. “Substituir a memória principal.” não decorre do princípio aplicável: DMA assume a transferência de dados e costuma sinalizar a conclusão por interrupção. “Decidir todos os desvios do programa.” deixa de executar a análise necessária: Diferencie a preparação da operação pela CPU da movimentação repetitiva dos bytes.', sort_order=4 where id='70000000-0000-4000-8000-000009300224';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Mover o bloco entre dispositivo e memória com pouca intervenção da CPU.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300225';

update public.question_solutions set final_answer_markdown='Arbitragem de barramento.', explanation_markdown='Arbitragem resolve competição por um recurso compartilhado entre mestres de barramento. No caso apresentado, Identifique o conflito: dois solicitantes, um canal físico. A decisão de posse deve ocorrer antes da transferência de endereço e dados. Logo, “Arbitragem de barramento.” é a conclusão correta. “Decodificação de opcode.” não cumpre o critério técnico do caso: A decisão de posse deve ocorrer antes da transferência de endereço e dados. “Correção de erro.” não decorre do princípio aplicável: Arbitragem resolve competição por um recurso compartilhado entre mestres de barramento. “Previsão de desvio.” deixa de executar a análise necessária: Identifique o conflito: dois solicitantes, um canal físico.' where question_id='40000000-0000-4000-8000-000000930023';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de barramentos: Dois mestres solicitam o mesmo barramento compartilhado no mesmo ciclo. Que mecanismo decide quem pode iniciar a transferência?', sort_order=1 where id='70000000-0000-4000-8000-000009300231';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Arbitragem resolve competição por um recurso compartilhado entre mestres de barramento.', sort_order=2 where id='70000000-0000-4000-8000-000009300232';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o conflito: dois solicitantes, um canal físico. No enunciado, Dois mestres solicitam o mesmo barramento compartilhado no mesmo ciclo. Que mecanismo decide quem pode iniciar a transferência? A decisão de posse deve ocorrer antes da transferência de endereço e dados.', sort_order=3 where id='70000000-0000-4000-8000-000009300233';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Decodificação de opcode.” não cumpre o critério técnico do caso: A decisão de posse deve ocorrer antes da transferência de endereço e dados. “Correção de erro.” não decorre do princípio aplicável: Arbitragem resolve competição por um recurso compartilhado entre mestres de barramento. “Previsão de desvio.” deixa de executar a análise necessária: Identifique o conflito: dois solicitantes, um canal físico.', sort_order=4 where id='70000000-0000-4000-8000-000009300234';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Arbitragem de barramento.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300235';

update public.question_solutions set final_answer_markdown='Hazard de dados.', explanation_markdown='Dependência produtor-consumidor exige que o valor esteja disponível antes do uso. No caso apresentado, Observe se a causa é dado pendente, recurso disputado ou escolha de fluxo. I2 não pode usar o resultado correto enquanto I1 não o produzir ou encaminhar. Logo, “Hazard de dados.” é a conclusão correta. “Hazard estrutural causado por um salto.” não cumpre o critério técnico do caso: I2 não pode usar o resultado correto enquanto I1 não o produzir ou encaminhar. “Falha de página.” não decorre do princípio aplicável: Dependência produtor-consumidor exige que o valor esteja disponível antes do uso. “Erro de paridade.” deixa de executar a análise necessária: Observe se a causa é dado pendente, recurso disputado ou escolha de fluxo.' where question_id='40000000-0000-4000-8000-000000930024';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de pipeline: A instrução I2 precisa do resultado que I1 ainda produzirá. Que risco de pipeline existe?', sort_order=1 where id='70000000-0000-4000-8000-000009300241';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Dependência produtor-consumidor exige que o valor esteja disponível antes do uso.', sort_order=2 where id='70000000-0000-4000-8000-000009300242';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Observe se a causa é dado pendente, recurso disputado ou escolha de fluxo. No enunciado, A instrução I2 precisa do resultado que I1 ainda produzirá. Que risco de pipeline existe? I2 não pode usar o resultado correto enquanto I1 não o produzir ou encaminhar.', sort_order=3 where id='70000000-0000-4000-8000-000009300243';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Hazard estrutural causado por um salto.” não cumpre o critério técnico do caso: I2 não pode usar o resultado correto enquanto I1 não o produzir ou encaminhar. “Falha de página.” não decorre do princípio aplicável: Dependência produtor-consumidor exige que o valor esteja disponível antes do uso. “Erro de paridade.” deixa de executar a análise necessária: Observe se a causa é dado pendente, recurso disputado ou escolha de fluxo.', sort_order=4 where id='70000000-0000-4000-8000-000009300244';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Hazard de dados.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300245';

update public.question_solutions set final_answer_markdown='Elas pertencem ao fluxo errado e não podem alterar o estado arquitetural.', explanation_markdown='Execução especulativa só é segura se efeitos de um caminho incorreto forem descartados. No caso apresentado, Siga o fluxo real após avaliar a condição e compare com o caminho buscado. Permitir que o caminho errado grave registradores ou memória produziria resultado incorreto. Logo, “Elas pertencem ao fluxo errado e não podem alterar o estado arquitetural.” é a conclusão correta. “Elas sempre são inválidas.” não cumpre o critério técnico do caso: Permitir que o caminho errado grave registradores ou memória produziria resultado incorreto. “A cache não pode conter instruções.” não decorre do princípio aplicável: Execução especulativa só é segura se efeitos de um caminho incorreto forem descartados. “O PC não pode ser atualizado.” deixa de executar a análise necessária: Siga o fluxo real após avaliar a condição e compare com o caminho buscado.' where question_id='40000000-0000-4000-8000-000000930025';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de pipeline: Uma previsão de desvio é considerada tomada, mas a condição avaliada mostra que não deveria desviar. Por que instruções do caminho previsto precisam ser anuladas?', sort_order=1 where id='70000000-0000-4000-8000-000009300251';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Execução especulativa só é segura se efeitos de um caminho incorreto forem descartados.', sort_order=2 where id='70000000-0000-4000-8000-000009300252';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Siga o fluxo real após avaliar a condição e compare com o caminho buscado. No enunciado, Uma previsão de desvio é considerada tomada, mas a condição avaliada mostra que não deveria desviar. Por que instruções do caminho previsto precisam ser anuladas? Permitir que o caminho errado grave registradores ou memória produziria resultado incorreto.', sort_order=3 where id='70000000-0000-4000-8000-000009300253';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Elas sempre são inválidas.” não cumpre o critério técnico do caso: Permitir que o caminho errado grave registradores ou memória produziria resultado incorreto. “A cache não pode conter instruções.” não decorre do princípio aplicável: Execução especulativa só é segura se efeitos de um caminho incorreto forem descartados. “O PC não pode ser atualizado.” deixa de executar a análise necessária: Siga o fluxo real após avaliar a condição e compare com o caminho buscado.', sort_order=4 where id='70000000-0000-4000-8000-000009300254';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Elas pertencem ao fluxo errado e não podem alterar o estado arquitetural.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300255';

commit;
