-- Bloco 2: reescreve somente dicas e passos das questões MC 34 a 66.
-- Enunciados, alternativas, gabaritos, tags e explicações permanecem intactos.
begin;

create temporary table c1_block_02_steps (
  question_id uuid primary key, hints text[] not null, titles text[] not null, steps text[] not null
) on commit drop;

insert into c1_block_02_steps values
('00000042-0000-4000-8000-000000003400',array['Em um modelo exponencial, separe o valor inicial do fator que se repete.','O que está elevado a $t$ é o fator acumulado, e não a população inicial.','Substitua $t=5$ sem multiplicar o 800 pelo expoente.'],array['Separe as partes do modelo','Leia o fator anual','Conte os cinco anos','Escreva o fator acumulado','Distinga fator e população'],array['No modelo $P=800(1,04)^t$, o número $800$ é a população no instante inicial.','O crescimento de 4% corresponde ao fator anual $1,04$.','Cinco anos significam que esse fator será aplicado cinco vezes.','Por isso, o fator acumulado é $(1,04)^5$.','Multiplicar por $800$ daria a população depois de cinco anos, não apenas o fator pedido.']),
('00000042-0000-4000-8000-000000003500',array['Uma inversa deve desfazer a regra original na ordem contrária.','Comece isolando a entrada na relação $y=5x+2$.','Depois de trocar os nomes das variáveis, confira se o resultado desfaz multiplicar por 5 e somar 2.'],array['Escreva a relação com y','Troque entrada e saída','Desfaça a soma de 2','Desfaça a multiplicação por 5','Registre a inversa'],array['Escrevemos a função como $y=5x+2$.','Na relação inversa, $x=5y+2$.','Subtraindo $2$, obtemos $x-2=5y$.','Dividindo por $5$, fica $y=(x-2)/5$.','Logo, $f^{-1}(x)=(x-2)/5$.']),
('00000042-0000-4000-8000-000000003600',array['Para ter inversa, uma função não pode enviar duas entradas diferentes para a mesma saída.','Pense no que ocorre com $x$ e $-x$ na função quadrática.','A restrição $x\ge0$ remove uma das duas entradas simétricas.'],array['Recorde a exigência da inversa','Compare entradas opostas','Observe a duplicidade de saídas','Restrinja um lado da parábola','Conclua sobre a injetividade'],array['Uma inversa funcional exige que a função original seja injetiva.','Em $x^2$, por exemplo, $2$ e $-2$ produzem ambos a saída $4$.','Em todo $\mathbb R$, essa repetição impede a inversa de ser função.','Ao limitar o domínio a $x\ge0$, fica apenas uma entrada não negativa para cada saída.','Assim a função passa a ser injetiva e pode ter inversa nesse domínio.']),
('00000042-0000-4000-8000-000000003700',array['O logaritmo responde qual expoente a base deve receber.','Procure um expoente que transforme 2 em 1.','Use a regra de que toda base não nula elevada a zero vale 1.'],array['Traduza a pergunta logarítmica','Procure a potência igual a 1','Aplique o expoente zero','Volte ao logaritmo','Conclua o valor'],array['A expressão $\log_2(1)$ pergunta por qual expoente $k$ satisfaz $2^k=1$.','A base $2$ é não nula.','Portanto $2^0=1$.','O expoente procurado é $0$.','Assim, $\log_2(1)=0$.']),
('00000042-0000-4000-8000-000000003800',array['A base do logaritmo e a base da potência são a mesma: $a$.','Reescreva a expressão como a pergunta $a^k=a^7$.','Com $a>0$ e $a\ne1$, a igualdade das potências determina os expoentes.'],array['Identifique bases iguais','Converta para uma potência','Compare os expoentes','Use as restrições da base','Simplifique o logaritmo'],array['Queremos o expoente $k$ para o qual $a^k=a^7$.','As duas potências têm a mesma base $a$.','Como $a>0$ e $a\ne1$, a função exponencial é injetiva.','Logo, $k=7$.','Portanto $\log_a(a^7)=7$.']),
('00000042-0000-4000-8000-000000003900',array['Quando a incógnita está no expoente e as bases não coincidem, use logaritmo.','Aplique $\log_5$ aos dois lados para transformar o expoente em coeficiente.','Depois de encontrar $x$, verifique se o expoente fica igual a $\log_5 2$.'],array['Isole a potência exponencial','Aplique logaritmo de base 5','Traga o expoente para fora','Resolva a equação linear','Teste a forma obtida'],array['Partimos de $5^{x+1}=2$.','Aplicando $\log_5$, temos $\log_5(5^{x+1})=\log_5 2$.','O lado esquerdo simplifica para $x+1$.','Assim, $x+1=\log_5 2$, e $x=\log_5 2-1$.','Substituir esse expoente devolve $5^{\log_5 2}=2$.']),
('00000042-0000-4000-8000-000000004000',array['Decair 20% não significa ficar com 20%; significa retirar 20% do valor anterior.','Converta 20% para $0,20$ e subtraia de 1.','Compare o fator encontrado com 1: em um decaimento ele deve ser menor.'],array['Interprete a porcentagem perdida','Converta para decimal','Calcule a parte restante','Escreva o fator multiplicativo','Cheque o sentido do modelo'],array['O enunciado informa uma perda de 20% a cada período.','Em decimal, a parcela perdida é $0,20$.','A parcela que permanece é $1-0,20=0,80$.','Assim, cada novo valor é o anterior multiplicado por $0,80$.','Como $0,80<1$, o fator realmente representa decaimento.']),
('00000042-0000-4000-8000-000000004100',array['O produto está dentro de um único logaritmo natural.','A propriedade de produto troca multiplicação no argumento por adição fora do log.','Não distribua $\ln$ como se fosse uma multiplicação de números.'],array['Reconheça o produto interno','Use a propriedade do produto','Separe os dois fatores','Evite multiplicar logaritmos','Escreva a equivalência'],array['A expressão é $\ln(ab)$, cujo argumento é o produto $ab$.','Para argumentos positivos, vale $\ln(ab)=\ln a+\ln b$.','Cada fator passa a ter seu próprio logaritmo.','A regra não produz $\ln a\,\ln b$.','Logo, a simplificação correta é $\ln a+\ln b$.']),
('00000042-0000-4000-8000-000000004200',array['Há duas propriedades atuando: potência no numerador e quociente no argumento.','Primeiro separe o quociente em uma diferença de logaritmos.','Em seguida, transforme o expoente 4 em coeficiente de $\ln x$.'],array['Separe o quociente','Aplique a regra do quociente','Trate a potência do numerador','Mantenha o logaritmo de y','Combine as simplificações'],array['Começamos por $\ln(x^4/y)$.','A regra do quociente dá $\ln(x^4)-\ln y$.','Pela regra da potência, $\ln(x^4)=4\ln x$.','O termo do denominador permanece $-\ln y$.','Assim, o resultado é $4\ln x-\ln y$.']),
('00000042-0000-4000-8000-000000004300',array['O argumento de um logaritmo deve ser positivo, não apenas diferente de zero.','Observe o que ocorre com $\log_3 x$ quando $x$ se aproxima de zero pela direita.','A fronteira do domínio determina uma reta vertical no gráfico.'],array['Localize a fronteira do domínio','Aproxime-se pelo lado permitido','Observe o comportamento do log','Identifique a reta limite','Nomeie a assíntota'],array['Para $y=\log_3 x$, o domínio é $x>0$.','O valor $0$ é a fronteira desse domínio, mas não pertence a ele.','Quando $x$ tende a $0$ pela direita, o logaritmo diminui sem limite.','O gráfico se aproxima da reta vertical que passa por $x=0$.','Portanto a assíntota vertical é $x=0$.']),
('00000042-0000-4000-8000-000000004400',array['Compare a base com 1 para decidir se a exponencial cresce ou decai.','Teste mentalmente uma base entre zero e um, como $1/2$, em expoentes maiores.','Uma base negativa não define $a^x$ para todos os reais.'],array['Use o valor de referência 1','Escolha uma base fracionária','Aumente o expoente','Observe a redução dos valores','Caracterize o decaimento'],array['Uma função $a^x$ de base positiva é exponencial.','Se $0<a<1$, por exemplo $a=1/2$, então $(1/2)^1>(1/2)^2$.','Aumentar $x$ produz valores cada vez menores.','Isso é o comportamento de decaimento exponencial.','Logo, a condição é $0<a<1$.']),
('00000042-0000-4000-8000-000000004500',array['Triplicar a cada 4 horas equivale a multiplicar por 3 em cada período.','Escreva 27 como potência de 3 para descobrir quantos períodos são necessários.','Multiplique o número de períodos por 4 horas.'],array['Identifique o fator por período','Reescreva 27 como potência','Conte as triplicações','Converta períodos em horas','Verifique o fator final'],array['Cada período de 4 horas multiplica a cultura por $3$.','Como $27=3^3$, é preciso triplicar três vezes.','Portanto decorreram 3 períodos.','Cada período dura 4 horas, então o tempo é $3\cdot4=12$ horas.','Depois de 12 horas, o fator é $3^3=27$, confirmando o resultado.']),
('00000042-0000-4000-8000-000000004600',array['A base de $e^0$ é diferente de zero.','Use a regra geral para qualquer base não nula elevada ao expoente zero.','Não confunda expoente zero com resultado zero.'],array['Observe a base não nula','Aplique a regra do expoente zero','Interprete o elemento neutro','Descarte a confusão com zero','Conclua a potência'],array['A constante $e$ é positiva e, portanto, não é zero.','Para toda base não nula, vale $a^0=1$.','O resultado é o elemento neutro da multiplicação.','O expoente ser zero não torna a potência igual a zero.','Assim, $e^0=1$.']),
('00000042-0000-4000-8000-000000004700',array['Converta o logaritmo em uma potência de base 4.','A fração $3/2$ pode ser lida como raiz quadrada de uma potência cúbica.','Verifique elevando 8 à potência $3/2$.'],array['Passe à forma exponencial','Separe numerador e denominador do expoente','Calcule a raiz de 8','Eleve ao cubo','Confira a igualdade'],array['A igualdade $\log_4 x=3/2$ equivale a $x=4^{3/2}$.','O expoente $3/2$ significa elevar à terceira potência e tirar raiz quadrada.','Como $4^{1/2}=2$, temos $4^{3/2}=2^3$.','Assim, $x=8$.','De fato, $8^{2/3}=4$, que confirma a forma logarítmica.']),
('00000042-0000-4000-8000-000000004800',array['Mudança de base conserva o expoente que relaciona 7 e 20.','Use um logaritmo disponível na calculadora, como $\ln$ ou $\log_{10}$.','O quociente deve ter o logaritmo de 20 em cima e o de 7 embaixo.'],array['Defina o expoente procurado','Escreva a relação exponencial','Aplique ln aos dois lados','Isole o expoente','Interprete a fórmula'],array['Se $k=\log_7 20$, então $7^k=20$.','Aplicamos $\ln$ aos dois lados: $\ln(7^k)=\ln20$.','Pela propriedade da potência, $k\ln7=\ln20$.','Dividindo por $\ln7$, obtemos $k=\ln20/\ln7$.','Essa razão pode ser calculada com uma calculadora comum.']),
('00000042-0000-4000-8000-000000004900',array['$\ln$ é a inversa da exponencial de base $e$.','Reconheça que o argumento tem a forma $e^u$, com $u=-3$.','A resposta deve recuperar o expoente, inclusive seu sinal.'],array['Identifique a composição inversa','Leia o expoente do argumento','Aplique a propriedade de inversão','Preserve o sinal negativo','Registre o resultado'],array['A função é $f(x)=\ln x$.','A entrada fornecida é $e^{-3}$.','Como $\ln(e^u)=u$, a aplicação desfaz a exponencial.','Aqui, $u=-3$, e esse sinal deve ser mantido.','Portanto $f(e^{-3})=-3$.']),
('00000042-0000-4000-8000-000000005000',array['Na forma $\ln(e^u)$, o logaritmo natural recupera o expoente $u$.','Identifique que o expoente do argumento é $-3$.','Não troque o resultado pelo próprio número $e^{-3}$; ele é a entrada da função.'],array['Leia a regra da função','Substitua a entrada exponencial','Use a inversão entre ln e e','Recupere o expoente','Diferencie entrada e saída'],array['A regra dada é $f(x)=\ln x$.','Ao substituir $x=e^{-3}$, obtemos $f(e^{-3})=\ln(e^{-3})$.','O logaritmo natural desfaz a exponencial de base $e$.','Assim, o resultado é o expoente $-3$.','Portanto a saída da função é $-3$, e não a própria entrada $e^{-3}$.']),
('00000042-0000-4000-8000-000000005100',array['Em um limite de polinômio, a continuidade permite substituir o valor de aproximação.','Troque $x$ por 2 em cada termo da expressão $3x+1$.','Some depois de fazer a multiplicação.'],array['Reconheça a continuidade polinomial','Substitua o ponto de aproximação','Multiplique o coeficiente','Some a constante','Conclua o limite'],array['A expressão $3x+1$ é um polinômio, portanto é contínua em $x=2$.','Podemos calcular o limite por substituição direta.','Substituindo, obtemos $3\cdot2+1$.','Isso resulta em $6+1=7$.','Logo, $\lim_{x\to2}(3x+1)=7$.']),
('00000042-0000-4000-8000-000000005200',array['A substituição direta gera $0/0$, sinal de que uma simplificação algébrica é necessária.','Fatore $x^2-9$ como diferença de quadrados.','Cancele $x-3$ apenas antes de substituir, pois o limite olha valores próximos de 3.'],array['Teste a substituição inicial','Fatore o numerador','Reescreva a fração','Cancele o fator comum','Avalie o limite simplificado'],array['Em $x=3$, a fração produz $0/0$, uma forma indeterminada.','Fatoramos $x^2-9=(x-3)(x+3)$.','Para $x\ne3$, a fração fica $(x-3)(x+3)/(x-3)$.','Cancelando o fator comum, sobra $x+3$.','Assim, o limite é $3+3=6$.']),
('00000042-0000-4000-8000-000000005300',array['A expressão dá $0/0$ em $x=0$; a raiz no numerador sugere racionalização.','Multiplique numerador e denominador pelo conjugado $\sqrt{x+4}+2$.','Após simplificar, substitua 0 na expressão sem radical no numerador.'],array['Detecte a forma indeterminada','Escolha o conjugado','Racionalize o numerador','Cancele o fator x','Calcule o limite restante'],array['Substituir $x=0$ produz $(2-2)/0$, isto é, $0/0$.','Multiplicamos pelo conjugado $\sqrt{x+4}+2$.','O numerador vira $(x+4)-4=x$.','O fator $x$ cancela com o denominador, restando $1/(\sqrt{x+4}+2)$.','Em $x=0$, o limite é $1/(2+2)=1/4$.']),
('00000042-0000-4000-8000-000000005400',array['Um limite bilateral só existe se as aproximações pela esquerda e pela direita concordarem.','Compare os dois valores laterais citados no enunciado.','Quando eles diferem, não há um único número para representar o limite.'],array['Recorde o critério bilateral','Examine o lado esquerdo','Examine o lado direito','Compare os dois resultados','Decida a existência'],array['O limite $\lim_{x\to a}f(x)$ reúne os comportamentos pelos dois lados de $a$.','O enunciado informa que os limites laterais são diferentes.','Assim, aproximar-se por um lado produz um valor e pelo outro, outro valor.','Não existe um único candidato que satisfaça ambos.','Portanto o limite bilateral não existe.']),
('00000042-0000-4000-8000-000000005500',array['Este é um limite trigonométrico fundamental e usa medida em radianos.','A fração tem seno no numerador e o próprio ângulo no denominador.','À medida que $x$ se aproxima de zero, a razão se aproxima de 1.'],array['Reconheça o limite fundamental','Confira a forma seno sobre ângulo','Use a medida em radianos','Aplique a propriedade conhecida','Informe o valor'],array['A expressão é exatamente $\sin x/x$ quando $x\to0$.','Esse limite notável é válido com $x$ medido em radianos.','Ele descreve que seno e ângulo têm a mesma aproximação linear perto de zero.','Assim, a razão tende a $1$.','Logo, $\lim_{x\to0}\sin x/x=1$.']),
('00000042-0000-4000-8000-000000005600',array['Para uma fração racional no infinito, compare os termos de maior grau.','Divida numerador e denominador por $x^2$.','Os termos que ficam com $1/x$ ou $1/x^2$ desaparecem no limite.'],array['Compare os graus dominantes','Divida pela maior potência','Simplifique cada parcela','Faça x crescer sem limite','Forme a razão dos líderes'],array['Numerador e denominador têm grau 2.','Dividindo por $x^2$, obtemos $(5-1/x)/(2+7/x^2)$.','Quando $x\to\infty$, tanto $1/x$ quanto $7/x^2$ tendem a zero.','A fração passa a se comportar como $5/2$.','Portanto o limite é $5/2$.']),
('00000042-0000-4000-8000-000000005700',array['Procure os valores que anulam o denominador de uma função racional.','Resolva $x+4=0$.','Um ponto que causa divisão por zero não pertence ao domínio e é uma descontinuidade.'],array['Examine a fração','Iguale o denominador a zero','Resolva a equação linear','Relacione ao domínio','Indique o ponto descontínuo'],array['A função é $1/(x+4)$.','Ela deixa de existir quando o denominador vale zero.','Resolvendo $x+4=0$, encontramos $x=-4$.','Nesse ponto ocorreria divisão por zero.','Logo, a função é descontínua em $x=-4$.']),
('00000042-0000-4000-8000-000000005800',array['Compare a fórmula com seu domínio: o fator cancelável ainda deixa uma ausência no ponto original.','Fatore $x^2-1$ antes de simplificar a fração.','Veja que o limite existe em 1, mas a expressão inicial não está definida ali.'],array['Fatore o numerador','Mostre o fator comum','Simplifique fora do ponto','Observe a falha no domínio','Classifique a descontinuidade'],array['O numerador fatorado é $x^2-1=(x-1)(x+1)$.','Para $x\ne1$, a fração simplifica para $x+1$.','Essa expressão se aproxima de $2$ quando $x$ se aproxima de $1$.','Entretanto, a fórmula original ainda tem denominador zero em $x=1$.','Há um furo que poderia ser preenchido: a descontinuidade é removível.']),
('00000042-0000-4000-8000-000000005900',array['Em uma função definida por partes, continuidade no ponto de troca exige concordância entre os ramos.','Calcule o limite do ramo $x+1$ quando $x$ se aproxima de 2 pela esquerda.','Escolha $k$ igual a esse valor, pois ele governa o ramo que inclui $x=2$.'],array['Identifique o ponto de junção','Avalie o limite pela esquerda','Leia o valor do ramo direito','Iguale os dois valores','Fixe o valor de k'],array['A mudança de regra ocorre em $x=2$.','Pelo ramo esquerdo, $x+1$ tende a $2+1=3$.','No ramo direito, e no próprio ponto, a função vale $k$.','Para não haver salto, precisamos de $k=3$.','Com essa escolha, os dois lados e o valor da função coincidem.']),
('00000042-0000-4000-8000-000000006000',array['Assíntota horizontal descreve o valor de $y$ quando $x$ fica muito grande em módulo.','Observe o que acontece com uma fração de numerador constante e denominador crescente.','Não confunda a reta horizontal $y=0$ com a assíntota vertical $x=0$.'],array['Analise o comportamento distante','Faça o denominador crescer','Compare o tamanho da fração','Identifique a altura aproximada','Diferencie os eixos'],array['Para $1/x$, o numerador permanece 1 enquanto o denominador cresce em módulo.','Por isso, os valores da fração ficam cada vez mais próximos de zero.','Isso ocorre tanto para $x\to\infty$ quanto para $x\to-\infty$.','A reta de altura zero é a que o gráfico se aproxima.','Logo, a assíntota horizontal é $y=0$.']),
('00000042-0000-4000-8000-000000006100',array['Assíntotas verticais aparecem nos zeros do denominador que não são cancelados.','Fatore $x^2-4$ como produto de dois fatores lineares.','Cada zero encontrado corresponde a uma reta vertical.'],array['Fatore o denominador','Encontre o primeiro zero','Encontre o segundo zero','Cheque a ausência de cancelamento','Liste as assíntotas'],array['O denominador é $x^2-4=(x-2)(x+2)$.','O fator $x-2$ zera em $x=2$.','O fator $x+2$ zera em $x=-2$.','Como o numerador é 1, nenhum desses fatores pode ser cancelado.','As assíntotas verticais são $x=-2$ e $x=2$.']),
('00000042-0000-4000-8000-000000006200',array['A expressão tem a forma do limite fundamental da exponencial.','Perto de zero, $e^x$ pode ser aproximado por $1+x$.','Depois de subtrair 1, o termo dominante no numerador é $x$.'],array['Reconheça o padrão exponencial','Use a aproximação local','Subtraia a unidade','Compare com o denominador','Aplique o limite notável'],array['O limite pedido é $(e^x-1)/x$ quando $x\to0$.','A função exponencial satisfaz $e^x=1+x+$ termos menores perto de zero.','Logo, $e^x-1$ se comporta como $x$.','A razão entre dois termos equivalentes a $x$ tende a 1.','Portanto o limite fundamental vale $1$.']),
('00000042-0000-4000-8000-000000006300',array['Continuidade significa ausência de quebras no comportamento da função dentro do intervalo.','Um salto cria limites laterais diferentes no ponto em que ocorre.','Se há salto, a definição de continuidade falha naquele ponto.'],array['Lembre a ideia de continuidade','Descreva um salto','Compare os lados da quebra','Relacione à definição','Responda sobre a possibilidade'],array['Uma função contínua acompanha seu próprio limite em cada ponto do intervalo.','Em um salto, o valor vindo pela esquerda difere do valor vindo pela direita.','Assim, nem o limite bilateral existe nesse ponto.','Sem limite bilateral, a continuidade não pode ocorrer.','Portanto uma função contínua em $[a,b]$ não pode ter salto no interior.']),
('00000042-0000-4000-8000-000000006400',array['Continuidade em um ponto só pode ser discutida se a função estiver definida nele.','O argumento de $\ln x$ precisa ser positivo.','Compare o ponto 0 com a condição $x>0$.'],array['Verifique o domínio do logaritmo','Imponha argumento positivo','Teste o ponto zero','Aplique a condição de continuidade','Conclua a falha'],array['Para $\ln x$, a condição de domínio é $x>0$.','O valor $x=0$ não satisfaz essa condição.','Portanto $\ln0$ não é um número real definido.','Como falta o valor da função no ponto, ela não pode ser contínua ali.','Logo, $\ln x$ não é contínua em $x=0$.']),
('00000042-0000-4000-8000-000000006500',array['A identidade $1-\cos x=2\sin^2(x/2)$ transforma o numerador em uma forma ligada ao limite do seno.','Divida o denominador para introduzir $x/2$ nas razões trigonométricas.','Use que $\sin(x/2)/(x/2)$ tende a 1.'],array['Aplique a identidade do cosseno','Reescreva a fração','Introduza o meio ângulo','Use o limite do seno','Calcule o coeficiente restante'],array['Usamos $1-\cos x=2\sin^2(x/2)$.','Então a fração é $2\sin^2(x/2)/x^2$.','Ela pode ser escrita como $\frac12[\sin(x/2)/(x/2)]^2$.','Quando $x\to0$, a razão entre colchetes tende a 1.','Assim, o limite é $\frac12\cdot1^2=1/2$.']),
('00000042-0000-4000-8000-000000006600',array['Limite trata da tendência perto de um ponto, não necessariamente do valor no ponto.','Observe que o enunciado informa uma aproximação de $f(x)$ para $L$ quando $x$ se aproxima de $a$.','Só poderíamos afirmar $f(a)=L$ se a função fosse contínua em $a$.'],array['Leia a notação de limite','Diferencie proximidade e igualdade','Observe o papel de x','Evite usar f(a) sem hipótese','Traduza em palavras'],array['A escrita $\lim_{x\to a}f(x)=L$ observa valores de $f(x)$ com $x$ próximo de $a$.','Ela afirma que esses valores se aproximam de $L$.','O ponto $a$ pode até estar fora do domínio ou ter outro valor atribuído.','Por isso o limite sozinho não garante que $f(a)=L$.','Em palavras, $f(x)$ se aproxima de $L$ quando $x$ se aproxima de $a$.']);

-- Remove os registros legados antes de inserir as versões específicas deste bloco.
delete from public.question_hints where question_id in (select question_id from c1_block_02_steps);
delete from public.question_solution_steps where question_id in (select question_id from c1_block_02_steps);

insert into public.question_hints (id,question_id,content_markdown,sort_order)
select format('00000083-0000-4000-8000-%s',lpad((row_number() over(order by question_id)*10+ord)::text,12,'0'))::uuid,
question_id,hint,ord
from c1_block_02_steps cross join lateral unnest(hints) with ordinality as h(hint,ord);

insert into public.question_solution_steps (id,question_id,title,content_markdown,sort_order)
select format('00000093-0000-4000-8000-%s',lpad((row_number() over(order by question_id)*10+ord)::text,12,'0'))::uuid,
question_id,title,step,ord
from c1_block_02_steps
cross join lateral unnest(titles) with ordinality as t(title,ord)
cross join lateral unnest(steps) with ordinality as s(step,step_ord)
where ord=step_ord;

commit;
