-- Bloco 1: reescreve somente dicas e passos das primeiras 33 questões MC.
-- Enunciados, alternativas, gabaritos, tags e explicações permanecem intactos.
begin;

create temporary table c1_block_01_steps (
  question_id uuid primary key, hints text[] not null, titles text[] not null, steps text[] not null
) on commit drop;

insert into c1_block_01_steps values
('00000042-0000-4000-8000-000000000100',array['Em uma raiz quadrada real, observe o que o radicando não pode ser.','Transforme a restrição do radicando em uma desigualdade para $x$.','Teste o valor de fronteira na expressão antes de decidir se o colchete é aberto ou fechado.'],array['Examine o radicando','Imponha a condição real','Isole a variável','Inclua a fronteira','Escreva o domínio'],array['A única restrição vem de $x-3$, que está dentro da raiz.','Para a raiz ser real, precisamos de $x-3\ge0$.','Somando $3$ aos dois lados, obtemos $x\ge3$.','Em $x=3$, a raiz vale $0$, portanto esse valor é permitido.','Todos os valores a partir de $3$ formam $[3,\infty)$.']),
('00000042-0000-4000-8000-000000000200',array['Uma fração não é definida quando seu denominador vale zero.','Fatore $x^2-9$ para localizar os dois valores proibidos.','Depois de excluir os zeros, expresse o restante dos reais.'],array['Localize o denominador','Fatore a diferença de quadrados','Encontre os zeros proibidos','Retire os dois pontos','Descreva os reais restantes'],array['O denominador da função é $x^2-9$.','Como $x^2-9=(x-3)(x+3)$, os fatores mostram onde ele pode zerar.','Os zeros são $x=3$ e $x=-3$.','Nesses dois pontos haveria divisão por zero, então nenhum deles pertence ao domínio.','O domínio é $\mathbb{R}\setminus\{-3,3\}$.']),
('00000042-0000-4000-8000-000000000300',array['O argumento de qualquer logaritmo natural deve ser estritamente positivo.','Escreva $5-2x>0$ e trate o sinal negativo ao dividir a desigualdade.','Confira se um valor menor que $5/2$, como $0$, realmente torna o argumento positivo.'],array['Observe o argumento do logaritmo','Escreva a desigualdade','Transponha o termo com x','Inverta a comparação','Cheque um valor permitido'],array['O argumento de $\ln$ é $5-2x$.','A condição de existência é $5-2x>0$.','Daí segue $-2x>-5$.','Ao dividir por $-2$, o sentido se inverte e resulta $x<5/2$.','Por exemplo, em $x=0$, o argumento é $5>0$, confirmando a condição.']),
('00000042-0000-4000-8000-000000000400',array['Substitua $-2$ usando parênteses em cada ocorrência de $x$.','Calcule a potência antes da multiplicação por $2$.','Compare o sinal do termo quadrático com o sinal do termo linear.'],array['Substitua o argumento negativo','Eleve o argumento ao quadrado','Multiplique o termo quadrático','Some o termo constante','Leia o valor da função'],array['Começamos com $f(-2)=2(-2)^2-3$.','O quadrado elimina o sinal: $(-2)^2=4$.','Assim, $2\cdot4=8$.','Subtraindo $3$, obtemos $8-3=5$.','Logo, a saída associada a $-2$ é $5$.']),
('00000042-0000-4000-8000-000000000500',array['Compare $-3$ com a condição que acompanha cada ramo.','Como $-3<0$, use somente a expressão linear.','Substitua e mantenha o sinal negativo entre parênteses.'],array['Escolha o ramo negativo','Substitua na expressão linear','Some uma unidade','Descarte o outro ramo','Conclua a avaliação'],array['O ponto pedido é $-3$, que satisfaz $x<0$.','Portanto usamos $f(x)=x+1$, e não $x^2$.','Então $f(-3)=-3+1$.','O cálculo resulta em $-2$.','Assim, $f(-3)=-2$.']),
('00000042-0000-4000-8000-000000000600',array['O número $0$ não satisfaz $x<0$.','Procure o ramo cuja desigualdade inclui o sinal de igualdade.','Avalie a potência correspondente ao ramo escolhido.'],array['Verifique a fronteira','Selecione o ramo com igualdade','Substitua x por zero','Calcule a potência','Registre o valor'],array['Para $x=0$, a condição $x<0$ é falsa.','A condição $x\ge0$ é verdadeira, por isso usamos $f(x)=x^2$.','Substituindo, fica $f(0)=0^2$.','A potência é $0$.','Logo, $f(0)=0$.']),
('00000042-0000-4000-8000-000000000700',array['Em $f\circ g$, a função mais próxima do argumento atua primeiro.','Calcule $g(1)$ antes de usar $f$.','Use o resultado de $g$ como entrada de $f$.'],array['Leia a ordem da composição','Aplique g ao número 1','Use a saída como nova entrada','Aplique f ao resultado','Conclua a composição'],array['A notação $f\circ g$ significa aplicar primeiro $g$.','Temos $g(1)=3\cdot1=3$.','Agora o número $3$ entra em $f$.','Então $f(3)=3+2=5$.','Portanto $(f\circ g)(1)=5$.']),
('00000042-0000-4000-8000-000000000800',array['A composição $g\circ f$ começa por $f(x)$.','Substitua a expressão completa $x+2$ no lugar do argumento de $g$.','Distribua o fator $3$ pelos dois termos antes de simplificar.'],array['Comece pela função interna','Escreva a entrada de g','Substitua f(x) em g','Distribua o coeficiente','Simplifique a expressão'],array['Em $g\circ f$, a função interna é $f(x)=x+2$.','A regra de $g$ é multiplicar sua entrada por $3$.','Assim, $g(f(x))=3(x+2)$.','Distribuindo, temos $3x+6$.','Logo, $(g\circ f)(x)=3x+6$.']),
('00000042-0000-4000-8000-000000000900',array['A raiz de uma expressão exige que o que está dentro dela seja não negativo.','Em $f\circ g$, a saída $x-4$ será o radicando.','Resolva $x-4\ge0$ e veja qual intervalo começa na fronteira.'],array['Escreva a composição','Identifique o novo radicando','Imponha a condição da raiz','Resolva a desigualdade','Dê o domínio composto'],array['A composição é $f(g(x))=\sqrt{x-4}$.','O radicando agora é $x-4$.','Para a raiz existir, $x-4\ge0$.','Somando $4$, obtemos $x\ge4$.','O domínio é $[4,\infty)$.']),
('00000042-0000-4000-8000-000000001000',array['Uma alteração dentro de $f(\cdot)$ afeta o eixo horizontal.','Compare o ponto que antes usava entrada $a$ com a nova entrada que produz $a$.','Para obter $f(a)$ em $f(x-2)$, escolha $x=a+2$.'],array['Compare as entradas','Fixe uma saída antiga','Encontre a nova abscissa','Leia o sentido do movimento','Nomeie o deslocamento'],array['Considere um ponto original $(a,f(a))$.','No novo gráfico queremos $f(x-2)=f(a)$.','Isso exige $x-2=a$, ou seja, $x=a+2$.','O mesmo valor de saída aparece duas unidades mais à direita.','Portanto o gráfico se desloca 2 unidades para a direita.']),
('00000042-0000-4000-8000-000000001100',array['O sinal de menos está fora da função, então ele atua sobre a saída.','Compare um ponto $(x,y)$ do gráfico original com $(x,-y)$.','Observe qual eixo mantém a coordenada x e troca o sinal da altura.'],array['Isole o sinal externo','Compare as coordenadas','Mantenha a abscissa','Troque a ordenada','Identifique a reflexão'],array['Se $y=f(x)$, a nova altura é $-f(x)$.','Assim, cada ponto $(x,y)$ vira $(x,-y)$.','A coordenada horizontal não muda.','A coordenada vertical troca de sinal.','Essa transformação é a reflexão no eixo $x$.']),
('00000042-0000-4000-8000-000000001200',array['O fator $2$ está dentro da função, portanto a mudança é horizontal.','Compare onde um valor $f(a)$ aparece na nova expressão.','Resolva $2x=a$ para relacionar a nova abscissa à antiga.'],array['Acompanhe um valor do gráfico','Iguale o argumento a a','Resolva para a nova posição','Compare a distância horizontal','Classifique a transformação'],array['Um valor antigo $f(a)$ aparece quando $2x=a$.','Daí, a nova posição é $x=a/2$.','Cada distância horizontal até a origem fica pela metade.','Por exemplo, um ponto em $x=4$ passa a aparecer em $x=2$.','O gráfico sofre compressão horizontal por fator $2$.']),
('00000042-0000-4000-8000-000000001300',array['Uma inversa funcional exige que cada valor de saída venha de no máximo uma entrada.','Pense em uma reta horizontal atravessando o gráfico.','Se alguma reta horizontal encontrar dois pontos, a inversa não será função.'],array['Relacione inversa e unicidade','Trace uma reta horizontal mental','Conte as interseções','Interprete duas interseções','Nomeie o teste'],array['Para uma inversa ser função, a função original precisa ser injetiva.','Uma reta horizontal representa uma mesma saída $y=c$.','Se ela encontra o gráfico mais de uma vez, há duas entradas para a mesma saída.','Isso impede que a inversa atribua uma única imagem a $c$.','O critério gráfico é o teste da reta horizontal.']),
('00000042-0000-4000-8000-000000001400',array['Para encontrar uma inversa, troque os papéis de entrada e saída e isole a nova saída.','Comece por $y=3x-7$ antes de trocar $x$ e $y$.','No final, componha mentalmente para verificar que a expressão recupera a entrada.'],array['Escreva a regra original','Troque x e y','Isole a nova saída','Rebatize a inversa','Cheque por composição'],array['A função original satisfaz $y=3x-7$.','Trocando as variáveis, fica $x=3y-7$.','Somamos $7$ e dividimos por $3$: $y=(x+7)/3$.','Essa é a regra de $f^{-1}(x)$.','Aplicar $3((x+7)/3)-7$ devolve $x$, confirmando a inversa.']),
('00000042-0000-4000-8000-000000001500',array['Teste dois argumentos opostos que tenham o mesmo quadrado.','Compare $f(2)$ e $f(-2)$.','Explique por que duas pré-imagens impedem uma inversa que seja função.'],array['Escolha entradas opostas','Calcule os dois quadrados','Compare as imagens','Reconheça a falha de injetividade','Conclua sobre a inversa'],array['Para $f(x)=x^2$, use as entradas $2$ e $-2$.','Temos $f(2)=4$ e também $f(-2)=4$.','A mesma saída positiva vem de duas entradas distintas.','Logo, $x^2$ não é injetiva em todo $\mathbb R$.','Por isso sua inversa não pode ser uma função nesse domínio.']),
('00000042-0000-4000-8000-000000001600',array['Todo número não nulo elevado a zero vale 1.','Pense na regra de divisão de potências de mesma base.','Verifique que $2^0\cdot2^k=2^k$.'],array['Use a regra dos expoentes','Compare potências iguais','Encontre o fator neutro','Aplique à base 2','Conclua o valor'],array['Pela regra, $2^k/2^k=2^{k-k}=2^0$.','Mas uma quantidade não nula dividida por ela mesma vale $1$.','Assim, $2^0$ deve ser o fator neutro multiplicativo.','Isso também garante $2^0\cdot2^k=2^k$.','Portanto $2^0=1$.']),
('00000042-0000-4000-8000-000000001700',array['Um logaritmo pergunta qual expoente produz o argumento a partir da base.','Reescreva $\log_2 32=5$ como uma potência.','Calcule potências sucessivas de 2 até obter 32.'],array['Leia base e argumento','Traduza para forma exponencial','Calcule a potência de 2','Compare com 32','Conclua o expoente'],array['A base do logaritmo é $2$ e o argumento é $32$.','Perguntamos qual expoente $k$ satisfaz $2^k=32$.','Como $2^5=32$, o expoente procurado é $5$.','Logo a igualdade logarítmica é $\log_2 32=5$.','A resposta registra o expoente, não o valor $32$.']),
('00000042-0000-4000-8000-000000001800',array['Conte quantos intervalos de 3 horas cabem em 9 horas.','Cada intervalo completo multiplica a quantidade por 2.','Escreva a multiplicação repetida como uma potência de 2.'],array['Conte os períodos','Associe um fator a cada período','Escreva a potência','Calcule o fator total','Interprete o resultado'],array['De $0$ a $9$ horas decorrem $9/3=3$ períodos.','Em cada período, a quantidade dobra, isto é, multiplica por $2$.','O fator total é $2^3$.','Calculando, $2^3=8$.','Após 9 horas, a quantidade é oito vezes a inicial.']),
('00000042-0000-4000-8000-000000001900',array['Calcule $f(-x)$ e compare-o com $f(x)$.','Observe se o resultado é igual a $f(x)$ ou ao seu oposto.','Relacione $f(-x)=-f(x)$ à simetria do gráfico.'],array['Substitua -x na função','Simplifique os sinais','Compare com a função original','Reconheça a paridade','Descreva a simetria'],array['Para $f(x)=x^3$, temos $f(-x)=(-x)^3=-x^3$.','Como $f(x)=x^3$, resulta $f(-x)=-f(x)$.','Essa é exatamente a definição de função ímpar.','Em uma função ímpar, $(x,y)$ e $(-x,-y)$ aparecem juntos.','O gráfico é simétrico em relação à origem.']),
('00000042-0000-4000-8000-000000002000',array['Taxa média é a variação da saída dividida pela variação da entrada.','Calcule primeiro $f(3)$ e $f(1)$.','Use o denominador $3-1$, não apenas o ponto final.'],array['Escreva a fórmula da secante','Avalie os extremos','Calcule a variação vertical','Calcule a variação horizontal','Divida as variações'],array['A taxa média em $[1,3]$ é $\frac{f(3)-f(1)}{3-1}$.','Como $f(3)=9$ e $f(1)=1$, a variação de saída é $8$.','A variação de entrada é $2$.','Então a razão é $8/2$.','Logo, a taxa média é $4$.']),
('00000042-0000-4000-8000-000000002100',array['O coeficiente angular compara mudança vertical e mudança horizontal.','Subtraia as coordenadas y na mesma ordem em que subtrair as coordenadas x.','Reduza a fração obtida para interpretar a inclinação.'],array['Liste os dois pontos','Calcule a variação em y','Calcule a variação em x','Forme a razão de inclinação','Simplifique o coeficiente'],array['Os pontos são $(2,5)$ e $(6,17)$.','A mudança vertical é $17-5=12$.','A mudança horizontal é $6-2=4$.','Assim, o coeficiente angular é $12/4$.','A reta tem inclinação $3$.']),
('00000042-0000-4000-8000-000000002200',array['Uma equação de valor absoluto representa duas distâncias possíveis na reta real.','Separe $|x-1|=4$ em os casos $x-1=4$ e $x-1=-4$.','Verifique as duas soluções na expressão original.'],array['Interprete a distância','Abra o caso positivo','Abra o caso negativo','Resolva as duas equações','Reúna as soluções'],array['A igualdade diz que a distância entre $x$ e $1$ é $4$.','No primeiro caso, $x-1=4$, então $x=5$.','No segundo, $x-1=-4$, então $x=-3$.','Ambos estão a quatro unidades de $1$.','O conjunto solução é $\{-3,5\}$.']),
('00000042-0000-4000-8000-000000002300',array['Assíntota vertical ocorre onde o denominador se aproxima de zero sem cancelamento.','Resolva $x-2=0$.','Observe que o numerador é 1 e não pode cancelar o fator.'],array['Examine o denominador','Encontre seu zero','Cheque o numerador','Relacione ao comportamento infinito','Escreva a reta vertical'],array['A função é $1/(x-2)$.','O denominador se anula quando $x=2$.','O numerador continua igual a $1$, então não há fator a cancelar.','Perto de $2$, os valores crescem em módulo sem limite.','A assíntota vertical é a reta $x=2$.']),
('00000042-0000-4000-8000-000000002400',array['Em uma fração racional com mesmos graus, compare os coeficientes líderes.','Os termos de maior grau são $3x^2$ e $x^2$.','Divida ambos por $x^2$ para ver o comportamento quando $x$ cresce.'],array['Compare os graus','Isole os termos dominantes','Divida pelo maior grau','Tome o limite no infinito','Identifique a reta horizontal'],array['Numerador e denominador têm grau $2$.','Os termos dominantes são $3x^2$ e $x^2$.','Dividindo por $x^2$, a fração vira $\frac{3+1/x^2}{1-4/x^2}$.','Quando $x$ cresce, os termos com $1/x^2$ tendem a zero.','O limite é $3$, logo a assíntota horizontal é $y=3$.']),
('00000042-0000-4000-8000-000000002500',array['Na notação $f(a)=b$, identifique qual número entra e qual sai.','O número dentro dos parênteses é a entrada.','A igualdade informa a saída correspondente, não uma operação entre 2 e 7.'],array['Leia a notação funcional','Localize a entrada','Localize a saída','Traduza em palavras','Confirme a associação'],array['A expressão dada é $f(2)=7$.','O argumento $2$ é o valor fornecido à função.','O número $7$ é o resultado produzido para essa entrada.','Em palavras, a função associa 2 a 7.','Não há informação sobre outros valores de entrada.']),
('00000042-0000-4000-8000-000000002600',array['O logaritmo de base 10 procura um expoente para a potência de 10.','Escreva $\log_{10}(1000)=k$ como $10^k=1000$.','Conte quantos fatores 10 formam 1000.'],array['Identifique a base decimal','Traduza em potência','Fatore 1000 em dezenas','Leia o expoente','Volte à forma logarítmica'],array['A base é $10$ e o argumento é $1000$.','Queremos $k$ tal que $10^k=1000$.','Como $1000=10\cdot10\cdot10=10^3$, temos $k=3$.','Portanto o logaritmo vale $3$.','A resposta é o expoente que produz mil.']),
('00000042-0000-4000-8000-000000002700',array['Dobra significa multiplicar por 2 a cada período.','Conte quatro períodos de uma hora entre o início e 4 horas.','Multiplique 500 pelo fator $2^4$.'],array['Registre a população inicial','Conte as duplicações','Escreva o fator exponencial','Multiplique pelo início','Interprete a contagem'],array['A cultura começa com $500$ células.','Após quatro horas, ocorreram quatro duplicações.','O fator acumulado é $2^4=16$.','Então a quantidade é $500\cdot16$.','Após 4 horas haverá $8000$ células.']),
('00000042-0000-4000-8000-000000002800',array['Reescreva 27 como potência de base 3.','Depois de igualar os expoentes, lembre-se de resolver a equação linear que sobra.','Substitua o valor encontrado no expoente para conferir a potência.'],array['Reescreva o segundo membro','Iguale os expoentes','Monte a equação linear','Isole x','Verifique a potência'],array['Como $27=3^3$, a equação fica $3^{2x-1}=3^3$.','Bases iguais e positivas permitem igualar os expoentes.','Assim, $2x-1=3$.','Somando 1 e dividindo por 2, obtemos $x=2$.','De fato, $3^{2\cdot2-1}=3^3=27$.']),
('00000042-0000-4000-8000-000000002900',array['O logaritmo natural só aceita argumentos positivos.','O argumento de $\ln x$ é o próprio $x$.','Compare a condição com os intervalos da reta real.'],array['Localize o argumento','Imponha positividade','Exclua o zero','Exclua os negativos','Escreva o domínio'],array['Na expressão $\ln x$, o argumento é $x$.','A regra exige $x>0$.','O zero não é permitido porque $\ln0$ não existe.','Números negativos também não podem ser argumentos reais de $\ln$.','O domínio é formado pelos $x$ positivos.']),
('00000042-0000-4000-8000-000000003000',array['$\ln$ e a exponencial de base $e$ são funções inversas.','Reconheça que o argumento de $\ln$ é exatamente $e^5$.','Aplique a propriedade $\ln(e^a)=a$.'],array['Reconheça funções inversas','Identifique o expoente','Aplique a inversão','Simplifique o resultado','Cheque a equivalência'],array['A expressão é $\ln(e^5)$.','O logaritmo natural desfaz a exponencial de mesma base.','Logo, $\ln(e^5)=5$.','Não é necessário aproximar $e^5$ numericamente.','A resposta recupera o expoente original, $5$.']),
('00000042-0000-4000-8000-000000003100',array['Para desfazer $\ln$, aplique a exponencial nos dois lados.','Antes de resolver, registre que $x-1$ precisa ser positivo.','Depois de obter $x-1=e^2$, some 1 aos dois lados.'],array['Registre a condição de domínio','Aplique a exponencial','Elimine o logaritmo','Isole a variável','Cheque a condição'],array['O domínio exige $x-1>0$, portanto $x>1$.','Aplicando $e^{(\cdot)}$ nos dois lados, temos $x-1=e^2$.','O logaritmo foi desfeito pela exponencial.','Somando $1$, obtemos $x=1+e^2$.','Esse valor é maior que 1, logo satisfaz o domínio.']),
('00000042-0000-4000-8000-000000003200',array['Uma subtração no argumento desloca o gráfico horizontalmente.','Compare a posição em que $2^{x-3}$ tem o mesmo valor que $2^a$.','Resolva $x-3=a$ para identificar o sentido.'],array['Acompanhe um valor da exponencial','Iguale o novo argumento','Resolva a nova abscissa','Compare com a posição antiga','Nomeie o deslocamento'],array['Um valor antigo $2^a$ aparece no novo gráfico quando $x-3=a$.','Assim, sua nova posição é $x=a+3$.','Cada ponto aparece três unidades com abscissa maior.','A altura do ponto não muda.','Portanto há deslocamento de 3 unidades para a direita.']),
('00000042-0000-4000-8000-000000003300',array['Crescer 5% significa multiplicar por $1+0,05$ a cada ano.','Use 200 como valor inicial, correspondente a $t=0$.','O expoente $t$ conta quantos anos de crescimento composto ocorreram.'],array['Identifique o valor inicial','Converta a taxa em fator','Conte os períodos anuais','Monte o modelo exponencial','Cheque o instante inicial'],array['A população inicial é $200$.','Uma taxa de 5% produz fator anual $1,05$.','Após $t$ anos, esse fator é aplicado $t$ vezes.','O modelo é $200(1,05)^t$.','Quando $t=0$, ele retorna $200$, como o enunciado exige.']);

insert into public.question_hints (id,question_id,content_markdown,sort_order)
select format('00000082-0000-4000-8000-%s',lpad((row_number() over(order by question_id)*10+ord)::text,12,'0'))::uuid,
question_id,hint,ord
from c1_block_01_steps cross join lateral unnest(hints) with ordinality as h(hint,ord)
on conflict (question_id,sort_order) do update set content_markdown=excluded.content_markdown;

insert into public.question_solution_steps (id,question_id,title,content_markdown,sort_order)
select format('00000092-0000-4000-8000-%s',lpad((row_number() over(order by question_id)*10+ord)::text,12,'0'))::uuid,
question_id,title,step,ord
from c1_block_01_steps
cross join lateral unnest(titles) with ordinality as t(title,ord)
cross join lateral unnest(steps) with ordinality as s(step,step_ord)
where ord=step_ord
on conflict (question_id,sort_order) do update set title=excluded.title,content_markdown=excluded.content_markdown;

commit;
