-- Arquitetura de Computadores: revisão de gabaritos, lote 05.
-- Atualiza apenas soluções e passos; tentativas e alternativas são preservadas.
begin;

update public.question_solutions set final_answer_markdown='Instruções, registradores e efeitos visíveis ao programa.', explanation_markdown='ISA é o contrato entre software de baixo nível e processador. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Instruções, registradores e efeitos visíveis ao programa.” é a conclusão correta. “O layout dos transistores.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “A marca da cache.” não decorre do princípio aplicável: ISA é o contrato entre software de baixo nível e processador. “A linguagem C.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930101';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de ISA: O que uma ISA especifica principalmente?', sort_order=1 where id='70000000-0000-4000-8000-000009301011';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='ISA é o contrato entre software de baixo nível e processador.', sort_order=2 where id='70000000-0000-4000-8000-000009301012';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, O que uma ISA especifica principalmente? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301013';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“O layout dos transistores.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “A marca da cache.” não decorre do princípio aplicável: ISA é o contrato entre software de baixo nível e processador. “A linguagem C.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301014';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Instruções, registradores e efeitos visíveis ao programa.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301015';

update public.question_solutions set final_answer_markdown='Porque todos os campos dividem o mesmo orçamento de bits.', explanation_markdown='Formato fixo impõe trade-off entre campos. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Porque todos os campos dividem o mesmo orçamento de bits.” é a conclusão correta. “Porque o PC perde valor.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Porque RAM reduz tamanho.” não decorre do princípio aplicável: Formato fixo impõe trade-off entre campos. “Porque ALU não usa bits.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930102';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de formato de instrução: Por que um opcode mais longo reduz espaço para operandos em instrução de tamanho fixo?', sort_order=1 where id='70000000-0000-4000-8000-000009301021';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Formato fixo impõe trade-off entre campos.', sort_order=2 where id='70000000-0000-4000-8000-000009301022';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Por que um opcode mais longo reduz espaço para operandos em instrução de tamanho fixo? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301023';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Porque o PC perde valor.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Porque RAM reduz tamanho.” não decorre do princípio aplicável: Formato fixo impõe trade-off entre campos. “Porque ALU não usa bits.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301024';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Porque todos os campos dividem o mesmo orçamento de bits.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301025';

update public.question_solutions set final_answer_markdown='$6$', explanation_markdown='Subtraia $4+3+3$ de $16$. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “$6$” é a conclusão correta. “$3$” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “$9$” não decorre do princípio aplicável: Subtraia $4+3+3$ de $16$. “$16$” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930103';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de opcode: Um formato de 16 bits reserva 4 para opcode e 3 para cada registrador. Quantos bits restam para imediato em instrução com dois registradores?', sort_order=1 where id='70000000-0000-4000-8000-000009301031';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Subtraia $4+3+3$ de $16$.', sort_order=2 where id='70000000-0000-4000-8000-000009301032';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Um formato de 16 bits reserva 4 para opcode e 3 para cada registrador. Quantos bits restam para imediato em instrução com dois registradores? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301033';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$3$” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “$9$” não decorre do princípio aplicável: Subtraia $4+3+3$ de $16$. “$16$” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301034';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$6$”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301035';

update public.question_solutions set final_answer_markdown='Um valor codificado na própria instrução.', explanation_markdown='Campo imediato representa valor, não localização. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Um valor codificado na própria instrução.” é a conclusão correta. “Um dado buscado da RAM.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “O endereço do PC.” não decorre do princípio aplicável: Campo imediato representa valor, não localização. “Uma linha de cache.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930104';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de imediato: No endereçamento imediato, o operando é:', sort_order=1 where id='70000000-0000-4000-8000-000009301041';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Campo imediato representa valor, não localização.', sort_order=2 where id='70000000-0000-4000-8000-000009301042';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, No endereçamento imediato, o operando é: A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301043';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Um dado buscado da RAM.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “O endereço do PC.” não decorre do princípio aplicável: Campo imediato representa valor, não localização. “Uma linha de cache.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301044';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Um valor codificado na própria instrução.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301045';

update public.question_solutions set final_answer_markdown='$0x1000$.', explanation_markdown='O registrador contém endereço efetivo no modo indireto. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “$0x1000$.” é a conclusão correta. “O conteúdo futuro de R1.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “O opcode.” não decorre do princípio aplicável: O registrador contém endereço efetivo no modo indireto. “O valor zero.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930105';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de indireto por registrador: Se R3 contém $0x1000$, o que LOAD R1,[R3] usa como endereço?', sort_order=1 where id='70000000-0000-4000-8000-000009301051';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='O registrador contém endereço efetivo no modo indireto.', sort_order=2 where id='70000000-0000-4000-8000-000009301052';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Se R3 contém $0x1000$, o que LOAD R1,[R3] usa como endereço? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301053';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“O conteúdo futuro de R1.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “O opcode.” não decorre do princípio aplicável: O registrador contém endereço efetivo no modo indireto. “O valor zero.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301054';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$0x1000$.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301055';

update public.question_solutions set final_answer_markdown='$112$.', explanation_markdown='Base mais deslocamento soma os dois valores. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “$112$.” é a conclusão correta. “$88$.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “$1200$.” não decorre do princípio aplicável: Base mais deslocamento soma os dois valores. “$12$.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930106';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de base e deslocamento: Com R2=$100$ e deslocamento $12$, qual endereço efetivo é usado por LOAD R1,12(R2)?', sort_order=1 where id='70000000-0000-4000-8000-000009301061';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Base mais deslocamento soma os dois valores.', sort_order=2 where id='70000000-0000-4000-8000-000009301062';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Com R2=$100$ e deslocamento $12$, qual endereço efetivo é usado por LOAD R1,12(R2)? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301063';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$88$.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “$1200$.” não decorre do princípio aplicável: Base mais deslocamento soma os dois valores. “$12$.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301064';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$112$.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301065';

update public.question_solutions set final_answer_markdown='Permite calcular base mais índice escalado pelo tamanho do elemento.', explanation_markdown='Índice representa posição lógica e escala transforma em deslocamento em bytes. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Permite calcular base mais índice escalado pelo tamanho do elemento.” é a conclusão correta. “Elimina registradores.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Torna memória sequencial.” não decorre do princípio aplicável: Índice representa posição lógica e escala transforma em deslocamento em bytes. “Dispensa limites.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930107';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de endereçamento indexado: Por que indexado é adequado a vetor de palavras de 4 bytes?', sort_order=1 where id='70000000-0000-4000-8000-000009301071';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Índice representa posição lógica e escala transforma em deslocamento em bytes.', sort_order=2 where id='70000000-0000-4000-8000-000009301072';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Por que indexado é adequado a vetor de palavras de 4 bytes? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301073';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Elimina registradores.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Torna memória sequencial.” não decorre do princípio aplicável: Índice representa posição lógica e escala transforma em deslocamento em bytes. “Dispensa limites.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301074';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Permite calcular base mais índice escalado pelo tamanho do elemento.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301075';

update public.question_solutions set final_answer_markdown='SP.', explanation_markdown='Stack pointer acompanha a extremidade usada por push e pop. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “SP.” é a conclusão correta. “PC.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “IR.” não decorre do princípio aplicável: Stack pointer acompanha a extremidade usada por push e pop. “MAR.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930108';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de pilha: Qual registrador normalmente aponta o topo da pilha?', sort_order=1 where id='70000000-0000-4000-8000-000009301081';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Stack pointer acompanha a extremidade usada por push e pop.', sort_order=2 where id='70000000-0000-4000-8000-000009301082';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Qual registrador normalmente aponta o topo da pilha? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301083';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“PC.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “IR.” não decorre do princípio aplicável: Stack pointer acompanha a extremidade usada por push e pop. “MAR.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301084';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “SP.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301085';

update public.question_solutions set final_answer_markdown='O endereço de retorno.', explanation_markdown='Retorno deve saber onde continuar após o procedimento. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “O endereço de retorno.” é a conclusão correta. “A linha de cache inteira.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “A frequência do clock.” não decorre do princípio aplicável: Retorno deve saber onde continuar após o procedimento. “O opcode anterior.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930109';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de chamada: O que uma instrução CALL precisa preservar para permitir RET?', sort_order=1 where id='70000000-0000-4000-8000-000009301091';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Retorno deve saber onde continuar após o procedimento.', sort_order=2 where id='70000000-0000-4000-8000-000009301092';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, O que uma instrução CALL precisa preservar para permitir RET? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301093';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A linha de cache inteira.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “A frequência do clock.” não decorre do princípio aplicável: Retorno deve saber onde continuar após o procedimento. “O opcode anterior.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301094';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “O endereço de retorno.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301095';

update public.question_solutions set final_answer_markdown='Para preservar valores que o chamador espera manter.', explanation_markdown='Convenção define quais valores sobrevivem à chamada. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Para preservar valores que o chamador espera manter.” é a conclusão correta. “Para aumentar opcodes.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para evitar toda RAM.” não decorre do princípio aplicável: Convenção define quais valores sobrevivem à chamada. “Para atualizar TLB.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930110';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de convenção de chamada: Por que salvar registradores callee-saved ao entrar em uma função?', sort_order=1 where id='70000000-0000-4000-8000-000009301101';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Convenção define quais valores sobrevivem à chamada.', sort_order=2 where id='70000000-0000-4000-8000-000009301102';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Por que salvar registradores callee-saved ao entrar em uma função? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301103';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para aumentar opcodes.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para evitar toda RAM.” não decorre do princípio aplicável: Convenção define quais valores sobrevivem à chamada. “Para atualizar TLB.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301104';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para preservar valores que o chamador espera manter.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301105';

update public.question_solutions set final_answer_markdown='Uma condição ou flags produzidas por comparação.', explanation_markdown='O fluxo muda conforme resultado lógico da condição. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Uma condição ou flags produzidas por comparação.” é a conclusão correta. “A capacidade do SSD.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “A largura da ROM.” não decorre do princípio aplicável: O fluxo muda conforme resultado lógico da condição. “O caractere ASCII.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930111';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de desvio condicional: Que informação um branch condicional consulta?', sort_order=1 where id='70000000-0000-4000-8000-000009301111';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='O fluxo muda conforme resultado lógico da condição.', sort_order=2 where id='70000000-0000-4000-8000-000009301112';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Que informação um branch condicional consulta? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301113';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A capacidade do SSD.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “A largura da ROM.” não decorre do princípio aplicável: O fluxo muda conforme resultado lógico da condição. “O caractere ASCII.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301114';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Uma condição ou flags produzidas por comparação.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301115';

update public.question_solutions set final_answer_markdown='Para decidir se os operandos eram iguais.', explanation_markdown='Resultado zero de subtração indica igualdade numérica. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Para decidir se os operandos eram iguais.” é a conclusão correta. “Para limpar cache.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para endereçar RAM.” não decorre do princípio aplicável: Resultado zero de subtração indica igualdade numérica. “Para codificar opcode.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930112';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de flags: Após SUB R1,R2, por que uma flag zero pode ser útil?', sort_order=1 where id='70000000-0000-4000-8000-000009301121';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Resultado zero de subtração indica igualdade numérica.', sort_order=2 where id='70000000-0000-4000-8000-000009301122';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Após SUB R1,R2, por que uma flag zero pode ser útil? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301123';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para limpar cache.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para endereçar RAM.” não decorre do princípio aplicável: Resultado zero de subtração indica igualdade numérica. “Para codificar opcode.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301124';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para decidir se os operandos eram iguais.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301125';

update public.question_solutions set final_answer_markdown='O alvo é expresso em relação à posição atual.', explanation_markdown='Deslocamento relativo permanece válido ao mover bloco de código. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “O alvo é expresso em relação à posição atual.” é a conclusão correta. “Não precisa de instrução.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Usa endereço físico fixo.” não decorre do princípio aplicável: Deslocamento relativo permanece válido ao mover bloco de código. “Elimina linker.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930113';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de PC relativo: Qual vantagem de desvio PC-relative em código relocável?', sort_order=1 where id='70000000-0000-4000-8000-000009301131';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Deslocamento relativo permanece válido ao mover bloco de código.', sort_order=2 where id='70000000-0000-4000-8000-000009301132';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Qual vantagem de desvio PC-relative em código relocável? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301133';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Não precisa de instrução.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Usa endereço físico fixo.” não decorre do princípio aplicável: Deslocamento relativo permanece válido ao mover bloco de código. “Elimina linker.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301134';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “O alvo é expresso em relação à posição atual.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301135';

update public.question_solutions set final_answer_markdown='É um evento que transfere controle para tratamento especial.', explanation_markdown='Exceção interrompe fluxo normal para preservar controle seguro. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “É um evento que transfere controle para tratamento especial.” é a conclusão correta. “Nunca salva contexto.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “É sempre E/S.” não decorre do princípio aplicável: Exceção interrompe fluxo normal para preservar controle seguro. “Não altera fluxo.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930114';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de exceção: O que diferencia exceção de instrução comum?', sort_order=1 where id='70000000-0000-4000-8000-000009301141';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Exceção interrompe fluxo normal para preservar controle seguro.', sort_order=2 where id='70000000-0000-4000-8000-000009301142';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, O que diferencia exceção de instrução comum? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301143';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Nunca salva contexto.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “É sempre E/S.” não decorre do princípio aplicável: Exceção interrompe fluxo normal para preservar controle seguro. “Não altera fluxo.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301144';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “É um evento que transfere controle para tratamento especial.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301145';

update public.question_solutions set final_answer_markdown='Interrupção costuma ser externa e assíncrona; exceção decorre da execução.', explanation_markdown='Origem temporal distingue eventos externos de falhas internas. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Interrupção costuma ser externa e assíncrona; exceção decorre da execução.” é a conclusão correta. “Uma usa RAM e outra não.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Ambas são apenas saltos.” não decorre do princípio aplicável: Origem temporal distingue eventos externos de falhas internas. “Exceção sempre vem de disco.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930115';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de interrupção: Qual diferença típica entre interrupção e exceção?', sort_order=1 where id='70000000-0000-4000-8000-000009301151';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Origem temporal distingue eventos externos de falhas internas.', sort_order=2 where id='70000000-0000-4000-8000-000009301152';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Qual diferença típica entre interrupção e exceção? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301153';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Uma usa RAM e outra não.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Ambas são apenas saltos.” não decorre do princípio aplicável: Origem temporal distingue eventos externos de falhas internas. “Exceção sempre vem de disco.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301154';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Interrupção costuma ser externa e assíncrona; exceção decorre da execução.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301155';

update public.question_solutions set final_answer_markdown='Para impedir que programas controlem recursos globais sem mediação.', explanation_markdown='Proteção separa autoridade do SO de aplicações. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Para impedir que programas controlem recursos globais sem mediação.” é a conclusão correta. “Para reduzir bits do opcode.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para acelerar cache.” não decorre do princípio aplicável: Proteção separa autoridade do SO de aplicações. “Para mudar endianess.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930116';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de proteção: Por que instruções privilegiadas não podem rodar em modo usuário?', sort_order=1 where id='70000000-0000-4000-8000-000009301161';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Proteção separa autoridade do SO de aplicações.', sort_order=2 where id='70000000-0000-4000-8000-000009301162';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Por que instruções privilegiadas não podem rodar em modo usuário? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301163';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para reduzir bits do opcode.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para acelerar cache.” não decorre do princípio aplicável: Proteção separa autoridade do SO de aplicações. “Para mudar endianess.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301164';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para impedir que programas controlem recursos globais sem mediação.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301165';

update public.question_solutions set final_answer_markdown='Somente loads e stores acessam memória.', explanation_markdown='Operações aritméticas atuam em registradores. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Somente loads e stores acessam memória.” é a conclusão correta. “ALU sempre escreve RAM.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Não há registradores.” não decorre do princípio aplicável: Operações aritméticas atuam em registradores. “Desvios não existem.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930117';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de RISC: Qual é uma característica load/store?', sort_order=1 where id='70000000-0000-4000-8000-000009301171';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Operações aritméticas atuam em registradores.', sort_order=2 where id='70000000-0000-4000-8000-000009301172';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Qual é uma característica load/store? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301173';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“ALU sempre escreve RAM.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Não há registradores.” não decorre do princípio aplicável: Operações aritméticas atuam em registradores. “Desvios não existem.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301174';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Somente loads e stores acessam memória.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301175';

update public.question_solutions set final_answer_markdown='Decodificação e busca podem ser mais complexas.', explanation_markdown='Fronteiras de instrução variáveis exigem identificação adicional. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Decodificação e busca podem ser mais complexas.” é a conclusão correta. “Não podem acessar memória.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Não têm opcode.” não decorre do princípio aplicável: Fronteiras de instrução variáveis exigem identificação adicional. “Eliminam pipeline.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930118';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de CISC: Qual custo de instruções de tamanho variável?', sort_order=1 where id='70000000-0000-4000-8000-000009301181';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Fronteiras de instrução variáveis exigem identificação adicional.', sort_order=2 where id='70000000-0000-4000-8000-000009301182';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Qual custo de instruções de tamanho variável? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301183';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Não podem acessar memória.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Não têm opcode.” não decorre do princípio aplicável: Fronteiras de instrução variáveis exigem identificação adicional. “Eliminam pipeline.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301184';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Decodificação e busca podem ser mais complexas.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301185';

update public.question_solutions set final_answer_markdown='Para implementar instruções complexas por microoperações sequenciadas.', explanation_markdown='Microprograma controla passos internos de execução. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Para implementar instruções complexas por microoperações sequenciadas.” é a conclusão correta. “Para substituir toda ISA.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para remover controle.” não decorre do princípio aplicável: Microprograma controla passos internos de execução. “Para guardar arquivos.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930119';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de microcódigo: Quando microcódigo é útil?', sort_order=1 where id='70000000-0000-4000-8000-000009301191';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Microprograma controla passos internos de execução.', sort_order=2 where id='70000000-0000-4000-8000-000009301192';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Quando microcódigo é útil? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301193';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para substituir toda ISA.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para remover controle.” não decorre do princípio aplicável: Microprograma controla passos internos de execução. “Para guardar arquivos.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301194';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para implementar instruções complexas por microoperações sequenciadas.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301195';

update public.question_solutions set final_answer_markdown='Dependências falsas por reutilização de nome.', explanation_markdown='Nomes físicos distintos removem WAR e WAW artificiais. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Dependências falsas por reutilização de nome.” é a conclusão correta. “Dependência verdadeira RAW.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Falha de página.” não decorre do princípio aplicável: Nomes físicos distintos removem WAR e WAW artificiais. “Erro de paridade.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930120';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de renomeação: Que hazard a renomeação de registradores ajuda a eliminar?', sort_order=1 where id='70000000-0000-4000-8000-000009301201';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Nomes físicos distintos removem WAR e WAW artificiais.', sort_order=2 where id='70000000-0000-4000-8000-000009301202';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Que hazard a renomeação de registradores ajuda a eliminar? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301203';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Dependência verdadeira RAW.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Falha de página.” não decorre do princípio aplicável: Nomes físicos distintos removem WAR e WAW artificiais. “Erro de paridade.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301204';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Dependências falsas por reutilização de nome.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301205';

update public.question_solutions set final_answer_markdown='Para preservar estado arquitetural e exceções precisas.', explanation_markdown='Resultado interno pode ocorrer cedo; visibilidade deve respeitar programa. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Para preservar estado arquitetural e exceções precisas.” é a conclusão correta. “Para desacelerar ULA.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para eliminar registradores.” não decorre do princípio aplicável: Resultado interno pode ocorrer cedo; visibilidade deve respeitar programa. “Para impedir cache hit.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930121';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de fora de ordem: Por que execução fora de ordem ainda precisa aposentar instruções em ordem?', sort_order=1 where id='70000000-0000-4000-8000-000009301211';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Resultado interno pode ocorrer cedo; visibilidade deve respeitar programa.', sort_order=2 where id='70000000-0000-4000-8000-000009301212';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Por que execução fora de ordem ainda precisa aposentar instruções em ordem? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301213';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para desacelerar ULA.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Para eliminar registradores.” não decorre do princípio aplicável: Resultado interno pode ocorrer cedo; visibilidade deve respeitar programa. “Para impedir cache hit.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301214';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para preservar estado arquitetural e exceções precisas.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301215';

update public.question_solutions set final_answer_markdown='Uma instrução opera sobre vários dados em paralelo.', explanation_markdown='Dados independentes podem compartilhar a mesma operação. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Uma instrução opera sobre vários dados em paralelo.” é a conclusão correta. “Muitos opcodes sequenciais.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Muitos discos.” não decorre do princípio aplicável: Dados independentes podem compartilhar a mesma operação. “Apenas uma palavra.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930122';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de SIMD: O que SIMD explora?', sort_order=1 where id='70000000-0000-4000-8000-000009301221';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Dados independentes podem compartilhar a mesma operação.', sort_order=2 where id='70000000-0000-4000-8000-000009301222';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, O que SIMD explora? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301223';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Muitos opcodes sequenciais.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Muitos discos.” não decorre do princípio aplicável: Dados independentes podem compartilhar a mesma operação. “Apenas uma palavra.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301224';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Uma instrução opera sobre vários dados em paralelo.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301225';

update public.question_solutions set final_answer_markdown='Entrega resultado a estágio consumidor antes de escrevê-lo no registrador.', explanation_markdown='Encaminhamento reduz espera em dependências específicas. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Entrega resultado a estágio consumidor antes de escrevê-lo no registrador.” é a conclusão correta. “Grava no SSD.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Remove dependência verdadeira.” não decorre do princípio aplicável: Encaminhamento reduz espera em dependências específicas. “Prevê desvio.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930123';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de pipeline: O que forwarding faz?', sort_order=1 where id='70000000-0000-4000-8000-000009301231';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Encaminhamento reduz espera em dependências específicas.', sort_order=2 where id='70000000-0000-4000-8000-000009301232';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, O que forwarding faz? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301233';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Grava no SSD.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Remove dependência verdadeira.” não decorre do princípio aplicável: Encaminhamento reduz espera em dependências específicas. “Prevê desvio.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301234';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Entrega resultado a estágio consumidor antes de escrevê-lo no registrador.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301235';

update public.question_solutions set final_answer_markdown='Não necessariamente; melhora principalmente throughput após enchimento.', explanation_markdown='Sobreposição beneficia sequência, mas cada estágio ainda consome tempo. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Não necessariamente; melhora principalmente throughput após enchimento.” é a conclusão correta. “Sempre reduz a latência a um quinto.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Elimina clock.” não decorre do princípio aplicável: Sobreposição beneficia sequência, mas cada estágio ainda consome tempo. “Não sobrepõe etapas.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930124';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de CPI: Pipeline ideal de cinco estágios reduz tempo de uma única instrução?', sort_order=1 where id='70000000-0000-4000-8000-000009301241';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Sobreposição beneficia sequência, mas cada estágio ainda consome tempo.', sort_order=2 where id='70000000-0000-4000-8000-000009301242';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Pipeline ideal de cinco estágios reduz tempo de uma única instrução? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301243';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Sempre reduz a latência a um quinto.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Elimina clock.” não decorre do princípio aplicável: Sobreposição beneficia sequência, mas cada estágio ainda consome tempo. “Não sobrepõe etapas.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301244';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Não necessariamente; melhora principalmente throughput após enchimento.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301245';

update public.question_solutions set final_answer_markdown='Evitar descarte de trabalho buscado no caminho errado.', explanation_markdown='Predição correta mantém pipeline no fluxo útil. No caso apresentado, Modele explicitamente o estado e o endereço envolvidos. A conclusão deve preservar os efeitos definidos pela instrução. Logo, “Evitar descarte de trabalho buscado no caminho errado.” é a conclusão correta. “Aumentar tamanho da RAM.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Corrigir memória.” não decorre do princípio aplicável: Predição correta mantém pipeline no fluxo útil. “Eliminar PC.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.' where question_id='40000000-0000-4000-8000-000000930125';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de previsão de desvio: Qual benefício de um preditor acertar um desvio?', sort_order=1 where id='70000000-0000-4000-8000-000009301251';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Predição correta mantém pipeline no fluxo útil.', sort_order=2 where id='70000000-0000-4000-8000-000009301252';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Modele explicitamente o estado e o endereço envolvidos. No enunciado, Qual benefício de um preditor acertar um desvio? A conclusão deve preservar os efeitos definidos pela instrução.', sort_order=3 where id='70000000-0000-4000-8000-000009301253';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Aumentar tamanho da RAM.” não cumpre o critério técnico do caso: A conclusão deve preservar os efeitos definidos pela instrução. “Corrigir memória.” não decorre do princípio aplicável: Predição correta mantém pipeline no fluxo útil. “Eliminar PC.” deixa de executar a análise necessária: Modele explicitamente o estado e o endereço envolvidos.', sort_order=4 where id='70000000-0000-4000-8000-000009301254';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Evitar descarte de trabalho buscado no caminho errado.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301255';

commit;
