-- Arquitetura de Computadores: revisão de gabaritos, lote 03.
-- Atualiza apenas soluções e passos; tentativas e alternativas são preservadas.
begin;

update public.question_solutions set final_answer_markdown='$overline A+overline B$', explanation_markdown='A lei de De Morgan troca AND por OR ao negar cada operando. No caso apresentado, Aplique a negação a toda a conjunção. A tabela-verdade confirma igualdade em todos os casos. Logo, “$overline A+overline B$” é a conclusão correta. “$overline Acdotoverline B$” não cumpre o critério técnico do caso: A tabela-verdade confirma igualdade em todos os casos. “$A+B$” não decorre do princípio aplicável: A lei de De Morgan troca AND por OR ao negar cada operando. “$Acdot B$” deixa de executar a análise necessária: Aplique a negação a toda a conjunção.' where question_id='40000000-0000-4000-8000-000000930051';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de álgebra booleana: Qual expressão equivale a $overline{Acdot B}$?', sort_order=1 where id='70000000-0000-4000-8000-000009300511';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='A lei de De Morgan troca AND por OR ao negar cada operando.', sort_order=2 where id='70000000-0000-4000-8000-000009300512';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Aplique a negação a toda a conjunção. No enunciado, Qual expressão equivale a $overline{Acdot B}$? A tabela-verdade confirma igualdade em todos os casos.', sort_order=3 where id='70000000-0000-4000-8000-000009300513';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$overline Acdotoverline B$” não cumpre o critério técnico do caso: A tabela-verdade confirma igualdade em todos os casos. “$A+B$” não decorre do princípio aplicável: A lei de De Morgan troca AND por OR ao negar cada operando. “$Acdot B$” deixa de executar a análise necessária: Aplique a negação a toda a conjunção.', sort_order=4 where id='70000000-0000-4000-8000-000009300514';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$overline A+overline B$”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300515';

update public.question_solutions set final_answer_markdown='$A$', explanation_markdown='Fatoração produz $A(B+overline B)$. No caso apresentado, Use complementaridade dentro dos parênteses. $B+overline B=1$, restando $A$. Logo, “$A$” é a conclusão correta. “$B$” não cumpre o critério técnico do caso: $B+overline B=1$, restando $A$. “$Acdot B$” não decorre do princípio aplicável: Fatoração produz $A(B+overline B)$. “$1$” deixa de executar a análise necessária: Use complementaridade dentro dos parênteses.' where question_id='40000000-0000-4000-8000-000000930052';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de álgebra booleana: Simplifique $Acdot B+Acdotoverline B$.', sort_order=1 where id='70000000-0000-4000-8000-000009300521';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Fatoração produz $A(B+overline B)$.', sort_order=2 where id='70000000-0000-4000-8000-000009300522';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Use complementaridade dentro dos parênteses. No enunciado, Simplifique $Acdot B+Acdotoverline B$. $B+overline B=1$, restando $A$.', sort_order=3 where id='70000000-0000-4000-8000-000009300523';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$B$” não cumpre o critério técnico do caso: $B+overline B=1$, restando $A$. “$Acdot B$” não decorre do princípio aplicável: Fatoração produz $A(B+overline B)$. “$1$” deixa de executar a análise necessária: Use complementaridade dentro dos parênteses.', sort_order=4 where id='70000000-0000-4000-8000-000009300524';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$A$”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300525';

update public.question_solutions set final_answer_markdown='Quando as entradas são diferentes.', explanation_markdown='XOR representa desigualdade entre dois bits. No caso apresentado, Compare os quatro pares possíveis de entrada. Apenas $01$ e $10$ ativam a saída. Logo, “Quando as entradas são diferentes.” é a conclusão correta. “Quando ambas são $1$.” não cumpre o critério técnico do caso: Apenas $01$ e $10$ ativam a saída. “Quando ambas são $0$.” não decorre do princípio aplicável: XOR representa desigualdade entre dois bits. “Quando o clock sobe.” deixa de executar a análise necessária: Compare os quatro pares possíveis de entrada.' where question_id='40000000-0000-4000-8000-000000930053';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de portas lógicas: Quando uma porta XOR de duas entradas produz $1$?', sort_order=1 where id='70000000-0000-4000-8000-000009300531';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='XOR representa desigualdade entre dois bits.', sort_order=2 where id='70000000-0000-4000-8000-000009300532';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare os quatro pares possíveis de entrada. No enunciado, Quando uma porta XOR de duas entradas produz $1$? Apenas $01$ e $10$ ativam a saída.', sort_order=3 where id='70000000-0000-4000-8000-000009300533';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Quando ambas são $1$.” não cumpre o critério técnico do caso: Apenas $01$ e $10$ ativam a saída. “Quando ambas são $0$.” não decorre do princípio aplicável: XOR representa desigualdade entre dois bits. “Quando o clock sobe.” deixa de executar a análise necessária: Compare os quatro pares possíveis de entrada.', sort_order=4 where id='70000000-0000-4000-8000-000009300534';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Quando as entradas são diferentes.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300535';

update public.question_solutions set final_answer_markdown='Porque combinações de NAND implementam NOT, AND e OR.', explanation_markdown='Funcionalidade universal vem de poder construir um conjunto funcionalmente completo. No caso apresentado, Comece construindo NOT com entradas NAND unidas. Depois de NOT, De Morgan permite formar AND e OR. Logo, “Porque combinações de NAND implementam NOT, AND e OR.” é a conclusão correta. “Porque armazena um bit.” não cumpre o critério técnico do caso: Depois de NOT, De Morgan permite formar AND e OR. “Porque só aceita uma entrada.” não decorre do princípio aplicável: Funcionalidade universal vem de poder construir um conjunto funcionalmente completo. “Porque substitui o clock.” deixa de executar a análise necessária: Comece construindo NOT com entradas NAND unidas.' where question_id='40000000-0000-4000-8000-000000930054';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de portas universais: Por que NAND é considerada porta universal?', sort_order=1 where id='70000000-0000-4000-8000-000009300541';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Funcionalidade universal vem de poder construir um conjunto funcionalmente completo.', sort_order=2 where id='70000000-0000-4000-8000-000009300542';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Comece construindo NOT com entradas NAND unidas. No enunciado, Por que NAND é considerada porta universal? Depois de NOT, De Morgan permite formar AND e OR.', sort_order=3 where id='70000000-0000-4000-8000-000009300543';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Porque armazena um bit.” não cumpre o critério técnico do caso: Depois de NOT, De Morgan permite formar AND e OR. “Porque só aceita uma entrada.” não decorre do princípio aplicável: Funcionalidade universal vem de poder construir um conjunto funcionalmente completo. “Porque substitui o clock.” deixa de executar a análise necessária: Comece construindo NOT com entradas NAND unidas.', sort_order=4 where id='70000000-0000-4000-8000-000009300544';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Porque combinações de NAND implementam NOT, AND e OR.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300545';

update public.question_solutions set final_answer_markdown='São logicamente equivalentes.', explanation_markdown='Equivalência lógica depende da função, não da implementação física. No caso apresentado, Compare tabelas-verdade ou simplifique as expressões. Mesmo comportamento não garante custo ou atraso iguais. Logo, “São logicamente equivalentes.” é a conclusão correta. “Têm a mesma quantidade de portas.” não cumpre o critério técnico do caso: Mesmo comportamento não garante custo ou atraso iguais. “Possuem o mesmo atraso.” não decorre do princípio aplicável: Equivalência lógica depende da função, não da implementação física. “Usam a mesma tecnologia física.” deixa de executar a análise necessária: Compare tabelas-verdade ou simplifique as expressões.' where question_id='40000000-0000-4000-8000-000000930055';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de equivalência de circuitos: Dois circuitos têm expressões diferentes, mas mesma saída para todas as entradas. Qual conclusão é válida?', sort_order=1 where id='70000000-0000-4000-8000-000009300551';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Equivalência lógica depende da função, não da implementação física.', sort_order=2 where id='70000000-0000-4000-8000-000009300552';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare tabelas-verdade ou simplifique as expressões. No enunciado, Dois circuitos têm expressões diferentes, mas mesma saída para todas as entradas. Qual conclusão é válida? Mesmo comportamento não garante custo ou atraso iguais.', sort_order=3 where id='70000000-0000-4000-8000-000009300553';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Têm a mesma quantidade de portas.” não cumpre o critério técnico do caso: Mesmo comportamento não garante custo ou atraso iguais. “Possuem o mesmo atraso.” não decorre do princípio aplicável: Equivalência lógica depende da função, não da implementação física. “Usam a mesma tecnologia física.” deixa de executar a análise necessária: Compare tabelas-verdade ou simplifique as expressões.', sort_order=4 where id='70000000-0000-4000-8000-000009300554';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “São logicamente equivalentes.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300555';

update public.question_solutions set final_answer_markdown='Encaminhar uma entre oito entradas para uma saída.', explanation_markdown='Linhas de seleção escolhem qual entrada aparece na saída. No caso apresentado, Observe se o bloco escolhe, expande ou armazena informação. Um MUX concentra várias fontes em um destino. Logo, “Encaminhar uma entre oito entradas para uma saída.” é a conclusão correta. “Decodificar uma entrada em oito saídas.” não cumpre o critério técnico do caso: Um MUX concentra várias fontes em um destino. “Somar oito operandos.” não decorre do princípio aplicável: Linhas de seleção escolhem qual entrada aparece na saída. “Guardar oito bits.” deixa de executar a análise necessária: Observe se o bloco escolhe, expande ou armazena informação.' where question_id='40000000-0000-4000-8000-000000930056';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de multiplexador: Qual é a função de um multiplexador $8:1$?', sort_order=1 where id='70000000-0000-4000-8000-000009300561';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Linhas de seleção escolhem qual entrada aparece na saída.', sort_order=2 where id='70000000-0000-4000-8000-000009300562';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Observe se o bloco escolhe, expande ou armazena informação. No enunciado, Qual é a função de um multiplexador $8:1$? Um MUX concentra várias fontes em um destino.', sort_order=3 where id='70000000-0000-4000-8000-000009300563';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Decodificar uma entrada em oito saídas.” não cumpre o critério técnico do caso: Um MUX concentra várias fontes em um destino. “Somar oito operandos.” não decorre do princípio aplicável: Linhas de seleção escolhem qual entrada aparece na saída. “Guardar oito bits.” deixa de executar a análise necessária: Observe se o bloco escolhe, expande ou armazena informação.', sort_order=4 where id='70000000-0000-4000-8000-000009300564';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Encaminhar uma entre oito entradas para uma saída.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300565';

update public.question_solutions set final_answer_markdown='$4$', explanation_markdown='$n$ seletores distinguem $2^n$ entradas. No caso apresentado, Resolva $2^n=16$. Quatro bits codificam dezesseis escolhas. Logo, “$4$” é a conclusão correta. “$2$” não cumpre o critério técnico do caso: Quatro bits codificam dezesseis escolhas. “$8$” não decorre do princípio aplicável: $n$ seletores distinguem $2^n$ entradas. “$16$” deixa de executar a análise necessária: Resolva $2^n=16$.' where question_id='40000000-0000-4000-8000-000000930057';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de decodificador: Quantas linhas de seleção são necessárias para um multiplexador $16:1$?', sort_order=1 where id='70000000-0000-4000-8000-000009300571';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='$n$ seletores distinguem $2^n$ entradas.', sort_order=2 where id='70000000-0000-4000-8000-000009300572';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Resolva $2^n=16$. No enunciado, Quantas linhas de seleção são necessárias para um multiplexador $16:1$? Quatro bits codificam dezesseis escolhas.', sort_order=3 where id='70000000-0000-4000-8000-000009300573';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$2$” não cumpre o critério técnico do caso: Quatro bits codificam dezesseis escolhas. “$8$” não decorre do princípio aplicável: $n$ seletores distinguem $2^n$ entradas. “$16$” deixa de executar a análise necessária: Resolva $2^n=16$.', sort_order=4 where id='70000000-0000-4000-8000-000009300574';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$4$”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300575';

update public.question_solutions set final_answer_markdown='Soma $0$ e carry $1$.', explanation_markdown='Soma é XOR; carry é AND. No caso apresentado, Avalie as duas portas para o par $11$. $1oplus1=0$ e $1cdot1=1$. Logo, “Soma $0$ e carry $1$.” é a conclusão correta. “Soma $1$ e carry $0$.” não cumpre o critério técnico do caso: $1oplus1=0$ e $1cdot1=1$. “Soma $1$ e carry $1$.” não decorre do princípio aplicável: Soma é XOR; carry é AND. “Soma $0$ e carry $0$.” deixa de executar a análise necessária: Avalie as duas portas para o par $11$.' where question_id='40000000-0000-4000-8000-000000930058';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de meio somador: Para entradas $A=1$ e $B=1$, quais são soma e carry de um meio somador?', sort_order=1 where id='70000000-0000-4000-8000-000009300581';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Soma é XOR; carry é AND.', sort_order=2 where id='70000000-0000-4000-8000-000009300582';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Avalie as duas portas para o par $11$. No enunciado, Para entradas $A=1$ e $B=1$, quais são soma e carry de um meio somador? $1oplus1=0$ e $1cdot1=1$.', sort_order=3 where id='70000000-0000-4000-8000-000009300583';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Soma $1$ e carry $0$.” não cumpre o critério técnico do caso: $1oplus1=0$ e $1cdot1=1$. “Soma $1$ e carry $1$.” não decorre do princípio aplicável: Soma é XOR; carry é AND. “Soma $0$ e carry $0$.” deixa de executar a análise necessária: Avalie as duas portas para o par $11$.', sort_order=4 where id='70000000-0000-4000-8000-000009300584';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Soma $0$ e carry $1$.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300585';

update public.question_solutions set final_answer_markdown='Para somar também o transporte vindo da posição menos significativa.', explanation_markdown='Em palavras multibit, cada coluna pode receber transporte da anterior. No caso apresentado, Considere a soma de três bits: dois operandos e carry-in. Sem carry-in, o circuito falha em cadeias de soma. Logo, “Para somar também o transporte vindo da posição menos significativa.” é a conclusão correta. “Para guardar resultados antigos.” não cumpre o critério técnico do caso: Sem carry-in, o circuito falha em cadeias de soma. “Para inverter o operando.” não decorre do princípio aplicável: Em palavras multibit, cada coluna pode receber transporte da anterior. “Para escolher o clock.” deixa de executar a análise necessária: Considere a soma de três bits: dois operandos e carry-in.' where question_id='40000000-0000-4000-8000-000000930059';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de somador completo: Por que um somador completo precisa de entrada de carry?', sort_order=1 where id='70000000-0000-4000-8000-000009300591';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Em palavras multibit, cada coluna pode receber transporte da anterior.', sort_order=2 where id='70000000-0000-4000-8000-000009300592';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Considere a soma de três bits: dois operandos e carry-in. No enunciado, Por que um somador completo precisa de entrada de carry? Sem carry-in, o circuito falha em cadeias de soma.', sort_order=3 where id='70000000-0000-4000-8000-000009300593';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para guardar resultados antigos.” não cumpre o critério técnico do caso: Sem carry-in, o circuito falha em cadeias de soma. “Para inverter o operando.” não decorre do princípio aplicável: Em palavras multibit, cada coluna pode receber transporte da anterior. “Para escolher o clock.” deixa de executar a análise necessária: Considere a soma de três bits: dois operandos e carry-in.', sort_order=4 where id='70000000-0000-4000-8000-000009300594';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para somar também o transporte vindo da posição menos significativa.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300595';

update public.question_solutions set final_answer_markdown='Se um operando é maior, igual ou menor que o outro.', explanation_markdown='Comparação é circuito combinacional sem estado persistente. No caso apresentado, Identifique a relação pedida entre os dois números. As três relações cobrem todos os resultados de comparação. Logo, “Se um operando é maior, igual ou menor que o outro.” é a conclusão correta. “A próxima instrução.” não cumpre o critério técnico do caso: As três relações cobrem todos os resultados de comparação. “Uma linha de cache.” não decorre do princípio aplicável: Comparação é circuito combinacional sem estado persistente. “Um endereço físico.” deixa de executar a análise necessária: Identifique a relação pedida entre os dois números.' where question_id='40000000-0000-4000-8000-000000930060';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de comparador: Que saída um comparador de magnitude pode fornecer?', sort_order=1 where id='70000000-0000-4000-8000-000009300601';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Comparação é circuito combinacional sem estado persistente.', sort_order=2 where id='70000000-0000-4000-8000-000009300602';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique a relação pedida entre os dois números. No enunciado, Que saída um comparador de magnitude pode fornecer? As três relações cobrem todos os resultados de comparação.', sort_order=3 where id='70000000-0000-4000-8000-000009300603';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A próxima instrução.” não cumpre o critério técnico do caso: As três relações cobrem todos os resultados de comparação. “Uma linha de cache.” não decorre do princípio aplicável: Comparação é circuito combinacional sem estado persistente. “Um endereço físico.” deixa de executar a análise necessária: Identifique a relação pedida entre os dois números.', sort_order=4 where id='70000000-0000-4000-8000-000009300604';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Se um operando é maior, igual ou menor que o outro.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300605';

update public.question_solutions set final_answer_markdown='Para definir qual entrada determina a saída.', explanation_markdown='Um codificador comum pressupõe uma entrada ativa; prioridade resolve concorrência. No caso apresentado, Pergunte como o circuito deve reagir a múltiplas solicitações. A regra de prioridade torna a saída determinística. Logo, “Para definir qual entrada determina a saída.” é a conclusão correta. “Para armazenar a entrada mais antiga.” não cumpre o critério técnico do caso: A regra de prioridade torna a saída determinística. “Para gerar clock.” não decorre do princípio aplicável: Um codificador comum pressupõe uma entrada ativa; prioridade resolve concorrência. “Para corrigir erro de memória.” deixa de executar a análise necessária: Pergunte como o circuito deve reagir a múltiplas solicitações.' where question_id='40000000-0000-4000-8000-000000930061';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de codificador: Um codificador de prioridade recebe duas entradas ativas. Por que a prioridade é necessária?', sort_order=1 where id='70000000-0000-4000-8000-000009300611';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Um codificador comum pressupõe uma entrada ativa; prioridade resolve concorrência.', sort_order=2 where id='70000000-0000-4000-8000-000009300612';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Pergunte como o circuito deve reagir a múltiplas solicitações. No enunciado, Um codificador de prioridade recebe duas entradas ativas. Por que a prioridade é necessária? A regra de prioridade torna a saída determinística.', sort_order=3 where id='70000000-0000-4000-8000-000009300613';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para armazenar a entrada mais antiga.” não cumpre o critério técnico do caso: A regra de prioridade torna a saída determinística. “Para gerar clock.” não decorre do princípio aplicável: Um codificador comum pressupõe uma entrada ativa; prioridade resolve concorrência. “Para corrigir erro de memória.” deixa de executar a análise necessária: Pergunte como o circuito deve reagir a múltiplas solicitações.', sort_order=4 where id='70000000-0000-4000-8000-000009300614';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para definir qual entrada determina a saída.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300615';

update public.question_solutions set final_answer_markdown='Aumenta o atraso de propagação.', explanation_markdown='Cada porta precisa de tempo para estabilizar após alteração na entrada. No caso apresentado, Some conceitualmente atrasos ao longo do caminho crítico. Mais níveis em série normalmente alongam o caminho crítico. Logo, “Aumenta o atraso de propagação.” é a conclusão correta. “A saída ganha memória.” não cumpre o critério técnico do caso: Mais níveis em série normalmente alongam o caminho crítico. “O clock deixa de existir.” não decorre do princípio aplicável: Cada porta precisa de tempo para estabilizar após alteração na entrada. “A função deixa de ser booleana.” deixa de executar a análise necessária: Some conceitualmente atrasos ao longo do caminho crítico.' where question_id='40000000-0000-4000-8000-000000930062';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de atraso combinacional: Ao aumentar a quantidade de níveis lógicos em um circuito combinacional, qual efeito tende a ocorrer?', sort_order=1 where id='70000000-0000-4000-8000-000009300621';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Cada porta precisa de tempo para estabilizar após alteração na entrada.', sort_order=2 where id='70000000-0000-4000-8000-000009300622';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Some conceitualmente atrasos ao longo do caminho crítico. No enunciado, Ao aumentar a quantidade de níveis lógicos em um circuito combinacional, qual efeito tende a ocorrer? Mais níveis em série normalmente alongam o caminho crítico.', sort_order=3 where id='70000000-0000-4000-8000-000009300623';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A saída ganha memória.” não cumpre o critério técnico do caso: Mais níveis em série normalmente alongam o caminho crítico. “O clock deixa de existir.” não decorre do princípio aplicável: Cada porta precisa de tempo para estabilizar após alteração na entrada. “A função deixa de ser booleana.” deixa de executar a análise necessária: Some conceitualmente atrasos ao longo do caminho crítico.', sort_order=4 where id='70000000-0000-4000-8000-000009300624';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Aumenta o atraso de propagação.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300625';

update public.question_solutions set final_answer_markdown='Definir quando o estado é amostrado ou atualizado.', explanation_markdown='Elementos sequenciais sincronizam mudanças de estado com eventos de clock. No caso apresentado, Diferencie o sinal de tempo dos sinais de dados. O clock coordena, mas não contém o dado armazenado. Logo, “Definir quando o estado é amostrado ou atualizado.” é a conclusão correta. “Transportar dados entre RAM e disco.” não cumpre o critério técnico do caso: O clock coordena, mas não contém o dado armazenado. “Escolher um opcode.” não decorre do princípio aplicável: Elementos sequenciais sincronizam mudanças de estado com eventos de clock. “Eliminar hazards combinacionais.” deixa de executar a análise necessária: Diferencie o sinal de tempo dos sinais de dados.' where question_id='40000000-0000-4000-8000-000000930063';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de clock: Qual é o papel do clock em um circuito sequencial?', sort_order=1 where id='70000000-0000-4000-8000-000009300631';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Elementos sequenciais sincronizam mudanças de estado com eventos de clock.', sort_order=2 where id='70000000-0000-4000-8000-000009300632';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Diferencie o sinal de tempo dos sinais de dados. No enunciado, Qual é o papel do clock em um circuito sequencial? O clock coordena, mas não contém o dado armazenado.', sort_order=3 where id='70000000-0000-4000-8000-000009300633';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Transportar dados entre RAM e disco.” não cumpre o critério técnico do caso: O clock coordena, mas não contém o dado armazenado. “Escolher um opcode.” não decorre do princípio aplicável: Elementos sequenciais sincronizam mudanças de estado com eventos de clock. “Eliminar hazards combinacionais.” deixa de executar a análise necessária: Diferencie o sinal de tempo dos sinais de dados.', sort_order=4 where id='70000000-0000-4000-8000-000009300634';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Definir quando o estado é amostrado ou atualizado.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300635';

update public.question_solutions set final_answer_markdown='Copia D para Q.', explanation_markdown='Flip-flop D amostra seu dado na borda e o mantém até nova borda. No caso apresentado, Observe D imediatamente no evento ativo. Q passa a refletir a amostra de D. Logo, “Copia D para Q.” é a conclusão correta. “Inverte Q sempre.” não cumpre o critério técnico do caso: Q passa a refletir a amostra de D. “Soma D a Q.” não decorre do princípio aplicável: Flip-flop D amostra seu dado na borda e o mantém até nova borda. “Zera todas as saídas.” deixa de executar a análise necessária: Observe D imediatamente no evento ativo.' where question_id='40000000-0000-4000-8000-000000930064';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de flip-flop D: Na borda ativa do clock, o que um flip-flop D faz?', sort_order=1 where id='70000000-0000-4000-8000-000009300641';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Flip-flop D amostra seu dado na borda e o mantém até nova borda.', sort_order=2 where id='70000000-0000-4000-8000-000009300642';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Observe D imediatamente no evento ativo. No enunciado, Na borda ativa do clock, o que um flip-flop D faz? Q passa a refletir a amostra de D.', sort_order=3 where id='70000000-0000-4000-8000-000009300643';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Inverte Q sempre.” não cumpre o critério técnico do caso: Q passa a refletir a amostra de D. “Soma D a Q.” não decorre do princípio aplicável: Flip-flop D amostra seu dado na borda e o mantém até nova borda. “Zera todas as saídas.” deixa de executar a análise necessária: Observe D imediatamente no evento ativo.', sort_order=4 where id='70000000-0000-4000-8000-000009300644';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Copia D para Q.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300645';

update public.question_solutions set final_answer_markdown='O latch pode acompanhar a entrada durante um nível ativo.', explanation_markdown='Latch é sensível a nível; flip-flop, tipicamente, a transição de borda. No caso apresentado, Compare uma janela de transparência com um instante de amostragem. A janela do latch pode permitir alterações enquanto está habilitado. Logo, “O latch pode acompanhar a entrada durante um nível ativo.” é a conclusão correta. “O flip-flop não armazena bits.” não cumpre o critério técnico do caso: A janela do latch pode permitir alterações enquanto está habilitado. “O latch não usa controle.” não decorre do princípio aplicável: Latch é sensível a nível; flip-flop, tipicamente, a transição de borda. “Ambos só funcionam sem clock.” deixa de executar a análise necessária: Compare uma janela de transparência com um instante de amostragem.' where question_id='40000000-0000-4000-8000-000000930065';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de latch e flip-flop: Qual diferença prática distingue latch transparente de flip-flop sensível à borda?', sort_order=1 where id='70000000-0000-4000-8000-000009300651';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Latch é sensível a nível; flip-flop, tipicamente, a transição de borda.', sort_order=2 where id='70000000-0000-4000-8000-000009300652';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare uma janela de transparência com um instante de amostragem. No enunciado, Qual diferença prática distingue latch transparente de flip-flop sensível à borda? A janela do latch pode permitir alterações enquanto está habilitado.', sort_order=3 where id='70000000-0000-4000-8000-000009300653';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“O flip-flop não armazena bits.” não cumpre o critério técnico do caso: A janela do latch pode permitir alterações enquanto está habilitado. “O latch não usa controle.” não decorre do princípio aplicável: Latch é sensível a nível; flip-flop, tipicamente, a transição de borda. “Ambos só funcionam sem clock.” deixa de executar a análise necessária: Compare uma janela de transparência com um instante de amostragem.', sort_order=4 where id='70000000-0000-4000-8000-000009300654';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “O latch pode acompanhar a entrada durante um nível ativo.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300655';

update public.question_solutions set final_answer_markdown='Metastabilidade ou valor amostrado imprevisível.', explanation_markdown='O dado deve permanecer estável antes e após a borda para ser amostrado com segurança. No caso apresentado, Relacione a mudança de D ao instante de clock. Violação temporal não é uma operação lógica válida do circuito. Logo, “Metastabilidade ou valor amostrado imprevisível.” é a conclusão correta. “A ULA faz overflow.” não cumpre o critério técnico do caso: Violação temporal não é uma operação lógica válida do circuito. “A cache sofre miss.” não decorre do princípio aplicável: O dado deve permanecer estável antes e após a borda para ser amostrado com segurança. “O endereço vira imediato.” deixa de executar a análise necessária: Relacione a mudança de D ao instante de clock.' where question_id='40000000-0000-4000-8000-000000930066';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de setup e hold: Qual risco existe se D mudar durante a janela de setup/hold de um flip-flop?', sort_order=1 where id='70000000-0000-4000-8000-000009300661';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='O dado deve permanecer estável antes e após a borda para ser amostrado com segurança.', sort_order=2 where id='70000000-0000-4000-8000-000009300662';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Relacione a mudança de D ao instante de clock. No enunciado, Qual risco existe se D mudar durante a janela de setup/hold de um flip-flop? Violação temporal não é uma operação lógica válida do circuito.', sort_order=3 where id='70000000-0000-4000-8000-000009300663';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“A ULA faz overflow.” não cumpre o critério técnico do caso: Violação temporal não é uma operação lógica válida do circuito. “A cache sofre miss.” não decorre do princípio aplicável: O dado deve permanecer estável antes e após a borda para ser amostrado com segurança. “O endereço vira imediato.” deixa de executar a análise necessária: Relacione a mudança de D ao instante de clock.', sort_order=4 where id='70000000-0000-4000-8000-000009300664';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Metastabilidade ou valor amostrado imprevisível.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300665';

update public.question_solutions set final_answer_markdown='$32$', explanation_markdown='Cada flip-flop D armazena um bit. No caso apresentado, Associe a largura da palavra à quantidade de bits guardados. Um flip-flop por bit preserva a palavra inteira. Logo, “$32$” é a conclusão correta. “$16$” não cumpre o critério técnico do caso: Um flip-flop por bit preserva a palavra inteira. “$8$” não decorre do princípio aplicável: Cada flip-flop D armazena um bit. “$64$” deixa de executar a análise necessária: Associe a largura da palavra à quantidade de bits guardados.' where question_id='40000000-0000-4000-8000-000000930067';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de registradores: Quantos flip-flops D são necessários para armazenar uma palavra de 32 bits?', sort_order=1 where id='70000000-0000-4000-8000-000009300671';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Cada flip-flop D armazena um bit.', sort_order=2 where id='70000000-0000-4000-8000-000009300672';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Associe a largura da palavra à quantidade de bits guardados. No enunciado, Quantos flip-flops D são necessários para armazenar uma palavra de 32 bits? Um flip-flop por bit preserva a palavra inteira.', sort_order=3 where id='70000000-0000-4000-8000-000009300673';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$16$” não cumpre o critério técnico do caso: Um flip-flop por bit preserva a palavra inteira. “$8$” não decorre do princípio aplicável: Cada flip-flop D armazena um bit. “$64$” deixa de executar a análise necessária: Associe a largura da palavra à quantidade de bits guardados.', sort_order=4 where id='70000000-0000-4000-8000-000009300674';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$32$”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300675';

update public.question_solutions set final_answer_markdown='Cada bit move-se para a posição vizinha à direita.', explanation_markdown='Estágios sequenciais transferem o conteúdo entre si a cada clock. No caso apresentado, Acompanhe o sentido indicado e a posição que recebe novo bit. O conteúdo anterior de cada estágio alimenta o próximo. Logo, “Cada bit move-se para a posição vizinha à direita.” é a conclusão correta. “Todos os bits são somados.” não cumpre o critério técnico do caso: O conteúdo anterior de cada estágio alimenta o próximo. “A memória vira ROM.” não decorre do princípio aplicável: Estágios sequenciais transferem o conteúdo entre si a cada clock. “O PC é zerado.” deixa de executar a análise necessária: Acompanhe o sentido indicado e a posição que recebe novo bit.' where question_id='40000000-0000-4000-8000-000000930068';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de registrador de deslocamento: O que ocorre em um registrador de deslocamento à direita após um pulso?', sort_order=1 where id='70000000-0000-4000-8000-000009300681';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Estágios sequenciais transferem o conteúdo entre si a cada clock.', sort_order=2 where id='70000000-0000-4000-8000-000009300682';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Acompanhe o sentido indicado e a posição que recebe novo bit. No enunciado, O que ocorre em um registrador de deslocamento à direita após um pulso? O conteúdo anterior de cada estágio alimenta o próximo.', sort_order=3 where id='70000000-0000-4000-8000-000009300683';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Todos os bits são somados.” não cumpre o critério técnico do caso: O conteúdo anterior de cada estágio alimenta o próximo. “A memória vira ROM.” não decorre do princípio aplicável: Estágios sequenciais transferem o conteúdo entre si a cada clock. “O PC é zerado.” deixa de executar a análise necessária: Acompanhe o sentido indicado e a posição que recebe novo bit.', sort_order=4 where id='70000000-0000-4000-8000-000009300684';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Cada bit move-se para a posição vizinha à direita.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300685';

update public.question_solutions set final_answer_markdown='$0000_2$.', explanation_markdown='Contador de largura fixa opera módulo $2^n$. No caso apresentado, Some um e descarte o carry que excede quatro bits. $16$ não cabe em quatro bits, ocorrendo retorno a zero. Logo, “$0000_2$.” é a conclusão correta. “$1111_2$.” não cumpre o critério técnico do caso: $16$ não cabe em quatro bits, ocorrendo retorno a zero. “$0001_2$.” não decorre do princípio aplicável: Contador de largura fixa opera módulo $2^n$. “$10000_2$.” deixa de executar a análise necessária: Some um e descarte o carry que excede quatro bits.' where question_id='40000000-0000-4000-8000-000000930069';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de contador: Um contador binário de 4 bits parte de $1111_2$ e incrementa uma vez. Sem lógica extra, qual estado segue?', sort_order=1 where id='70000000-0000-4000-8000-000009300691';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Contador de largura fixa opera módulo $2^n$.', sort_order=2 where id='70000000-0000-4000-8000-000009300692';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Some um e descarte o carry que excede quatro bits. No enunciado, Um contador binário de 4 bits parte de $1111_2$ e incrementa uma vez. Sem lógica extra, qual estado segue? $16$ não cabe em quatro bits, ocorrendo retorno a zero.', sort_order=3 where id='70000000-0000-4000-8000-000009300693';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$1111_2$.” não cumpre o critério técnico do caso: $16$ não cabe em quatro bits, ocorrendo retorno a zero. “$0001_2$.” não decorre do princípio aplicável: Contador de largura fixa opera módulo $2^n$. “$10000_2$.” deixa de executar a análise necessária: Some um e descarte o carry que excede quatro bits.', sort_order=4 where id='70000000-0000-4000-8000-000009300694';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$0000_2$.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300695';

update public.question_solutions set final_answer_markdown='RAM comum perde conteúdo sem energia; ROM preserva seu conteúdo.', explanation_markdown='Volatilidade se refere à retenção de dados sem alimentação. No caso apresentado, Compare o comportamento após desligar o sistema. A distinção não depende do tipo de dado guardado. Logo, “RAM comum perde conteúdo sem energia; ROM preserva seu conteúdo.” é a conclusão correta. “ROM é sempre mais rápida.” não cumpre o critério técnico do caso: A distinção não depende do tipo de dado guardado. “RAM não aceita endereços.” não decorre do princípio aplicável: Volatilidade se refere à retenção de dados sem alimentação. “ROM não armazena instruções.” deixa de executar a análise necessária: Compare o comportamento após desligar o sistema.' where question_id='40000000-0000-4000-8000-000000930070';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de RAM e ROM: Qual afirmação diferencia RAM e ROM de modo essencial?', sort_order=1 where id='70000000-0000-4000-8000-000009300701';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Volatilidade se refere à retenção de dados sem alimentação.', sort_order=2 where id='70000000-0000-4000-8000-000009300702';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Compare o comportamento após desligar o sistema. No enunciado, Qual afirmação diferencia RAM e ROM de modo essencial? A distinção não depende do tipo de dado guardado.', sort_order=3 where id='70000000-0000-4000-8000-000009300703';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“ROM é sempre mais rápida.” não cumpre o critério técnico do caso: A distinção não depende do tipo de dado guardado. “RAM não aceita endereços.” não decorre do princípio aplicável: Volatilidade se refere à retenção de dados sem alimentação. “ROM não armazena instruções.” deixa de executar a análise necessária: Compare o comportamento após desligar o sistema.', sort_order=4 where id='70000000-0000-4000-8000-000009300704';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “RAM comum perde conteúdo sem energia; ROM preserva seu conteúdo.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300705';

update public.question_solutions set final_answer_markdown='$1024$ bytes.', explanation_markdown='$1K$ posições, cada uma com 8 bits, equivale a um byte por posição. No caso apresentado, Multiplique quantidade de palavras pela largura em bytes. $1024	imes1$ byte resulta em $1024$ bytes. Logo, “$1024$ bytes.” é a conclusão correta. “$8$ bytes.” não cumpre o critério técnico do caso: $1024	imes1$ byte resulta em $1024$ bytes. “$8192$ bytes.” não decorre do princípio aplicável: $1K$ posições, cada uma com 8 bits, equivale a um byte por posição. “$512$ bytes.” deixa de executar a análise necessária: Multiplique quantidade de palavras pela largura em bytes.' where question_id='40000000-0000-4000-8000-000000930071';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de chip de memória: Um chip $1K	imes8$ armazena quantos bytes?', sort_order=1 where id='70000000-0000-4000-8000-000009300711';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='$1K$ posições, cada uma com 8 bits, equivale a um byte por posição.', sort_order=2 where id='70000000-0000-4000-8000-000009300712';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Multiplique quantidade de palavras pela largura em bytes. No enunciado, Um chip $1K	imes8$ armazena quantos bytes? $1024	imes1$ byte resulta em $1024$ bytes.', sort_order=3 where id='70000000-0000-4000-8000-000009300713';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$8$ bytes.” não cumpre o critério técnico do caso: $1024	imes1$ byte resulta em $1024$ bytes. “$8192$ bytes.” não decorre do princípio aplicável: $1K$ posições, cada uma com 8 bits, equivale a um byte por posição. “$512$ bytes.” deixa de executar a análise necessária: Multiplique quantidade de palavras pela largura em bytes.', sort_order=4 where id='70000000-0000-4000-8000-000009300714';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$1024$ bytes.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300715';

update public.question_solutions set final_answer_markdown='$8$', explanation_markdown='São necessários quatro bancos de endereços e dois chips em paralelo por palavra. No caso apresentado, Separe expansão de profundidade ($4K/1K$) e largura ($16/8$). $4	imes2=8$ chips atendem ambos os requisitos. Logo, “$8$” é a conclusão correta. “$2$” não cumpre o critério técnico do caso: $4	imes2=8$ chips atendem ambos os requisitos. “$4$” não decorre do princípio aplicável: São necessários quatro bancos de endereços e dois chips em paralelo por palavra. “$16$” deixa de executar a análise necessária: Separe expansão de profundidade ($4K/1K$) e largura ($16/8$).' where question_id='40000000-0000-4000-8000-000000930072';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de composição de memória: Para construir memória $4K	imes16$ usando chips $1K	imes8$, quantos chips são necessários?', sort_order=1 where id='70000000-0000-4000-8000-000009300721';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='São necessários quatro bancos de endereços e dois chips em paralelo por palavra.', sort_order=2 where id='70000000-0000-4000-8000-000009300722';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Separe expansão de profundidade ($4K/1K$) e largura ($16/8$). No enunciado, Para construir memória $4K	imes16$ usando chips $1K	imes8$, quantos chips são necessários? $4	imes2=8$ chips atendem ambos os requisitos.', sort_order=3 where id='70000000-0000-4000-8000-000009300723';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“$2$” não cumpre o critério técnico do caso: $4	imes2=8$ chips atendem ambos os requisitos. “$4$” não decorre do princípio aplicável: São necessários quatro bancos de endereços e dois chips em paralelo por palavra. “$16$” deixa de executar a análise necessária: Separe expansão de profundidade ($4K/1K$) e largura ($16/8$).', sort_order=4 where id='70000000-0000-4000-8000-000009300724';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “$8$”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300725';

update public.question_solutions set final_answer_markdown='Ativar o dispositivo cujo intervalo de endereços foi selecionado.', explanation_markdown='O endereço identifica o destino; o decodificador gera o sinal de seleção. No caso apresentado, Siga o endereço desde o barramento até o chip selecionado. Só o dispositivo correspondente deve responder à transação. Logo, “Ativar o dispositivo cujo intervalo de endereços foi selecionado.” é a conclusão correta. “Converter dados em instruções.” não cumpre o critério técnico do caso: Só o dispositivo correspondente deve responder à transação. “Aumentar a largura do barramento.” não decorre do princípio aplicável: O endereço identifica o destino; o decodificador gera o sinal de seleção. “Sincronizar flip-flops.” deixa de executar a análise necessária: Siga o endereço desde o barramento até o chip selecionado.' where question_id='40000000-0000-4000-8000-000000930073';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de decodificação de endereço: Qual é a função de um decodificador de endereço para periféricos?', sort_order=1 where id='70000000-0000-4000-8000-000009300731';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='O endereço identifica o destino; o decodificador gera o sinal de seleção.', sort_order=2 where id='70000000-0000-4000-8000-000009300732';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Siga o endereço desde o barramento até o chip selecionado. No enunciado, Qual é a função de um decodificador de endereço para periféricos? Só o dispositivo correspondente deve responder à transação.', sort_order=3 where id='70000000-0000-4000-8000-000009300733';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Converter dados em instruções.” não cumpre o critério técnico do caso: Só o dispositivo correspondente deve responder à transação. “Aumentar a largura do barramento.” não decorre do princípio aplicável: O endereço identifica o destino; o decodificador gera o sinal de seleção. “Sincronizar flip-flops.” deixa de executar a análise necessária: Siga o endereço desde o barramento até o chip selecionado.', sort_order=4 where id='70000000-0000-4000-8000-000009300734';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Ativar o dispositivo cujo intervalo de endereços foi selecionado.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300735';

update public.question_solutions set final_answer_markdown='Quantos bits podem ser transferidos em paralelo por transação.', explanation_markdown='Barramento de dados carrega conteúdo; sua largura define o tamanho do caminho. No caso apresentado, Diferencie largura de dados de quantidade de linhas de endereço. Mais bits por transferência não altera sozinho a capacidade endereçável. Logo, “Quantos bits podem ser transferidos em paralelo por transação.” é a conclusão correta. “Quantos endereços existem.” não cumpre o critério técnico do caso: Mais bits por transferência não altera sozinho a capacidade endereçável. “Qual é a ISA.” não decorre do princípio aplicável: Barramento de dados carrega conteúdo; sua largura define o tamanho do caminho. “A quantidade de registradores.” deixa de executar a análise necessária: Diferencie largura de dados de quantidade de linhas de endereço.' where question_id='40000000-0000-4000-8000-000000930074';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de barramento: O que a largura de um barramento de dados determina diretamente?', sort_order=1 where id='70000000-0000-4000-8000-000009300741';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Barramento de dados carrega conteúdo; sua largura define o tamanho do caminho.', sort_order=2 where id='70000000-0000-4000-8000-000009300742';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Diferencie largura de dados de quantidade de linhas de endereço. No enunciado, O que a largura de um barramento de dados determina diretamente? Mais bits por transferência não altera sozinho a capacidade endereçável.', sort_order=3 where id='70000000-0000-4000-8000-000009300743';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Quantos endereços existem.” não cumpre o critério técnico do caso: Mais bits por transferência não altera sozinho a capacidade endereçável. “Qual é a ISA.” não decorre do princípio aplicável: Barramento de dados carrega conteúdo; sua largura define o tamanho do caminho. “A quantidade de registradores.” deixa de executar a análise necessária: Diferencie largura de dados de quantidade de linhas de endereço.', sort_order=4 where id='70000000-0000-4000-8000-000009300744';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Quantos bits podem ser transferidos em paralelo por transação.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300745';

update public.question_solutions set final_answer_markdown='Para reduzir risco de metastabilidade e eventos mal amostrados.', explanation_markdown='Domínios temporais diferentes não garantem setup/hold entre si. No caso apresentado, Relacione a chegada imprevisível do sinal à borda do clock local. Sincronizadores dão tempo para resolver estados instáveis. Logo, “Para reduzir risco de metastabilidade e eventos mal amostrados.” é a conclusão correta. “Para aumentar o tamanho da ROM.” não cumpre o critério técnico do caso: Sincronizadores dão tempo para resolver estados instáveis. “Para evitar complemento de dois.” não decorre do princípio aplicável: Domínios temporais diferentes não garantem setup/hold entre si. “Para eliminar o barramento.” deixa de executar a análise necessária: Relacione a chegada imprevisível do sinal à borda do clock local.' where question_id='40000000-0000-4000-8000-000000930075';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de sincronização: Por que sinais assíncronos devem ser sincronizados antes de entrar em lógica de clock único?', sort_order=1 where id='70000000-0000-4000-8000-000009300751';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Domínios temporais diferentes não garantem setup/hold entre si.', sort_order=2 where id='70000000-0000-4000-8000-000009300752';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Relacione a chegada imprevisível do sinal à borda do clock local. No enunciado, Por que sinais assíncronos devem ser sincronizados antes de entrar em lógica de clock único? Sincronizadores dão tempo para resolver estados instáveis.', sort_order=3 where id='70000000-0000-4000-8000-000009300753';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para aumentar o tamanho da ROM.” não cumpre o critério técnico do caso: Sincronizadores dão tempo para resolver estados instáveis. “Para evitar complemento de dois.” não decorre do princípio aplicável: Domínios temporais diferentes não garantem setup/hold entre si. “Para eliminar o barramento.” deixa de executar a análise necessária: Relacione a chegada imprevisível do sinal à borda do clock local.', sort_order=4 where id='70000000-0000-4000-8000-000009300754';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para reduzir risco de metastabilidade e eventos mal amostrados.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009300755';

commit;
