-- Bloco 3: reescreve somente dicas e passos das questões MC 67 a 100.
-- Enunciados, alternativas, gabaritos, tags e explicações permanecem intactos.
begin;

create temporary table c1_block_03_steps (
  question_id uuid primary key, hints text[] not null, titles text[] not null, steps text[] not null
) on commit drop;

insert into c1_block_03_steps values
('00000042-0000-4000-8000-000000006700',array['Compare o grau 1 do numerador com o grau 2 do denominador.','Divida a fração inteira por $x^2$, a maior potência presente.','Quando $x$ cresce, confirme que os termos com $1/x$ desaparecem.'],array['Compare os graus','Normalize pela maior potência','Simplifique o numerador','Observe o denominador','Tome o limite'],array['O numerador $3x+1$ tem grau 1 e o denominador $x^2+1$ tem grau 2.','Dividindo ambos por $x^2$, obtemos $(3/x+1/x^2)/(1+1/x^2)$.','No numerador, $3/x$ e $1/x^2$ tendem a zero.','O denominador tende a $1$.','Assim, a razão tende a $0$.']),
('00000042-0000-4000-8000-000000006800',array['Examine os dois lados de $c$, pois o denominador troca de sinal ali.','Para $x<c$, $x-c$ é negativo; para $x>c$, é positivo.','Um limite finito exigiria o mesmo número nos dois lados.'],array['Fixe o ponto c','Aproxime-se pela esquerda','Aproxime-se pela direita','Compare os comportamentos','Decida a existência'],array['A função é $1/(x-c)$.','Quando $x$ se aproxima de $c$ pela esquerda, $x-c$ é um número negativo muito pequeno e a fração tende a $-\infty$.','Pela direita, o denominador é positivo muito pequeno e a fração tende a $+\infty$.','Os comportamentos laterais não coincidem e não são finitos.','Isso ocorre para todo $c$, então não há nenhum valor que satisfaça a condição.']),
('00000042-0000-4000-8000-000000006900',array['A lei da soma vale quando os limites envolvidos existem.','Pense em separar uma expressão como $f(x)+g(x)$ em dois comportamentos próximos do ponto.','Não confunda essa lei algébrica com regra da cadeia, que é de derivadas.'],array['Reconheça a operação','Escreva a lei correspondente','Separe os dois limites','Some os resultados','Nomeie a propriedade'],array['Para limites existentes, vale $\lim(f(x)+g(x))=\lim f(x)+\lim g(x)$.','A operação no interior é uma soma.','Cada parcela pode ser analisada separadamente.','Depois, somamos os dois limites obtidos.','Essa propriedade é a lei da soma dos limites.']),
('00000042-0000-4000-8000-000000007000',array['A substituição direta produz $0/0$, então use o conjugado da raiz.','Multiplique por $\sqrt{x}+2$ no numerador e no denominador.','Depois do cancelamento, avalie a expressão simplificada em 4.'],array['Teste a substituição','Escolha o conjugado','Racionalize o numerador','Cancele o fator comum','Avalie o limite'],array['Em $x=4$, temos $(2-2)/(4-4)$, ou seja, $0/0$.','Multiplicamos por $(\sqrt{x}+2)/(\sqrt{x}+2)$.','O numerador passa a ser $x-4$.','Cancelando $x-4$, sobra $1/(\sqrt{x}+2)$.','Substituindo $x=4$, obtemos $1/(2+2)=1/4$.']),
('00000042-0000-4000-8000-000000007100',array['O Teorema do Confronto precisa de uma função entre duas outras.','As funções que limitam por baixo e por cima devem tender ao mesmo número.','Nesse caso, a função central não tem outro valor possível para o limite.'],array['Organize as três funções','Escreva as desigualdades','Compare os limites externos','Aplique o aprisionamento','Conclua sobre a função central'],array['O teorema parte de uma relação como $g(x)\le f(x)\le h(x)$ perto do ponto.','As funções $g$ e $h$ limitam a função central.','Se ambas tendem ao mesmo número $L$, elas apertam $f$ em torno de $L$.','Não resta espaço para $f$ tender a um valor diferente.','Portanto, a condição é duas funções limitarem uma terceira e terem o mesmo limite.']),
('00000042-0000-4000-8000-000000007200',array['Polinômios são contínuos em todos os números reais.','Substitua $-1$ na potência cúbica, preservando o sinal dentro dos parênteses.','Lembre que uma potência ímpar mantém o sinal negativo.'],array['Use a continuidade do polinômio','Substitua o ponto','Calcule a potência ímpar','Leia o sinal do resultado','Registre o limite'],array['A função $x^3$ é polinomial e contínua em $-1$.','Então o limite é obtido por substituição direta: $(-1)^3$.','Como o expoente é ímpar, o resultado é $-1$.','Não há indeterminação nem restrição de domínio.','Logo, $\lim_{x\to-1}x^3=-1$.']),
('00000042-0000-4000-8000-000000007300',array['Avalie $|x|/x$ separadamente em valores negativos e positivos.','Para $x<0$, $|x|=-x$; para $x>0$, $|x|=x$.','Compare as duas aproximações de zero antes de afirmar um limite.'],array['Separe os dois lados de zero','Calcule o ramo negativo','Calcule o ramo positivo','Compare os limites laterais','Classifique o comportamento'],array['Se $x<0$, então $|x|=-x$ e $|x|/x=-1$.','Se $x>0$, então $|x|=x$ e $|x|/x=1$.','Assim, pela esquerda a função se aproxima de $-1$.','Pela direita, aproxima-se de $1$.','Há um salto entre $-1$ e $1$ em zero, portanto o limite bilateral não existe.']),
('00000042-0000-4000-8000-000000007400',array['Compare o crescimento do logaritmo com o crescimento linear de $x$.','Divida numerador e denominador por $x$ não simplifica o logaritmo; use a hierarquia de crescimento.','O logaritmo cresce sem limite, mas muito mais devagar que uma função linear.'],array['Identifique os crescimentos','Compare logaritmo e reta','Observe o quociente','Use a taxa relativa','Conclua o limite'],array['Tanto $\ln x$ quanto $x$ crescem quando $x\to\infty$.','Porém $\ln x$ cresce mais lentamente que qualquer potência positiva de $x$, inclusive $x$.','Assim, o denominador aumenta muito mais rapidamente que o numerador.','A razão $\ln x/x$ fica cada vez menor e positiva.','Portanto seu limite é $0$.']),
('00000042-0000-4000-8000-000000007500',array['A soma, o produto e o quociente de contínuas preservam continuidade quando são definidos.','Verifique a condição especial do quociente: o denominador não pode zerar em $a$.','Use a hipótese $g(a)\ne0$ diretamente.'],array['Liste as hipóteses','Use a continuidade de f e g','Examine o denominador','Aplique a regra do quociente','Responda à afirmação'],array['As funções $f$ e $g$ são contínuas em $a$.','O enunciado também garante $g(a)\ne0$.','Logo, a divisão por $g(a)$ é válida nesse ponto.','A regra do quociente de funções contínuas se aplica.','Assim, $f/g$ é contínua em $a$.']),
('00000042-0000-4000-8000-000000007600',array['Na regra da potência, o expoente vem para frente e diminui uma unidade.','Aplique a regra somente ao termo $x^5$.','Cheque que o novo expoente é $4$, não $5$.'],array['Identifique a potência','Traga o expoente como coeficiente','Reduza o expoente','Escreva a derivada','Cheque a regra'],array['A função é $x^5$.','Pela regra da potência, $d(x^n)/dx=nx^{n-1}$.','Com $n=5$, o coeficiente é $5$.','O expoente passa de $5$ para $4$.','Portanto, a derivada é $5x^4$.']),
('00000042-0000-4000-8000-000000007700',array['Derive cada termo do polinômio separadamente.','No termo $3x^2$, o 3 permanece como coeficiente.','A derivada da constante $-4x$ é $-4$.'],array['Separe os termos','Derive o quadrático','Mantenha o coeficiente','Derive o termo linear','Some as derivadas'],array['A expressão é $3x^2-4x$.','Para $3x^2$, a regra da potência dá $3\cdot2x=6x$.','Para $-4x$, a derivada é $-4$.','Não há termo constante adicional.','Somando, obtemos $6x-4$.']),
('00000042-0000-4000-8000-000000007800',array['Uma constante não varia quando $x$ muda.','Use a definição de derivada: a diferença de uma constante com ela mesma é zero.','Não confunda o valor 7 da função com sua taxa de variação.'],array['Observe a função constante','Compare dois valores próximos','Calcule a variação','Divida pela variação de x','Conclua a derivada'],array['A função vale $7$ para qualquer valor de $x$.','Assim, $f(x+h)-f(x)=7-7=0$.','A razão de variação é $0/h$, para $h\ne0$.','Seu limite também é zero.','Logo, $d(7)/dx=0$.']),
('00000042-0000-4000-8000-000000007900',array['Reescreva $1/x$ como $x^{-1}$ para aplicar a regra da potência.','Multiplique o expoente $-1$ por $x^{-2}$.','A forma final pode voltar a ser escrita como fração.'],array['Troque para expoente negativo','Aplique a regra da potência','Reduza o expoente','Converta para fração','Verifique o sinal'],array['Temos $1/x=x^{-1}$.','A derivada é $-1\cdot x^{-2}$.','Isso simplifica para $-x^{-2}$.','Como $x^{-2}=1/x^2$, escrevemos $-1/x^2$.','O sinal negativo é indispensável porque o expoente original era negativo.']),
('00000042-0000-4000-8000-000000008000',array['Escreva a raiz como potência $x^{1/2}$.','A regra da potência reduz $1/2$ para $-1/2$.','Converta $x^{-1/2}$ de volta para uma raiz no denominador.'],array['Reescreva a raiz','Aplique o expoente fracionário','Calcule o novo expoente','Use o coeficiente um meio','Retorne à forma radical'],array['A raiz quadrada é $\sqrt{x}=x^{1/2}$.','Derivando, temos $(1/2)x^{-1/2}$.','O expoente negativo indica que a potência vai para o denominador.','Como $x^{1/2}=\sqrt{x}$, resulta $1/(2\sqrt{x})$.','Essa é a derivada para $x>0$.']),
('00000042-0000-4000-8000-000000008100',array['A exponencial de base $e$ é uma função cuja derivada é ela mesma.','Não multiplique por $x$; isso seria confundir com derivada de um produto.','Compare a função inicial e a expressão derivada.'],array['Reconheça a exponencial natural','Aplique a regra específica','Mantenha a base e o expoente','Evite fator extra','Registre a igualdade'],array['A função é $e^x$.','A regra fundamental informa que $d(e^x)/dx=e^x$.','A base $e$ torna essa derivada especialmente simples.','Não aparece um fator $x$ fora da exponencial.','Logo, a derivada continua sendo $e^x$.']),
('00000042-0000-4000-8000-000000008200',array['A derivada de $\ln x$ vem da taxa de variação do logaritmo natural.','A fórmula é válida no domínio real positivo do logaritmo.','Não derive como se $\ln x$ fosse uma potência de $x$.'],array['Identifique o logaritmo natural','Recorde seu domínio','Aplique a fórmula conhecida','Mantenha x no denominador','Conclua a derivada'],array['A função é $\ln x$, definida para $x>0$.','Sua derivada fundamental é $1/x$.','O resultado diminui à medida que $x$ cresce.','Não é correto manter $\ln x$ nem elevar $x$ ao quadrado.','Portanto, $d(\ln x)/dx=1/x$.']),
('00000042-0000-4000-8000-000000008300',array['Para seno, a derivada troca para cosseno sem sinal negativo.','Compare com a regra do cosseno, que é a que produz sinal negativo.','O argumento é apenas $x$, então não há fator de cadeia.'],array['Reconheça a função seno','Use a regra trigonométrica','Cheque o sinal','Observe o argumento simples','Escreva a derivada'],array['A função a derivar é $\sin x$.','A regra básica é $d(\sin x)/dx=\cos x$.','O sinal negativo pertence à derivada de $\cos x$, não a esta.','Como o argumento é $x$, sua derivada é 1.','Logo, o resultado é $\cos x$.']),
('00000042-0000-4000-8000-000000008400',array['A derivada de cosseno inclui um sinal negativo.','Diferencie cosseno de seno: são regras parecidas, mas não iguais.','O argumento $x$ não acrescenta nenhum fator.'],array['Identifique o cosseno','Recorde a regra com sinal','Aplique ao argumento x','Evite trocar por seno positivo','Conclua a expressão'],array['A função é $\cos x$.','Sua derivada é $-\sin x$.','O sinal negativo faz parte da regra trigonométrica.','Como a derivada do argumento $x$ é 1, nada mais é multiplicado.','Portanto, $d(\cos x)/dx=-\sin x$.']),
('00000042-0000-4000-8000-000000008500',array['Derive $x^3$ e $x^{-2}$ de forma independente.','No segundo termo, o expoente negativo produz coeficiente negativo e diminui para $-3$.','Mantenha os expoentes negativos até terminar; depois decida se quer usar frações.'],array['Separe as duas potências','Derive o termo cúbico','Derive a potência negativa','Some os resultados','Cheque expoentes e sinais'],array['A derivada de $x^3$ é $3x^2$.','Para $x^{-2}$, a regra da potência dá $-2x^{-3}$.','O expoente passa de $-2$ para $-3$.','Somamos as derivadas dos termos.','Assim, o resultado é $3x^2-2x^{-3}$.']),
('00000042-0000-4000-8000-000000008600',array['Reescreva a raiz cúbica como $x^{1/3}$.','O coeficiente externo 4 permanece e multiplica o expoente $1/3$.','O expoente resultante é negativo e corresponde a um denominador.'],array['Converta a raiz cúbica','Mantenha o coeficiente 4','Aplique a regra da potência','Transforme o expoente negativo','Apresente a fração'],array['Temos $4x^{1/3}$.','A derivada de $x^{1/3}$ é $(1/3)x^{-2/3}$.','Multiplicando pelo coeficiente 4, obtemos $(4/3)x^{-2/3}$.','Como $x^{-2/3}=1/x^{2/3}$, a potência vai para o denominador.','Logo, a derivada é $4/(3x^{2/3})$.']),
('00000042-0000-4000-8000-000000008700',array['O fator constante $1/4$ acompanha a derivada de $x^4$.','Derive $x^4$ antes de simplificar o produto.','O 4 que aparece pela regra cancela o denominador 4.'],array['Isole o fator constante','Derive a potência quarta','Multiplique os coeficientes','Cancele os fatores 4','Escreva o resultado'],array['A função pode ser lida como $(1/4)x^4$.','A derivada de $x^4$ é $4x^3$.','Multiplicando pelo fator externo, temos $(1/4)\cdot4x^3$.','Os fatores 4 se cancelam.','Portanto, a derivada é $x^3$.']),
('00000042-0000-4000-8000-000000008800',array['Uma constante somada ou subtraída desaparece ao derivar.','Aplique a regra da potência apenas ao termo $2x^3$.','Não mantenha o $-5$ na resposta, pois sua derivada é zero.'],array['Separe termo variável e constante','Derive o cubo','Multiplique pelo coeficiente','Derive a constante','Simplifique a soma'],array['A expressão é $2x^3-5$.','A derivada de $x^3$ é $3x^2$.','Com o coeficiente 2, obtemos $6x^2$.','A derivada da constante $-5$ é zero.','Assim, a derivada total é $6x^2$.']),
('00000042-0000-4000-8000-000000008900',array['Primeiro encontre a função derivada; só depois use $x=3$.','A constante 1 desaparece ao derivar $x^2+1$.','Substitua 3 em $2x$, não na função original.'],array['Derive antes de avaliar','Elimine a constante','Obtenha a expressão derivada','Substitua x por 3','Calcule a taxa pontual'],array['Para $f(x)=x^2+1$, temos $f''(x)=2x$.','O termo constante 1 contribui com zero para a derivada.','Agora avaliamos a derivada no ponto pedido.','$f''(3)=2\cdot3=6$.','Portanto, a taxa instantânea em $x=3$ é $6$.']),
('00000042-0000-4000-8000-000000009000',array['Derive a expressão inteira antes de substituir $x=1$.','A derivada de $-3x$ é $-3$.','Depois da derivação, os dois termos devem se cancelar no ponto indicado.'],array['Aplique a regra da potência','Derive o termo linear','Monte a derivada','Avalie no ponto 1','Verifique o cancelamento'],array['Para $x^3-3x$, a derivada de $x^3$ é $3x^2$.','A derivada de $-3x$ é $-3$.','Logo, $f''(x)=3x^2-3$.','Em $x=1$, temos $3\cdot1^2-3=0$.','Assim, a derivada no ponto é $0$.']),
('00000042-0000-4000-8000-000000009100',array['A derivada de tangente pode ser lembrada pela identidade entre secante e cosseno.','A regra correta envolve secante ao quadrado.','Não eleve a própria tangente ao quadrado.'],array['Identifique a tangente','Recorde a regra trigonométrica','Escreva a secante ao quadrado','Diferencie do distrator comum','Conclua a derivada'],array['A função é $\tan x$.','A regra de derivação é $d(\tan x)/dx=\sec^2x$.','O quadrado incide sobre a secante.','A expressão $\tan^2x$ não é a derivada de tangente.','Portanto, o resultado é $\sec^2x$.']),
('00000042-0000-4000-8000-000000009200',array['A derivada de secante é um produto de secante e tangente.','Não confunda com a derivada de tangente, que é $\sec^2x$.','O argumento simples $x$ não adiciona fator extra.'],array['Reconheça a secante','Use a fórmula específica','Escreva os dois fatores','Compare com a regra da tangente','Finalize a derivada'],array['A função dada é $\sec x$.','Sua derivada é $\sec x\tan x$.','Ela é um produto, não uma soma e nem apenas uma potência de secante.','A regra $\sec^2x$ pertence a $\tan x$.','Logo, $d(\sec x)/dx=\sec x\tan x$.']),
('00000042-0000-4000-8000-000000009300',array['O logaritmo de base 10 pode ser reescrito com logaritmo natural.','Use $\log_{10}x=\ln x/\ln10$.','Como $\ln10$ é constante, ele permanece no denominador.'],array['Mude a base do logaritmo','Isole o fator constante','Derive ln x','Mantenha ln 10 fixo','Escreva a fração final'],array['Pela mudança de base, $\log_{10}x=\ln x/\ln10$.','O número $\ln10$ é uma constante.','A derivada do numerador $\ln x$ é $1/x$.','Então a derivada é $(1/x)/\ln10$.','Simplificando, obtemos $1/(x\ln10)$.']),
('00000042-0000-4000-8000-000000009400',array['Aplique a regra da potência com expoente fracionário $7/2$.','O novo expoente será $7/2-1$.','Subtraia 1 escrevendo-o como $2/2$.'],array['Identifique o expoente fracionário','Traga o expoente à frente','Subtraia uma unidade','Simplifique a fração do expoente','Registre a derivada'],array['A função é $x^{7/2}$.','O coeficiente da derivada é $7/2$.','O novo expoente é $7/2-1=7/2-2/2=5/2$.','Portanto a potência restante é $x^{5/2}$.','A derivada é $(7/2)x^{5/2}$.']),
('00000042-0000-4000-8000-000000009500',array['Um expoente negativo ainda segue a regra da potência.','Multiplique o expoente $-4$ e reduza-o para $-5$.','O sinal negativo vem do próprio coeficiente $-4$.'],array['Leia o expoente negativo','Aplique a regra geral','Diminua o expoente','Mantenha o coeficiente negativo','Conclua a forma potência'],array['Temos $x^{-4}$.','A regra da potência fornece $-4x^{-4-1}$.','Calculando o expoente, resulta $-4x^{-5}$.','O sinal não desaparece ao derivar.','Logo, a derivada é $-4x^{-5}$.']),
('00000042-0000-4000-8000-000000009600',array['A derivada de uma função linear $ax+b$ é o coeficiente $a$.','O termo constante $-9$ não contribui para a taxa de variação.','Verifique que a reta sobe 5 unidades para cada unidade horizontal.'],array['Separe coeficiente e constante','Aplique a regra linear','Elimine a constante','Interprete a inclinação','Informe a derivada'],array['A função é $5x-9$.','A derivada de $5x$ é $5$.','A derivada de $-9$ é zero.','Assim, a taxa de variação é constante e igual ao coeficiente angular da reta.','Portanto, $d(5x-9)/dx=5$.']),
('00000042-0000-4000-8000-000000009700',array['Fatore ou derive o quadrático antes de avaliar em $x=4$.','A derivada de $x^2-2x+1$ é $2x-2$.','Só então substitua o ponto indicado.'],array['Derive o polinômio','Trate cada termo','Monte a derivada','Avalie em x igual a 4','Calcule o valor numérico'],array['A derivada de $x^2$ é $2x$.','A derivada de $-2x$ é $-2$ e a de $1$ é zero.','Assim, $f''(x)=2x-2$.','Em $x=4$, temos $2\cdot4-2=6$.','Logo, a derivada no ponto é $6$.']),
('00000042-0000-4000-8000-000000009800',array['Escreva a raiz quinta como $x^{1/5}$.','Ao derivar, $1/5-1=-4/5$.','Use o expoente negativo para colocar a potência no denominador.'],array['Converta a potência fracionária','Aplique a regra','Subtraia uma unidade','Reescreva o expoente negativo','Forme o denominador'],array['A função é $x^{1/5}$.','Sua derivada é $(1/5)x^{1/5-1}$.','O expoente fica $-4/5$.','Logo temos $(1/5)x^{-4/5}=1/(5x^{4/5})$.','Essa é a expressão correta da derivada.']),
('00000042-0000-4000-8000-000000009900',array['Use a regra da soma para derivar seno e termo linear separadamente.','A derivada de seno é cosseno, e a de $x$ é 1.','Some os dois resultados, sem manter o $x$ original.'],array['Separe a soma','Derive o seno','Derive o termo linear','Some as derivadas','Escreva a expressão final'],array['A função é $\sin x+x$.','A derivada de $\sin x$ é $\cos x$.','A derivada de $x$ é $1$.','Pela regra da soma, adicionamos os dois resultados.','Portanto, a derivada é $\cos x+1$.']),
('00000042-0000-4000-8000-000000010000',array['A regra da soma permite derivar a exponencial e o logaritmo separadamente.','Use $d(e^x)/dx=e^x$ e $d(\ln x)/dx=1/x$.','O domínio da parcela logarítmica exige $x>0$.'],array['Observe as duas parcelas','Derive a exponencial','Derive o logaritmo','Some os resultados','Cheque o domínio'],array['A função é $e^x+\ln x$.','A derivada de $e^x$ permanece $e^x$.','A derivada de $\ln x$ é $1/x$.','Somando, obtemos $e^x+1/x$.','A fórmula é considerada no domínio $x>0$, onde o logaritmo está definido.']);

delete from public.question_hints where question_id in (select question_id from c1_block_03_steps);
delete from public.question_solution_steps where question_id in (select question_id from c1_block_03_steps);

insert into public.question_hints (id,question_id,content_markdown,sort_order)
select format('00000085-0000-4000-8000-%s',lpad((row_number() over(order by question_id)*10+ord)::text,12,'0'))::uuid,
question_id,hint,ord
from c1_block_03_steps cross join lateral unnest(hints) with ordinality as h(hint,ord);

insert into public.question_solution_steps (id,question_id,title,content_markdown,sort_order)
select format('00000095-0000-4000-8000-%s',lpad((row_number() over(order by question_id)*10+ord)::text,12,'0'))::uuid,
question_id,title,step,ord
from c1_block_03_steps
cross join lateral unnest(titles) with ordinality as t(title,ord)
cross join lateral unnest(steps) with ordinality as s(step,step_ord)
where ord=step_ord;

commit;
