-- Arquitetura de Computadores: revisão de gabaritos, lote 06.
-- Atualiza apenas soluções e passos; tentativas e alternativas são preservadas.
begin;

update public.question_solutions set final_answer_markdown='Executá-las simultaneamente em núcleos distintos.', explanation_markdown='Vários núcleos fornecem recursos de execução paralelos. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Executá-las simultaneamente em núcleos distintos.” é a conclusão correta. “Eliminar memória.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Trocar ISA.” não decorre do princípio aplicável: Vários núcleos fornecem recursos de execução paralelos. “Dispensar SO.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930126';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de multicore: Qual vantagem multicore oferece a tarefas independentes?', sort_order=1 where id='70000000-0000-4000-8000-000009301261';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Vários núcleos fornecem recursos de execução paralelos.', sort_order=2 where id='70000000-0000-4000-8000-000009301262';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual vantagem multicore oferece a tarefas independentes? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301263';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Eliminar memória.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Trocar ISA.” não decorre do princípio aplicável: Vários núcleos fornecem recursos de execução paralelos. “Dispensar SO.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301264';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Executá-las simultaneamente em núcleos distintos.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301265';

update public.question_solutions set final_answer_markdown='Alternando threads quando uma está parada por latência.', explanation_markdown='Threads aproveitam unidades ociosas por espera. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Alternando threads quando uma está parada por latência.” é a conclusão correta. “Duplicando RAM.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Eliminando cache.” não decorre do princípio aplicável: Threads aproveitam unidades ociosas por espera. “Executando só uma thread.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930127';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de SMT: Como SMT pode aumentar utilização de um núcleo?', sort_order=1 where id='70000000-0000-4000-8000-000009301271';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Threads aproveitam unidades ociosas por espera.', sort_order=2 where id='70000000-0000-4000-8000-000009301272';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Como SMT pode aumentar utilização de um núcleo? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301273';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Duplicando RAM.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Eliminando cache.” não decorre do princípio aplicável: Threads aproveitam unidades ociosas por espera. “Executando só uma thread.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301274';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Alternando threads quando uma está parada por latência.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301275';

update public.question_solutions set final_answer_markdown='Para que leituras observem valores compatíveis após escritas compartilhadas.', explanation_markdown='Cópias de uma linha podem divergir sem protocolo. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Para que leituras observem valores compatíveis após escritas compartilhadas.” é a conclusão correta. “Para acelerar clock.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Para apagar RAM.” não decorre do princípio aplicável: Cópias de uma linha podem divergir sem protocolo. “Para remover threads.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930128';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de coerência: Por que caches privadas exigem coerência?', sort_order=1 where id='70000000-0000-4000-8000-000009301281';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Cópias de uma linha podem divergir sem protocolo.', sort_order=2 where id='70000000-0000-4000-8000-000009301282';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que caches privadas exigem coerência? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301283';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para acelerar clock.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Para apagar RAM.” não decorre do princípio aplicável: Cópias de uma linha podem divergir sem protocolo. “Para remover threads.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301284';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para que leituras observem valores compatíveis após escritas compartilhadas.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301285';

update public.question_solutions set final_answer_markdown='Define quais ordens de leitura e escrita são observáveis.', explanation_markdown='Reordenação pode mudar o que outra thread enxerga. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Define quais ordens de leitura e escrita são observáveis.” é a conclusão correta. “Define ASCII.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Substitui locks.” não decorre do princípio aplicável: Reordenação pode mudar o que outra thread enxerga. “Elimina caches.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930129';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de consistência: Por que consistência de memória importa em programas paralelos?', sort_order=1 where id='70000000-0000-4000-8000-000009301291';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Reordenação pode mudar o que outra thread enxerga.', sort_order=2 where id='70000000-0000-4000-8000-000009301292';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que consistência de memória importa em programas paralelos? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301293';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Define ASCII.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Substitui locks.” não decorre do princípio aplicável: Reordenação pode mudar o que outra thread enxerga. “Elimina caches.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301294';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Define quais ordens de leitura e escrita são observáveis.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301295';

update public.question_solutions set final_answer_markdown='Permitir acesso exclusivo a uma seção crítica.', explanation_markdown='Exclusão mútua protege estado compartilhado. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Permitir acesso exclusivo a uma seção crítica.” é a conclusão correta. “Aumentar cache.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Criar DMA.” não decorre do princípio aplicável: Exclusão mútua protege estado compartilhado. “Traduzir endereços.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930130';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de lock: Qual é a função de um mutex?', sort_order=1 where id='70000000-0000-4000-8000-000009301301';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Exclusão mútua protege estado compartilhado.', sort_order=2 where id='70000000-0000-4000-8000-000009301302';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual é a função de um mutex? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301303';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Aumentar cache.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Criar DMA.” não decorre do princípio aplicável: Exclusão mútua protege estado compartilhado. “Traduzir endereços.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301304';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Permitir acesso exclusivo a uma seção crítica.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301305';

update public.question_solutions set final_answer_markdown='Espera circular por recursos.', explanation_markdown='Ciclo de espera impede progresso se recursos não são liberados. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Espera circular por recursos.” é a conclusão correta. “Cache hit.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Ponto flutuante.” não decorre do princípio aplicável: Ciclo de espera impede progresso se recursos não são liberados. “Endereço alinhado.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930131';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de deadlock: Qual condição é necessária para deadlock?', sort_order=1 where id='70000000-0000-4000-8000-000009301311';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Ciclo de espera impede progresso se recursos não são liberados.', sort_order=2 where id='70000000-0000-4000-8000-000009301312';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual condição é necessária para deadlock? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301313';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Cache hit.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Ponto flutuante.” não decorre do princípio aplicável: Ciclo de espera impede progresso se recursos não são liberados. “Endereço alinhado.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301314';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Espera circular por recursos.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301315';

update public.question_solutions set final_answer_markdown='Latência de memória depende do nó que a possui.', explanation_markdown='Memória local e remota têm custos diferentes. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Latência de memória depende do nó que a possui.” é a conclusão correta. “Há uma única RAM sem variação.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Não há núcleos.” não decorre do princípio aplicável: Memória local e remota têm custos diferentes. “Todo acesso é serial.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930132';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de NUMA: Qual característica define NUMA?', sort_order=1 where id='70000000-0000-4000-8000-000009301321';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Memória local e remota têm custos diferentes.', sort_order=2 where id='70000000-0000-4000-8000-000009301322';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual característica define NUMA? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301323';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Há uma única RAM sem variação.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Não há núcleos.” não decorre do princípio aplicável: Memória local e remota têm custos diferentes. “Todo acesso é serial.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301324';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Latência de memória depende do nó que a possui.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301325';

update public.question_solutions set final_answer_markdown='Muitas operações semelhantes sobre grandes conjuntos de dados.', explanation_markdown='Paralelismo massivo favorece dados independentes. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Muitas operações semelhantes sobre grandes conjuntos de dados.” é a conclusão correta. “Uma única decisão serial.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “E/S de teclado.” não decorre do princípio aplicável: Paralelismo massivo favorece dados independentes. “Tabela de páginas.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930133';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de GPU: Que tipo de trabalho favorece GPU?', sort_order=1 where id='70000000-0000-4000-8000-000009301331';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Paralelismo massivo favorece dados independentes.', sort_order=2 where id='70000000-0000-4000-8000-000009301332';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Que tipo de trabalho favorece GPU? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301333';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Uma única decisão serial.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “E/S de teclado.” não decorre do princípio aplicável: Paralelismo massivo favorece dados independentes. “Tabela de páginas.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301334';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Muitas operações semelhantes sobre grandes conjuntos de dados.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301335';

update public.question_solutions set final_answer_markdown='Ela determina latência e largura de banda entre nós.', explanation_markdown='Comunicação depende dos caminhos físicos disponíveis. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Ela determina latência e largura de banda entre nós.” é a conclusão correta. “Muda tipos de dados.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Remove protocolos.” não decorre do princípio aplicável: Comunicação depende dos caminhos físicos disponíveis. “Elimina SO.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930134';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de interconexão: Por que topologia de rede afeta multiprocessador?', sort_order=1 where id='70000000-0000-4000-8000-000009301341';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Comunicação depende dos caminhos físicos disponíveis.', sort_order=2 where id='70000000-0000-4000-8000-000009301342';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que topologia de rede afeta multiprocessador? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301343';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Muda tipos de dados.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Remove protocolos.” não decorre do princípio aplicável: Comunicação depende dos caminhos físicos disponíveis. “Elimina SO.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301344';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Ela determina latência e largura de banda entre nós.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301345';

update public.question_solutions set final_answer_markdown='Muitas threads serializam na mesma seção crítica.', explanation_markdown='Recurso exclusivo cria parte serial do programa. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Muitas threads serializam na mesma seção crítica.” é a conclusão correta. “Aumenta número de núcleos.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Reduz contenção.” não decorre do princípio aplicável: Recurso exclusivo cria parte serial do programa. “Melhora cache sempre.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930135';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de escalabilidade: Por que lock global limita escalabilidade?', sort_order=1 where id='70000000-0000-4000-8000-000009301351';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Recurso exclusivo cria parte serial do programa.', sort_order=2 where id='70000000-0000-4000-8000-000009301352';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que lock global limita escalabilidade? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301353';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Aumenta número de núcleos.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Reduz contenção.” não decorre do princípio aplicável: Recurso exclusivo cria parte serial do programa. “Melhora cache sempre.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301354';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Muitas threads serializam na mesma seção crítica.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301355';

update public.question_solutions set final_answer_markdown='Ambientes virtuais isolados sobre o mesmo hardware.', explanation_markdown='Virtualização multiplexa recursos com isolamento. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Ambientes virtuais isolados sobre o mesmo hardware.” é a conclusão correta. “Uma cache L1.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Uma ULA adicional.” não decorre do princípio aplicável: Virtualização multiplexa recursos com isolamento. “Um opcode.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930136';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de virtualização: O que um hipervisor fornece?', sort_order=1 where id='70000000-0000-4000-8000-000009301361';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Virtualização multiplexa recursos com isolamento.', sort_order=2 where id='70000000-0000-4000-8000-000009301362';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, O que um hipervisor fornece? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301363';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Uma cache L1.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Uma ULA adicional.” não decorre do princípio aplicável: Virtualização multiplexa recursos com isolamento. “Um opcode.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301364';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Ambientes virtuais isolados sobre o mesmo hardware.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301365';

update public.question_solutions set final_answer_markdown='Para que o hipervisor controle efeito sensível.', explanation_markdown='Controle privilegiado precisa de mediação. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Para que o hipervisor controle efeito sensível.” é a conclusão correta. “Para desligar CPU.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Para corromper PC.” não decorre do princípio aplicável: Controle privilegiado precisa de mediação. “Para evitar RAM.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930137';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de trap: Por que instrução privilegiada em VM pode causar trap?', sort_order=1 where id='70000000-0000-4000-8000-000009301371';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Controle privilegiado precisa de mediação.', sort_order=2 where id='70000000-0000-4000-8000-000009301372';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que instrução privilegiada em VM pode causar trap? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301373';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para desligar CPU.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Para corromper PC.” não decorre do princípio aplicável: Controle privilegiado precisa de mediação. “Para evitar RAM.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301374';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para que o hipervisor controle efeito sensível.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301375';

update public.question_solutions set final_answer_markdown='Traduções adicionais podem aumentar pressão no TLB.', explanation_markdown='Mais camadas de mapeamento exigem caches de tradução eficientes. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Traduções adicionais podem aumentar pressão no TLB.” é a conclusão correta. “Não há endereços.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “RAM fica infinita.” não decorre do princípio aplicável: Mais camadas de mapeamento exigem caches de tradução eficientes. “DMA desaparece.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930138';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de virtualização: Qual custo pode surgir ao virtualizar memória?', sort_order=1 where id='70000000-0000-4000-8000-000009301381';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Mais camadas de mapeamento exigem caches de tradução eficientes.', sort_order=2 where id='70000000-0000-4000-8000-000009301382';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual custo pode surgir ao virtualizar memória? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301383';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Não há endereços.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “RAM fica infinita.” não decorre do princípio aplicável: Mais camadas de mapeamento exigem caches de tradução eficientes. “DMA desaparece.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301384';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Traduções adicionais podem aumentar pressão no TLB.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301385';

update public.question_solutions set final_answer_markdown='DVFS.', explanation_markdown='Potência dinâmica depende de frequência e tensão. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “DVFS.” é a conclusão correta. “DMA.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “ECC.” não decorre do princípio aplicável: Potência dinâmica depende de frequência e tensão. “RAID.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930139';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de energia: Qual técnica reduz energia dinâmica ao diminuir frequência e tensão?', sort_order=1 where id='70000000-0000-4000-8000-000009301391';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Potência dinâmica depende de frequência e tensão.', sort_order=2 where id='70000000-0000-4000-8000-000009301392';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual técnica reduz energia dinâmica ao diminuir frequência e tensão? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301393';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“DMA.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “ECC.” não decorre do princípio aplicável: Potência dinâmica depende de frequência e tensão. “RAID.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301394';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “DVFS.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301395';

update public.question_solutions set final_answer_markdown='Reduz consumo de vazamento e comutação.', explanation_markdown='Blocos sem trabalho não precisam permanecer ativos. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Reduz consumo de vazamento e comutação.” é a conclusão correta. “Aumenta opcodes.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Cria memória.” não decorre do princípio aplicável: Blocos sem trabalho não precisam permanecer ativos. “Remove clock global.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930140';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de energia: Por que desligar blocos ociosos economiza energia?', sort_order=1 where id='70000000-0000-4000-8000-000009301401';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Blocos sem trabalho não precisam permanecer ativos.', sort_order=2 where id='70000000-0000-4000-8000-000009301402';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que desligar blocos ociosos economiza energia? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301403';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Aumenta opcodes.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Cria memória.” não decorre do princípio aplicável: Blocos sem trabalho não precisam permanecer ativos. “Remove clock global.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301404';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Reduz consumo de vazamento e comutação.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301405';

update public.question_solutions set final_answer_markdown='CPI, memória e paralelismo também limitam o tempo.', explanation_markdown='Tempo combina frequência, trabalho e esperas. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “CPI, memória e paralelismo também limitam o tempo.” é a conclusão correta. “Clock não afeta nada.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “RAM vira ROM.” não decorre do princípio aplicável: Tempo combina frequência, trabalho e esperas. “ISA desaparece.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930141';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de desempenho: Por que aumentar clock pode não melhorar desempenho proporcionalmente?', sort_order=1 where id='70000000-0000-4000-8000-000009301411';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Tempo combina frequência, trabalho e esperas.', sort_order=2 where id='70000000-0000-4000-8000-000009301412';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que aumentar clock pode não melhorar desempenho proporcionalmente? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301413';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Clock não afeta nada.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “RAM vira ROM.” não decorre do princípio aplicável: Tempo combina frequência, trabalho e esperas. “ISA desaparece.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301414';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “CPI, memória e paralelismo também limitam o tempo.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301415';

update public.question_solutions set final_answer_markdown='Detectar e corrigir certos erros de bits.', explanation_markdown='Redundância permite reconhecer inconsistências. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Detectar e corrigir certos erros de bits.” é a conclusão correta. “Aumentar capacidade lógica.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Remover endereços.” não decorre do princípio aplicável: Redundância permite reconhecer inconsistências. “Substituir cache.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930142';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de confiabilidade: Qual objetivo de ECC em memória?', sort_order=1 where id='70000000-0000-4000-8000-000009301421';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Redundância permite reconhecer inconsistências.', sort_order=2 where id='70000000-0000-4000-8000-000009301422';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual objetivo de ECC em memória? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301423';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Aumentar capacidade lógica.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Remover endereços.” não decorre do princípio aplicável: Redundância permite reconhecer inconsistências. “Substituir cache.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301424';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Detectar e corrigir certos erros de bits.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301425';

update public.question_solutions set final_answer_markdown='Impede executar código em páginas marcadas como dados.', explanation_markdown='Permissões de página separam leitura, escrita e execução. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Impede executar código em páginas marcadas como dados.” é a conclusão correta. “Apaga dados.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Aumenta largura de barramento.” não decorre do princípio aplicável: Permissões de página separam leitura, escrita e execução. “Desliga TLB.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930143';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de segurança: Por que NX/DEP protege memória?', sort_order=1 where id='70000000-0000-4000-8000-000009301431';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Permissões de página separam leitura, escrita e execução.', sort_order=2 where id='70000000-0000-4000-8000-000009301432';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que NX/DEP protege memória? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301433';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Apaga dados.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Aumenta largura de barramento.” não decorre do princípio aplicável: Permissões de página separam leitura, escrita e execução. “Desliga TLB.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301434';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Impede executar código em páginas marcadas como dados.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301435';

update public.question_solutions set final_answer_markdown='Efeitos microarquiteturais podem revelar dados por canais laterais.', explanation_markdown='Dados especulativos podem afetar cache mesmo após descarte arquitetural. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Efeitos microarquiteturais podem revelar dados por canais laterais.” é a conclusão correta. “Muda resultado arquitetural sempre.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Elimina cache.” não decorre do princípio aplicável: Dados especulativos podem afetar cache mesmo após descarte arquitetural. “Desliga interrupções.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930144';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de especulação: Que risco de segurança pode vir de execução especulativa?', sort_order=1 where id='70000000-0000-4000-8000-000009301441';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Dados especulativos podem afetar cache mesmo após descarte arquitetural.', sort_order=2 where id='70000000-0000-4000-8000-000009301442';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Que risco de segurança pode vir de execução especulativa? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301443';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Muda resultado arquitetural sempre.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Elimina cache.” não decorre do princípio aplicável: Dados especulativos podem afetar cache mesmo após descarte arquitetural. “Desliga interrupções.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301444';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Efeitos microarquiteturais podem revelar dados por canais laterais.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301445';

update public.question_solutions set final_answer_markdown='Duplicar componentes ou dados para tolerar falhas.', explanation_markdown='Alternativa disponível mantém serviço após falha. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Duplicar componentes ou dados para tolerar falhas.” é a conclusão correta. “Remover cópias.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Usar só um disco.” não decorre do princípio aplicável: Alternativa disponível mantém serviço após falha. “Evitar testes.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930145';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de confiabilidade: O que significa redundância em sistemas?', sort_order=1 where id='70000000-0000-4000-8000-000009301451';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Alternativa disponível mantém serviço após falha.', sort_order=2 where id='70000000-0000-4000-8000-000009301452';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, O que significa redundância em sistemas? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301453';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Remover cópias.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Usar só um disco.” não decorre do princípio aplicável: Alternativa disponível mantém serviço após falha. “Evitar testes.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301454';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Duplicar componentes ou dados para tolerar falhas.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301455';

update public.question_solutions set final_answer_markdown='Programas exercitam recursos diferentes do sistema.', explanation_markdown='Desempenho depende da carga de trabalho. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Programas exercitam recursos diferentes do sistema.” é a conclusão correta. “Um teste mede tudo perfeitamente.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Clock basta.” não decorre do princípio aplicável: Desempenho depende da carga de trabalho. “CPI é sempre igual.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930146';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de benchmark: Por que usar mais de um benchmark?', sort_order=1 where id='70000000-0000-4000-8000-000009301461';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Desempenho depende da carga de trabalho.', sort_order=2 where id='70000000-0000-4000-8000-000009301462';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que usar mais de um benchmark? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301463';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Um teste mede tudo perfeitamente.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Clock basta.” não decorre do princípio aplicável: Desempenho depende da carga de trabalho. “CPI é sempre igual.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301464';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Programas exercitam recursos diferentes do sistema.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301465';

update public.question_solutions set final_answer_markdown='A que ocupa fração relevante do tempo total.', explanation_markdown='Amdahl pondera benefício pela frequência de uso. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “A que ocupa fração relevante do tempo total.” é a conclusão correta. “Qualquer parte rara.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Somente I/O.” não decorre do princípio aplicável: Amdahl pondera benefício pela frequência de uso. “A mais simples.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930147';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de Amdahl: Qual parte deve ser otimizada para obter grande speedup global?', sort_order=1 where id='70000000-0000-4000-8000-000009301471';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Amdahl pondera benefício pela frequência de uso.', sort_order=2 where id='70000000-0000-4000-8000-000009301472';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual parte deve ser otimizada para obter grande speedup global? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301473';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Qualquer parte rara.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Somente I/O.” não decorre do princípio aplicável: Amdahl pondera benefício pela frequência de uso. “A mais simples.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301474';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “A que ocupa fração relevante do tempo total.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301475';

update public.question_solutions set final_answer_markdown='Latência é tempo por operação; throughput é taxa de operações.', explanation_markdown='Pipeline pode melhorar taxa sem reduzir tempo individual. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Latência é tempo por operação; throughput é taxa de operações.” é a conclusão correta. “São sinônimos.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Ambos são capacidade.” não decorre do princípio aplicável: Pipeline pode melhorar taxa sem reduzir tempo individual. “Ambos são clock.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930148';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de latência e throughput: Qual diferença entre latência e throughput?', sort_order=1 where id='70000000-0000-4000-8000-000009301481';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Pipeline pode melhorar taxa sem reduzir tempo individual.', sort_order=2 where id='70000000-0000-4000-8000-000009301482';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual diferença entre latência e throughput? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301483';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“São sinônimos.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Ambos são capacidade.” não decorre do princípio aplicável: Pipeline pode melhorar taxa sem reduzir tempo individual. “Ambos são clock.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301484';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Latência é tempo por operação; throughput é taxa de operações.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301485';

update public.question_solutions set final_answer_markdown='Para reduzir custo, energia e componentes externos.', explanation_markdown='Integração atende aplicações específicas compactas. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Para reduzir custo, energia e componentes externos.” é a conclusão correta. “Para eliminar software.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Para aumentar tamanho físico.” não decorre do princípio aplicável: Integração atende aplicações específicas compactas. “Para evitar E/S.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930149';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de sistema embarcado: Por que microcontrolador integra periféricos no chip?', sort_order=1 where id='70000000-0000-4000-8000-000009301491';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Integração atende aplicações específicas compactas.', sort_order=2 where id='70000000-0000-4000-8000-000009301492';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Por que microcontrolador integra periféricos no chip? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301493';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Para eliminar software.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Para aumentar tamanho físico.” não decorre do princípio aplicável: Integração atende aplicações específicas compactas. “Para evitar E/S.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301494';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Para reduzir custo, energia e componentes externos.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301495';

update public.question_solutions set final_answer_markdown='Equilibrar custo, energia, desempenho e confiabilidade conforme a carga.', explanation_markdown='Não há métrica única que domine todos os projetos. No caso apresentado, Identifique o recurso compartilhado e a regra de execução. A alternativa correta deve manter desempenho e correção. Logo, “Equilibrar custo, energia, desempenho e confiabilidade conforme a carga.” é a conclusão correta. “Maximizar apenas clock.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Ignorar software.” não decorre do princípio aplicável: Não há métrica única que domine todos os projetos. “Escolher sem requisitos.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.' where question_id='40000000-0000-4000-8000-000000930150';
update public.question_solution_steps set title='Delimite o problema', content_markdown='O enunciado apresenta esta situação de trade-off: Qual decisão é típica de arquitetura?', sort_order=1 where id='70000000-0000-4000-8000-000009301501';
update public.question_solution_steps set title='Recupere o princípio', content_markdown='Não há métrica única que domine todos os projetos.', sort_order=2 where id='70000000-0000-4000-8000-000009301502';
update public.question_solution_steps set title='Aplique o critério', content_markdown='Identifique o recurso compartilhado e a regra de execução. No enunciado, Qual decisão é típica de arquitetura? A alternativa correta deve manter desempenho e correção.', sort_order=3 where id='70000000-0000-4000-8000-000009301503';
update public.question_solution_steps set title='Analise os distratores', content_markdown='“Maximizar apenas clock.” não cumpre o critério técnico do caso: A alternativa correta deve manter desempenho e correção. “Ignorar software.” não decorre do princípio aplicável: Não há métrica única que domine todos os projetos. “Escolher sem requisitos.” deixa de executar a análise necessária: Identifique o recurso compartilhado e a regra de execução.', sort_order=4 where id='70000000-0000-4000-8000-000009301504';
update public.question_solution_steps set title='Verifique a conclusão', content_markdown='A alternativa correta é “Equilibrar custo, energia, desempenho e confiabilidade conforme a carga.”, pois é a única que respeita o princípio e o cenário apresentados.', sort_order=5 where id='70000000-0000-4000-8000-000009301505';

commit;
